### PR TITLE
filter_lua: Fix record split in mpack implementation

### LINKED ISSUE #5496: Can't split record with lua filter
## Bug Report

**Describe the bug**
The record split on lua filter isn't working for me. I tried to follow the steps on [docs](https://docs.fluentbit.io/manual/pipeline/filters/lua#record-split) to return a list of records, but it's always being handled as a single record. 

**To Reproduce**
- Steps to reproduce the problem:

Create the file `split.conf`:
```
[Input]
    Name    dummy
    Dummy   {"x": [ {"a1":"aa", "z1":"zz"}, {"b1":"bb", "x1":"xx"}, {"c1":"cc"} ]}

[Filter]
    Name    lua
    Match   *
    code    function cb_split(tag, timestamp, record) if record["x"] ~= nil then return 2, timestamp, record["x"] else return 2, timestamp, record end end
    call    cb_split

[Output]
    Name    stdout
    Match   *
```
Run with the following command:
```
docker run -ti -v $(pwd)/split.conf:/fluent-bit/etc/fluent-bit.conf cr.fluentbit.io/fluent/fluent-bit:1.9.3-debug
```
The output will be the following:
```
[0] dummy.0: [1653481844.893756173, [{"a1"=>"aa", "z1"=>"zz"}, {"b1"=>"bb", "x1"=>"xx"}, {"c1"=>"cc"}]]
[0] dummy.0: [1653481845.892637465, [{"a1"=>"aa", "z1"=>"zz"}, {"b1"=>"bb", "x1"=>"xx"}, {"c1"=>"cc"}]]
[0] dummy.0: [1653481846.895785632, [{"a1"=>"aa", "z1"=>"zz"}, {"b1"=>"bb", "x1"=>"xx"}, {"c1"=>"cc"}]]
[0] dummy.0: [1653481847.891129591, [{"a1"=>"aa", "z1"=>"zz"}, {"b1"=>"bb", "x1"=>"xx"}, {"c1"=>"cc"}]]
```

**Expected behavior**
It should split the objects inside the "x" node and return as separated messages:
```
[0] dummy.0: [1538435928.310583591, {"a1"=>"aa", "z1"=>"zz"}]
[1] dummy.0: [1538435928.310583591, {"x1"=>"xx", "b1"=>"bb"}]
[2] dummy.0: [1538435928.310583591, {"c1"=>"cc"}]
```

**Screenshots**
image

**Your Environment**

* Version used: 1.9.3
* Configuration:
* Environment name and version (e.g. Kubernetes? What version?): Docker image `fluent-bit:1.9.3-debug`
* Server type and version:
* Operating System and version:
* Filters and plugins:

**Additional context**

We're trying to do a POC with fluent-bit but this is preventing us from continuing. Am I'm doing something wrong or is this a bug? 
Thanks in advance!

### PR DESCRIPTION
**Pull request by tarruda**
Fix the mpack implementation of lua, which didn't handle record
splitting.

Fix #5496

Signed-off-by: Thiago Padilha <thiago@calyptia.com>

### CODE REVIEW

**Review by brunomrpx — DISMISSED** [review]

**Review by LucasGeneroso — APPROVED** [review]

File: plugins/filter_lua/lua.c [hunk 1]
```diff
@@ -112,6 +112,45 @@ static void mpack_buffer_flush(mpack_writer_t* writer, const char* buffer, size_
...
+      /* write array tag */
+      mpack_write_tag(writer, mpack_tag_array(2));
+      /* write timestamp */
+      flb_time_append_to_mpack(writer, t, 0);
+      /* convert */
+      flb_lua_tompack(l, writer, 0, l2cc);
+  }
+  /* pop */
+  lua_pop(l, 1);
+}
```
Comment (nokute78) [inline plugins/filter_lua/lua.c:152]: Could you check indent level ?

https://github.com/fluent/fluent-bit/blob/master/CONTRIBUTING.md#coding-style
```
You have to pay attention to the code indentation, tabs are 4 spaces, spaces on conditionals, etc. If your code submission is not aligned, it will be rejected.
```

**Review by nokute78 — CHANGES_REQUESTED** [review]
- Could you check indent level ?
- Could you add a test code ?

**Review by nokute78 — APPROVED** [review]
@tarruda Thank you for updating. LGTM.

I confirmed the test failed if this patch was not merged.
```
Test split_record...                            [2022/05/29 07:56:28] [ info] [fluent bit] version=1.9.4, commit=5204e28fe3, pid=7826
[2022/05/29 07:56:28] [ info] [storage] version=1.2.0, type=memory-only, sync=normal, checksum=disabled, max_chunks_up=128
[2022/05/29 07:56:28] [ info] [cmetrics] version=0.3.1
[2022/05/29 07:56:28] [ info] [sp] stream processor started
[ FAILED ]
  filter_lua.c:697: Check !strcmp(outbuf, expected)... failed
    expected:
    [5.000000,{"a1":"aa"}][5.000000,{"b1":"bb"}][5.000000,{"c1":"cc"}]
    got:
    [5.000000,[{"a1":"aa"},{"b1":"bb"},{"c1":"cc"}]]
[2022/05/29 07:56:29] [ warn] [engine] service will shutdown in max 1 seconds
[2022/05/29 07:56:30] [ info] [engine] service has stopped (0 pending tasks)
FAILED: 1 of 8 unit tests has failed.
```

**Comment by pwhelan** [comment]
I have personally tested it and it works for me.

**Comment by edsiper** [comment]
thanks everyone!
