### PR TITLE
fix Oracle Log Analytics output plugin 400 Bad Request issue

### LINKED ISSUE #8684: Oracle Log Analytics output plugin 400 Bad Request error
## Bug Report

**Describe the bug**
400 Bad Request error when use Oracle Log Analytics (`plugins/out_oracle_log_analytics`)

**To Reproduce**
- Rubular link if applicable:
```
cat <<EOF >> /mnt/fluent-bit.conf
[SERVICE]
  flush 1

[INPUT]
  Name   dummy

[Output]
  Name oracle_log_analytics
  Match *
  Namespace nxxxxxxx0
  config_file_location /mnt/oci-config
  oci_la_log_group_id ocid1.loganalyticsloggroup.oc1.ap-tokyo-1.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  oci_la_log_source_name source-name
  tls On
  tls.verify Off
EOF

docker run -it --rm \
           -v /mnt/fluent-bit.conf:/mnt/fluent-bit.conf \
           -v /mnt/oci-config:/mnt/oci-config \
           -v /mnt/key.pem:/mnt/key.pem \
           cr.fluentbit.io/fluent/fluent-bit:latest -vv -c /mnt/fluent-bit.conf
```

- Example log message if applicable:
```
Fluent Bit v3.0.2
* Copyright (C) 2015-2024 The Fluent Bit Authors
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io

___________.__                        __    __________.__  __          ________
\_   _____/|  |  __ __   ____   _____/  |_  \______   \__|/  |_  ___  _\_____  \
 |    __)  |  | |  |  \_/ __ \ /    \   __\  |    |  _/  \   __\ \  \/ / _(__  <
 |     \   |  |_|  |  /\  ___/|   |  \  |    |    |   \  ||  |    \   / /       \
 \___  /   |____/____/  \___  >___|  /__|    |______  /__||__|     \_/ /______  /
     \/                     \/     \/               \/                        \/

[2024/04/08 14:11:46] [ info] Configuration:
[2024/04/08 14:11:46] [ info]  flush time     | 1.000000 seconds
[2024/04/08 14:11:46] [ info]  grace          | 5 seconds
[2024/04/08 14:11:46] [ info]  daemon         | 0
[2024/04/08 14:11:46] [ info] ___________
[2024/04/08 14:11:46] [ info]  inputs:
[2024/04/08 14:11:46] [ info]      dummy
[2024/04/08 14:11:46] [ info] ___________
[2024/04/08 14:11:46] [ info]  filters:
[2024/04/08 14:11:46] [ info] ___________
[2024/04/08 14:11:46] [ info]  outputs:
[2024/04/08 14:11:46] [ info]      oracle_log_analytics.0
[2024/04/08 14:11:46] [ info] ___________
[2024/04/08 14:11:46] [ info]  collectors:
[2024/04/08 14:11:46] [ info] [fluent bit] version=3.0.2, commit=f670ce791d, pid=217570
[2024/04/08 14:11:46] [debug] [engine] coroutine stack size: 24576 bytes (24.0K)
[2024/04/08 14:11:46] [ info] [storage] ver=1.5.1, type=memory, sync=normal, checksum=off, max_chunks_up=128
[2024/04/08 14:11:46] [ info] [cmetrics] version=0.7.1
[2024/04/08 14:11:46] [ info] [ctraces ] version=0.4.0
[2024/04/08 14:11:46] [ info] [input:dummy:dummy.0] initializing
[2024/04/08 14:11:46] [ info] [input:dummy:dummy.0] storage_strategy='memory' (memory only)
[2024/04/08 14:11:46] [debug] [dummy:dummy.0] created event channels: read=21 write=22
[2024/04/08 14:11:46] [debug] [oracle_log_analytics:oracle_log_analytics.0] created event channels: read=23 write=24
[2024/04/08 14:11:46] [debug] [output:oracle_log_analytics:oracle_log_analytics.0] content = [DEFAULT]
region=ap-tokyo-1
user=ocid1.user.oc1..xxxxxxxxxxxxxxxxxxxxxxxxxxx
tenancy=ocid1.tenancy.oc1..xxxxxxxxxxxxxxxxxxxxxxxxxxx
fingerprint=16:35:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx
key_file=/mnt/key.pem

[2024/04/08 14:11:46] [debug] [output:oracle_log_analytics:oracle_log_analytics.0] line = [DEFAULT]
[2024/04/08 14:11:46] [ info] [output:oracle_log_analytics:oracle_log_analytics.0] found profile
[2024/04/08 14:11:46] [debug] [output:oracle_log_analytics:oracle_log_analytics.0] line = region=ap-tokyo-1
[2024/04/08 14:11:46] [debug] [output:oracle_log_analytics:oracle_log_analytics.0] eq_pos 6
[2024/04/08 14:11:46] [debug] [output:oracle_log_analytics:oracle_log_analytics.0] key = region
[2024/04/08 14:11:46] [debug] [output:oracle_log_analytics:oracle_log_analytics.0] line = user=ocid1.user.oc1..xxxxxxxxxxxxxxxxxxxxxxxxxxx
[2024/04/08 14:11:46] [debug] [output:oracle_log_analytics:oracle_log_analytics.0] eq_pos 4
[2024/04/08 14:11:46] [debug] [output:oracle_log_analytics:oracle_log_analytics.0] key = user
[2024/04/08 14:11:46] [debug] [output:oracle_log_analytics:oracle_log_analytics.0] line = tenancy=ocid1.tenancy.oc1..xxxxxxxxxxxxxxxxxxxxxxxxxxx
[2024/04/08 14:11:46] [debug] [output:oracle_log_analytics:oracle_log_analytics.0] eq_pos 7
[2024/04/08 14:11:46] [debug] [output:oracle_log_analytics:oracle_log_analytics.0] key = tenancy
[2024/04/08 14:11:46] [debug] [output:oracle_log_analytics:oracle_log_analytics.0] line = fingerprint=16:35:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx
[2024/04/08 14:11:46] [debug] [output:oracle_log_analytics:oracle_log_analytics.0] eq_pos 11
[2024/04/08 14:11:46] [debug] [output:oracle_log_analytics:oracle_log_analytics.0] key = fingerprint
[2024/04/08 14:11:46] [debug] [output:oracle_log_analytics:oracle_log_analytics.0] line = key_file=/mnt/key.pem
[2024/04/08 14:11:46] [debug] [output:oracle_log_analytics:oracle_log_analytics.0] eq_pos 8
[2024/04/08 14:11:46] [debug] [output:oracle_log_analytics:oracle_log_analytics.0] key = key_file
[2024/04/08 14:11:46] [ info] [output:oracle_log_analytics:oracle_log_analytics.0] initialized logan plugin
[2024/04/08 14:11:46] [ info] [sp] stream processor started
[2024/04/08 14:11:46] [ info] [output:oracle_log_analytics:oracle_log_analytics.0] worker #0 started
[2024/04/08 14:11:47] [debug] [input chunk] update output instances with new chunk size diff=36, records=1, input=dummy.0
[2024/04/08 14:11:48] [debug] [task] created task=0x7fd7400d73b0 id=0 OK
[2024/04/08 14:11:48] [debug] [output:oracle_log_analytics:oracle_log_analytics.0] task_id=0 assigned to thread #0
[2024/04/08 14:11:48] [debug] [input chunk] update output instances with new chunk size diff=36, records=1, input=dummy.0
[2024/04/08 14:11:48] [debug] [output:oracle_log_analytics:oracle_log_analytics.0] payload={"logEvents":[{"logSourceName":"source-name","logRecords":["dummy"]}]}
[2024/04/08 14:11:48] [debug] [output:oracle_log_analytics:oracle_log_analytics.0] lg_id=ocid1.loganalyticsloggroup.oc1.ap-tokyo-1.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
[2024/04/08 14:11:48] [debug] [output:oracle_log_analytics:oracle_log_analytics.0] full_uri=/20200601/namespaces/nxxxxxxx0/actions/uploadLogEventsFile?logGroupId=ocid1.loganalyticsloggroup.oc1.ap-tokyo-1.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx&payloadType=JSON
[2024/04/08 14:11:48] [debug] [upstream] KA connection #40 to loganalytics.ap-tokyo-1.oci.oraclecloud.com:443 is connected
[2024/04/08 14:11:48] [debug] [http_client] not using http_proxy for header
[2024/04/08 14:11:48] [debug] [output:oracle_log_analytics:oracle_log_analytics.0] built client
[2024/04/08 14:11:48] [debug] [output:oracle_log_analytics:oracle_log_analytics.0] built request
[2024/04/08 14:11:48] [debug] [http_client] server loganalytics.ap-tokyo-1.oci.oraclecloud.com:443 will close connection #40
[2024/04/08 14:11:48] [debug] [output:oracle_log_analytics:oracle_log_analytics.0] placed request
[2024/04/08 14:11:48] [debug] [output:oracle_log_analytics:oracle_log_analytics.0] request header POST /20200601/namespaces/nxxxxxxx0/actions/uploadLogEventsFile?logGroupId=ocid1.loganalyticsloggroup.oc1.ap-tokyo-1.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx&payloadType=JSON HTTP/1.1
host: loganalytics.ap-tokyo-1.oci.oraclecloud.com
date: Mon, 08 Apr 2024 14:11:48 GMT
x-content-sha256: loganalytics.ap-tokyo-1.oci.oraclecloud.com
[2024/04/08 14:11:48] [ info] [output:oracle_log_analytics:oracle_log_analytics.0] Unable to parser error response. reponse is not valid json
[2024/04/08 14:11:48] [error] [output:oracle_log_analytics:oracle_log_analytics.0] loganalytics.ap-tokyo-1.oci.oraclecloud.com:443, retry=false, HTTP status=400
<h1>Bad Message 400</h1><pre>reason: Illegal character CNTL=0x0</pre>
[2024/04/08 14:11:48] [debug] [out flush] cb_destroy coro_id=0
[2024/04/08 14:11:48] [debug] [retry] new retry created for task_id=0 attempts=1
[2024/04/08 14:11:48] [ warn] [engine] failed to flush chunk '217570-1712585507.215377216.flb', retry in 7 seconds: task_id=0, input=dummy.0 > output=oracle_log_analytics.0 (out_id=0)
[2024/04/08 14:11:49] [debug] [task] created task=0x7fd7400d1230 id=1 OK
[2024/04/08 14:11:49] [debug] [output:oracle_log_analytics:oracle_log_analytics.0] task_id=1 assigned to thread #0
[2024/04/08 14:11:49] [debug] [input chunk] update output instances with new chunk size diff=36, records=1, input=dummy.0
[2024/04/08 14:11:49] [debug] [output:oracle_log_analytics:oracle_log_analytics.0] payload={"logEvents":[{"logSourceName":"poc-app-file","logRecords":["dummy"]}]}
[2024/04/08 14:11:49] [debug] [output:oracle_log_analytics:oracle_log_analytics.0] lg_id=ocid1.loganalyticsloggroup.oc1.ap-tokyo-1.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
[2024/04/08 14:11:49] [error] [/root/fluent-bit/src/flb_sds.c:43 errno=12] Cannot allocate memory
[2024/04/08 14:11:49] [error] [/root/fluent-bit/plugins/out_oracle_log_analytics/oci_logan.c:609 errno=12] Cannot allocate memory
[2024/04/08 14:11:49] [error] [output:oracle_log_analytics:oracle_log_analytics.0] unable to compose uri for logGroup: ocid1.loganalyticsloggroup.oc1.ap-tokyo-1.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx logSet: (null)
[2024/04/08 14:11:49] [debug] [output:oracle_log_analytics:oracle_log_analytics.0] full_uri=(null)
[2024/04/08 14:11:49] [ warn] [net] getaddrinfo(host='Qty��', err=8): Misformatted domain name
[2024/04/08 14:11:49] [2024/04/08 14:11:49] [debug] [upstream] connection #-1 failed to �z:939555520
[engine] caught signal (SIGSEGV)
#0  0x560de8d7a80a      in  flb_upstream_decrement_total_connections_count() at src/flb_upstream.c:1127
#1  0x560de8d7a830      in  flb_upstream_decrement_total_connections_count() at src/flb_upstream.c:1130
#2  0x560de8d7a830      in  flb_upstream_decrement_total_connections_count() at src/flb_upstream.c:1130
#3  0x560de8d795f4      in  prepare_destroy_conn() at src/flb_upstream.c:508
#4  0x560de8d7962b      in  prepare_destroy_conn_safe() at src/flb_upstream.c:524
#5  0x560de8d79832      in  create_conn() at src/flb_upstream.c:592
#6  0x560de8d79d92      in  flb_upstream_conn_get() at src/flb_upstream.c:774
#7  0x560de919acfe      in  flush_to_endpoint() at plugins/out_oracle_log_analytics/oci_logan.c:643
#8  0x560de919cbea      in  total_flush() at plugins/out_oracle_log_analytics/oci_logan.c:1165
#9  0x560de919ccdf      in  cb_oci_logan_flush() at plugins/out_oracle_log_analytics/oci_logan.c:1192
#10 0x560de8d346c6      in  output_pre_cb_flush() at include/fluent-bit/flb_output.h:597
#11 0x560de9a6610a      in  co_init() at lib/monkey/deps/flb_libco/amd64.c:117
```
- Steps to reproduce the problem:

**Expected behavior**
Successfully post data to the Oracle Logging Analytics service.

**Screenshots**

**Your Environment**

* Version used:
Image: cr.fluentbit.io/fluent/fluent-bit:latest
Digest: sha256:6b8af5cb8ec1c7c630a47d63eefcc83b133b6951e54e120f10c0367c7a217db5

docker run --rm cr.fluentbit.io/fluent/fluent-bit:latest --version
Fluent Bit v3.0.1
Git commit: cf3e53ce03e85eddfa1474600a6b30a7f508e461

* Configuration:
```
[SERVICE]
  flush 1

[INPUT]
  Name   dummy

[Output]
  Name oracle_log_analytics
  Match *
  Namespace ${namespace}
  config_file_location /mnt/oci-config
  oci_la_log_group_id ${group_id}
  oci_la_log_source_name source-name
  tls On
  tls.verify Off
```

* Filters and plugins:
INPUT : dummy
Output : oracle_log_analytics

**Additional context**
Three notable points can be found from the logs:
1, `request header` was printed after error hapended, but only three headers(`host`, `date`, `x-content-sha256`)
2, The value of header `x-content-sha256` has wrong value, which should be sha256 hash of post body
3, `Cannot allocate memory` occurred in source code `/root/fluent-bit/src/flb_sds.c:43`

### PR DESCRIPTION
**Pull request by handsomecheung**
Fresh the variable `tmp_sds` (which is still holding info for header `host`) before handle the new header `x-content-sha256`.

Fixes #8684

----
Enter `[N/A]` in the box, if an item is not applicable to your change.

**Testing**
Before we can approve your change; please submit the following in a comment:

- [ ] Example configuration file for the change
```
[SERVICE]
  flush 1

[INPUT]
  Name   dummy

[Output]
  Name oracle_log_analytics
  Match *
  Namespace ${namespace}
  config_file_location /mnt/oci-config
  oci_la_log_group_id ${group_id}
  oci_la_log_source_name source-name
  tls On
  tls.verify Off
```

- [ ] Debug log output from testing the change

```
[2024/04/08 14:11:48] [debug] [output:oracle_log_analytics:oracle_log_analytics.0] placed request
[2024/04/08 14:11:48] [debug] [output:oracle_log_analytics:oracle_log_analytics.0] request header POST /20200601/namespaces/nxxxxxxx0/actions/uploadLogEventsFile?logGroupId=ocid1.loganalyticsloggroup.oc1.ap-tokyo-1.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx&payloadType=JSON HTTP/1.1
host: loganalytics.ap-tokyo-1.oci.oraclecloud.com
date: Mon, 08 Apr 2024 14:11:48 GMT
x-content-sha256: loganalytics.ap-tokyo-1.oci.oraclecloud.com
[2024/04/08 14:11:48] [ info] [output:oracle_log_analytics:oracle_log_analytics.0] Unable to parser error response. reponse is not valid json
[2024/04/08 14:11:48] [error] [output:oracle_log_analytics:oracle_log_analytics.0] loganalytics.ap-tokyo-1.oci.oraclecloud.com:443, retry=false, HTTP status=400
<h1>Bad Message 400</h1><pre>reason: Illegal character CNTL=0x0</pre>
[2024/04/08 14:11:48] [debug] [out flush] cb_destroy coro_id=0
[2024/04/08 14:11:48] [debug] [retry] new retry created for task_id=0 attempts=1
[2024/04/08 14:11:48] [ warn] [engine] failed to flush chunk '217570-1712585507.215377216.flb', retry in 7 seconds: task_id=0, input=dummy.0 > output=oracle_log_analytics.0 (out_id=0)
[2024/04/08 14:11:49] [debug] [task] created task=0x7fd7400d1230 id=1 OK
[2024/04/08 14:11:49] [debug] [output:oracle_log_analytics:oracle_log_analytics.0] task_id=1 assigned to thread #0
[2024/04/08 14:11:49] [debug] [input chunk] update output instances with new chunk size diff=36, records=1, input=dummy.0
[2024/04/08 14:11:49] [debug] [output:oracle_log_analytics:oracle_log_analytics.0] payload={"logEvents":[{"logSourceName":"poc-app-file","logRecords":["dummy"]}]}
[2024/04/08 14:11:49] [debug] [output:oracle_log_analytics:oracle_log_analytics.0] lg_id=ocid1.loganalyticsloggroup.oc1.ap-tokyo-1.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
[2024/04/08 14:11:49] [error] [/root/fluent-bit/src/flb_sds.c:43 errno=12] Cannot allocate memory
[2024/04/08 14:11:49] [error] [/root/fluent-bit/plugins/out_oracle_log_analytics/oci_logan.c:609 errno=12] Cannot allocate memory
[2024/04/08 14:11:49] [error] [output:oracle_log_analytics:oracle_log_analytics.0] unable to compose uri for logGroup: ocid1.loganalyticsloggroup.oc1.ap-tokyo-1.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx logSet: (null)
[2024/04/08 14:11:49] [debug] [output:oracle_log_analytics:oracle_log_analytics.0] full_uri=(null)
```

- [N/A] Attached [Valgrind](https://valgrind.org/docs/manual/quick-start.html) output that shows no leaks or memory corruption was found

If this is a change to packaging of containers or native binaries then please confirm it works for all targets.

- [N/A] Run [local packaging test](./packaging/local-build-all.sh) showing all targets (including any new ones) build.
- [N/A] Set `ok-package-test` label to test for all targets (requires maintainer to do).

**Documentation**

- [N/A] Documentation required for this feature

**Backporting**

- [N/A] Backport to latest stable release.

----

Fluent Bit is licensed under Apache 2.0, by submitting this pull request I understand that this code will be released under the terms of that license.

### CODE REVIEW

File: plugins/out_oracle_log_analytics/oci_logan.c [hunk 1]
```diff
@@ -278,6 +278,13 @@ static int build_headers(struct flb_http_client *c, struct flb_oci_logan *ctx,
         goto error_label;
     }
 
+    tmp_sds = NULL;
```
Comment (edsiper) [inline plugins/out_oracle_log_analytics/oci_logan.c:281]: this initialization is not needed since the next line will set the value

**Review by edsiper — CHANGES_REQUESTED** [review]

**Comment by edsiper** [comment]
Thanks for this contribution. Change requests:

- extra variable initialization is not needed
- fix the subject of the commit, it must start with: `out_oracle_analytics: ...`
- sign off the commits (DCO error)

File: plugins/out_oracle_log_analytics/oci_logan.c (hunk 1 above)
Comment (handsomecheung) [reply plugins/out_oracle_log_analytics/oci_logan.c:281]: sorry for mistakes. thank you for the changes.
