### PR TITLE
out_es: fix trace_error truncating the response

### LINKED ISSUE #5314: Do not truncate elasticsearch errors when Buffer_Size is set to False
## Bug Report

**Describe the bug**
It seems that even if `Buffer_Size` is set to `False` or to a very big number like `10m`, responses from the Elasticsearch HTTP service are still truncated.

**To Reproduce**
- Example log message if applicable:
```
[2022/04/15 09:14:17] [error] [output:es:es.1] error: Output
{"took":34,"errors":true,"items":[{"create":{"_index":"test-2022.04.14.22-000086","_id":"uxWALIABaLfE49Atc-4a","_version":1,"result":"created","_shards":{"total":2,"successful":2,"failed":0},"_seq_no":97650842,"_primary_term":4,"status":201}},{"create":{"_index":"test-2022.04.14.22-000086","_id":"vBWALIABaLfE49Atc-4a","_version":1,"result":"created","_shards":{"total":2,"successful":2,"failed":0},"_seq_no":98935675,"_primary_term":3,"status":201}},{"create":{"_index":"test-2022.04.14.22-000086","_id":"vRWALIABaLfE49Atc-4a","_version":1,"result":"created","_shards":{"total":2,"successful":2,"failed":0},"_seq_no":104317246,"_primary_term":4,"status":201}},{"create":{"_index":"test-2022.04.14.22-000086","_id":"vhWALIABaLfE49Atc-4a","_version":1,"result":"created","_shards":{"total":2,"successful":2,"failed":0},"_seq_no":98935676,"_primary_term":3,"status":201}},{"create":{"_index":"test-2022.04.14.22-000086","_id":"vxWALIABaLfE49Atc-4a","_version":1,"result":"created","_shards":{"total":2,"successful":2,"failed":0},"_seq_no":97650843,"_primary_term":4,"status":201}},{"create":{"_index":"test-2022.04.14.22-000086","_id":"wBWALIABaLfE49Atc-4a","_version":1,"result":"created","_shards":{"total":2,"successful":2,"failed":0},"_seq_no":98935678,"_primary_term":3,"status":201}},{"create":{"_index":"test-2022.04.14.22-000086","_id":"wRWALIABaLfE49Atc-4a","_version":1,"result":"created","_shards":{"total":2,"successful":2,"failed":0},"_seq_no":88055529,"_primary_term":4,"status":201}},{"create":{"_index":"test-2022.04.14.22-000086","_id":"whWALIABaLfE49Atc-4a","_version":1,"result":"created","_shards":{"total":2,"successful":2,"failed":0},"_seq_no":88055530,"_primary_term":4,"status":201}},{"create":{"_index":"test-2022.04.14.22-000086","_id":"wxWALIABaLfE49Atc-4a","_version":1,"result":"created","_shards":{"total":2,"successful":2,"failed":0},"_seq_no":88055531,"_primary_term":4,"status":201}},{"create":{"_index":"test-2022.04.14.22-000086","_id":"xBWALIABaLfE49Atc-4a","_version":1,"result":"created","_shards":{"total":2,"successful":2,"failed":0},"_seq_no":99960371,"_primary_term":4,"status":201}},{"create":{"_index":"test-2022.04.14.22-000086","_id":"xRWALIABaLfE49Atc-4a","_version":1,"result":"created","_shards":{"total":2,"successful":2,"failed":0},"_seq_no":104317247,"_primary_term":4,"status":201}},{"create":{"_index":"test-2022.04.14.22-000086","_id":"xhWALIABaLfE49Atc-4a","_version":1,"result":"created","_shards":{"total":2,"successful":2,"failed":0},"_seq_no":97650844,"_primary_term":4,"status":201}},{"create":{"_index":"test-2022.04.14.22-000086","_id":"xxWALIABaLfE49Atc-4a","_version":1,"result":"created","_shards":{"total":2,"successful":2,"failed":0},"_seq_no":99960372,"_primary_term":4,"status":201}},{"create":{"_index":"test-2022.04.14.22-000086","_id":"yBWALIABaLfE49Atc-4a","_version":1,"result":"created","_shards":{"total":2,"successful":2,"failed":0},"_seq_no":104317248,"_primary_term":4,"status":201}},{"create":{"_index":"test-2022.04.14.22-000086","_id":"yRWALIABaLfE49Atc-4a","_version":1,"result":"created","_shards":{"total":2,"successful":2,"failed":0},"_seq_no":88055532,"_primary_term":4,"status":201}},{"create":{"_index":"test-2022.04.14.22-000086","_id":"yhWALIABaLfE49Atc-4a","_version":1,"result":"created","_shards":{"total":2,"successful":2,"failed":0},"_seq_no":104317249,"_primary_term":4,"status":201}},{"create":{"_index":"test-2022.04.14.22-000086","_id":"yxWALIABaLfE49Atc-4a","_version":1,"result":"created","_shards":{"total":2,"successful":2,"failed":0},"_seq_no":97650845,"_primary_term":4,"status":201}},{"create":{"_index":"test-2022.04.14.22-000086","_id":"zBWALIABaLfE49Atc-4a","_version":1,"result":"created","_shards":{"total":2,"successful":2,"failed":0},"_seq_no":99960373,"_primary_term":4,"status":201}},{"create":{"_index":"test-2022.04.14.22-000086","_id":"zRWALIABaLfE49Atc-4a","_version":1,"result":"created","_shards":{"total":2,"successful":2,"fa
[2022/04/15 09:14:17] [ warn] [engine] failed to flush chunk '1-1649978824.248946957.flb', retry in 20 seconds: task_id=13, input=storage_backlog.1 > output=es.1 (out_id=1)

```
- Steps to reproduce the problem:
This is not very easy to reproduce but it seems that every time elasticsearch returns a long error, like in the case of a  `400` fluent-bit truncates it.
  
**Expected behavior**
Fluent-bit should not truncate the HTTP error.

**Your Environment**
Version used: 1.9.1
Configuration:
Environment name and version (e.g. Kubernetes? What version?): k8s v1.21.8
Server type and version: AWS EC2
Elasticsearch version: 8.1.2
Operating System and version: Flatcar Container Linux by Kinvolk 2905.2.6 (Oklo)
Filters and plugins:
```
    [SERVICE]
        Flush 5
        Grace 30
        Daemon Off
        Log_Level info
        Parsers_File parsers.conf
        Parsers_File custom_parsers.conf
        HTTP_Server On
        HTTP_Listen 0.0.0.0
        HTTP_Port 2020
        storage.path /var/log/fluent-bit-test//storage
        storage.sync normal
        storage.checksum off
        storage.backlog.mem_limit 20M
        storage.metrics on

    [INPUT]
        Name            tail
        Path            /var/log/containers/*_test_*.log
        Parser          docker
        Tag             kube.*
        Path_Key        log.file
        mem_buf_limit   10MB
        storage.type    filesystem
        Rotate_Wait     60
        DB              /var/log/fluent-bit-test/log.db
        DB.sync         normal
        DB.locking      true
        DB.journal_mode WAL
        Read_from_Head  true

    [FILTER]
        Buffer_Size 128k
        Name kubernetes
        Match kube.*
        Merge_Log On
        Keep_Log Off
        K8S-Logging.Parser On
        K8S-Logging.Exclude On
        Labels On
        Annotations On
        Kube_Tag_Prefix kube.var.logs.container.

    [FILTER]
        Name modify
        Match kube.*
        Rename log msg

    [FILTER]
        Name modify
        Match kube.*
        Remove date
        Remove @timestamp

    [FILTER]
        Name modify
        Match kube.*
        Set cluster development

    [FILTER]
        Name lua
        Match kube.*
        script /fluent-bit/scripts/fixKubernetesInfo.lua
        call transform

    [FILTER]
        Name lua
        Match kube.*
        script /fluent-bit/scripts/fixErrorObject.lua
        call transform

    [OUTPUT]
        Name s3
        Match *
        bucket mybucket
        region eu-west-1
        store_dir /var/log/fluent-bit-test//s3
        canned_acl bucket-owner-full-control
        s3_key_format /year=%Y/month=%m/day=%d/hour=%H/namespace=test/$TAG[4]_$UUID.json.gz
        s3_key_format_tag_delimiters ._
        compression gzip
        use_put_object True
        total_file_size 50M
        upload_timeout 5m
        auto_retry_requests True
        Retry_Limit False
        workers 1

    [OUTPUT]
        Name es
        Match *
        Host redacted.com
        Port 1234
        Buffer_Size False
        HTTP_User myuser
        HTTP_Passwd verysecret
        Index app-logs
        Include_Tag_Key On
        Tag_Key log.tags
        Time_Key log.read_at_time
        tls On
        tls.verify On
        Retry_Limit False
        Trace_Error On
```

### PR DESCRIPTION
**Pull request by PettitWesley**
Fixes #5314 5314

Signed-off-by: Wesley Pettit <wppttt@amazon.com>

----
Enter `[N/A]` in the box, if an item is not applicable to your change.

**Testing**
Before we can approve your change; please submit the following in a comment:
- [ ] Example configuration file for the change
- [ ] Debug log output from testing the change

- [ ] Attached [Valgrind](https://valgrind.org/docs/manual/quick-start.html) output that shows no leaks or memory corruption was found

If this is a change to packaging of containers or native binaries then please confirm it works for all targets.
- [ ] Attached [local packaging test](./packaging/local-build-all.sh) output showing all targets (including any new ones) build.

**Documentation**

- [ ] Documentation required for this feature

**Backporting**

- [ ] Backport to latest stable release.

----

Fluent Bit is licensed under Apache 2.0, by submitting this pull request I understand that this code will be released under the terms of that license.

### CODE REVIEW

File: plugins/out_es/es.c [hunk 1]
```diff
@@ -876,6 +876,7 @@ static void cb_es_flush(struct flb_event_chunk *event_chunk,
         }
 
         if (c->resp.payload_size > 0) {
+            flb_plg_error(ctx->ins, "Raw payload size: %zu", c->resp.payload_size);
```
Comment (PettitWesley) [inline plugins/out_es/es.c:879]: oops I need to remove this...

Comment (PettitWesley) [reply plugins/out_es/es.c]: fixed

File: plugins/out_es/es.c [hunk 2]
```diff
@@ -886,12 +886,13 @@ static void cb_es_flush(struct flb_event_chunk *event_chunk,
...
+                     * Trace_Output can be used to see the request. 
+                     * We must use fwrite since the flb_log functions
+                     * will truncate data. 
                      */
-                    flb_plg_debug(ctx->ins, "error caused by: Input\n%s\n",
-                                  pack);
-                    flb_plg_error(ctx->ins, "error: Output\n%s",
-                                  c->resp.payload);
+                    fwrite(c->resp.payload, 1, c->resp.payload_size, stdout);
+                    fflush(stdout);
```
Comment (nokute78) [inline plugins/out_es/es.c:895]: flb_log_ outputs logs to `stderr`.

```
$ bin/fluent-bit -i dummy -o s3 -vvv 2> stderr.txt
$ cat stderr.txt 
Fluent Bit v2.0.0
* Copyright (C) 2015-2022 The Fluent Bit Authors
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io

[2022/07/24 07:19:15] [ info] Configuration:
[2022/07/24 07:19:15] [ info]  flush time     | 1.000000 seconds
[2022/07/24 07:19:15] [ info]  grace          | 5 seconds
[2022/07/24 07:19:15] [ info]  daemon         | 0
[2022/07/24 07:19:15] [ info] ___________
[2022/07/24 07:19:15] [ info]  inputs:
[2022/07/24 07:19:15] [ info]      dummy
[2022/07/24 07:19:15] [ info] ___________
[2022/07/24 07:19:15] [ info]  filters:
[2022/07/24 07:19:15] [ info] ___________
[2022/07/24 07:19:15] [ info]  outputs:
[2022/07/24 07:19:15] [ info]      s3.0
[2022/07/24 07:19:15] [ info] ___________
[2022/07/24 07:19:15] [ info]  collectors:
[2022/07/24 07:19:15] [ info] [fluent bit] version=2.0.0, commit=53f2e45291, pid=3776
[2022/07/24 07:19:15] [debug] [engine] coroutine stack size: 24576 bytes (24.0K)
[2022/07/24 07:19:15] [ info] [storage] version=1.2.0, type=memory-only, sync=normal, checksum=disabled, max_chunks_up=128
[2022/07/24 07:19:15] [ info] [cmetrics] version=0.3.5
[2022/07/24 07:19:15] [debug] [dummy:dummy.0] created event channels: read=21 write=22
[2022/07/24 07:19:15] [debug] [s3:s3.0] created event channels: read=23 write=24
[2022/07/24 07:19:15] [error] [output:s3:s3.0] 'bucket' is a required parameter
[2022/07/24 07:19:15] [error] [output] failed to initialize 's3' plugin
[2022/07/24 07:19:15] [error] [lib] backend failed
[2022/07/24 07:19:15] [ info] [input] pausing dummy.0
$ 
```

File: plugins/out_es/es.c [hunk 3]
```diff
@@ -886,12 +886,13 @@ static void cb_es_flush(struct flb_event_chunk *event_chunk,
...
+                     * response from Elasticsearch explaining the problem.
+                     * Trace_Output can be used to see the request. 
+                     * We must use fwrite since the flb_log functions
+                     * will truncate data. 
                      */
-                    flb_plg_debug(ctx->ins, "error caused by: Input\n%s\n",
-                                  pack);
-                    flb_plg_error(ctx->ins, "error: Output\n%s",
-                                  c->resp.payload);
+                    fwrite(c->resp.payload, 1, c->resp.payload_size, stdout);
```
Comment (nokute78) [inline plugins/out_es/es.c:894]: This patch changes log format.

How about checking payload_size ?
If `c->resp.payload_size` is less than 4k (truncated size), use flb_plg_* to keep same format if the log will not be truncated.

**Review by nokute78 — CHANGES_REQUESTED** [review]
I added two comments.

File: plugins/out_es/es.c (hunk 3 above)
Comment (PettitWesley) [reply plugins/out_es/es.c:894]: Sure I can do that

Comment (PettitWesley) [reply plugins/out_es/es.c]: Fixed

**Comment by PettitWesley** [comment]
@nokute78 updated

**Review by nokute78 — CHANGES_REQUESTED** [review]
@PettitWesley Thank you for updating.
I missed a point that fluent-bit can write log to a file using `-l` option.
https://github.com/fluent/fluent-bit/blob/v1.9.6/src/flb_log.c#L65

I think it may be better to add/modify `flb_log_*` function at `flb_log.c`.
- Not to truncate log
- Take care a destination, stderr ? or file ?

**Comment by PettitWesley** [comment]
@nokute78 I agree that fixing the flb_log functions is more ideal, but I am not sure of the best way to do it. The size limitation seems very built into how the code works: https://github.com/fluent/fluent-bit/blob/v1.9.6/src/flb_log.c#L47

It seems like this code requires a max log message size... it can't be infinite. May be it should be user configurable? 

@edsiper

**Comment by edsiper** [comment]
there is a limitation because we use a pipe. we would need to move to a ring-buffer strategy for v2.0 (we already added a ring buffer api)

**Comment by PettitWesley** [comment]
@edsiper What should we do for now? We need to fix this bug before 2.0. Should we stick with my fix to print to stderr? But then as @nokute78 mentioned this isn't ideal since Fluent Bit supports `Log_File` in Service section and we will break that since stderr won't be directed to the log file.

**Comment by nokute78** [comment]
@PettitWesley Hmm, a workaround is 
- flb_log
  - Add new `flb_log_` API that returns a truncated limit size. It is a size of msg of `log_message` https://github.com/fluent/fluent-bit/blob/v1.9.6/src/flb_log.c#L47.
- out_es
  - Check if `resp_size` is greater than the limit size using new flb_log API.
  - If it is true, invoke `flb_plg_error` and passed log size should be the limit size.
  - Move `resp.payload` pointer , decrement `resp_size` and iterates until `resp_size` is 0.

File: plugins/out_es/es.c [hunk 4]
```diff
@@ -886,12 +886,24 @@ static void cb_es_flush(struct flb_event_chunk *event_chunk,
...
+                     * response from Elasticsearch explaining the problem.
+                     * Trace_Output can be used to see the request. 
                      */
-                    flb_plg_debug(ctx->ins, "error caused by: Input\n%s\n",
-                                  pack);
-                    flb_plg_error(ctx->ins, "error: Output\n%s",
-                                  c->resp.payload);
+                    if (pack_size < 4000) {
+                        flb_plg_debug(ctx->ins, "error caused by: Input\n%s\n",
+                                      pack);
```
Comment (gitfool) [inline plugins/out_es/es.c:894]: @PettitWesley this needs the fix too.

Comment (PettitWesley) [reply plugins/out_es/es.c:894]: oops

Comment (PettitWesley) [reply plugins/out_es/es.c:894]: thanks for checking

File: plugins/out_es/es.c [hunk 5]
```diff
@@ -886,12 +886,24 @@ static void cb_es_flush(struct flb_event_chunk *event_chunk,
...
                      * If trace_error is set, trace the actual
-                     * input/output to Elasticsearch that caused the problem.
+                     * response from Elasticsearch explaining the problem.
+                     * Trace_Output can be used to see the request. 
                      */
-                    flb_plg_debug(ctx->ins, "error caused by: Input\n%s\n",
-                                  pack);
-                    flb_plg_error(ctx->ins, "error: Output\n%s",
-                                  c->resp.payload);
+                    if (pack_size < 4000) {
```
Comment (gitfool) [inline plugins/out_es/es.c:892]: Shouldn't this be `4096` or are you purposefully short of exactly 4KB?

Comment (PettitWesley) [reply plugins/out_es/es.c:892]: I need to test this if we go with it. But yea that was the thought- I think it needs to be less than the actual limit, but need to check it by testing. 

The current recommended solution from Takahiro & Eduardo here is to iteratively write 4KB blocks of the response via the flb_log function... by creating new functions that return the actual number of bytes processed, which I bet is less than 4KB since each message gets the timestamp and plugin name added to it...

**Comment by PettitWesley** [comment]
@nokute78 @edsiper Sorry, but I'm no longer feeling strongly about allocating my effort to build a new `flb_log` style function that can return the amount of bytes read so we can iteratively write the buffer.

**Why?**

1. This actually won't necessarily be better for the user. See each log msg is not guaranteed to be written sequentially to stdout/wherever AFAICT. If you have multiple threads running and pushing logs, it can get intermixed. So then the payload may become unreadable.
2. This is a debugging option, and I think as a short term fix it does not need to have the most perfect experience. In my interactions with customers, I rarely ever encounter someone using the log file option. (Which is the reason for this more complicated proposal, if we only cared about stdout/stderr, then we could just use `printf`).



I would like to contribute the fix that I have here as a short term improvement that gets us closer to the ideal. 

```
                    if (c->resp.payload_size < 4000) {
                        flb_plg_error(ctx->ins, "error: Output\n%s",
                                      c->resp.payload);
                    } else {
                        /*
                        * We must use fwrite since the flb_log functions
                        * will truncate data at 4KB
                        */
                        fwrite(c->resp.payload, 1, c->resp.payload_size, stderr);
                        fflush(stderr);
                    }
```

**Why truncate at 4000 not 4096?**

First of all, the log message buffer is slightly smaller than 4096: https://github.com/fluent/fluent-bit/blob/master/src/flb_log.c#L47

And then it always has to add the header with timestamp and plugin name (including hidden chars for formatting), so the idea is that we don't know how big that bit is, and as a short term fix, 4000 is a safe number, we can always print at least 4000 bytes. 

In the future, we could improve this further, **but this short term fix will unblock my customer who reported it.**

**Comment by edsiper** [comment]
sounds good to me to merge this now. 

@nokute78 I like the idea of https://github.com/fluent/fluent-bit/pull/5761#issuecomment-1200331827 where the logger api can truncate the message size.. can you implement that ?

**Comment by nokute78** [comment]
@edsiper  I created a patch https://github.com/fluent/fluent-bit/pull/5952 .
Could you check it ?
