### PR TITLE
config_format: yaml: fix 'customs' section handling(#7559)

### LINKED ISSUE #7559: Custom sections cause YAML parser error
## Steps to reproduce.

Specify a custom entry in the configuration.

```yaml
customs:
  - name: calyptia

pipeline:
  inputs:
    - name: fluentbit_metrics
      scrape_interval: 30
      scrape_on_start: true
      tag: _calyptia_cloud
service:
  HTTP_Listen: 0.0.0.0
  HTTP_PORT: 2020
  HTTP_Server: 'On'
  Log_Level: debug
```
Run this command:

```
docker run -v $(pwd)/test.yaml:/config/fluent-bit.yaml fluent/fluent-bit:latest -c /config/fluent-bit.yaml -vvvv
```

### Actual results

```
Fluent Bit v2.1.4
* Copyright (C) 2015-2022 The Fluent Bit Authors
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io

[2023/06/14 09:23:26] [error] [config] YAML error found in file "/config/fluent-bit.yaml", line 2, column 10: unexpected event 'scalar-event' (6) in state 15.
[2023/06/14 09:23:26] [error] configuration file contains errors, aborting.
```

### Expected results

Parsing works and the custom section gets loaded correctly.

### PR DESCRIPTION
**Pull request by nokute78**
Fixes #7559 

This patch is to fix yaml config file parser to handle 'customs' section.

----
Enter `[N/A]` in the box, if an item is not applicable to your change.

**Testing**
Before we can approve your change; please submit the following in a comment:
- [X] Example configuration file for the change
- [X] Debug log output from testing the change

- [X] Attached [Valgrind](https://valgrind.org/docs/manual/quick-start.html) output that shows no leaks or memory corruption was found

If this is a change to packaging of containers or native binaries then please confirm it works for all targets.
- [N/A] Run [local packaging test](./packaging/local-build-all.sh) showing all targets (including any new ones) build.
- [N/A] Set `ok-package-test` label to test for all targets (requires maintainer to do).

**Documentation**

- [N/A] Documentation required for this feature

**Backporting**

- [N/A] Backport to latest stable release.

## Configuration 

```
customs:
  - name: calyptia

pipeline:
  inputs:
    - name: fluentbit_metrics
      scrape_interval: 30
      scrape_on_start: true
      tag: _calyptia_cloud
service:
  HTTP_Listen: 0.0.0.0
  HTTP_PORT: 2020
  HTTP_Server: 'On'
  Log_Level: debug
```

## Debug/Valgrind output

```
$ valgrind --leak-check=full bin/flb-it-config_format_yaml
Test customs section...                         > section:
  name: customs
  type: CUSTOM
  properties:
    - name           : calyptia
  groups    : NONE
> section:
  name: INPUT
  type: INPUT
  properties:
    - name           : fluentbit_metrics
    - scrape_interval: 30
    - scrape_on_start: true
    - tag            : _calyptia_cloud
  groups    : NONE
> section:
  name: service
  type: SERVICE
  properties:
    - http_listen    : 0.0.0.0
    - http_port      : 2020
    - http_server    : On
    - log_level      : debug
  groups    : NONE
[ OK ]
==58970== Warning: invalid file descriptor -1 in syscall close()
==58970== 
==58970== HEAP SUMMARY:
==58970==     in use at exit: 0 bytes in 0 blocks
==58970==   total heap usage: 1,036 allocs, 1,036 frees, 163,766 bytes allocated
==58970== 
==58970== All heap blocks were freed -- no leaks are possible
==58970== 
==58970== For lists of detected and suppressed errors, rerun with: -s
==58970== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
SUCCESS: All unit tests have passed.
==58968== 
==58968== HEAP SUMMARY:
==58968==     in use at exit: 0 bytes in 0 blocks
==58968==   total heap usage: 3 allocs, 3 frees, 1,093 bytes allocated
==58968== 
==58968== All heap blocks were freed -- no leaks are possible
==58968== 
==58968== For lists of detected and suppressed errors, rerun with: -s
==58968== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
```

----

Fluent Bit is licensed under Apache 2.0, by submitting this pull request I understand that this code will be released under the terms of that license.

### CODE REVIEW

File: src/config_format/flb_cf_yaml.c [hunk 1]
```diff
@@ -453,7 +566,7 @@ static int consume_event(struct flb_cf *cf, struct local_ctx *ctx,
     case STATE_CUSTOM:
         switch (event->type) {
         case YAML_SEQUENCE_START_EVENT:
-            s->state = STATE_CUSTOM_SEQUENCE;
+            s->state = STATE_PLUGIN_TYPE;
```
Comment (nokute78) [inline src/config_format/flb_cf_yaml.c:569]: 'customs' section is for custom plugin.
So I set `STATE_PLUGIN_TYPE` like other plugins.
