### PR TITLE
Issue 2734: Fix support for more than 32 output plugins

### LINKED ISSUE #2734: FluentBit 1.6.1+ with kafka-rest: data ends up in multiple Kafka topics (should be in just one)
## Bug Report

**Describe the bug**
Below is a simplified config for 2 outputs:
```
    [OUTPUT]
        Name              kafka-rest
        Include_Tag_Key   On
        Tag_Key           sourcetype
        Match             tas.backgrounder.log.raw
        Topic             tas.backgrounder.log.raw
    [OUTPUT]
        Name              kafka-rest
        Include_Tag_Key   On
        Tag_Key           sourcetype
        Match             tas.hyper.control.raw
        Topic             tas.hyper.control.raw
```

I currently use v1.3.3 and v1.4.5 in two different environments and in each of them when I consume from `tas.backgrounder.log.raw` Kafka topic - I only get events with `sourcetype` of `tas.backgrounder.log.raw` and content from log files that were tagged with `tas.backgrounder.log.raw` during INPUT stage. Same with `tas.hyper.control.raw`.

However, when using v1.6.1+ (I tried v1.6.1 and 1.6.2) in the `tas.backgrounder.log.raw` topic I see events belonging to both `tas.backgrounder.log.raw` and `tas.hyper.control.raw` tags. And the same goes for the `tas.hyper.control.raw` Kafka topic.

**To Reproduce**

I realize the infrastructure is complex. I'm willing to demo the issue via a web call / screen share.

- Steps to reproduce the problem: install v1.6.1 or 1.6.2

**Expected behavior**
Each Kafka topic has only events for the corresponding tag

**Your Environment**

* Version used: 1.3.3 (td-agent-bit, standalone hosts) and 1.4.5 (fluent-bit, AWS EKS)
* Configuration: config file used with v1.4.5 in AWS EKS is attached. 
* Environment name and version (e.g. Kubernetes? What version?): used with v1.4.5: EKS 1.17
* Operating System and version: used with v1.3.3: CentOS 7
* Filters and plugins: tail, kafka-rest, rewrire_tag, lua

**Additional context**
We want to use fluent-bit/td-agent-bit as the collection agent for all logs. Raw logs are sent to Kafka where they are preprocessed (time zone is fixed, parsed) and are made available for other teams.
[fb-bug-repro-config.yaml.gz](https://github.com/fluent/fluent-bit/files/5455295/fb-bug-repro-config.yaml.gz)

Today, we have 60+ file globs in Kubernetes and 180+ for standalone hosts. The max number of open files i saw on Kubernetes was over 8,000.

### PR DESCRIPTION
**Pull request by jlunavtgrad**
This patch increases the size of the bitfield used to keep track of which
output plugins a chunk is routed to. The previous implementation used 
a single uint64_t bitfield which can support up to 64 output plugins,
but due to an implicit conversion to 32-bit values would fail if more than
32 outputs were specified. 

This implementation supports an arbitrary number of outputs, with the 
limit defined by `FLB_ROUTES_MASK_ELEMENTS`.

flb_routes_mask.c defines helper methods for getting, setting, and clearing 
bits in the router mask bitfield. The bitfield is stored as an array of uint64_t
values where each bit is used to determine if an input chunk is to be routed 
to a given output plugin. The output plugin's bit position is determined by 
the id given to the instance. Ids are assigned sequentially starting from 0.

This patch also removes `mask_id` from the `flb_output_instance` struct
which was previously used to keep track of which bit in the
`flb_input_chunk.routes_mask` an output instance was associated
with.

Fixes #2734

----
**Testing**
Before we can approve your change; please submit the following in a comment:
- [ ] Example configuration file for the change
[fluentbit-reduced-inputs.txt](https://github.com/fluent/fluent-bit/files/5722292/fluentbit-reduced-inputs.txt)
- [ ] Debug log output from testing the change
[logs.txt](https://github.com/fluent/fluent-bit/files/5722287/logs.txt)

- [N/A] Attached [Valgrind](https://valgrind.org/docs/manual/quick-start.html) output that shows no leaks or memory corruption was found

**Documentation**

- [N/A] Documentation required for this feature

----

Fluent Bit is licensed under Apache 2.0, by submitting this pull request I understand that this code will be released under the terms of that license.

### CODE REVIEW

**Comment by edsiper** [comment]
@JeffLuoo can you help on reviewing this one ?

File: src/flb_input_chunk.c [hunk 1]
```diff
@@ -260,21 +257,21 @@ int flb_input_chunk_find_space_new_data(struct flb_input_chunk *ic,
 }
 
 /*
- * Returns routes_mask of output instances that will reach the limit
+ * Returns a non-zero result if any output instances will reach the limit
  * after buffering the new data
  */
-uint64_t flb_input_chunk_get_overlimit_routes_mask(struct flb_input_chunk *ic,
+int flb_input_chunk_has_overlimit_routes(struct flb_input_chunk *ic,
                                                    size_t chunk_size)
```
Comment (JeffLuoo) [inline src/flb_input_chunk.c:264]: nit: indentation

File: src/flb_output.c [hunk 2]
```diff
@@ -249,17 +249,6 @@ struct flb_output_instance *flb_output_new(struct flb_config *config,
         return NULL;
     }
```
Comment (JeffLuoo) [inline src/flb_output.c:251]: line 242: mask_id can be removed as the new implementation will use the id only.

**Review by JeffLuoo — COMMENTED** [review]
Hi, @jlunavtgrad Thank you for your contribution!! Overall the patch LGTM and just some minor issues as I commented.

@edsiper Could you please review it again to see if I missed anything? Thank you!

File: src/flb_output.c (hunk 2 above)
Comment (jlunavtgrad) [reply src/flb_output.c:251]: Good catch

File: src/flb_input_chunk.c (hunk 1 above)
Comment (jlunavtgrad) [reply src/flb_input_chunk.c]: Fixed

**Comment by jlunavtgrad** [comment]
Thanks @JeffLuoo! It's been a while since I worked in C, kinda fun to get back to it. Thanks for reviewing

**Comment by jlunavtgrad** [comment]
@edsiper I hope this fix gets pulled in, the issue it resolves blocked my team from upgrading for several months. We are going forward with a forked build for now, but don't want to maintain that if we don't have to.

**Comment by edsiper** [comment]
Hi, we were busy re-architecting for multi-threading support, would you please adjust the PR on top of GIT master ?

**Comment by jlunavtgrad** [comment]
Whoa, multithreading!? I rebased my code on top of master and ran it through my ad-hoc integration tests. The latest code definitely performs better since it now overwhelms my test setup with kakfa rest proxy. Is there a way to turn down the threading so I can run my latest build through my test plan?

**Comment by edsiper** [comment]
@jlunavtgrad thanks for working on this PR, I think we are in good timing to merge it before v1.7 release which happens in a few days.

Note that multi-threading support for output plugins should not be an issue for your implementation, what runs "optionally" in a separate thread is the flush callback of every plugin, but every that is about plugin initialization and exit runs in the parent thread.

**Comment by edsiper** [comment]
pls fix the latest conflict reflected by latest changes on  src/flb_output.c

**Comment by jlunavtgrad** [comment]
@edsiper I updated the conflicting file. Thanks for getting this in

**Comment by edsiper** [comment]
thanks!
