### PR TITLE
pipe: add flb_pipe_error

### LINKED ISSUE #3146: flb_errno printing wrong error codes on windows
On windows, the flp_errno routine does not print the error codes of the errors that actually happen.

For example: in dlb_io.c:255, net_io_write_async can return, because FLB_WOULDBLOCK detected the socket would block by looking at WSAGetLastError. The caller (flb_http_client.c:1161) notices the error and tries to do error reporting with flb_errno. However, flb_errno only checks errno, not WSAGetLastError, which contains the appropriate error code windows. Consequently, the error messages look like this:

`[2021/03/02 12:29:00] [error] [O:\fluent-bit\src\flb_http_client.c:1161 errno=0] No error`

Not very helpful. I expect the error routine to output the actual error from WSAGetLastError.

To reproduce, tail a file to an elasticsearch output where the host is unreachable on windows.

### PR DESCRIPTION
**Pull request by braydonk**
On Windows, the `flb_pipe_r` and `flb_pipe_w` macros do not set errno on failure, meaning calling `flb_errno` in error scenarios is insufficient. This PR adds a new macro that will check the correct place, `WSAGetLastError`, and output a similar error message. On Linux this will still be `flb_errno`, meaning messages should work the same as they always did, but now on Windows we will get actual error messages.

Fixes #3146

----
Enter `[N/A]` in the box, if an item is not applicable to your change.

**Testing**
Before we can approve your change; please submit the following in a comment:

- [ ] Example configuration file for the change
- [ ] Debug log output from testing the change

I had trouble finding a scenario wherein a proper `winsock.h` failure is propagated. In #3146 they mentioned sending to an elasticsearch host that is not available, but the pattern for how the http client handles that error appears to have changed such that a direct pipe read error isn't propagated.

To test the log format, I made this local change on Windows:
```diff
--- a/src/flb_utils.c
+++ b/src/flb_utils.c
@@ -494,7 +494,9 @@ int flb_utils_timer_consume(flb_pipefd_t fd)
     int ret;
     uint64_t val;

-    ret = flb_pipe_r(fd, &val, sizeof(val));
+    // ret = flb_pipe_r(fd, &val, sizeof(val));
+    ret = -1;
+    WSASetLastError(WSAEADDRINUSE);
     if (ret == -1) {
         flb_pipe_error();
         return -1;
```
Resulting log:
```
[2025/02/27 18:01:58] [error] [C:\Users\braydonk\Git\fluent-bit\src\flb_utils.c:501 WSAGetLastError=10048] Only one usage of each socket address (protocol/network address/port) is normally permitted.
```
On Linux I made the following similar local change:
```diff
--- a/src/flb_utils.c
+++ b/src/flb_utils.c
@@ -494,7 +494,9 @@ int flb_utils_timer_consume(flb_pipefd_t fd)
     int ret;
     uint64_t val;
 
-    ret = flb_pipe_r(fd, &val, sizeof(val));
+    // ret = flb_pipe_r(fd, &val, sizeof(val));
+    ret = -1;
+    errno = EADDRINUSE;
     if (ret == -1) {
         flb_pipe_error();
         return -1;
```
And this is the resulting error message:
```
[2025/02/28 13:57:17] [error] [/usr/local/google/home/braydonk/Git/fluent-bit/src/flb_utils.c:501 errno=98] Address already in use
``` 

- [ ] Attached [Valgrind](https://valgrind.org/docs/manual/quick-start.html) output that shows no leaks or memory corruption was found

**Documentation**

Docs PR should not be required.

**Backporting**
- [x] Backport to latest stable release.

----

Fluent Bit is licensed under Apache 2.0, by submitting this pull request I understand that this code will be released under the terms of that license.

### CODE REVIEW

**Comment by braydonk** [comment]
That `s390x` failure doesn't look related to this PR.

File: include/fluent-bit/flb_log.h [hunk 1]
```diff
@@ -232,11 +232,18 @@ static inline int flb_log_suppress_check(int log_suppress_interval, const char *
 int flb_log_worker_init(struct flb_worker *worker);
 int flb_log_worker_destroy(struct flb_worker *worker);
 int flb_errno_print(int errnum, const char *file, int line);
+int flb_WSAGetLastError_print(int errnum, const char *file, int line);
```
Comment (leonardo-albertovich) [inline include/fluent-bit/flb_log.h:235]: Could you please change these names to follow the coding style?

File: include/fluent-bit/flb_log.h [hunk 2]
```diff
@@ -232,11 +232,18 @@ static inline int flb_log_suppress_check(int log_suppress_interval, const char *
...
 
 #ifdef __FLB_FILENAME__
 #define flb_errno() flb_errno_print(errno, __FLB_FILENAME__, __LINE__)
+#ifdef WIN32
+#define flb_WSAGetLastError() flb_WSAGetLastError_print(WSAGetLastError(), __FLB_FILENAME__, __LINE__)
```
Comment (leonardo-albertovich) [inline include/fluent-bit/flb_log.h:240]: Could you please change these names to follow the coding style?

File: src/flb_log.c [hunk 3]
```diff
@@ -121,7 +126,7 @@ static inline int log_read(flb_pipefd_t fd, struct flb_log *log)
     bytes = flb_pipe_read_all(fd, &msg, sizeof(struct log_message));
 
     if (bytes <= 0) {
-        flb_errno();
+        flb_pipe_error();
```
Comment (leonardo-albertovich) [inline src/flb_log.c:129]: In this case there is an `flb_error` call in the second error exitt code path inside of `flb_pipe_read_all` which could cause confusion, could you remove it?

File: src/flb_log.c [hunk 4]
```diff
@@ -745,6 +750,17 @@ int flb_errno_print(int errnum, const char *file, int line)
...
+int flb_WSAGetLastError_print(int errnum, const char *file, int line)
+{
+#ifdef WIN32
+    char buf[256];
+    FormatMessage(FORMAT_MESSAGE_FROM_SYSTEM | FORMAT_MESSAGE_IGNORE_INSERTS,
+                  NULL, errnum, MAKELANGID(LANG_NEUTRAL, SUBLANG_DEFAULT),
+                  buf, sizeof(buf), NULL);
+    flb_error("[%s:%i WSAGetLastError=%i] %s", file, line, errnum, buf);
+#endif
+}
```
Comment (leonardo-albertovich) [inline src/flb_log.c:762]: Please add a return value or change the return type to `void`

File: src/flb_log.c [hunk 5]
```diff
@@ -745,6 +750,17 @@ int flb_errno_print(int errnum, const char *file, int line)
     return 0;
 }
 
+int flb_WSAGetLastError_print(int errnum, const char *file, int line)
+{
+#ifdef WIN32
```
Comment (leonardo-albertovich) [inline src/flb_log.c:755]: Would it be better to make the body of the function or the whole function conditional? 
This function is only referenced by `flb_WSAGetLastError` if our target is Windows so I don't think making the whole thing conditional would be a problem.

File: include/fluent-bit/flb_log.h (hunk 2 above)
Comment (leonardo-albertovich) [reply include/fluent-bit/flb_log.h:240]: I think this function should be renamed, otherwise the current name suggests it would return the error code rather than printing it.

**Review by leonardo-albertovich — CHANGES_REQUESTED** [review]

File: src/flb_log.c (hunk 5 above)
Comment (braydonk) [reply src/flb_log.c]: Yep fair assessment. Done in [7a1429c](https://github.com/fluent/fluent-bit/pull/10017/commits/7a1429c720b7ac8aa9d74943b44be7c2743678cf)

File: src/flb_log.c (hunk 4 above)
Comment (braydonk) [reply src/flb_log.c:760]: Added a return value to keep it lined up with `flb_errno` in [7a1429c](https://github.com/fluent/fluent-bit/pull/10017/commits/7a1429c720b7ac8aa9d74943b44be7c2743678cf)

File: src/flb_log.c (hunk 3 above)
Comment (braydonk) [reply src/flb_log.c]: Good catch, fixed in [7a1429c](https://github.com/fluent/fluent-bit/pull/10017/commits/7a1429c720b7ac8aa9d74943b44be7c2743678cf)

File: include/fluent-bit/flb_log.h (hunk 2 above)
Comment (leonardo-albertovich) [reply include/fluent-bit/flb_log.h:242]: I'd appreciate it if you named it `flb_wsa_get_last_error`. 

I agree with you that `flb_errno` presents the same issue in terms of its name but as you might imagine changing its name would involve a boat load of changes which even if minimal would be super noisy so it might not be the right time for that.

What do you think of having both `flb_errno` and `flb_wsa_get_last_error_print` return the error code in addition to printing it just as a first step?

I understand that this would basically eat the error code that the function itself could generate (if error conditions were handled) which could make this a step in the wrong direction so let me know what you think about that.

The "critical" thing to me is changing those names from camel case to snake case.

Comment (braydonk) [reply include/fluent-bit/flb_log.h]: Although no callers will currently use that return value, I don't see any actual harm in simply returning the `errnum` value. Did that along with the rename in [429bbe1](https://github.com/fluent/fluent-bit/pull/10017/commits/429bbe1a0828c848ad19e2b4ba4ffa15c183efce)

**Review by leonardo-albertovich — APPROVED** [review]
