### PR TITLE
tail: Fix handling of long lines

### LINKED ISSUE #3491: Tail plugin line handling issues
## Bug Report

A recent change (dab53392096f2764af85a5230d0ac0de9879f74f) introduce a fix for null character handling, but interferes with the way lines are handled in a few cases.

- Long lines
 Long lines are supposed to progressively grow the buffer until the line fits, or max_buffer_size is reached. Then the line can be skipped, or the file will be marked as failed. The new behavior doesn't grow the buffer and skips along until the last portion of the line is found. The remaining portion of the line is ingested instead of being skipped.

- Unterminated lines
If an unterminated line is read into the buffer the old behavior is to wait (indefinitely) for a terminating character. The new behavior is to skip any unterminated data in the buffer.

**To Reproduce**
- Config 
```
[INPUT]
  Name tail
  Path test.log
  Buffer_Max_Size 32mb
  Skip_Long_Lines On
  Read_From_Head On

[OUTPUT]
  Name file
  Match *
  Path output.txt
```
- Long line that should be read completely
```

# generate a long line, but not longer than Buffer_Max_Size
openssl rand -hex 32000 >> test.log
# check length of input
tail -n 1 test.log | wc -c
64001
# check length of output
tail -n 1 output/tail.0 | cut -d " " -f2- | jq -r ".[1].log" | wc -c
2561 # <-- expect 64001
```
- Incomplete log line that shouldn't be ingested
```
# Partial log line, not terminated with line ending
echo -n "hello " >> test.log
# The rest of the line, with line ending
echo "world" >> test.log
# check the output
tail -n 1 output/tail.0 | cut -d " " -f2- | jq -r ".[1].log"
world    # <-- expect hello world
```

**Your Environment**

* Version used: 1.8.0
* Operating System and version: linux
* Filters and plugins: tail

**Additional context**
I have a fix for this bug in pull request #3490

### PR DESCRIPTION
**Pull request by jlunavtgrad**
This patch restores the behavior of skipping a line that is longer than buffer_max_size. A recent change (dab53392096f2764af85a5230d0ac0de9879f74f) modified the behavior of long line handling and prevented buffer sizes from growing to accommodate long lines and caused the end portion of the line to be ingested rather than skipped. This patch also ensures that the file offset is properly maintained when skipping long lines.

Signed-off-by: Joaquin Luna <jlunavtgrad@gmail.com>

Fixes #3491

----
**Testing**

- Generate test log file
```bash
# null chars at the beginning
printf "\0\0\0hello world\n" > test.log
# 50 regular lines
for i in `seq 1 50`; do openssl rand -hex 100 >> test.log; done
# One very long line
openssl rand -hex 320000 >> test.log
# 25 more lines of data
for i in `seq 1 25`; do openssl rand -hex 100 >> test.log; done
```
- config file
```
[INPUT]
  Name tail
  Path test.log
  DB fluent-bit.db
  Skip_Long_Lines On
  Read_From_Head On

[OUTPUT]
  Name counter
  Match *
```
- Verify offsets after test
```bash
stat -c%s test.log
180470921
sqlite3 fluent-bit.db "select offset from in_tail_files"
180470921
```

- Test logs
```
[2021/05/16 04:29:45] [ info] Configuration:
[2021/05/16 04:29:45] [ info]  flush time     | 5.000000 seconds
[2021/05/16 04:29:45] [ info]  grace          | 5 seconds
[2021/05/16 04:29:45] [ info]  daemon         | 0
[2021/05/16 04:29:45] [ info] ___________
[2021/05/16 04:29:45] [ info]  inputs:
[2021/05/16 04:29:45] [ info]      tail
[2021/05/16 04:29:45] [ info] ___________
[2021/05/16 04:29:45] [ info]  filters:
[2021/05/16 04:29:45] [ info] ___________
[2021/05/16 04:29:45] [ info]  outputs:
[2021/05/16 04:29:45] [ info]      counter.0
[2021/05/16 04:29:45] [ info] ___________
[2021/05/16 04:29:45] [ info]  collectors:
[2021/05/16 04:29:45] [ info] [engine] started (pid=18893)
[2021/05/16 04:29:45] [debug] [engine] coroutine stack size: 24576 bytes (24.0K)
[2021/05/16 04:29:45] [debug] [storage] [cio stream] new stream registered: tail.0
[2021/05/16 04:29:45] [ info] [storage] version=1.1.1, initializing...
[2021/05/16 04:29:45] [ info] [storage] in-memory
[2021/05/16 04:29:45] [ info] [storage] normal synchronization mode, checksum disabled, max_chunks_up=128
[2021/05/16 04:29:45] [debug] [input:tail:tail.0] inotify watch fd=23
[2021/05/16 04:29:45] [debug] [input:tail:tail.0] scanning path test.log
[2021/05/16 04:29:45] [debug] [input:tail:tail.0] inode=2951839 with offset=0 appended as test.log
[2021/05/16 04:29:45] [debug] [input:tail:tail.0] scan_glob add(): test.log, inode 2951839
[2021/05/16 04:29:45] [debug] [input:tail:tail.0] 1 new files found on path 'test.log'
[2021/05/16 04:29:45] [debug] [counter:counter.0] created event channels: read=27 write=28
[2021/05/16 04:29:45] [debug] [router] match rule tail.0:counter.0
[2021/05/16 04:29:45] [ info] [sp] stream processor started
[2021/05/16 04:29:45] [ warn] [input:tail:tail.0] file=test.log have long lines. Skipping long lines.
[2021/05/16 04:29:45] [debug] [input:tail:tail.0] inode=2951839 file=test.log promote to TAIL_EVENT
[2021/05/16 04:29:45] [ info] [input:tail:tail.0] inotify_fs_add(): inode=2951839 watch_fd=1 name=test.log
[2021/05/16 04:29:49] [debug] [task] created task=0x7f44a9037960 id=0 OK
1621139389.708933,30 (total = 76)
[2021/05/16 04:29:49] [debug] [out coro] cb_destroy coro_id=0
[2021/05/16 04:29:49] [debug] [task] destroy task=0x7f44a9037960 (task_id=0)
^C[2021/05/16 04:29:51] [engine] caught signal (SIGINT)
[2021/05/16 04:29:51] [ info] [input] pausing tail.0
[2021/05/16 04:29:51] [ warn] [engine] service will stop in 5 seconds
^[[A[2021/05/16 04:29:55] [ info] [engine] service stopped
[2021/05/16 04:29:55] [debug] [input:tail:tail.0] inode=2951839 removing file name test.log
[2021/05/16 04:29:55] [ info] [input:tail:tail.0] inotify_fs_remove(): inode=2951839 watch_fd=1

### CODE REVIEW

**Comment by jlunavtgrad** [comment]
Tagging @jsjeannotte for visibility

**Comment by jlunavtgrad** [comment]
Also tagging @nokute78 since you helped identify the problem with long line handling

**Comment by nokute78** [comment]
@jlunavtgrad  Thank you for contribution.

Before reviewing, can you check DCO and valgrind output ?
* CI reports that DCO needs action.
* Valgrind reports `Conditional jump or move depends on uninitialised value(s)`. 

I tested your configuration and test.log.
Valgrind reports errors.
```
$ valgrind --leak-check=full bin/fluent-bit -c a.conf 
==25971== Memcheck, a memory error detector
==25971== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==25971== Using Valgrind-3.15.0 and LibVEX; rerun with -h for copyright info
==25971== Command: bin/fluent-bit -c a.conf
==25971== 
Fluent Bit v1.8.0
* Copyright (C) 2019-2021 The Fluent Bit Authors
* Copyright (C) 2015-2018 Treasure Data
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io

[2021/05/17 20:45:27] [ info] [engine] started (pid=25971)
[2021/05/17 20:45:27] [ info] [storage] version=1.1.1, initializing...
[2021/05/17 20:45:27] [ info] [storage] in-memory
[2021/05/17 20:45:27] [ info] [storage] normal synchronization mode, checksum disabled, max_chunks_up=128
[2021/05/17 20:45:28] [ info] [sp] stream processor started
==25971== Thread 2 flb-pipeline:
==25971== Conditional jump or move depends on uninitialised value(s)
==25971==    at 0x48429FA: memmove (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==25971==    by 0x1C7C92: consume_bytes (tail_file.c:50)
==25971==    by 0x1CAA72: flb_tail_file_chunk (tail_file.c:1004)
==25971==    by 0x1C201B: in_tail_collect_static (tail.c:140)
==25971==    by 0x174A5F: flb_input_collector_fd (flb_input.c:1022)
==25971==    by 0x1864EB: flb_engine_handle_event (flb_engine.c:363)
==25971==    by 0x1864EB: flb_engine_start (flb_engine.c:617)
==25971==    by 0x16907C: flb_lib_worker (flb_lib.c:605)
==25971==    by 0x4864608: start_thread (pthread_create.c:477)
==25971==    by 0x4B10292: clone (clone.S:95)
==25971== 
==25971== Conditional jump or move depends on uninitialised value(s)
==25971==    at 0x4842A11: memmove (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==25971==    by 0x1C7C92: consume_bytes (tail_file.c:50)
==25971==    by 0x1CAA72: flb_tail_file_chunk (tail_file.c:1004)
==25971==    by 0x1C201B: in_tail_collect_static (tail.c:140)
==25971==    by 0x174A5F: flb_input_collector_fd (flb_input.c:1022)
==25971==    by 0x1864EB: flb_engine_handle_event (flb_engine.c:363)
==25971==    by 0x1864EB: flb_engine_start (flb_engine.c:617)
==25971==    by 0x16907C: flb_lib_worker (flb_lib.c:605)
==25971==    by 0x4864608: start_thread (pthread_create.c:477)
==25971==    by 0x4B10292: clone (clone.S:95)
==25971== 
==25971== Conditional jump or move depends on uninitialised value(s)
==25971==    at 0x4842A20: memmove (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==25971==    by 0x1C7C92: consume_bytes (tail_file.c:50)
==25971==    by 0x1CAA72: flb_tail_file_chunk (tail_file.c:1004)
==25971==    by 0x1C201B: in_tail_collect_static (tail.c:140)
==25971==    by 0x174A5F: flb_input_collector_fd (flb_input.c:1022)
==25971==    by 0x1864EB: flb_engine_handle_event (flb_engine.c:363)
==25971==    by 0x1864EB: flb_engine_start (flb_engine.c:617)
==25971==    by 0x16907C: flb_lib_worker (flb_lib.c:605)
==25971==    by 0x4864608: start_thread (pthread_create.c:477)
==25971==    by 0x4B10292: clone (clone.S:95)
==25971== 
==25971== Conditional jump or move depends on uninitialised value(s)
==25971==    at 0x4842B08: memmove (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==25971==    by 0x1C7C92: consume_bytes (tail_file.c:50)
==25971==    by 0x1CAA72: flb_tail_file_chunk (tail_file.c:1004)
==25971==    by 0x1C201B: in_tail_collect_static (tail.c:140)
==25971==    by 0x174A5F: flb_input_collector_fd (flb_input.c:1022)
==25971==    by 0x1864EB: flb_engine_handle_event (flb_engine.c:363)
==25971==    by 0x1864EB: flb_engine_start (flb_engine.c:617)
==25971==    by 0x16907C: flb_lib_worker (flb_lib.c:605)
==25971==    by 0x4864608: start_thread (pthread_create.c:477)
==25971==    by 0x4B10292: clone (clone.S:95)
==25971== 
==25971== Use of uninitialised value of size 8
==25971==    at 0x4842B60: memmove (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==25971==    by 0x1C7C92: consume_bytes (tail_file.c:50)
==25971==    by 0x1CAA72: flb_tail_file_chunk (tail_file.c:1004)
==25971==    by 0x1C201B: in_tail_collect_static (tail.c:140)
==25971==    by 0x174A5F: flb_input_collector_fd (flb_input.c:1022)
==25971==    by 0x1864EB: flb_engine_handle_event (flb_engine.c:363)
==25971==    by 0x1864EB: flb_engine_start (flb_engine.c:617)
==25971==    by 0x16907C: flb_lib_worker (flb_lib.c:605)
==25971==    by 0x4864608: start_thread (pthread_create.c:477)
==25971==    by 0x4B10292: clone (clone.S:95)
==25971== 
.
.
.
```

**Comment by jlunavtgrad** [comment]
@nokute78 Thanks for running this through valgrind, good catch! I've fixed the uninitialized value and valgrind output looks clean

**Comment by nokute78** [comment]
Thank you for updating. Valgrind output is OK!

I tested `Skip_Long_Lines Off` case and it may be error.
Can you check it ?

## Configuration 

```
[INPUT]
  Name tail
  Path test.log
  DB fluent-bit.db
#  Skip_Long_Lines On
  Read_From_Head On

[OUTPUT]
  Name counter
  Match *
```

It reports error and doesn't output.
```
$ bin/fluent-bit -c a.conf 
Fluent Bit v1.8.0
* Copyright (C) 2019-2021 The Fluent Bit Authors
* Copyright (C) 2015-2018 Treasure Data
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io

[2021/05/19 21:16:12] [ info] [engine] started (pid=32687)
[2021/05/19 21:16:12] [ info] [storage] version=1.1.1, initializing...
[2021/05/19 21:16:12] [ info] [storage] in-memory
[2021/05/19 21:16:12] [ info] [storage] normal synchronization mode, checksum disabled, max_chunks_up=128
[2021/05/19 21:16:12] [ info] [sp] stream processor started
[2021/05/19 21:16:12] [error] [input:tail:tail.0] file=test.log requires a larger buffer size, lines are too long. Skipping file.
^C[2021/05/19 21:16:30] [engine] caught signal (SIGINT)
[2021/05/19 21:16:30] [ info] [input] pausing tail.0
[2021/05/19 21:16:30] [ warn] [engine] service will stop in 5 seconds
^C[2021/05/19 21:16:30] [engine] caught signal (SIGINT)
```

On the other hand, current [master](https://github.com/fluent/fluent-bit/tree/b141d11b0e8e25accf4f11da6e5bc02856824d8f)  and v1.7.5 reads log and outputs.

```
$ bin/fluent-bit -c a.conf 
Fluent Bit v1.8.0
* Copyright (C) 2019-2021 The Fluent Bit Authors
* Copyright (C) 2015-2018 Treasure Data
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io

[2021/05/19 21:18:57] [ info] [engine] started (pid=32710)
[2021/05/19 21:18:57] [ info] [storage] version=1.1.1, initializing...
[2021/05/19 21:18:57] [ info] [storage] in-memory
[2021/05/19 21:18:57] [ info] [storage] normal synchronization mode, checksum disabled, max_chunks_up=128
[2021/05/19 21:18:57] [ info] [sp] stream processor started
[2021/05/19 21:18:57] [ info] [input:tail:tail.0] inotify_fs_add(): inode=1472762 watch_fd=1 name=test.log
1621426742.176739,78 (total = 78)
^C[2021/05/19 21:19:02] [engine] caught signal (SIGINT)
[2021/05/19 21:19:02] [ info] [input] pausing tail.0
[2021/05/19 21:19:02] [ warn] [engine] service will stop in 5 seconds
[2021/05/19 21:19:07] [ info] [engine] service stopped
[2021/05/19 21:19:07] [ info] [input:tail:tail.0] inotify_fs_remove(): inode=1472762 watch_fd=1
```

File: plugins/in_tail/tail_file.c [hunk 1]
```diff
@@ -370,8 +369,10 @@ static int process_content(struct flb_tail_file *file, size_t *bytes)
                                    out_sbuf->data,
                                    out_sbuf->size);
     }
-    else {
+    else if (file->skip_next) {
         *bytes = file->buf_len;
+    } else {
```
Comment (nokute78) [inline plugins/in_tail/tail_file.c:374]: Can you add newline after `}` ?

like 
```c
}
else {
```
https://github.com/fluent/fluent-bit/blob/master/CONTRIBUTING.md#braces-usage-on-conditionals-loops-and-functions

Comment (jlunavtgrad) [reply plugins/in_tail/tail_file.c]: Done

**Comment by jlunavtgrad** [comment]
> I tested `Skip_Long_Lines Off` case and it may be error. It reports error and doesn't output.

When fluent-bit encounters a line that is longer than the buffer it is supposed to increase the buffer up to `max_buff_size`. If the line is longer than max_buff_size then the flunent-bit will log an error and skip the file unless `Skip_Long_Lines` is enabled.

This patch fixes a bug introduced in version 1.7.5 that broke two things:
- It prevents the buffer size from growing to `max_buff_size`. Any line that is longer than `buffer_chunk_size` will be handled line a long line
- It breaks the `Skip_Long_Lines` feature. Long lines are not skipped, but rather the beginning of the line is skipped and the end of the long line is ingested.

This patch also fixes a long standing bug where long lines also caused the offset in the database to be incorrect when long lines were skipped.

**Comment by jlunavtgrad** [comment]
Removed the errant patch file

**Review by nokute78 — APPROVED** [review]
@jlunavtgrad Thank you! I got it.
LGTM.

@edsiper Any comments?

**Comment by edsiper** [comment]
all good, thanks everyone!
