### PR TITLE
in_splunk: fix memory corruption by resetting parser after reallocation

### LINKED ISSUE #9964: [in_splunk] Memory corruption in splunk input plugin after buffer reallocation
## Issue description
The Splunk input plugin (in_splunk) crashes with a segmentation fault when processing HTTP/1.1 requests that require buffer reallocation. The crash occurs due to invalid memory references to HTTP headers after buffer reallocation.

## Reproduction steps
1. Configure Fluent Bit with the provided configuration
2. Build and run the test client 
3. Send HTTP/1.1 requests to trigger the crash

## Current behavior
When using HTTP/1.1 connections (http2: off), the process crashes with SIGSEGV when accessing header data. However, when using HTTP/2 (http2: on), the requests are processed successfully with 200 responses.

When the crash occurs, we see corrupted data in the logs before the segfault:

```
Error sending request: Post "http://localhost:9393/services/collector/event": EOF
C5��' IS NOT VALID. Size is: 26. fluentTag is: nil
full record:	{
  SPLUNK_HEC_TOKEN = "\0\26\0\0\0�\127\0\0\r\14C5�\127\0\0\5\0\0\0�\127\0\0\6",
  bytes = 26694,
  datetime = "06/Feb/2025:17:00:54 -0300",
  event_type = "web",
  host = "120.226.22.46",
  method = "PUT",
  protocol = "HTTP/1.0",
  referer = "http://www.forwardinnovate.org/back-end",
  request = "/platforms/e-business/e-commerce",
  status = 500,
  ["user-identifier"] = "emard6662"
}
```

The process then crashes with this stack trace:

```
[2025/02/20 10:06:11] [engine] caught signal (SIGSEGV)
#0  0x7d9b43            in  splunk_prot_handle() at plugins/in_splunk/splunk_prot.c:720
#1  0x7d3cfe            in  splunk_conn_event() at plugins/in_splunk/splunk_conn.c:98
#2  0x50d737            in  flb_engine_start() at src/flb_engine.c:1060
#3  0x4aa710            in  flb_lib_worker() at src/flb_lib.c:835
```

## Root cause
When the connection buffer requires reallocation to handle more data, the pointers to parsed HTTP headers become invalid as they reference memory locations in the old buffer. The current reallocation code doesn't properly handle updating these pointer references, leading to memory corruption when attempting to access header data.

## Impact
- Affects processing of HTTP/1.1 requests requiring buffer expansion
- Potential data loss due to incomplete request processing

### Fluent Bit configuration

```yaml
service:
  log_level: trace
pipeline:
  inputs:
    - name: splunk
      alias: splunk_hec
      listen: 0.0.0.0
      port: "9393"
      buffer_max_size: 15M
      buffer_chunk_size: 512K
      store_token_in_metadata: off
      splunk_token_key: "SPLUNK_HEC_TOKEN"
      splunk_token: 'AAAA-AAAA-AAAA-AAAA,aaaa-aaaa-aaaa-aaaa,12,21'
      tls.verify: "off"
      tls.debug: "1"
      tag: hec
      http2: off
  filters:
    - name: lua
      match: "hec"
      call: doit
      code: |
        local inspect = require('inspect')
        local tokenMap = {['AAAA-AAAA-AAAA-AAAA'] = 'logs.token1',['aaaa-aaaa-aaaa-aaaa'] = 'logs.token2',['12'] = 'logs.token3',['21'] = 'logs.token4',['111'] = 'logs.token3',['222'] = 'logs.token4',['133'] = 'logs.token3',['2444'] = 'logs.token4',['1555'] = 'logs.token3',['2666'] = 'logs.token4',['1777'] = 'logs.token3',['28888'] = 'logs.token4',['19999'] = 'logs.token3',['2212'] = 'logs.token4'}
        function doit(tag, ts, record, code)
            record['event_type'] = "web"
            record['fluentTag'] = tokenMap[string.sub(record.SPLUNK_HEC_TOKEN,8)]
            local test = string.sub(record.SPLUNK_HEC_TOKEN,1,6)
            if test ~= "Splunk" then
              print(string.format("ERROR Token='%s' IS NOT VALID. Size is: %s. fluentTag is: %s", record.SPLUNK_HEC_TOKEN, record.SPLUNK_HEC_TOKEN:len(), record.fluentTag))
              print("full record: ", inspect(record))
            end
            return 2, ts, record
        end
  outputs:
    - name: http
      alias: hec
      host: nohost
      port: "443"
      uri: /
      format: json_lines
      tls: true
      tls.verify: "on"
      tls.debug: "1"
      net.keepalive: true
      net.keepalive_idle_timeout: 30s
      net.connect_timeout: 10s
      net.connect_timeout_log_error: true
      net.keepalive_max_recycle: "2000"
      Match: logs.lastchance
```

### Test client

```go
package main
/*
Brendan Cooper
JDS Australia
version: 0.1
Last modified: 16 Sep 2024
License: Apache 2.0
*/
import (
    "bytes"
    "crypto/tls"
    "flag"
    "fmt"
    "net/http"
    "os"
    "sync"
    "time"
)

func main() {
    payloadFile := flag.String("payload", "", "Path to the JSON payload file")
    rps := flag.Int("rps", 1, "Number of requests per second")
    token := flag.String("token", "", "Bearer token for Authorization header")
    endpoint := flag.String("endpoint", "", "HTTP endpoint to send requests to")
    flag.Parse()

    if *payloadFile == "" || *rps <= 0 || *token == "" || *endpoint == "" {
       fmt.Println("Usage: go run main.go -payload=FILE -rps=NUMBER -token=TOKEN -endpoint=URL")
       return
    }

    payload, err := os.ReadFile(*payloadFile)
    if err != nil {
       fmt.Printf("Error reading payload file: %v\n", err)
       return
    }

    client := &http.Client{
       Transport: &http.Transport{
          TLSClientConfig: &tls.Config{InsecureSkipVerify: true},
       },
    }

    var wg sync.WaitGroup
    ticker := time.NewTicker(time.Second / time.Duration(*rps))
    defer ticker.Stop()

    for {
       <-ticker.C
       wg.Add(*rps)
       for i := 0; i < *rps; i++ {
          go func() {
             defer wg.Done()
             req, err := http.NewRequest("POST", *endpoint, bytes.NewBuffer(payload))
             if err != nil {
                fmt.Printf("Error creating request: %v\n", err)
                return
             }
             req.Header.Set("Content-Type", "application/json")
             req.Header.Set("Authorization", "Splunk "+*token)
             resp, err := client.Do(req)
             if err != nil {
                fmt.Printf("Error sending request: %v\n", err)
             } else {
                fmt.Printf("Response was %v\n", resp.StatusCode)
             }
          }()
       }
       wg.Wait()
    }
}
```

### Steps to reproduce
1. Save the Fluent Bit configuration as `fluent-bit.conf`
2. Create a JSON payload file with test data
3. Build and run the test client:

```bash
go build main.go
./main -payload=payload.json -rps=1 -token=AAAA-AAAA-AAAA-AAAA -endpoint=http://localhost:9393/services/collector/event
```

4. The issue manifests with HTTP/1.1 (http2: off) but works with HTTP/2 (http2: on)

## Workaround
Currently, using HTTP/2 avoids the issue as seen in the test results.

## Additional notes
- The issue appears consistently reproducible with HTTP/1.1 requests
- The underlying issue may affect other plugins using the Monkey HTTP parser in similar ways
- A long-term fix might require modifications to the Monkey HTTP parser to use offsets instead of direct pointers

## References
N/A

### PR DESCRIPTION
**Pull request by niedbalski**
When buffer reallocation occurs in HTTP/1.1 connections, parsed header references become invalid since they point to locations in the old buffer. This causes memory corruption and crashes when later accessing those headers.

Add splunk_conn_realloc_and_reparse() function that:
- Performs buffer reallocation
- Resets parser state

This ensures no dangling pointers exist after reallocation, preventing crashes at the cost of reparsing. A proper fix using offsets instead of pointers will be implemented in mk_http_parser in a future change.

Fixes #9964 

## Testing
See #9964 

```
[ikslabdein@toolbox repro]$ ./main -payload=payload.json -rps=1 -token=AAAA-AAAA-AAAA-AAAA -endpoint=http://localhost:9393/services/collecto
r/event
Response was 200
Response was 200
```
```
record token before: 	{
  SPLUNK_HEC_TOKEN = "Splunk AAAA-AAAA-AAAA-AAAA",
  bytes = 27294,
  datetime = "06/Feb/2025:17:00:54 -0300",
  host = "68.2.73.0",
  method = "HEAD",
  protocol = "HTTP/2.0",
  referer = "http://www.districtportals.com/e-business/strategize/paradigms",
  request = "/engineer/portals/markets/action-items",
  status = 302,
  ["user-identifier"] = "dach3307",
  <metatable> = {
    type = 2
  }
}
record token before: 	{
  SPLUNK_HEC_TOKEN = "Splunk AAAA-AAAA-AAAA-AAAA",
  bytes = 26694,
  datetime = "06/Feb/2025:17:00:54 -0300",
  host = "120.226.22.46",
  method = "PUT",
  protocol = "HTTP/1.0",
  referer = "http://www.forwardinnovate.org/back-end",
  request = "/platforms/e-business/e-commerce",
  status = 500,
  ["user-identifier"] = "emard6662",
  <metatable> = {
    type = 2
  }
}
record token before: 	{
  SPLUNK_HEC_TOKEN = "Splunk AAAA-AAAA-AAAA-AAAA",
  bytes = 27367,
  datetime = "06/Feb/2025:17:00:54 -0300",
  host = "234.88.165.193",
  method = "POST",
  protocol = "HTTP/2.0",
  referer = "http://www.centralweb-readiness.name/e-commerce",
  request = "/roi/e-business",
  status = 204,
  ["user-identifier"] = "-",
  <metatable> = {
    type = 2
  }
}
```

```
[2025/02/20 11:39:47] [debug] [input:splunk:splunk_hec] realloc buffer 2048000 -> 2560000 bytes
[2025/02/20 11:39:47] [debug] [input:splunk:splunk_hec] realloc completed successfully size=2560000
[2025/02/20 11:39:47] [trace] [input:splunk:splunk_hec at /var/home/ikslabdein/code/oss/upstream/plugins/in_splunk/splunk_conn.c:105] fd=61 buffer realloc 2560000 -> 2560000
[2025/02/20 11:39:47] [trace] [input:splunk:splunk_hec at /var/home/ikslabdein/code/oss/upstream/plugins/in_splunk/splunk_conn.c:122] read()=512000 pre_len=2047999 now_len=2559999
[2025/02/20 11:39:47] [debug] [input:splunk:splunk_hec] realloc buffer 2560000 -> 3072000 bytes
[2025/02/20 11:39:47] [debug] [input:splunk:splunk_hec] realloc completed successfully size=3072000
[2025/02/20 11:39:47] [trace] [input:splunk:splunk_hec at /var/home/ikslabdein/code/oss/upstream/plugins/in_splunk/splunk_conn.c:105] fd=61 buffer realloc 3072000 -> 3072000
[2025/02/20 11:39:47] [trace] [input:splunk:splunk_hec at /var/home/ikslabdein/code/oss/upstream/plugins/in_splunk/splunk_conn.c:122] read()=204439 pre_len=2559999 now_len=2764438
[2025/02/20 11:39:48] [debug] [task] created task=0x7f2270155330 id=0 without routes, dropping.
[2025/02/20 11:39:48] [debug] [task] destroy task=0x7f2270155330 (task_id=0)
[2025/02/20 11:39:48] [debug] [task] created task=0x7f2270155410 id=0 without routes, dropping.
[2025/02/20 11:39:48] [debug] [task] destroy task=0x7f2270155410 (task_id=0)
[2025/02/20 11:39:48] [trace] [input:splunk:splunk_hec at /var/home/ikslabdein/code/oss/upstream/plugins/in_splunk/splunk_conn.c:117] fd=61 closed connection
[2025/02/20 11:39:48] [trace] [input:splunk:splunk_hec at /var/home/ikslabdein/code/oss/upstream/plugins/in_splunk/splunk_conn.c:117] fd=60 closed connection
[2025/02/20 11:39:48] [trace] [input:splunk:splunk_hec at /var/home/ikslabdein/code/oss/upstream/plugins/in_splunk/splunk_conn.c:117] fd=59 closed connection

```

### CODE REVIEW

File: plugins/in_splunk/splunk_conn.c [hunk 1]
```diff
@@ -27,26 +27,58 @@
...
+                                   struct mk_server *server,
+                                   int client_fd);
+
+static int splunk_conn_realloc_and_reparse(struct flb_splunk *ctx,
+                                          struct splunk_conn *conn,
+                                          size_t size)
+{
+    char *tmp;
+
+    flb_plg_debug(ctx->ins, "realloc buffer %i -> %zu bytes",
```
Comment (edsiper) [inline plugins/in_splunk/splunk_conn.c:40]: I suggest move this to a trace level

File: plugins/in_splunk/splunk_conn.c [hunk 2]
```diff
@@ -27,26 +27,58 @@
...
+    }
+
+    /* Update buffer info */
+    conn->buf_data = tmp;
+    conn->buf_size = size;
+    /* Keep NULL termination */
+    conn->buf_data[conn->buf_len] = '\0';
+
+    /* Reset parser state */
+    memset(&conn->session.parser, 0, sizeof(struct mk_http_parser));
```
Comment (edsiper) [inline plugins/in_splunk/splunk_conn.c:58]: looking at the parser code, this memset() is not necessary:

https://github.com/fluent/fluent-bit/blob/master/lib/monkey/include/monkey/mk_http_parser.h#L356

File: plugins/in_splunk/splunk_conn.c [hunk 3]
```diff
@@ -27,26 +27,58 @@
...
+    mk_http_parser_init(&conn->session.parser);
+
+    flb_plg_debug(ctx->ins, "realloc completed successfully size=%zu", size);
```
Comment (edsiper) [inline plugins/in_splunk/splunk_conn.c:61]: not sure if this message is relevant

File: plugins/in_splunk/splunk_conn.c [hunk 4]
```diff
@@ -61,16 +93,14 @@ static int splunk_conn_event(void *data)
             }
 
             size = conn->buf_size + ctx->buffer_chunk_size;
-            tmp = flb_realloc(conn->buf_data, size);
-            if (!tmp) {
+            ret = splunk_conn_realloc_and_reparse(ctx, conn, size);
```
Comment (edsiper) [inline plugins/in_splunk/splunk_conn.c:96]: suggested name: splunk_conn_buffer_realloc()

**Review by edsiper — CHANGES_REQUESTED** [review]
great job! 

I added some minor change requested

File: plugins/in_splunk/splunk_conn.c [hunk 5]
```diff
@@ -27,26 +27,57 @@
 static void splunk_conn_request_init(struct mk_http_session *session,
                                      struct mk_http_request *request);
 
+static void splunk_conn_session_init(struct mk_http_session *session,
+                                   struct mk_server *server,
+                                   int client_fd);
+
+static int splunk_conn_buffer_realloc(struct flb_splunk *ctx,
```
Comment (clarkds14) [inline plugins/in_splunk/splunk_conn.c:34]: do we not have any unit tests for this?

Comment (edsiper) [reply plugins/in_splunk/splunk_conn.c:34]: we don't, I suggest internally how this can be added to the CI:

```
[ikslabdein@toolbox repro]$ ./main -payload=payload.json -rps=1 -token=AAAA-AAAA-AAAA-AAAA -endpoint=http://localhost:9393/services/collecto
```
