### PR TITLE
out_es: out_es: use snprintf wrapper function for bulk header(#4311)

### LINKED ISSUE #4311: [es_output] Generate_ID sometimes corrupts message structure during /_bulk requests.(possible cause: incorrect memory buffer size)
## Bug Report

**Describe the bug**
After migrating to 1.8.X fluent -bit version we started to see lots of errors:
`an id must be provided if version or value are set`
Quick investigation showed that it might be caused by adjusting the code to work with ES 7.5+ API.
Exactly the same issue: https://github.com/fluent/fluent-bit/issues/3909

In order to make it work we were forced to enable the setting: Generate_ID because we are using elasticsearch 6.4 and we cannot afford to migrate on newer version at the moment.
That solved our issue.
However we started to notice lots of 500 errors on our loadbalancer which is located in the front of elasticsearch coordinator nodes.
Using strace showed the issue with message corruption.
In the following examples i removed several fields for the sake of simplicity
Please check "_id" field. It is corrupted in both examples.

Example 1 of corrupted message:
```
Formatted message:
POST /_bulk HTTP/1.1
Host: elk.example.internal
X-Real-IP: 192.168.8.189
X-Forwarded-For: 192.168.10.141, 192.168.8.189
X-Forwarded-Proto: https
Content-Length: 1991
X-Forwarded-Port: 443
Content-Type: application/x-ndjson
User-Agent: Fluent-Bit

{"create":{"_index":"k8s-v1-abcdef-website-production-abcdef-website-production-abcdef-event-bus-handler-2021.11.10","_type":"_doc","_id":"ef8da3c7-14d0-bdc6-940a-e10d3c441487{"@timestamp":"2021-11-10T05:22:09.508Z","stream":"stderr","kubernetes":{"host":"ip-192-168-10-26.eu-central-1.compute.internal","labels":{"app_kubernetes_io/name":"website-production-web","pod-template-hash":"745f6cc4bc","app_kubernetes_io/instance":"website-production"}}}}}


Raw message in strace:
POST /_bulk HTTP/1.1\r\nHost: elk.exmaple.internal\r\nX-Real-IP: 192.168.8.189\r\nX-Forwarded-For: 192.168.10.141, 192.168.8.189\r\nX-Forwarded-Proto: https\r\nContent-Length: 1991\r\nX-Forwarded-Port: 443\r\nContent-Type: application/x-ndjsonUser-Agent: Fluent-Bit\r\n\r\n{\"create\":{\"_index\":\"k8s-v1-abcdef-website-production-abcdef-website-production-abcdef-event-bus-handler-2021.11.10\",\"_type\":\"_doc\",\"_id\":\"ef8da3c7-14d0-bdc6-940a-e10d3c441487\0\0\0\0{\"@timestamp\":\"2021-11-10T05:22:09.508Z\",\"stream\":\"stderr\",\"kubernetes\":{\"host\":\"ip-192-168-10-26.eu-central-1.compute.internal\",\"labels\":{\"app_kubernetes_io/name\":\"website-production-web\",\"pod-template-hash\":\"745f6cc4bc\",\"app_kubernetes_io/instance\":\"website-production\"}}}}}
```

Example 2 of corrupted message:
```
Formatted message:
POST /_bulk HTTP/1.1
Host: elk.example.internal
X-Real-IP: 192.168.8.189
X-Forwarded-For: 192.168.7.202, 192.168.8.189
X-Forwarded-Proto: https
Content-Length: 5536
X-Forwarded-Port: 443
Content-Type: application/x-ndjson
User-Agent: Fluent-Bit

{"create":{"_index":"k8s-v1-abcdef-website-production-abcdef-website-production-abcdef-event-bus-handler-2021.11.10","_type":"_doc","_id":"307e59d7-0cf8-8b65-d839-bû  9Vk8s{"@timestamp":"2021-11-10T05:18:59.183Z"}}}

Raw message in strace:
POST /_bulk HTTP/1.1\r\nHost: elk.example.internal\r\nX-Real-IP: 192.168.8.189\r\nX-Forwarded-For: 192.168.7.202, 192.168.8.189\r\nX-Forwarded-Proto: https\r\nContent-Length: 5536\r\nX-Forwarded-Port: 443\r\nContent-Type: application/x-ndjson\r\nUser-Agent: Fluent-Bit\r\n\r\n{\"create\":{\"_index\":\"k8s-v1-abcdef-website-production-abcdef-website-production-abcdef-event-bus-handler-2021.11.10\",\"_type\":\"_doc\",\"_id\":\"307e59d7-0cf8-8b65-d839-b\0\177\0\0\373\t\2279\5V\0\0k8s{\"@timestamp\":\"2021-11-10T05:18:59.183Z\"}}}\n
```
Unclear what happens to the message when code block responsible for generate_id begin to process:
https://github.com/fluent/fluent-bit/blob/master/plugins/out_es/es.c#L489-L507

I suspect the issue is either in 'MurmurHash3_x64_128' or 'snprintf' functions caused by incorrect buffer size.

Exception in elasticsearch:
```
{"error":{"root_cause":[{"type":"json_parse_exception","reason":"Illegal unquoted character ((CTRL-CHAR, code 0)): has to be escaped using backslash to be included in string value\n at [Source: org.elasticsearch.transport.netty4.ByteBufStreamInput@46755a1a; line: 1, column: 166]"}],"type":"json_parse_exception","reason":"Illegal unquoted character ((CTRL-CHAR, code 0)): has to be escaped using backslash to be included in string value\n at [Source: org.elasticsearch.transport.netty4.ByteBufStreamInput@46755a1a; line: 1, column: 166]"},"status":500}
```
Corruption happens always on column 166.
At the same time there is a preprocessor instruction:
```
#define ES_BULK_HEADER      165  /* ES Bulk API prefix line  */
```

**Your Environment**
Tried fluent-bit versions: 1.8.0 -> latest(1.8.9)
Version of elasticesarch cluster: 6.4.0
Fluent-bit primarily runs on EKS(AWS managed kubernetes service)
Fluent-bit configuration:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: logging
  labels:
    k8s-app: fluent-bit
data:
  # Configuration files: server, input, filters and output
  # ======================================================
  fluent-bit.conf: |
    [SERVICE]
        Flush           1
        Log_Level       error
        Daemon          Off
        Parsers_File    parsers.conf
        HTTP_Server     On
        HTTP_Listen     0.0.0.0
        HTTP_Port       2020
        Health_Check    On
        storage.metrics On

    @INCLUDE input-systemd.conf
    @INCLUDE input-kubernetes.conf
    @INCLUDE filter-kubernetes.conf
    @INCLUDE filter-api-logs.conf
    @INCLUDE filter-systemd.conf
    @INCLUDE output-elasticsearch.conf

  input-systemd.conf: |
    [INPUT]
      Name             systemd
      Path             /journal
      Tag              systemd.*
      Read_From_Tail   On
      Skip_Empty_Lines On
      Skip_Long_Lines  On


  input-kubernetes.conf: |
    [INPUT]
        Name             tail
        Tag              kube.*
        Path             /var/log/containers/*.log
        DB               /var/log/flb_kube.db
        Mem_Buf_Limit    5MB
        Skip_Empty_Lines On
        Skip_Long_Lines  On
        Refresh_Interval 10
        Docker_mode      On
        Parser           docker

  filter-kubernetes.conf: |
    [FILTER]
        Name                kubernetes
        Match               kube.*
        Kube_URL            https://kubernetes.default.svc:443
        Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
        Kube_Tag_Prefix     kube.var.log.containers.
        Keep_Log            Off
        Merge_Log           On
        Merge_Log_Key       app_log
        K8S-Logging.Parser  On
        K8S-Logging.Exclude Off

    [FILTER]
        Name                lua
        Match               kube.*
        script              /etc/fluent-bit/fluentbit.lua
        call                set_index

    # remove field from gatekeeper logs which generates too many indices
    [FILTER]
        Name                modify
        Match               kube.*
        Remove              app_log.updateConstraints


  filter-xcore-api-logs.conf: |
    [FILTER]
        Name                rewrite_tag
        Match               kube.*
        Rule                $app_log['__routing_key'] ^api-logs$ api-logs.$TAG[4].log true

    [FILTER]
        Name                nest
        Match               api-logs.*
        Operation           lift
        Nested_under        app_log

  filter-systemd.conf: |
    [FILTER]
        Name parser
        Match systemd.*
        Key_Name MESSAGE
        Parser systemd-json
        Reserve_Data True

    [FILTER]
        Name modify
        Match systemd.*
        Rename _SYSTEMD_UNIT systemd_unit

    # Append/Remove keys from log records
    [FILTER]
        Name aws
        Match *
        imds_version v1
        az true
        ec2_instance_id true
        ec2_instance_type true
        private_ip true
        ami_id true
        account_id true
        hostname true
        vpc_id true

    [FILTER]
        Name modify
        Match *

        Rename account_id aws_account_id
        Rename ami_id aws_ami_id
        Rename az aws_az
        Rename ec2_instance_id aws_instance_id
        Rename ec2_instance_type aws_instance_type
        Rename private_ip aws_private_ip
        Rename vpc_id aws_vpc_id

        Rename MESSAGE message
        Rename msg message
        Rename LOG message
        Rename log message

    [FILTER]
        Name record_modifier
        Match *

        Record environment ${ENVIRONMENT}

        Remove_Key _CURSOR
        Remove_Key _REALTIME_TIMESTAMP
        Remove_Key _MONOTONIC_TIMESTAMP
        Remove_Key _SOURCE_MONOTONIC_TIMESTAMP
        Remove_Key _BOOT_ID
        Remove_Key _MACHINE_ID
        Remove_Key PRIORITY
        Remove_Key SYSLOG_FACILITY
        Remove_Key SYSLOG_IDENTIFIER
        Remove_Key _CAP_EFFECTIVE
        Remove_Key _EXE
        Remove_Key _GID
        Remove_Key _PID
        Remove_Key _STREAM_ID
        Remove_Key _SYSTEMD_CGROUP
        Remove_Key _SYSTEMD_SLICE
        Remove_Key _TRANSPORT
        Remove_Key _UID
        Remove_Key _COMM
        Remove_Key CODE_FILE
        Remove_Key CODE_FUNC
        Remove_Key CODE_LINE
        Remove_Key TLOG_ID
        Remove_Key TLOG_REC
        Remove_Key TLOG_SESSION
        Remove_Key _AUDIT_LOGINUID
        Remove_Key _AUDIT_SESSION
        Remove_Key _CMDLINE
        Remove_Key _HOSTNAME
        Remove_Key _SOURCE_REALTIME_TIMESTAMP
        Remove_Key _SYSTEMD_OWNER_UID
        Remove_Key _SYSTEMD_SESSION


  output-elasticsearch.conf: |
    [OUTPUT]
        Name            es
        Match           systemd.*
        Host            ${FLUENT_ELASTICSEARCH_HOST}
        Port            ${FLUENT_ELASTICSEARCH_PORT}
        HTTP_User       ${FLUENT_ELASTICSEARCH_USER}
        HTTP_Passwd     ${FLUENT_ELASTICSEARCH_PASSWORD}
        tls on
        tls.verify off
        workers 1

        Generate_ID On
        Logstash_Format On
        Replace_Dots    On
        Logstash_Prefix fluent-bit-k8s-v4
        Retry_Limit     False

    [OUTPUT]
        Name            es
        Match           kube.*
        Host            ${FLUENT_ELASTICSEARCH_HOST}
        Port            ${FLUENT_ELASTICSEARCH_PORT}
        HTTP_User       ${FLUENT_ELASTICSEARCH_USER}
        HTTP_Passwd     ${FLUENT_ELASTICSEARCH_PASSWORD}
        tls on
        tls.verify off
        workers 1

        Generate_ID On
        Logstash_Format     On
        Logstash_Prefix_Key $es_index
        Replace_Dots        On
        Retry_Limit         False

    [OUTPUT]
        Name            es
        Match           xcore-api-logs.*
        Type            fluentd
        Host            ${FLUENT_ELASTICSEARCH_HOST}
        Port            ${FLUENT_ELASTICSEARCH_PORT}
        HTTP_User       ${FLUENT_ELASTICSEARCH_USER}
        HTTP_Passwd     ${FLUENT_ELASTICSEARCH_PASSWORD}
        tls on
        tls.verify off
        workers 1

        Generate_ID On
        Logstash_Format On
        Logstash_Prefix api.application
        Replace_Dots    On
        Retry_Limit     False

  parsers.conf: |
    [PARSER]
        Name        systemd-json
        Format      json
        Time_Key    time_local

    [PARSER]
        Name        docker
        Format      json
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
        Time_Keep   On


  fluentbit.lua: |
    function set_index(tag, timestamp, record)
        prefix = "k8s-v1"
        if record["kubernetes"] ~= nil then
            if record["kubernetes"]["namespace_name"] ~= nil then
                if record["kubernetes"]["container_name"] ~= nil then
                    record["es_index"] = prefix
                        .. "-"
                        .. record["kubernetes"]["namespace_name"]
                        .. "-"
                        .. record["kubernetes"]["container_name"]
                    return 1, timestamp, record
                end
                record["es_index"] = prefix
                    .. "-"
                    .. record["kubernetes"]["namespace_name"]
                return 1, timestamp, record
            end
        end
        return 1, timestamp, record
    end
```

Please let me know if you need any other information

### PR DESCRIPTION
**Pull request by nokute78**
Fixes #4311.

We used fixed char array to construct bulk header.
If long index( the length is greater than 80) , out_es creates broken json since the buffer is small and fixed.
We can reproduce the issue using below command.
```
fluent-bit -i cpu -o es -p generate_id=on -p index=123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890
```

This PR is to
- Add test case for the issue
- Add new API `flb_sds_snprintf_realloc` 
  - It is similar to snprintf. The difference is that the API increases the buffer of flb_sds_t if there is no room to snprintf.
- Use flb_sds_t to construct header and use new API to increase the buffer

----
Enter `[N/A]` in the box, if an item is not applicable to your change.

**Testing**
Before we can approve your change; please submit the following in a comment:
- [X] Example configuration file for the change
- [X] Debug log output from testing the change

- [X] Attached [Valgrind](https://valgrind.org/docs/manual/quick-start.html) output that shows no leaks or memory corruption was found

**Documentation**

- [N/A] Documentation required for this feature

## Example Configuration

1. `nc -l 9200`
2. exec fluent-bit using below command

```
fluent-bit -i cpu -o es -p generate_id=on -p index=123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890
```

## Debug output

```
$ nc -l 9200
POST /_bulk HTTP/1.1
Host: 127.0.0.1:9200
Content-Length: 1216
Content-Type: application/x-ndjson
User-Agent: Fluent-Bit

{"create":{"_index":"123456789012345678901234567890123456789012345678901234567890123456789012345678901","_type":"_doc","_id":"b9042b24-930a-1f00-d630-03b0ef375788"}}{"@timestamp":"2021-11-23T12:25:01.173Z","cpu_p":29,"user_p":28,"system_p":1.0,"cpu0.p_cpu":29.0,"cpu0.p_user":28.0,"cpu0.p_system":1.0}
```

```
$ bin/fluent-bit -i cpu -o es -p generate_id=on -p index=123456789012345678901234567890123456789012345678901234567890123456789012345678901
Fluent Bit v1.9.0
* Copyright (C) 2019-2021 The Fluent Bit Authors
* Copyright (C) 2015-2018 Treasure Data
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io

[2021/11/23 21:25:00] [ info] [engine] started (pid=115228)
[2021/11/23 21:25:00] [ info] [storage] version=1.1.5, initializing...
[2021/11/23 21:25:00] [ info] [storage] in-memory
[2021/11/23 21:25:00] [ info] [storage] normal synchronization mode, checksum disabled, max_chunks_up=128
[2021/11/23 21:25:00] [ info] [cmetrics] version=0.2.2
[2021/11/23 21:25:00] [ info] [sp] stream processor started
```

## Valgrind output

```
$ valgrind --leak-check=full bin/fluent-bit -i cpu -o es -p generate_id=on -p index=123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890 -p logstash_format=on
==115578== Memcheck, a memory error detector
==115578== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==115578== Using Valgrind-3.15.0 and LibVEX; rerun with -h for copyright info
==115578== Command: bin/fluent-bit -i cpu -o es -p generate_id=on -p index=123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890 -p logstash_format=on
==115578== 
Fluent Bit v1.9.0
* Copyright (C) 2019-2021 The Fluent Bit Authors
* Copyright (C) 2015-2018 Treasure Data
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io

[2021/11/23 21:30:39] [ info] [engine] started (pid=115578)
[2021/11/23 21:30:39] [ info] [storage] version=1.1.5, initializing...
[2021/11/23 21:30:39] [ info] [storage] in-memory
[2021/11/23 21:30:39] [ info] [storage] normal synchronization mode, checksum disabled, max_chunks_up=128
[2021/11/23 21:30:39] [ info] [cmetrics] version=0.2.2
[2021/11/23 21:30:39] [ info] [sp] stream processor started
==115578== Warning: client switching stacks?  SP change: 0x57e59f8 --> 0x4c8da80
==115578==          to suppress, use: --max-stackframe=11894648 or greater
==115578== Warning: client switching stacks?  SP change: 0x4c8da28 --> 0x57e59f8
==115578==          to suppress, use: --max-stackframe=11894736 or greater
==115578== Warning: client switching stacks?  SP change: 0x57e59f8 --> 0x4c8da28
==115578==          to suppress, use: --max-stackframe=11894736 or greater
==115578==          further instances of this message will not be shown.
^C[2021/11/23 21:30:48] [engine] caught signal (SIGINT)
[2021/11/23 21:30:48] [ info] [input] pausing cpu.0
[2021/11/23 21:30:48] [ warn] [engine] service will shutdown in max 5 seconds
[2021/11/23 21:30:49] [ info] [engine] service has stopped (0 pending tasks)
==115578== 
==115578== HEAP SUMMARY:
==115578==     in use at exit: 0 bytes in 0 blocks
==115578==   total heap usage: 1,323 allocs, 1,323 frees, 1,476,024 bytes allocated
==115578== 
==115578== All heap blocks were freed -- no leaks are possible
==115578== 
==115578== For lists of detected and suppressed errors, rerun with: -s
==115578== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
```

----

Fluent Bit is licensed under Apache 2.0, by submitting this pull request I understand that this code will be released under the terms of that license.

### CODE REVIEW

File: src/flb_sds.c [hunk 1]
```diff
@@ -407,3 +407,31 @@ void flb_sds_destroy(flb_sds_t s)
     head = FLB_SDS_HEADER(s);
     flb_free(head);
 }
+
```
Comment (edsiper) [inline src/flb_sds.c:410]: I think this function is not necessary and we can simply rely on flb_sds_printf() functionality. 

flb_sds_t by default always reallocate if necessary, and calculating the final length can be done with flb_sds_len()

**Review by edsiper — CHANGES_REQUESTED** [review]

File: src/flb_sds.c (hunk 1 above)
Comment (nokute78) [reply src/flb_sds.c:410]: Functionality is a little different.

`flb_sds_printf` appends offset `flb_sds_len(s)` and it means appends string.
https://github.com/fluent/fluent-bit/blob/v1.8.10/src/flb_sds.c#L367

I want to overwrite flb_sds_t.
So if we use the API to overwrite, we need to call `flb_sds_len_set(sds, 0)` before the API.
```c
flb_sds_len_set(j_index, 0);
out_buf = flb_sds_printf(&j_index,
                        ES_BULK_INDEX_FMT_ID_WITHOUT_TYPE,
                        es_index,  id_key_str);
```

Comment (edsiper) [reply src/flb_sds.c:410]: ah I understand. thanks for the clarification.

On that case so I would suggest renaming the new function from:

- flb_sds_snprintf_realloc

to 

- flb_sds_snprintf

basically the "realloc" context is something that works behind the scenes, where the user don't need to be aware of it (similar to other sds...)

Comment (nokute78) [reply src/flb_sds.c:410]: Thank you for comment.
I renamed.

**Comment by nokute78** [comment]
Note: flb-rt-out_elasticsearch failed since the test case `flb_test_index_type` and `flb_test_logstash_format` don't take care https://github.com/fluent/fluent-bit/commit/7f0db9ef07a6dcb6fd9c1af58c68301356747529
It is not related by this PR since current master also failed on that test cases.

https://github.com/fluent/fluent-bit/commit/7f0db9ef07a6dcb6fd9c1af58c68301356747529 is to use `create` operation.
However these test cases expect `index` operation.

**Comment by nokute78** [comment]
Note: I sent a PR https://github.com/fluent/fluent-bit/pull/4480 to fix test cases.
