### PR TITLE
filter_lua: support new return value to keep timestamp

### LINKED ISSUE #2015: Lua filters can mangle timestamps
Due to Lua's use of the double data type for numbers, and Fluent Bit's representation of timestamps as `<seconds>.<nanoseconds>` , conversion to and from the double type can cause a loss of precision that results in incorrect timestamps.

Consider this simple filter:

```lua
function noop(tag, timestamp, record)
    return 1, timestamp, record
```
Because it returns 1 for `code`, Fluent Bit will convert from the double back to its internal representation.

Then:
1. Suppose an original log line with timestamp `2020-02-19T18:00:00.001+00:00`
2. Fluent Bit parses that timestamp and according to the `stdout` output plugin, represents as `1582135200.001000000` which is as expected.
3. But if the Lua `noop()` filter is called, now some precision is lost, and the `stdout` output shows the timestamp is `1582135200.000999927`

To make matters worse, passing this through an output plugin that only supports milliseconds and which truncates rather than rounds (such as `es`) can result in a `@timestamp` with the wrong millisecond (`2020-02-19T18:00:00.000` in this example).

One solution would be to pass seconds and nanoseconds as separate parameters and treating each as longs without any fractional values.  By way of backward compatibility, a new config parameter could be introduced to use the new style function signature, which would be something like:

```lua
function filter(tag, timestamp_seconds, timestamp_nanoseconds, record)
```

### PR DESCRIPTION
**Pull request by nokute78**
To fix #2015 
This patch is to support new return value to preserve original timestamp.

| return value | description |
|---------------|-------------|
|-1 | drop the record |
|0 | keep the original |
|1| replace timestamp and record |
|2(new)|keep the original timestamp and replace record|

## configuration example

https://github.com/fluent/fluent-bit/issues/2015#issuecomment-612721855

example.lua
```lua
function test(tag, timestamp, record)
         record["filter"] = "lua"
         return 2, timestamp, record
end
```

output:
```
taka@ubuntu:~/git/fluent-bit/build/2015$ ../bin/fluent-bit -c a.conf 
Fluent Bit v1.5.0
* Copyright (C) 2019-2020 The Fluent Bit Authors
* Copyright (C) 2015-2018 Treasure Data
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io

[2020/04/13 13:42:58] [ info] [storage] version=1.0.3, initializing...
[2020/04/13 13:42:58] [ info] [storage] in-memory
[2020/04/13 13:42:58] [ info] [storage] normal synchronization mode, checksum disabled, max_chunks_up=128
[2020/04/13 13:42:58] [ info] [engine] started (pid=33800)
[2020/04/13 13:42:58] [ info] [input:forward:forward.0] listening on 0.0.0.0:24224
[2020/04/13 13:42:58] [ info] [sp] stream processor started
[0] hoge�: [1582135200.001000000, {"hoge"=>"hoge"}]
[0] hoge: [1582135200.001000000, {"filter"=>"lua", "hoge"=>"hoge"}]
```

----
Enter `[N/A]` in the box, if an item is not applicable to your change.

**Testing**
Before we can approve your change; please submit the following in a comment:
- [x] Example configuration file for the change
- [x] Debug log output from testing the change

- [x] Attached [Valgrind](https://valgrind.org/docs/manual/quick-start.html) output that shows no leaks or memory corruption was found

```
taka@ubuntu:~/git/fluent-bit/build/2015$ valgrind ../bin/fluent-bit -c a.conf 
==33808== Memcheck, a memory error detector
==33808== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==33808== Using Valgrind-3.13.0 and LibVEX; rerun with -h for copyright info
==33808== Command: ../bin/fluent-bit -c a.conf
==33808== 
Fluent Bit v1.5.0
* Copyright (C) 2019-2020 The Fluent Bit Authors
* Copyright (C) 2015-2018 Treasure Data
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io

[2020/04/13 13:43:39] [ info] [storage] version=1.0.3, initializing...
[2020/04/13 13:43:39] [ info] [storage] in-memory
[2020/04/13 13:43:39] [ info] [storage] normal synchronization mode, checksum disabled, max_chunks_up=128
[2020/04/13 13:43:39] [ info] [engine] started (pid=33808)
[2020/04/13 13:43:39] [ info] [input:forward:forward.0] listening on 0.0.0.0:24224
[2020/04/13 13:43:40] [ info] [sp] stream processor started
[0] hoge�: [1582135200.001000000, {"hoge"=>"hoge"}]
[0] hoge: [1582135200.001000000, {"filter"=>"lua", "hoge"=>"hoge"}]
^C[engine] caught signal (SIGINT)
==33808== 
==33808== HEAP SUMMARY:
==33808==     in use at exit: 0 bytes in 0 blocks
==33808==   total heap usage: 254 allocs, 254 frees, 470,224 bytes allocated
==33808== 
==33808== All heap blocks were freed -- no leaks are possible
==33808== 
==33808== For counts of detected and suppressed errors, rerun with: -v
==33808== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
taka@ubuntu:~/git/fluent-bit/build/2015$ 
```

**Documentation**

- [ ] Documentation required for this feature

If the patch is approved, I will write a document about this.

----

Fluent Bit is licensed under Apache 2.0, by submitting this pull request I understand that this code will be released under the terms of that license.

### CODE REVIEW

**Comment by nokute78** [comment]
In this case, `flb_time_from_double(&t, ts)` causes rounding error.
https://github.com/fluent/fluent-bit/blob/master/plugins/filter_lua/lua.c#L367

So I save original `flb_time` timestamp and reuse it when return value is 2.

**Comment by edsiper** [comment]
thanks @nokute78 !

File: scripts/test.lua [hunk 1]
```diff
@@ -7,15 +7,16 @@
    - cb_replace => Replace record content with a new table
 
    The key inside each function is to do a proper handling of the
-   return values. Each function must return 3 values:
+   return values. Each function must return 4 values:
```
Comment (l2dy) [inline scripts/test.lua:10]: The function should still return 3 values (code, timestamp, record).

Comment (nokute78) [reply scripts/test.lua:10]: @l2dy Oops! I was misunderstanding. 
I sent a patch to fix it. https://github.com/fluent/fluent-bit/pull/2117
Thank you.
