### PR TITLE
storage: recreate cio_stream if storage type is different(#8259)

### LINKED ISSUE #8259: Fluent Bit still buffers to the filesystem if the folder in `storage.path` exists even if `Emitter_Storage.type` is set to `memory`
## Bug Report

**Describe the bug**
If a rewrite tag filter has `Emitter_Storage.type` set to `memory`, Fluent Bit will act as if `Emitter_Storage.type` is set to `filesystem` if `storage.path` is set in the `[SERVICE]` section and the filter's folder exists.

I can confirm this also happens with inputs with `Storage.type` set to `memory`. 

**To Reproduce**

Fluent Bit config
```
[SERVICE]
    storage.path /fluent-bit/data

[INPUT]
    Name dummy
    Tag dummy

[FILTER]
    Name rewrite_tag
    Match dummy
    Rule $message dummy rewritten false
    Emitter_Name rewriter
    Emitter_Storage.type memory

[OUTPUT]
    Name stdout
    Match rewritten
```

- Steps to reproduce the problem:
1. `mkdir -p "$(pwd)/data/emitter.2"`
2. Watch for file system changes in the `data` directory: `inotifywait` in Linux or `fswatch` in Mac, for example.
3. Run Fluent Bit: `docker run --name fluentbit --rm -v $(pwd)/data:/fluent-bit/data:rw -v $(pwd)/fluentbit.conf:/config/fluentbit.conf:ro cr.fluentbit.io/fluent/fluent-bit:2.2.0 -c /config/fluentbit.conf`.

**Expected behavior**
No files will be created under the `data/emitter.2` directory.

**Your Environment**
* Version used: 2.2.0
* Configuration: Fluent Bit config given above
* Environment name and version (e.g. Kubernetes? What version?): Docker
* Server type and version: n/a
* Operating System and version: n/a
* Filters and plugins: n/a

**Additional context**
This makes having some inputs/rewrite filters use filesystem buffering while others use memory impossible.

### PR DESCRIPTION
**Pull request by nokute78**
Fixes #8259

cio_load creates storage stream if directory exists before creating input chunks.
It prevents to create memory stream by input plugins. 
This patch is to recreate stream if the stream type is different.

----
Enter `[N/A]` in the box, if an item is not applicable to your change.

**Testing**
Before we can approve your change; please submit the following in a comment:

- [X] Example configuration file for the change
- [X] Debug log output from testing the change

- [X] Attached [Valgrind](https://valgrind.org/docs/manual/quick-start.html) output that shows no leaks or memory corruption was found

If this is a change to packaging of containers or native binaries then please confirm it works for all targets.

- [N/A] Run [local packaging test](./packaging/local-build-all.sh) showing all targets (including any new ones) build.
- [N/A] Set `ok-package-test` label to test for all targets (requires maintainer to do).

**Documentation**

- [N/A] Documentation required for this feature

**Backporting**

- [ ] Backport to latest stable release.

## Configuration

```
[SERVICE]
    storage.path data

[INPUT]
    Name dummy
    Tag dummy

[FILTER]
    Name rewrite_tag
    Match dummy
    Rule $message dummy rewritten false
    Emitter_Name rewriter
    Emitter_Storage.type memory

[OUTPUT]
    Name stdout
    Match rewritten
```

## Debug/Valgrind output

1. `mkdir -p "$(pwd)/data/emitter.2"`
2. `fluent-bit -c a.conf`
3. No files are created under data/emitter.2 while running fluent-bit.

```
$ valgrind --leak-check=full bin/fluent-bit -c 8259.conf 
==78668== Memcheck, a memory error detector
==78668== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==78668== Using Valgrind-3.18.1 and LibVEX; rerun with -h for copyright info
==78668== Command: bin/fluent-bit -c 8259.conf
==78668== 
Fluent Bit v2.2.1
* Copyright (C) 2015-2023 The Fluent Bit Authors
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io

[2023/12/16 12:55:00] [ info] [fluent bit] version=2.2.1, commit=2389f44ee4, pid=78668
[2023/12/16 12:55:00] [ info] [storage] ver=1.2.0, type=memory+filesystem, sync=normal, checksum=off, max_chunks_up=128
[2023/12/16 12:55:00] [ info] [storage] backlog input plugin: storage_backlog.1
[2023/12/16 12:55:00] [ info] [cmetrics] version=0.6.5
[2023/12/16 12:55:00] [ info] [ctraces ] version=0.3.1
[2023/12/16 12:55:00] [ info] [input:dummy:dummy.0] initializing
[2023/12/16 12:55:00] [ info] [input:dummy:dummy.0] storage_strategy='memory' (memory only)
[2023/12/16 12:55:00] [ info] [input:storage_backlog:storage_backlog.1] initializing
[2023/12/16 12:55:00] [ info] [input:storage_backlog:storage_backlog.1] storage_strategy='memory' (memory only)
[2023/12/16 12:55:00] [ info] [input:storage_backlog:storage_backlog.1] queue memory limit: 95.4M
[2023/12/16 12:55:00] [ info] [input:emitter:rewriter] initializing
[2023/12/16 12:55:00] [ info] [input:emitter:rewriter] storage_strategy='memory' (memory only)
[2023/12/16 12:55:00] [ info] [storage] storage type mismatch. input type='memory' (memory only)
[2023/12/16 12:55:00] [ info] [storage] re-create stream
[2023/12/16 12:55:01] [ info] [sp] stream processor started
[2023/12/16 12:55:01] [ info] [output:stdout:stdout.0] worker #0 started
[0] rewritten: [[1702698901.293772520, {}], {"message"=>"dummy"}]
[0] rewritten: [[1702698902.298262899, {}], {"message"=>"dummy"}]
^C[2023/12/16 12:55:03] [engine] caught signal (SIGINT)
[0] rewritten: [[1702698903.241552179, {}], {"message"=>"dummy"}]
[2023/12/16 12:55:03] [ warn] [engine] service will shutdown in max 5 seconds
[2023/12/16 12:55:03] [ info] [input] pausing dummy.0
[2023/12/16 12:55:03] [ info] [input] pausing storage_backlog.1
[2023/12/16 12:55:04] [ info] [engine] service has stopped (0 pending tasks)
[2023/12/16 12:55:04] [ info] [input] pausing dummy.0
[2023/12/16 12:55:04] [ info] [input] pausing storage_backlog.1
[2023/12/16 12:55:04] [ info] [output:stdout:stdout.0] thread worker #0 stopping...
[2023/12/16 12:55:04] [ info] [output:stdout:stdout.0] thread worker #0 stopped
==78668== 
==78668== HEAP SUMMARY:
==78668==     in use at exit: 0 bytes in 0 blocks
==78668==   total heap usage: 2,365 allocs, 2,365 frees, 2,524,208 bytes allocated
==78668== 
==78668== All heap blocks were freed -- no leaks are possible
==78668== 
==78668== For lists of detected and suppressed errors, rerun with: -s
==78668== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)

```

----

Fluent Bit is licensed under Apache 2.0, by submitting this pull request I understand that this code will be released under the terms of that license.

### CODE REVIEW

File: src/flb_storage.c [hunk 1]
```diff
@@ -532,6 +532,18 @@ int flb_storage_input_create(struct cio_ctx *cio,
             return -1;
         }
     }
+    else if (stream->type != cio_storage_type) {
+        flb_info("[storage] storage type mismatch. input type=%s",
```
Comment (edsiper) [inline src/flb_storage.c:536]: I will put this as a debug instead of info

**Review by edsiper — CHANGES_REQUESTED** [review]

File: src/flb_storage.c (hunk 1 above)
Comment (nokute78) [reply src/flb_storage.c:536]: In this case user environment is need to be fixed.
- Remove storage
- Modify storage property

I think it is better the level is info or warn to notice it.
What do you think ?

Comment (edsiper) [reply src/flb_storage.c:536]: hmm, I would not remove the storage content for the user unless the directory is empty (no chunks), but I agree with better messaging.

Comment (nokute78) [reply src/flb_storage.c]: I modified log message. Could you check it ?
https://github.com/fluent/fluent-bit/pull/8290/commits/34c00a1f3bbcea33317e5a8f9d5e37ed087cb17d

**Comment by edsiper** [comment]
thank you
