### PR TITLE
in_kubernetes_events: Efficiently stream kubernetes events via watch

### LINKED ISSUE #8315: in_kubernetes_events: Inefficient Defaults Lead To Kube API Spamming/Resource Drain & extra processing required in fluent-bit
## Bug Report

**Describe the bug**
The current `in_kubernetes_events` plugin is polling the kubeapi every 500ms by default (unless you specifically update the `interval_(sec|nsec)` config options. It is retrieving the same data over and over and using improper resourceVersion semantics (see bug #8314) to detect resource (event) changes.

resourceVersion / resourceVersionMatch are unset during the call to `/api/v1/events` which requires a quorum of kube api servers before it's response.
> https://kubernetes.io/docs/reference/using-api/api-concepts/#semantics-for-get-and-list
> Unless you have strong consistency requirements, using resourceVersionMatch=NotOlderThan and a known resourceVersion is preferable since it can achieve better performance and scalability of your cluster than leaving resourceVersion and resourceVersionMatch unset, which requires quorum read to be served.

This combination in large clusters, especially when combined with another default (requesting events for all namespaces when not limiting to a single namespace with `kube_namespace`), can lead to several Mbs of data being constantly polled from the kube api servers every 500ms.

**To Reproduce**
- Steps to reproduce the problem:

Use the following input with defaults: 
```
[INPUT]
    name          kubernetes_events
    tag           k8s_events
```

set debug logging (`FLB_LOG_LEVEL=debug`) and you can see we are consistently polling the same data and skipping over resourceVersion information we already have. If you attach this to a debugger (or just rebuild with extra flb_plg_debug lines within this `do`: https://github.com/fluent/fluent-bit/blob/bc28e7855ee2d30b57e644999b5eb05e690f840f/plugins/in_kubernetes_events/kubernetes_events.c#L709)

**Expected behavior**
Running a `list` against the k8s cluster should only be done at startup or after our last resourceVersion is considered too far out of date by k8s (it will return a 410 when requesting too old of a version). Then we should follow [efficient-detection-of-changes](https://kubernetes.io/docs/reference/using-api/api-concepts/#efficient-detection-of-changes) which uses the resourceVersion of the `EventList` (not the individual events) to create a chunked stream of updates.

**Your Environment**

* Version used: 2.2.0

### PR DESCRIPTION
**Pull request by ryanohnemus**
Change `in_kubernetes_events` plugin to watch kubernetes events after requesting the event list. Instead of polling for the full event list every 500ms (default), an initial full events list is requested and then is a watch is requested. The watch will create an efficient http chunked stream that will push events as they are added, modified, or deleted from the cluster. The interval_sec and interval_nsec plugin config options now act as a reconnect timer if the watch stream is ended, instead of timer to re-poll the k8s cluster.

**Potentially Breaking**: this will require the kubernetes role used by fluent-bit to have `watch` permission in addition to the current `list` and `get` permissions.

Fixes #8315 

Leaving in draft as this is dependent on both #8316 & #8323, will rebase and move out of draft after those are reviewed/merged.

----
Enter `[N/A]` in the box, if an item is not applicable to your change.

**Testing**
Before we can approve your change; please submit the following in a comment:

- [ X] Example configuration file for the change
```
[INPUT]
    name          kubernetes_events
    tag           k8s_events
```

- [ ] Debug log output from testing the change

- [ ] Attached [Valgrind](https://valgrind.org/docs/manual/quick-start.html) output that shows no leaks or memory corruption was found

If this is a change to packaging of containers or native binaries then please confirm it works for all targets.

- [ ] Run [local packaging test](./packaging/local-build-all.sh) showing all targets (including any new ones) build.
- [ ] Set `ok-package-test` label to test for all targets (requires maintainer to do).

**Documentation**

- [ ] Documentation required for this feature

**Backporting**

- [ ] Backport to latest stable release.

----

Fluent Bit is licensed under Apache 2.0, by submitting this pull request I understand that this code will be released under the terms of that license.

### CODE REVIEW

File: plugins/in_kubernetes_events/kubernetes_events.c [hunk 1]
```diff
@@ -373,7 +358,7 @@ static bool check_event_is_filtered(struct k8s_events *ctx, msgpack_object *obj)
 
     // check if this is an old event.
```
Comment (edsiper) [inline plugins/in_kubernetes_events/kubernetes_events.c:359]: use /* */

File: plugins/in_kubernetes_events/kubernetes_events.c [hunk 2]
```diff
@@ -383,7 +368,121 @@ static bool check_event_is_filtered(struct k8s_events *ctx, msgpack_object *obj)
...
+static int process_event_object(struct k8s_events* ctx, flb_sds_t action,
+                         msgpack_object* item) 
+{
+    int ret = -1;
+    struct flb_time ts;
+    uint64_t resource_version;
+    msgpack_object* item_metadata;
+ 
+    if(strncmp(action, "ADDED", 5) != 0 && strncmp(action, "MODIFIED", 8) != 0 ) {
+        //We don't process DELETED nor BOOKMARK
```
Comment (edsiper) [inline plugins/in_kubernetes_events/kubernetes_events.c:381]: use /* */

File: plugins/in_kubernetes_events/kubernetes_events.c [hunk 3]
```diff
@@ -383,7 +368,121 @@ static bool check_event_is_filtered(struct k8s_events *ctx, msgpack_object *obj)
...
+        return 0;
+    }
+
+    item_metadata = record_get_field_ptr(item, "metadata");
+    if (item_metadata == NULL) {
+        flb_plg_warn(ctx->ins, "Event without metadata");
+        return -1;
+    }
+    ret = record_get_field_uint64(item_metadata,
+                                "resourceVersion", &resource_version);
```
Comment (edsiper) [inline plugins/in_kubernetes_events/kubernetes_events.c:391]: fix indentation

File: plugins/in_kubernetes_events/kubernetes_events.c [hunk 4]
```diff
@@ -383,7 +368,121 @@ static bool check_event_is_filtered(struct k8s_events *ctx, msgpack_object *obj)
...
+#endif
+
+    /* encode content as a log event */
+    flb_log_event_encoder_begin_record(ctx->encoder);
+    flb_log_event_encoder_set_timestamp(ctx->encoder, &ts);
+
+    ret = flb_log_event_encoder_set_body_from_msgpack_object(ctx->encoder, item);
+    if (ret == FLB_EVENT_ENCODER_SUCCESS) {
+        ret = flb_log_event_encoder_commit_record(ctx->encoder);
+    } else {
```
Comment (edsiper) [inline plugins/in_kubernetes_events/kubernetes_events.c:429]: else in a new line

File: plugins/in_kubernetes_events/kubernetes_events.c [hunk 5]
```diff
@@ -550,14 +584,35 @@ static int process_events(struct k8s_events *ctx, char *in_data, size_t in_size,
...
+        url = flb_sds_create(K8S_EVENTS_KUBE_API_URI);
+    } else {
+        url = flb_sds_create_size(strlen(K8S_EVENTS_KUBE_NAMESPACE_API_URI) + 
+                                  strlen(ctx->namespace));
+        flb_sds_printf(&url, K8S_EVENTS_KUBE_NAMESPACE_API_URI, ctx->namespace);
+    }
+
+    flb_sds_printf(&url, "?watch=1&resourceVersion=%llu", max_resource_version);
+    flb_plg_info(ctx->ins, "Requesting %s", url);
+    c = flb_http_client(u_conn, FLB_HTTP_GET, url,
```
Comment (edsiper) [inline plugins/in_kubernetes_events/kubernetes_events.c:603]: validate `c` is not NULL

File: plugins/in_kubernetes_events/kubernetes_events.c [hunk 6]
```diff
@@ -550,14 +584,35 @@ static int process_events(struct k8s_events *ctx, char *in_data, size_t in_size,
...
-static struct flb_http_client *make_event_api_request(struct k8s_events *ctx,
+static struct flb_http_client *make_event_watch_api_request(struct k8s_events *ctx,
+                                                      struct flb_connection *u_conn,                                                      
+                                                      uint64_t max_resource_version) {
+    flb_sds_t url;
+    struct flb_http_client *c;
+
+    if (ctx->namespace == NULL) {
+        url = flb_sds_create(K8S_EVENTS_KUBE_API_URI);
+    } else {
```
Comment (edsiper) [inline plugins/in_kubernetes_events/kubernetes_events.c:595]: else in new line

File: plugins/in_kubernetes_events/kubernetes_events.c [hunk 7]
```diff
@@ -679,6 +734,54 @@ static int k8s_events_sql_insert_event(struct k8s_events *ctx, msgpack_object *i
...
+{
+    int ret = 0;
+    char *token = NULL;
+    int root_type;
+    size_t consumed = 0;
+    char *buf_data = NULL;
+    size_t buf_size;
+    flb_sds_t payload;
+    
+    //we copy payload because tokenizer will overwrite when it finds end of string
```
Comment (edsiper) [inline plugins/in_kubernetes_events/kubernetes_events.c:748]: use /* */

File: plugins/in_kubernetes_events/kubernetes_events.c [hunk 8]
```diff
@@ -679,6 +734,54 @@ static int k8s_events_sql_insert_event(struct k8s_events *ctx, msgpack_object *i
...
+    payload = flb_sds_create_len(c->resp.payload, c->resp.payload_size);
+
+    token = strtok(payload, JSON_ARRAY_DELIM);
+    while ( token != NULL && ret == 0 ) {
+        ret = flb_pack_json(token, strlen(token), &buf_data, &buf_size, &root_type, &consumed);
+        if (ret == -1) {
+            flb_plg_error(ctx->ins, "could not process payload, incomplete or bad formed JSON: %s", token);
+        } else {
```
Comment (edsiper) [inline plugins/in_kubernetes_events/kubernetes_events.c:756]: else in new line (and all the others)

File: plugins/in_kubernetes_events/kubernetes_events.c [hunk 9]
```diff
@@ -679,6 +734,54 @@ static int k8s_events_sql_insert_event(struct k8s_events *ctx, msgpack_object *i
...
+            *bytes_consumed += strlen(token) + 1;
+            ret = process_watched_event(ctx, buf_data, buf_size);
+        }
+    
+        flb_free(buf_data);
+        if (buf_data) {
+            buf_data = NULL;
+        }
+        token = strtok(NULL, JSON_ARRAY_DELIM);
```
Comment (edsiper) [inline plugins/in_kubernetes_events/kubernetes_events.c:765]: we don't use strtok(). what do we need specifically here ?

File: plugins/in_kubernetes_events/kubernetes_events.c [hunk 10]
```diff
@@ -716,38 +821,70 @@ static int k8s_events_collect(struct flb_input_instance *ins,
...
         c = NULL;
     } while(continue_token != NULL);
 
     if (max_resource_version > ctx->last_resource_version) {
-        flb_plg_debug(ctx->ins, "set last resourceVersion=%lu", max_resource_version);
+        flb_plg_debug(ctx->ins, "set last resourceVersion=%llu", max_resource_version);
         ctx->last_resource_version = max_resource_version;
     }
+    
+    //Now that we've done a full list, we can use the resource version and do a watch
```
Comment (edsiper) [inline plugins/in_kubernetes_events/kubernetes_events.c:854]: /* */

**Review by edsiper — CHANGES_REQUESTED** [review]

File: plugins/in_kubernetes_events/kubernetes_events.c (hunk 9 above)
Comment (ryanohnemus) [reply plugins/in_kubernetes_events/kubernetes_events.c:765]: This function is processing data from the incoming http chunked stream (which is managed in the client.resp.payload) and I'm first creating a copy of that payload data into a string and then I use strtok is just to see if we have the `JSON_ARRAY_DELIM` available within any of the current data. If we do it makes a char* `token` to that string, then we attempt to parse it with the json lib. Then we just throw away the copied string. 

I can probably skip doing the copy and strtok and just use `strsep` on the client.resp.payload itself.

File: plugins/in_kubernetes_events/kubernetes_events.c (hunk 5 above)
Comment (ryanohnemus) [reply plugins/in_kubernetes_events/kubernetes_events.c:607]: this is done on line 865 after the return from this function

File: plugins/in_kubernetes_events/kubernetes_events.c (hunk 9 above)
Comment (ryanohnemus) [reply plugins/in_kubernetes_events/kubernetes_events.c]: good catch on this. I was not actually doing a second token check here... but i used `strpbrk` in the end and didn't need to make a copy of the payload string at all.

**Comment by ryanohnemus** [comment]
@edsiper - just force pushed a new version of this. I still have this PR draft mode because it was branched off of 2 other PRs: https://github.com/fluent/fluent-bit/pull/8316 & https://github.com/fluent/fluent-bit/pull/8323. I was assuming it would be easier to review those each individually and then I'd rebase this one with a smaller set of changes to review, but if you'd prefer to just do them all in one change PR review/merge, I can move this pr to ready to review.

**Comment by edsiper** [comment]
@ryanohnemus https://github.com/fluent/fluent-bit/pull/8316 & https://github.com/fluent/fluent-bit/pull/8323 are already merged. Let me know if this is ready please for v3 (before next monday)

**Comment by ryanohnemus** [comment]
Sounds great! I will rebase and fix the merge conflict and have this ready by tomorrow morning!

**Comment by ryanohnemus** [comment]
@edsiper this should be ready, however i'm getting ci build errors that i'm not able to reproduce in the dev container with the same cmake:

```
cmake  -DFLB_BACKTRACE=Off -DFLB_SHARED_LIB=Off -DFLB_DEBUG=On -DFLB_ALL=On -DFLB_EXAMPLES=Off -DFLB_JEMALLOC=On -DFLB_TESTS_INTERNAL=On -DFLB_TESTS_RUNTIME=On  -DFLB_WITHOUT_flb-rt-out_elasticsearch=1 -DFLB_WITHOUT_flb-rt-out_td=1 -DFLB_WITHOUT_flb-rt-out_forward=1 -DFLB_WITHOUT_flb-rt-in_disk=1 -DFLB_WITHOUT_flb-rt-in_proc=1 -DFLB_WITHOUT_flb-it-fstore=1 ../
```

The error is below, but i do not believe this is related to the changes in this diff: 
```
[ 21%] Building C object plugins/processor_sql/parser/CMakeFiles/processor-sql-parser.dir/sql_parser.c.o
In file included from /home/runner/work/fluent-bit/fluent-bit/plugins/processor_sql/parser/sql_parser.c:9:0:
/home/runner/work/fluent-bit/fluent-bit/include/fluent-bit/flb_mem.h:31:10: fatal error: jemalloc/jemalloc.h: No such file or directory
 #include <jemalloc/jemalloc.h>
          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [plugins/processor_sql/parser/CMakeFiles/processor-sql-parser.dir/build.make:90: plugins/processor_sql/parser/CMakeFiles/processor-sql-parser.dir/sql_parser.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:6975: plugins/processor_sql/parser/CMakeFiles/processor-sql-parser.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

**Comment by ryanohnemus** [comment]
@edsiper I was able to get a repro of the jemalloc build failure off the master branch and I believe it starts occurring with this commit: https://github.com/fluent/fluent-bit/commit/a89bf1cb7d8d7773161fd315abb8933c408a6600

**Comment by ryanohnemus** [comment]
@edsiper @patrick-stephens this didn't get merged in with 3.0 but it is ready to go. Can this be added to the next milestone/release?

**Comment by patrick-stephens** [comment]
Did you carry out the review comments from @edsiper ?

**Comment by ryanohnemus** [comment]
@patrick-stephens yes, unless I missed something they should all be marked resolved. I rebased and force pushed after some dependencies had a merge conflict, i think messes with the comment visibility

**Comment by edsiper** [comment]
@pwhelan do you think you can take a look at this one ?

File: plugins/in_kubernetes_events/kubernetes_events.c [hunk 11]
```diff
@@ -722,6 +857,43 @@ static int k8s_events_collect(struct flb_input_instance *ins,
...
+    ret = flb_http_do_request(c, &b_sent);
+    if (ret != 0) {
+        flb_plg_error(ins, "http do request error");
+        goto exit;
+    }
+
+    ret = FLB_HTTP_MORE;
+    bytes_consumed = 0;
+    chunk_proc_ret = 0;
+    while ((ret == FLB_HTTP_MORE || ret == FLB_HTTP_CHUNK_AVAILABLE) && chunk_proc_ret == 0) {
```
Comment (pwhelan) [inline plugins/in_kubernetes_events/kubernetes_events.c:884]: looping indefinitely inside the collect callback may not necessarily the correct way to do this. 

So far during my testing I have not seen any problems but this could result in problems with either starving out other coroutines or impeding safe shutdown.

From what I can tell there is a memory leak caused by the loop never actually exiting and therefore never calling `flb_http_client_destroy`.

```c
    ret = FLB_HTTP_MORE;
    bytes_consumed = 0;
    chunk_proc_ret = 0;
    while ((ret == FLB_HTTP_MORE || ret == FLB_HTTP_CHUNK_AVAILABLE) && chunk_proc_ret == 0) {
        ret = flb_http_get_response_data(c, bytes_consumed);
        bytes_consumed = 0;
        if( c->resp.status == 200 && ret == FLB_HTTP_CHUNK_AVAILABLE ) {
            chunk_proc_ret = process_http_chunk(ctx, c, &bytes_consumed);
        }
    }
    /* NOTE: skipping any processing after streaming socket closes */

    if (c->resp.status != 200) {
        flb_plg_warn(ins, "events watch failure, http_status=%d payload=%s", c->resp.status, c->resp.payload);
    }


    flb_plg_error(ins, "leaving collect callback"); // <- this line was added
                                                    // and never gets called.
exit:
    pthread_mutex_unlock(&ctx->lock);
    if (c) {
        flb_http_client_destroy(c);
    }
    if (u_conn) {
        flb_upstream_conn_release(u_conn);
    }
    FLB_INPUT_RETURN(0);
}
```

Here is the valgrind log:

```
==171983== 6,595 (32 direct, 6,563 indirect) bytes in 1 blocks are definitely lost in loss record 13 of 15
==171983==    at 0x484ABF3: calloc (vg_replace_malloc.c:1675)
==171983==    by 0x1F31F3: flb_calloc (flb_mem.h:95)
==171983==    by 0x1F3256: flb_kv_item_create_len (flb_kv.c:36)
==171983==    by 0x32F6D8: flb_http_add_header (flb_http_client.c:918)
==171983==    by 0x32ECE5: add_host_and_content_length (flb_http_client.c:617)
==171983==    by 0x32F1F4: flb_http_client (flb_http_client.c:763)
==171983==    by 0x446DE0: make_event_watch_api_request (kubernetes_events.c:606)
==171983==    by 0x4481F1: k8s_events_collect (kubernetes_events.c:863)
==171983==    by 0x22524B: input_pre_cb_collect (flb_input.h:517)
==171983==    by 0xFA30C6: co_init (amd64.c:117)
==171983== 
==171983== 25,184 (64 direct, 25,120 indirect) bytes in 1 blocks are definitely lost in loss record 15 of 15
==171983==    at 0x484ABF3: calloc (vg_replace_malloc.c:1675)
==171983==    by 0x2217BD: flb_calloc (flb_mem.h:95)
==171983==    by 0x225BF4: flb_input_coro_create (flb_input.h:437)
==171983==    by 0x225BF4: flb_input_coro_collect (flb_input.h:540)
==171983==    by 0x225BF4: input_collector_fd (flb_input_thread.c:158)
==171983==    by 0x22693E: engine_handle_event (flb_input_thread.c:180)
==171983==    by 0x22693E: input_thread (flb_input_thread.c:381)
==171983==    by 0x2868F1: step_callback (flb_worker.c:43)
==171983==    by 0x5348559: start_thread (pthread_create.c:447)
==171983==    by 0x53C5893: clone (clone.S:100)
==171983==
```

I see two ways this could be solved:

1. saving the flb_http_client in the context struct and releasing it during the exit callback (which might be unsafe).
2. implement the collection via flb_input_set_collector_event which would require quite a bit of work.

The in_mqtt plugin implements flb_input_set_collector_event in case you wanted something to reference.

**Review by pwhelan — COMMENTED** [review]
I have a lot of comments regarding the manner in which the events are continually processed.

File: plugins/in_kubernetes_events/kubernetes_events.c (hunk 11 above)
Comment (ryanohnemus) [reply plugins/in_kubernetes_events/kubernetes_events.c:884]: @pwhelan thank you for the feedback!

1) This input is threaded, I assumed this would be enough to isolate it from starving other coros, but I wasn't 100% certain. Is this enough?

2) I will look into the memory leak on shutdown, but I'd prefer to keep this as the collect time type for now as it would take a decent effort to move this to the event type.

Comment (pwhelan) [reply plugins/in_kubernetes_events/kubernetes_events.c:915]: > This input is threaded, I assumed this would be enough to isolate it from starving other coros, but I wasn't 100% certain. Is this enough?

Running in a thread should solve that. Since it also manages to use the network API that uses coroutines I think this will work just fine.

**Comment by ryanohnemus** [comment]
@pwhelan @edsiper @lecaros - this fell out of the next milestone with the last few 3.0 releases but is still ready to go. Can this be added to the existing 3.0.7 milestone? Thank you

**Comment by ryanohnemus** [comment]
Rebased to fix merge conflict.

@edsiper @pwhelan @lecaros could this be tagged in the 3.1.0 milestone so it does not get missed? Thank you!

**Comment by patrick-stephens** [comment]
We probably should update docs as well, particularly with the RBAC change. Could you link a docs PR @ryanohnemus ?

Do we have any int tests for this btw?

**Comment by ryanohnemus** [comment]
@patrick-stephens added doc via https://github.com/fluent/fluent-bit-docs/pull/1396

No int tests, but I added unit tests for the plugin in this PR.
