### PR TITLE
in_tail: Preventing incorrect inode usage from db. #8025

### LINKED ISSUE #8025: in_tail: missing log for offset processing due to non-existent old inodes in sqlite.
## Bug Report

**Describe the bug**
When Fluent-bit is monitoring a file that gets deleted after it has been shutdown, and if the inode exists in the SQLite file, it may result in log loss with incorrect offsets from duplicate inodes.

So accurate offset processing is required by comparing the filename of the previous inode.

```
on EXT4

echo "1" > testfile; stat -c %i testfile; rm -f testfile; echo "1" > testfile; stat -c %i testfile
4223667
4223667
```

**To Reproduce**
- Rubular link if applicable:
- Example log message if applicable:
```
[2023/10/11 09:53:11] [debug] [input:tail:tail.0] inode=4486486 with offset=2 appended as /root/testing/bulk2
```
- Steps to reproduce the problem:

```
# clear test files
rm -f /root/testing/bulk1
rm -f /root/testing/bulk2
rm -f /tmp/input.db

# fluentbit start	
/opt/fluent-bit/bin/fluent-bit_2.1.10 -c /opt/fluent-bit/etc/fluent-bit/fluent-bit.conf

echo "1" >> /root/testing/bulk1; stat -c %i /root/testing/bulk1

[2023/10/11 09:51:53] [debug] [input:tail:tail.0] inode=4486486 file=/root/testing/bulk1 promote to TAIL_EVENT
[2023/10/11 09:51:53] [ info] [input:tail:tail.0] inotify_fs_add(): inode=4486486 watch_fd=1 name=/root/testing/bulk1
[2023/10/11 09:51:53] [debug] [input:tail:tail.0] [static files] processed 0b, done
[2023/10/11 09:51:54] [debug] [task] created task=0x7f5d44a39e60 id=0 OK
[2023/10/11 09:51:54] [debug] [output:stdout:stdout.0] task_id=0 assigned to thread #0
[0] tail.0: [[1697017913.231894845, {}], {"log"=>"1"}]

# fluentbit stop
# sqlite3 /tmp/input.db
SQLite version 3.7.17 2013-05-20 00:56:22
sqlite> select * from in_tail_files;
1|/root/testing/bulk1|2|4486486|1697017913|0

# file change
rm -f /root/testing/bulk1; echo "2" >> /root/testing/bulk2 ; echo "3" >> /root/testing/bulk2; stat -c %i /root/testing/bulk2

# fluentbit start
# missing "2" log
/opt/fluent-bit/bin/fluent-bit_2.1.10 -c /opt/fluent-bit/etc/fluent-bit/fluent-bit.conf
[2023/10/11 09:53:11] [debug] [input:tail:tail.0] flb_tail_fs_inotify_init() initializing inotify tail input
[2023/10/11 09:53:11] [debug] [input:tail:tail.0] inotify watch fd=30
[2023/10/11 09:53:11] [debug] [input:tail:tail.0] scanning path /root/testing/bulk*
[2023/10/11 09:53:11] [debug] [input:tail:tail.0] inode=4486486 with offset=2 appended as /root/testing/bulk2
[2023/10/11 09:53:11] [debug] [input:tail:tail.0] scan_glob add(): /root/testing/bulk2, inode 4486486
[2023/10/11 09:53:11] [debug] [input:tail:tail.0] 1 new files found on path '/root/testing/bulk*'
[2023/10/11 09:53:11] [ info] [input:storage_backlog:storage_backlog.1] initializing
[2023/10/11 09:53:11] [ info] [input:storage_backlog:storage_backlog.1] storage_strategy='memory' (memory only)
[2023/10/11 09:53:11] [debug] [storage_backlog:storage_backlog.1] created event channels: read=32 write=33
[2023/10/11 09:53:11] [ info] [input:storage_backlog:storage_backlog.1] queue memory limit: 4.8M
[2023/10/11 09:53:11] [debug] [stdout:stdout.0] created event channels: read=34 write=35
[2023/10/11 09:53:11] [debug] [router] match rule tail.0:stdout.0
[2023/10/11 09:53:11] [debug] [router] match rule storage_backlog.1:stdout.0
[2023/10/11 09:53:11] [ info] [sp] stream processor started
[2023/10/11 09:53:11] [debug] [input chunk] update output instances with new chunk size diff=4096, records=1, input=tail.0
[2023/10/11 09:53:11] [ info] [output:stdout:stdout.0] worker #0 started
[2023/10/11 09:53:11] [debug] [input:tail:tail.0] [static files] processed 2b
[2023/10/11 09:53:11] [debug] [input:tail:tail.0] inode=4486486 file=/root/testing/bulk2 promote to TAIL_EVENT
[2023/10/11 09:53:11] [ info] [input:tail:tail.0] inotify_fs_add(): inode=4486486 watch_fd=1 name=/root/testing/bulk2
[2023/10/11 09:53:11] [debug] [input:tail:tail.0] [static files] processed 0b, done
[2023/10/11 09:53:11] [debug] [task] created task=0x7f8224639e60 id=0 OK
[2023/10/11 09:53:11] [debug] [output:stdout:stdout.0] task_id=0 assigned to thread #0
[0] tail.0: [[1697017991.013734539, {}], {"log"=>"3"}]

# invalid file name
# size change. 2 => 4
sqlite> select * from in_tail_files;
1|/root/testing/bulk1|4|4486486|1697017913|0

```
**Expected behavior**
Accurate offset processing is required by comparing the filename of the previous inode.

**Screenshots**
None

**Your Environment**

* Version used:
  * tested 2.1.10
* Configuration:
```
[SERVICE]
    flush        1
    daemon       Off
    log_level    debug

    parsers_file parsers.conf
    plugins_file plugins.conf
    storage.metrics on
    storage.path /tmp/storage
    storage.sync normal
    storage.checksum off
    storage.backlog.mem_limit 5M

[INPUT]
    Name tail
    Path /root/testing/bulk*
    Exclude_Path *.gz,*.zip

    Read_from_Head true
    Refresh_Interval 3
    Rotate_Wait 10

    storage.type filesystem
    storage.pause_on_chunks_overlimit true

    DB /tmp/input.db
    DB.sync normal
    DB.locking false

[OUTPUT]
    name  stdout
    match *
```
* Environment name and version (e.g. Kubernetes? What version?):
  * docker images CentOS 7.9.2009
  * no k8s
* Server type and version:
  * Intel i5-10400
  * file system : ssd ext4
* Operating System and version:
  * base system : Ubuntu 22.04
* Filters and plugins:
  * in_tail
**Additional context**

### PR DESCRIPTION
**Pull request by jinyongchoi**
Preventing incorrect inode usage from db.

The first commit involves deleting items that are not being monitored by Fluent-Bit when it starts.

The second commit involves considering already running Fluent-Bit instances, preventing incorrect inode usage during execution.
This commit is more about enhancement option than fixing a bug. That's why 'true' and 'false' may be needed depending on the user's use case.

Fixes #8025

----
Enter `[N/A]` in the box, if an item is not applicable to your change.

**Testing**
Before we can approve your change; please submit the following in a comment:
- [x] Example configuration file for the change

- fluent-bit-test.conf

```

[SERVICE]
    flush        1
    daemon       Off
    log_level    info

    parsers_file parsers.conf
    plugins_file plugins.conf
    storage.metrics on
    storage.path /tmp/storage
    storage.sync normal
    storage.checksum off
    storage.backlog.mem_limit 5M

[INPUT]
    Name tail
    Path /tmp/testing/bulk*
    Exclude_Path *.gz,*.zip
    log_level    info
    Offset_Key   offset

    Read_from_Head true
    Refresh_Interval 1
    Rotate_Wait 1
    Inotify_Watcher false
    
    storage.type filesystem
    storage.pause_on_chunks_overlimit true

    DB /tmp/input.db
    DB.sync normal
    DB.locking false
    # new config
    DB.compare_filename true

[OUTPUT]
    name  stdout
    match *

```

- gen.sh
To account for situations where file events may not be properly detected, the creation and deletion process is repeated without using 'sleep'.
```

#!/bin/bash

max_iterations=100000

for ((iteration = 1; iteration <= max_iterations; iteration++)); do
    start_range=$((($iteration - 1) * 100 + 1))
    end_range=$(($iteration * 100))

    for i in $(seq $start_range $end_range); do
        filename="bulk$i.log"
        echo "$i." >> "$filename"
        stat -c%i "$filename"
    done

    sleep 0

    for i in $(seq $start_range $end_range); do
        filename="bulk$i.log"
        rm "$filename"
    done
done

```

- (1/2) delete stale inode from db
```
mkdir -p  /tmp/testing/
cd /tmp/testing/
rm -f /tmp/input.db
rm -f /tmp/testing/*.log

# fluentbit start
/opt/fluent-bit/bin/fluent-bit_fixed -c /opt/fluent-bit/etc/fluent-bit/fluent-bit-test.conf

# write
echo "1" > /tmp/testing/bulk.log;stat -c %i /tmp/testing/bulk.log

# fluentbit stop

# logroate and create new one.
rm -f /tmp/testing/bulk.log

# fluentbit start
/opt/fluent-bit/bin/fluent-bit_fixed -c /opt/fluent-bit/etc/fluent-bit/fluent-bit-test.conf

# log
[2023/10/19 05:50:40] [ info] [input:tail:tail.0] db: delete unmonitored stale inodes from the database: count=1

```

- (2/2) If the filename differs when retrieving the inode from the database, the inode is deleted.
```
mkdir -p  /tmp/testing/
cd /tmp/testing/
rm -f /tmp/input.db
rm -f /tmp/testing/*.log

# fluentbit start
/opt/fluent-bit/bin/fluent-bit_fixed -c /opt/fluent-bit/etc/fluent-bit/fluent-bit-test.conf

# run gen script
while true; do sh ./gen.sh; sleep 0; done

# log
# Fluentbit can read or may fail to read, but it must not read incorrectly.
[2023/10/19 06:24:14] [ info] [input:tail:tail.0] db: exists stale file from database: id=19 inode=4491280 offset=5 name=/tmp/testing/bulk126.log file_inode=4491280 file_name=/tmp/testing/bulk925.log
[2023/10/19 06:24:14] [ info] [input:tail:tail.0] db: stale file deleted from database: id=19
[2023/10/19 06:24:14] [ info] [input:tail:tail.0] db: exists stale file from database: id=20 inode=4491305 offset=5 name=/tmp/testing/bulk127.log file_inode=4491305 file_name=/tmp/testing/bulk926.log
[2023/10/19 06:24:14] [ info] [input:tail:tail.0] db: stale file deleted from database: id=20
```

- [x] Debug log output from testing the change

```
(1/2) commit
[2023/10/19 05:13:58] [ info] [input:tail:tail.0] db: delete unmonitored stale inodes from the database: count=1
```

```
(2/2) commit
[2023/10/19 05:14:03] [ info] [input:tail:tail.0] db: exists stale file from database: id=1 inode=29632163 offset=12 name=test_db.log file_inode=29632163 file_name=test_db_moved.log
[2023/10/19 05:14:03] [ info] [input:tail:tail.0] db: stale file deleted from database: id=1
```

- [x] Attached [Valgrind](https://valgrind.org/docs/manual/quick-start.html) output that shows no leaks or memory corruption was found
```
valgrind --leak-check=full ./bin/flb-rt-in_tail
...
==120724== HEAP SUMMARY:
==120724==     in use at exit: 0 bytes in 0 blocks
==120724==   total heap usage: 98,919 allocs, 98,919 frees, 32,217,198 bytes allocated
==120724== 
==120724== All heap blocks were freed -- no leaks are possible
==120724== 
==120724== For lists of detected and suppressed errors, rerun with: -s
==120724== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
```

If this is a change to packaging of containers or native binaries then please confirm it works for all targets.
- [`N/A`] Run [local packaging test](./packaging/local-build-all.sh) showing all targets (including any new ones) build.
- [`N/A`] Set `ok-package-test` label to test for all targets (requires maintainer to do).

**Documentation**

- [x] Documentation required for this feature

[#1238](https://github.com/fluent/fluent-bit-docs/pull/1238)

**Backporting**

- [`N/A`] Backport to latest stable release.

----

Fluent Bit is licensed under Apache 2.0, by submitting this pull request I understand that this code will be released under the terms of that license.

### CODE REVIEW

**Comment by jinyongchoi** [comment]
This PR is now ready for review.
Thanks!

File: plugins/in_tail/tail_db.c [hunk 1]
```diff
@@ -116,11 +141,26 @@ static int db_file_exists(struct flb_tail_file *file,
...
         *offset = sqlite3_column_int64(ctx->stmt_get_file, 2);
 
         /* inode: column 3 */
         *inode = sqlite3_column_int64(ctx->stmt_get_file, 3);
+
+        /* Checking if the file's name and inode match exactly */
+        if (ctx->compare_filename) {
+            if (flb_tail_target_file_name_cmp((char *) name, file) != 0) {
+                exists = FLB_FALSE;
+                flb_plg_info(ctx->ins, "db: exists stale file from database:"
```
Comment (pwhelan) [inline plugins/in_tail/tail_db.c:157]: This should probably be demoted to debugging.

File: plugins/in_tail/tail_db.c [hunk 2]
```diff
@@ -168,6 +208,42 @@ static int db_file_insert(struct flb_tail_file *file, struct flb_tail_config *ct
     return flb_sqldb_last_id(ctx->db);
 }
 
+static int stmt_add_param_concat(struct flb_tail_config *ctx,
+                                 flb_sds_t *stmt_sql, uint64_t count)
+{
+    uint64_t i;
```
Comment (pwhelan) [inline plugins/in_tail/tail_db.c:214]: please use the less ambiguous 'idx' instead of just 'i'.

File: plugins/in_tail/tail_db.c [hunk 3]
```diff
@@ -275,3 +356,121 @@ int flb_tail_db_file_delete(struct flb_tail_file *file,
...
+/*
+ * Delete stale file from database
+ */
+int flb_tail_db_stale_file_delete(struct flb_input_instance *ins,
+                                  struct flb_config *config,
+                                  struct flb_tail_config *ctx)
+{
+    int ret = -1;
+    size_t sql_size;
+    uint64_t i;
```
Comment (pwhelan) [inline plugins/in_tail/tail_db.c:369]: same as above, for clarity's sake.

File: plugins/in_tail/tail_db.c [hunk 4]
```diff
@@ -95,16 +95,41 @@ int flb_tail_db_close(struct flb_sqldb *db)
     return 0;
 }
 
+static int flb_tail_db_file_delete_by_id(struct flb_tail_config *ctx,
+                                         uint64_t id)
+{
+    int ret;
+
+    /* Bind parameters */
+    sqlite3_bind_int64(ctx->stmt_delete_file, 1, id);
```
Comment (pwhelan) [inline plugins/in_tail/tail_db.c:104]: this call should check the return value: https://www.sqlite.org/c3ref/bind_blob.html.

File: plugins/in_tail/tail_db.c [hunk 5]
```diff
@@ -116,11 +141,26 @@ static int db_file_exists(struct flb_tail_file *file,
         /* id: column 0 */
         *id = sqlite3_column_int64(ctx->stmt_get_file, 0);
 
+        /* name: column 1 */
+        name = sqlite3_column_text(ctx->stmt_get_file, 1);
```
Comment (pwhelan) [inline plugins/in_tail/tail_db.c:145]: the return value for this call should be checked for a NULL value, just in case.

File: plugins/in_tail/tail_db.c [hunk 6]
```diff
@@ -275,3 +356,121 @@ int flb_tail_db_file_delete(struct flb_tail_file *file,
...
+                      ret);
+        flb_sds_destroy(stale_delete_sql);
+        return -1;
+    }
+
+    /* Bind parameters */
+    i = 1;
+    mk_list_foreach_safe(head, tmp, &ctx->files_static) {
+        file = mk_list_entry(head, struct flb_tail_file, _head);
+        sqlite3_bind_int64(stmt_delete_inodes, i, file->inode);
```
Comment (pwhelan) [inline plugins/in_tail/tail_db.c:454]: this call could also return an error, however unlikely it might be.

**Review by pwhelan — COMMENTED** [review]
I made a few observations concerning error checking. The actual functionality seems to be robust and the tests seem to actually prove the patch works as expected.

**Comment by edsiper** [comment]
@jinyongchoi thanks for your PR looking forward to merge this, would you please address the comments pointed out by @pwhelan ? thank you

**Comment by jinyongchoi** [comment]
@pwhelan Thank you for the review.
@edsiper I have addressed the points mentioned by @pwhelan.
Please review the changes at your convenience and let me know if any further adjustments are needed. 
thank you!

**Comment by RicardoAAD** [comment]
Tested the new implementation, and it works as expected. When the option **DB.compare_filename** is enabled, the incorrect offset issue doesn't occur

**Comment by pwhelan** [comment]
@edsiper I have checked and all my comments have been resolved.

**Review by pwhelan — APPROVED** [review]
LGTM

**Comment by edsiper** [comment]
thank you

**Comment by zdyj3170101136** [comment]
in k8s, this would cause re-read file after restart.

https://github.com/fluent/fluent-bit/issues/11060

**Comment by zdyj3170101136** [comment]
i wonder why this could fix the problem?

fluentbit first uses the inode to lookup in the hashtable.

If the inode cannot be found but there is a corresponding record in the db，it is strange.

Because when the file is deleted, the inode number and db will be deleted together
```
flb_tail_file_append -> flb_tail_file_exists -> db_file_exists 
```
