### PR TITLE
filter_multiline: Reset group metadata buf on flush - Fixes 9262,8925,9337,8567

### LINKED ISSUE #8567: CPU Continuously growing with Fluent-bit version > 2.0.14 on Windows Server 2019 with Multiline Filter Plugin
## Bug Report

**Describe the bug**
CPU Continuously growing with Fluent-bit version > 2.0.14 on Windows Server 2019 with Multiline Filter Plugin.
This is not issue with Fluent-bit version 2.0.14. Tried all the versions 2.1.* and 2.2.*, and all these versions has same issue.

**To Reproduce**
- Rubular link if applicable:
- Example log message if applicable:
```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluent-bit-windows
  labels:
    app: fluent-bit-windows
spec:
  selector:
    matchLabels:
      app: fluent-bit-windows
  template:
    metadata:
      labels:
        app: fluent-bit-windows
    spec:
      affinity:
       nodeAffinity:
         requiredDuringSchedulingIgnoredDuringExecution:
           nodeSelectorTerms:
           - matchExpressions:
             - key: kubernetes.io/os
               operator: In
               values:
               - windows
             - key: kubernetes.azure.com/os-sku
               operator: In
               values:
               - Windows2019 # For Windows 2022, use Windows2022
      containers:
      - name: fluent-bit
        image: fluent/fluent-bit:windows-2019-2.2.2 # For Windows 2022, use 2022 instead of 2019
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "750Mi"
            cpu: "500m"
          # requests:
          #   memory: "100Mi"
          #   cpu: "50m"
        volumeMounts:
        - mountPath: C:\ProgramData\docker\containers
          name: docker-windows-containers
          readOnly: true
        - mountPath: C:\var #Read + Write access on this for position file
          name: docker-windows-kuberenetes-container-logs
        - name: config-volume
          mountPath: /fluent-bit/etc/
      volumes:
      - name: docker-windows-kuberenetes-container-logs
        hostPath:
          path: C:\var
      - name: docker-windows-containers
        hostPath:
          path: C:\ProgramData\docker\containers
          type: DirectoryOrCreate
      - name: config-volume
        configMap:
          name: fluent-bit-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush         1
        Log_Level     info
        Daemon        off
        Parsers_File  parsers.conf

    [INPUT]
        Name                tail
        Path                C:\\var\\log\\containers\*.log
        Multiline.Parser    cri
        Tag                 windows.*
        Read_from_Head      true
        DB                  C:\\var\\log\\fblogs.db
        DB.Sync             Off
        Rotate_Wait         20
        Refresh_Interval    30
        Path_Key            filepath
        Skip_Long_Lines     On

    [FILTER]
        Name multiline
        Match *
        multiline.key_content log
        multiline.parser go,java,python

    [OUTPUT]
        Name          Null
        Match         *

```
- Steps to reproduce the problem:
1. Apply this yaml on to Kubernetes cluster with windows server 2019 nodes
kubectl apply -f https://raw.githubusercontent.com/microsoft/Docker-Provider/gangams/fix-windows-agent-cpu-breaches/test/fluent-bit-windows.yaml
2. Deploy some test workloads for example
kubectl apply -f https://raw.githubusercontent.com/microsoft/Docker-Provider/gangams/fix-windows-agent-cpu-breaches/test/scenario/multiline/dotnet-win.yaml
kubectl apply -f https://raw.githubusercontent.com/microsoft/Docker-Provider/gangams/fix-windows-agent-cpu-breaches/test/scenario/multiline/golang-win.yaml
kubectl apply -f https://raw.githubusercontent.com/microsoft/Docker-Provider/gangams/fix-windows-agent-cpu-breaches/test/scenario/multiline/java-win.yaml
kubectl apply -f https://raw.githubusercontent.com/microsoft/Docker-Provider/gangams/fix-windows-agent-cpu-breaches/test/scenario/multiline/python-win.yaml

**Expected behavior**
CPU shouldnt grow increasingly grow and usage should be same as fluent-bit version 2.0.14.

**Screenshots**
CPU Usage  with fluent-bit version 2.0.14 vs fluent-bit version 2.2.2
image

**Your Environment**

* Version used: Fluent-bit 2.0.14 and Fluent-bit 2.2.2
* Configuration: Kubernetes with Windows Server 2019
* Environment name and version (e.g. Kubernetes? What version?): Kubernetes, version : v1.26.12
* Server type and version: Windows Server 2019
* Operating System and version:
* Filters and plugins:  Tail, Multiline and Output

**Additional context**

### LINKED ISSUE #8925: Tail + Multi-line parser consumes more than 100% CPU
## Bug Report

**Describe the bug**
The Pod CPU usage keep raising until it reached it limit.
It does not happen with v1.9.x
The reason that i want to upgrade to v3.x is that it solve the MajorPageFault issue for us

**To Reproduce**
- Steps to reproduce the problem:
This is my configuration (i left only the relevant parts):
````
  service: |
    [SERVICE]
        Daemon Off
        Flush 1
        Log_Level info
        Parsers_File /fluent-bit/etc/parsers.conf
        Parsers_File /fluent-bit/etc/conf/custom_parsers.conf
        HTTP_Server On
        HTTP_Listen 0.0.0.0
        HTTP_Port 2020
        Health_Check On
        storage.path /var/log/flb-storage/
        storage.sync normal
        storage.checksum off
        storage.total_limit_size 500MB
        storage.pause_on_chunks_overlimit On
        storage.max_chunks_up 20
        storage.backlog.mem_limit 10MB
        storage.type filesystem
        storage.delete_irrecoverable_chunks On

  inputs: |
    [INPUT]
        Name tail
        Alias kube
        DB /var/log/flb_kube.db
        Path /var/log/containers/multiline-log-generator-*.log
        multiline.parser cri
        storage.type filesystem
        Tag kube.*
        Mem_Buf_Limit 5MB
        Static_Batch_Size 50MB
        Skip_Long_Lines On
        Inotify_Watcher True
        Refresh_Interval 10
        Rotate_Wait 60
        Buffer_Chunk_Size 32k

filters: |
    [FILTER]
        Name                  multiline
        Match                 kube.*
        multiline.parser      multiline-java
        multiline.key_content log
        emitter_mem_buf_limit 1MB
        emitter_storage.type  filesystem
        buffer                On
        flush_ms              1000
        mode                  parser
    [FILTER]
        Name                 parser
        Match                kube.*
        Key_Name             log
        Parser               javaspringboot
        Parser               javalog4j2
        Reserve_Data         On
    [FILTER]
        Name kubernetes
        Match kube.*
        Merge_Log            On
        Merge_Log_Key        data
        Keep_Log             On
        K8S-Logging.Parser   On
        K8S-Logging.Exclude  On
        Buffer_Size          64k
    [FILTER]
        Name                  nest
        Match                 kube.*
        Operation             lift
        Nested_under          kubernetes
        Add_prefix            kubernetes_
    [FILTER]
        Name                  nest
        Match                 kube.*
        Operation             lift
        Nested_under          kubernetes_labels
        Add_prefix            kubernetes_labels_
    [FILTER]
        Name                  nest
        Match                 kube.*
        Operation             lift
        Nested_under          kubernetes_annotations
        Add_prefix            kubernetes_annotations_     
    [FILTER]
        Name                  modify
        Match                 kube.*
        Rename                kubernetes_labels_app     app_name
    [FILTER]
        Name                  modify
        Match                 kube.*
        Rename                log                       message
        Rename                kubernetes_host           host
        Rename                kubernetes_pod_name       pod
        Rename                kubernetes_namespace_name namespace
        Rename                kubernetes_labels_env     env
        Rename                kubernetes_labels_app     app
        Rename                kubernetes_labels_build   build
        Rename                kubernetes_labels_model   model
        Hard_rename           time timestamp
        Remove                logtag
        Remove                stream
        Remove                _p
        Remove_wildcard       kubernetes

    [OUTPUT]
        Name Stdout
        Match kube.*
````
- Here is the deployment that i used to generate log
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: multiline-log-generator
spec:
  selector:
    matchLabels:
      app: multiline-log-generator
  replicas: 3
  template:
    metadata:
      labels:
        app: multiline-log-generator
    spec:
      containers:
      - name: multiline-log-generator
        image: busybox
        command: ["/bin/sh","-c"]
        # args: ["echo \"2024-05-31T02:31:38,925 [INFO] --- [1] i.f.k.c.d.i.AbstractWatchManager#logEndError : Watch connection error recieved 136654 times without progress, will reconnect if possible\"; while true; do echo \"io.fabric8.kubernetes.client.KubernetesClientException: Received 401 on websocket. Failure executing: GET at: https://50A83A7613136866C224BB3E0AFF6B61.gr7.ap-northeast-1.eks.amazonaws.com/api/v1/namespaces/jenkins/pods?resourceVersion=522500639&allowWatchBookmarks=true&watch=true. Message: Unauthorized.\";echo \"at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.requestFailure(OperationSupport.java:660)\";echo \"at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.requestFailure(OperationSupport.java:660)\";echo \"at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.requestFailure(OperationSupport.java:660)\"; sleep 1; done"]
        args: ["no=1;while true;do echo \"2024-06-06T22:57:16,270 [INFO ] --- [      Thread-98] c.w.d.s.AutoDrawService                  : 2024-06-06 22:57:16 彩票(LUCKYSB) [Draw] (53837690) 7,1,9,3,8,10,5,4,6,2 evict:[{key='[LUCKYSB]', deleted=0}, {key='[LUCKYSB_20240606]', deleted=0}, {key='resultsTodayCache[LUCKYSB]', deleted=0}, {key='resultsTodayCache[LUCKYSB_20240606]', deleted=0}]\";echo \"Line number $no\";no=$((no+1));sleep 0.1;done;tail -f /dev/null"]
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
      tolerations:
      - operator: "Exists"
        effect: "NoSchedule"
```
**Expected behavior**
The CPU usage should remain stable throughout the period since the number of logs collected or throughput is the same.

I am not really sure what wrong with my configuration because the performance is day and night between these 2 versions
**Screenshots**
v3.0.6 Metrics
image

v1.9.10
image

**Your Environment**

* Version used: 3.0.6
* Environment name and version (e.g. Kubernetes? What version?): Kubernetes

**Additional context**

### LINKED ISSUE #9262: The multiline plugin is abnormal.
## Bug Report

**Describe the bug**
I have the following problem after fluent-bit has been up for a while
The CPU usage keeps increasing until the CPU of the entire node is used up.
The memory usage of fluent-bit keep increasing, causing OOM.

**To Reproduce**
- Rubular link if applicable:
- Example log message if applicable:
```
[2024/08/22 06:29:13] [ info] [input] resume emitter_for_multiline.1
[2024/08/22 06:29:13] [ info] [input] resume tail.1
[2024/08/22 06:29:13] [ info] [input] resume tail.2
[2024/08/22 06:29:13] [ info] [input] resume tail.0
[2024/08/22 06:29:13] [ info] [input] emitter.3 resume (mem buf overlimit)
```
- Steps to reproduce the problem:

**Expected behavior**
The CPU usage and memory usage do not increase continuously

**Screenshots**

**Your Environment**
Version used: 3.1.6
Configuration:
Environment name and version (e.g. Kubernetes? What version?): Kubernetes v1.25.3
Server type and version:
Operating System and version:
Filters and plugins: tail multiline

**Additional context**
The fluent-bit.conf file in the first container is configured as follows:
```
[INPUT]
    name tail
    path /onip/log/*/var/profile/*/*.alog,/onip/log/*/var/profile/*/*.blog,xxx
    Path_Key path
    Key message
    Tag rating_profile
    Buffer_Chunk_Size 10M
    Buffer_Max_Size 10M
    Mem_Buf_Limit 10M
    Ignore_Older 1h

[INPUT]
    name tail
    path /onip/log/*/var/profile1/*/*.alog,/onip/log/*/var/profile1/*/*.blog,xxx
    Path_Key path
    Key message
    Tag rating_profile
    Buffer_Chunk_Size 10M
    Buffer_Max_Size 10M
    Mem_Buf_Limit 10M
    Ignore_Older 1h

[FILTER]
    Name modify
    Match rating_profile
    Add index_pre rating_profile
    Add formate_type rating_profile
    Add src_sys cbs_179_union_testing

[FILTER]
    name                  multiline
    match                 rating_profile
    multiline.key_content message
    multiline.parser      multiline_rating_profile

[FILTER]
    name                  grep
    match                 rating_profile
    regex                 message ^\d{8} \d{6}\.\d{3}
```
```
[MULTILINE_PARSER]
    name          multiline_rating_profile
    type          regex
    flush_timeout 1000
    rule      "start_state"   "^\d{8} \d{6}\.\d{3}"                    "cont"
    rule      "cont"          "^((?!^\d{8} \d{6}\.\d{3}).)*$" 
```
配置文件中添加了multiline
At first, the CPU usage keeps increasing. After the CPU usage reaches the top, (The CPU limits of the container are set to two cores.) The memory usage keeps increasing, and logs cannot be collected.
image
image
image

The configuration of the other container is as follows:
```
[INPUT]
    name tail
    path /onip/log/*/var/profile/*/*.alog,/onip/log/*/var/profile/*/*.blog,xxx
    Path_Key path
    Key message
    Tag rating_profile
    Buffer_Chunk_Size 10M
    Buffer_Max_Size 10M
    Mem_Buf_Limit 10M
    Ignore_Older 1h

[INPUT]
    name tail
    path /onip/log/*/var/profile1/*/*.alog,/onip/log/*/var/profile1/*/*.blog,xxx
    Path_Key path
    Key message
    Tag rating_profile
    Buffer_Chunk_Size 10M
    Buffer_Max_Size 10M
    Mem_Buf_Limit 10M
    Ignore_Older 1h

[FILTER]
    Name modify
    Match rating_profile
    Add index_pre rating_profile
    Add formate_type rating_profile
    Add src_sys cbs_179_union_testing

[FILTER]
    name                  grep
    match                 rating_profile
    regex                 message ^\d{8} \d{6}\.\d{3}
```
For the second container, I removed the multi-line parsing configuration. After the container was started, the CPU was stable.
image

I don't know if it's a problem with the configuration I wrote, or a problem with the multiline plugin.
However, the first container does collect single-line and multi-line log information in normal cases.
The second container can collect logs continuously.

### LINKED ISSUE #9337: CPU usage goes to 100% when using custom multiline parsing
## Bug Report

**Describe the bug**

After enabling multiline parsing with Fluentbit in an EKS cluster with Fluentbit, CPU usage of fluentbit pods goes to 100% of the limits after some hours (100m, but tried with 300m as well). Without multiline parsing CPU never goes above 8-9m. Even though multiline parsing works well for some hours, then it stops sending the logs, as CPU is throttled and, eventually, RAM usage reaches any limit you define for the pod as well, thus killing the pod through OOM error code.

The way logs should be parsed is simple:
`start_state`: any line with a timestamp (this is, including `[]` somewhere in the log) must be considered a new log.
`cont_state`: any line not including a timestamp (this is, not including a starting `[`) must be considered part of the last log.

**To Reproduce**
- Rubular link if applicable: https://rubular.com/r/gxWSpdiknqMlQa
- Example log message if applicable:
```
[2024-09-03 14:09:13,881] {file.py:function:211} INFO - request_id: 38bd4b23-d39d-4cf4-838d-f4cb6ae02fa6 - operation started
[2024-09-03 14:09:13,881] {file.py:function:224} INFO - request_id: 38bd4b23-d39d-4cf4-838d-f4cb6ae02fa6 - update, params: {'user_info': {'groups': [{'id': 'group_id', 'account': 'custom'}, {'id': 'group_id', 'account': 'custom', 'permissions': ''}], 'user_id': 'user_id'}, 'opt_id':opt_id, 'opt_obj':{'configuration': [{'key': 'size', 'value': '1.5'},
                   {'key': 'rnd_vl', 'value': '2024'},
                   {'key': 'cat_opt', 'value': 'static'}],
 'description': '',
 'function': 'function',
 'group_id': 'group_id',
 'name': 'function'}, }
[2024-09-03 14:09:13,882] {file.py:get:59} DEBUG - request_id: 38bd4b23-d39d-4cf4-838d-f4cb6ae02fa6 - Fetching objects with criteria : {'id': 'object_id'}

```

**Expected behavior**
Multiline is working fine, but eventually the pods will stop collecting the logs after reaching 100% of the CPU and/or memory limits.

**Screenshots**

**Your Environment**
K8s: `EKS 1.29 (AWS)`
EKS node image: `Bottlerocket OS 1.20.1 (aws-k8s-1.29)`
Fluentbit image: `cr.fluentbit.io/fluent/fluent-bit:3.0.4`
Helm chart: `helm.sh/chart=fluent-bit-0.46.7`

```bash
custom_parsers.conf:
----
[MULTILINE_PARSER]
    name          multiline-regex-python
    key_content   log
    type          regex
    flush_timeout 50
    #
    # Regex rules for multiline parsing
    # ---------------------------------
    #
    # configuration hints:
    #
    #  - first state always has the name: start_state
    #  - every field in the rule must be inside double quotes
    #
    # rules |   state name  | regex pattern                           | next state
    # ------|---------------|------------------------------------------|-----------
    rule      "start_state"   "^\[.*\].*"                                "cont"
    rule      "cont"             "^(?!\[).*"                               "cont"
```

```bash
fluent-bit.conf:
----
[SERVICE]
  Log_Level warn
  HTTP_Server  On
  HTTP_Listen  0.0.0.0
  HTTP_PORT    2020
  Health_Check On 
  HC_Errors_Count 5 
  HC_Retry_Failure_Count 5 
  HC_Period 5
  Parsers_File /fluent-bit/etc/parsers.conf
  Parsers_File /fluent-bit/etc/conf/custom_parsers.conf
  

[INPUT]
    Name              tail
    Tag               kube.*
    Path              /var/log/containers/*.log
    Exclude_Path      *istio-proxy*
    DB                /var/log/flb_kube.db
    multiline.parser  docker, cri
    Mem_Buf_Limit     64MB
    Skip_Long_Lines   On
    Refresh_Interval  10

[FILTER]
    Name                kubernetes
    Match               kube.*
    Kube_URL            https://kubernetes.default.svc.cluster.local:443
    Merge_Log           On
    Merge_Log_Key       data
    Keep_Log            On
    K8S-Logging.Parser  On
    K8S-Logging.Exclude On
    Buffer_Size         256k

[FILTER]
    Name grep
    Match kube.*
    Logical_Op or
    Exclude log health_check
    Exclude log Healthcheck

[FILTER]
    name                  multiline
    match                 kube.*
    multiline.key_content log
    multiline.parser      multiline-regex-python

[FILTER]
    Name            nest
    Match           kube.*
    Operation       lift
    Wildcard        kubernetes.*
    Nested_under    kubernetes
    Add_prefix      k8s_ 

[FILTER]
    Name                lua
    Match               kube.*
    Script              /fluent-bit/scripts/modify_fields.lua
    Call                modify_fields
...

[OUTPUT]
    Name  es
    Match kube.*
    Cloud_ID MASKED_CLOUD_ID
    Cloud_Auth MASKED_CLOUD_AUTH
    Logstash_Format On
    Logstash_Prefix_Key $index_prefix
    Retry_Limit 5
    Time_Key @timestamp
    tls On
    tls.verify Off
    Buffer_Size 5M
    Suppress_Type_Name On
    Trace_Error On

```

And the luascript referenced in the fluentbit config, which doesn't seem to affect:

```bash
modify_fields.lua:
----
math.randomseed(os.time())

function removeKeys(record)
    local keysToRemove = {
        "k8s_pod_id",
        "k8s_annotations",
        "k8s_docker_id",
        "k8s_container_hash",
        "stream"
    }

    for _, key in ipairs(keysToRemove) do
        record[key] = nil
    end
end

function handleK8sLabels(record)
    if not record["k8s_labels"] then
        return
    end

    labels = record["k8s_labels"]        
    local filtered_labels = {}

    if labels["app"] then
        filtered_labels["app"] = labels["app"]
    end

    if labels["app.kubernetes.io/instance"] then
        filtered_labels["instance"] = labels["app.kubernetes.io/instance"]
    end

    record["k8s_labels"] = filtered_labels
end

function removeTimestamp(record)
    local timestampPattern = "%d%d%d%d%-%d%d%-%d%d %d%d:%d%d:%d%d,%d%d%d"
    local log = record["log"]
    local logWithoutTimestamp = log:gsub(timestampPattern, "", 1)
    
    record["log"] = logWithoutTimestamp
end

-- Function to parse and update the container image
function extractContainerImage(record)
    local image = record["k8s_container_image"]
    if image and string.find(image, "/") and string.find(image, ":") then
        local image_name = string.match(image, ".*/(.*):")
        local version = string.match(image, ":(.*)")

        record["k8s_container_image"] = image_name
        if not record["k8s_labels"] then
            record["k8s_labels"] = {}
        end

        record["k8s_labels"]["version"] = version
    end
end

function extractRequestID(record)
    local log = record["log"]
    local uuid_pattern = "%x%x%x%x%x%x%x%x%-%x%x%x%x%-%x%x%x%x%-%x%x%x%x%-%x%x%x%x%x%x%x%x%x%x%x%x"

    -- Extract UUID if present
    local uuid = log:match("request_id%s*:%s*(" .. uuid_pattern .. ")")
    if uuid then
        record["request_id"] = uuid
        log = log:gsub("request_id%s*:%s*" .. uuid_pattern, "", 1)  -- Remove request_id: UUID
    else
        record["request_id"] = "None"
        log = log:gsub("request_id%s*:%s*None", "", 1)  -- Remove request_id: None
    end

    record["log"] = log
end


function extractLogLevel(record)
    local log = record["log"]
    local log_level = log:match("(%u+)%s-%-")

    if log_level then
        record["log_level"] = log_level
        log = log:gsub(log_level .. "%s-%-", "", 1)
    else
        record["log_level"] = nil
    end

    record["log"] = log
end

function extractProcessName(record)
    local log = record["log"]
    local process_name = log:match("%[(.-)%]")

    if process_name then
        log = log:gsub("%[(.-)%]", "", 1)
        record["process_name"] = process_name
    else
        record["process_name"] = nil
    end
    record["log"] = log
end

function extractFunctionCall(record)
    local log = record["log"]

    local function_call_pattern = "{(.-%S+:%S+:%d+)}"
    local function_call = log:match(function_call_pattern)

    if function_call then
        log = log:gsub(function_call_pattern, "", 1)
        record["function_call"] = function_call
    else
        record["function_call"] = nil
    end

    record["log"] = log
end

function trimLeadingHyphensAndSpaces(record)
    local log = record["log"]
    local trimmedLog = log:gsub("^[-%s]+", "")
    record["log"] = trimmedLog
end

function extractApiUserInfo(record)
    local log = record["log"]

    local user_info = {}
    local login_method = string.match(log, "authenticated by (%w+)")
    user_info["login_method"] = login_method

    local user_id = string.match(log, "User%s([%a%d%-]+)")
    user_info["user_id"] = user_id

    record["user_info"] = user_info
end

function extractOrchestratorUserInfo(record)
    local log = record["log"]

    local user_info = {}
    local user_id_pattern = "'user_id': '([^']+)'"
    local group_id_pattern = "'group_id': '([^']+)'"
    local function_pattern = "'function': '([^']+)'"

    local user_id = string.match(log, user_id_pattern)
    local group_id = string.match(log, group_id_pattern)
    local _function = string.match(log, function_pattern)

    user_info["user_id"] = user_id
    user_info["group_id"] = group_id
    user_info["function"] = _function

    record["user_info"] = user_info
end

-- Function to set the index prefix based on namespace
function setIndexPrefix(record)
    if record["k8s_namespace_name"] ~= nil then
        record['index_prefix'] = 'dev' .. '-' .. record["k8s_namespace_name"]
    else
        record['index_prefix'] = 'generic-index-'
    end
end

function modify_fields(tag, timestamp, record)
    handleK8sLabels(record)
    removeKeys(record)
    setIndexPrefix(record)

    local namespace = record["k8s_namespace_name"]

    if namespace == "NAMESPACE_NAME_TO_MODIFY_LOGS" then
        removeKeys(record)
        removeTimestamp(record)
        extractContainerImage(record)
        extractRequestID(record)
        extractLogLevel(record)
        extractProcessName(record)
        extractFunctionCall(record)
        trimLeadingHyphensAndSpaces(record)

        local container_image = record["k8s_container_image"]
        if container_image == "api" then
            extractApiUserInfo(record)
        elseif container_image == "MASKED_CONTAINER_IMAGE" then
            extractOrchestratorUserInfo(record)
        end
    end

    return 1, timestamp, record
end

```

### PR DESCRIPTION
**Pull request by drbugfinder-work**
This PR resets the size of the metadata buffer on a flush event, which fixes continuous growth of this buffer over time.

Fixes #9262, Fixes #8925, Fixes #9337, Fixes #8567
----
Enter `[N/A]` in the box, if an item is not applicable to your change.

**Testing**
Before we can approve your change; please submit the following in a comment:

- [N/A] Example configuration file for the change
- [N/A] Debug log output from testing the change

- [X] Attached [Valgrind](https://valgrind.org/docs/manual/quick-start.html) output that shows no leaks or memory corruption was found
```
root@fb-dev:~/test/fluent-bit/build# valgrind --leak-check=full ./bin/fluent-bit -c /root/test/fluent-bit.conf 
==645974== Memcheck, a memory error detector
==645974== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==645974== Using Valgrind-3.18.1 and LibVEX; rerun with -h for copyright info
==645974== Command: ./bin/fluent-bit -c /root/test/fluent-bit.conf
==645974== 
Fluent Bit v3.1.7
* Copyright (C) 2015-2024 The Fluent Bit Authors
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io

______ _                  _    ______ _ _           _____  __  
|  ___| |                | |   | ___ (_) |         |____ |/  | 
| |_  | |_   _  ___ _ __ | |_  | |_/ /_| |_  __   __   / /`| | 
|  _| | | | | |/ _ \ '_ \| __| | ___ \ | __| \ \ / /   \ \ | | 
| |   | | |_| |  __/ | | | |_  | |_/ / | |_   \ V /.___/ /_| |_
\_|   |_|\__,_|\___|_| |_|\__| \____/|_|\__|   \_/ \____(_)___/

[2024/09/26 08:59:23] [ info] [fluent bit] version=3.1.7, commit=c6e902a43a, pid=645974
[2024/09/26 08:59:23] [ info] [storage] ver=1.5.2, type=memory, sync=normal, checksum=off, max_chunks_up=128
[2024/09/26 08:59:23] [ info] [cmetrics] version=0.9.5
[2024/09/26 08:59:23] [ info] [ctraces ] version=0.5.5
[2024/09/26 08:59:23] [ info] [input:tail:tail.0] initializing
[2024/09/26 08:59:23] [ info] [input:tail:tail.0] storage_strategy='memory' (memory only)
[2024/09/26 08:59:23] [ info] [filter:multiline:multiline.0] created emitter: emitter_for_multiline.0
[2024/09/26 08:59:23] [ info] [input:emitter:emitter_for_multiline.0] initializing
[2024/09/26 08:59:23] [ info] [input:emitter:emitter_for_multiline.0] storage_strategy='memory' (memory only)
[2024/09/26 08:59:23] [ info] [sp] stream processor started
[2024/09/26 08:59:23] [ info] [output:file:file.0] worker #0 started
^C[2024/09/26 08:59:32] [engine] caught signal (SIGINT)
[2024/09/26 08:59:32] [ warn] [engine] service will shutdown in max 5 seconds
[2024/09/26 08:59:32] [ info] [input] pausing tail.0
[2024/09/26 08:59:32] [ info] [input] pausing emitter_for_multiline.0
[2024/09/26 08:59:32] [ info] [engine] service has stopped (0 pending tasks)
[2024/09/26 08:59:32] [ info] [input] pausing tail.0
[2024/09/26 08:59:32] [ info] [output:file:file.0] thread worker #0 stopping...
[2024/09/26 08:59:32] [ info] [input] pausing emitter_for_multiline.0
[2024/09/26 08:59:32] [ info] [output:file:file.0] thread worker #0 stopped
==645974== 
==645974== HEAP SUMMARY:
==645974==     in use at exit: 0 bytes in 0 blocks
==645974==   total heap usage: 2,437 allocs, 2,437 frees, 765,810 bytes allocated
==645974== 
==645974== All heap blocks were freed -- no leaks are possible
==645974== 
==645974== For lists of detected and suppressed errors, rerun with: -s
==645974== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
root@fb-dev:~/test/fluent-bit/build# 
```

If this is a change to packaging of containers or native binaries then please confirm it works for all targets.

- [N/A] Run [local packaging test](./packaging/local-build-all.sh) showing all targets (including any new ones) build.
- [N/A] Set `ok-package-test` label to test for all targets (requires maintainer to do).

**Documentation**

- [N/A] Documentation required for this feature

**Backporting**

- [N/A] Backport to latest stable release.

----

**Previous observations:** 
```
time spent in                flb_ml_flush_metadata_buffer: 0.001546 seconds. Current unix epoch 1727339480.353680724
number of loop iterations in flb_ml_flush_metadata_buffer: 9384
time spent in                flb_ml_flush_metadata_buffer: 0.001582 seconds. Current unix epoch 1727339480.355315022
number of loop iterations in flb_ml_flush_metadata_buffer: 9390
time spent in                flb_ml_flush_metadata_buffer: 0.001532 seconds. Current unix epoch 1727339480.356888513
...
time spent in                flb_ml_flush_metadata_buffer: 0.012588 seconds. Current unix epoch 1727339562.777399754
number of loop iterations in flb_ml_flush_metadata_buffer: 78762
time spent in                flb_ml_flush_metadata_buffer: 0.012442 seconds. Current unix epoch 1727339562.789904977
number of loop iterations in flb_ml_flush_metadata_buffer: 78768
time spent in                flb_ml_flush_metadata_buffer: 0.012519 seconds. Current unix epoch 1727339562.802487816
...
time spent in                flb_ml_flush_metadata_buffer: 0.026053 seconds. Current unix epoch 1727339877.411707060
number of loop iterations in flb_ml_flush_metadata_buffer: 174182
time spent in                flb_ml_flush_metadata_buffer: 0.026309 seconds. Current unix epoch 1727339877.438083181
number of loop iterations in flb_ml_flush_metadata_buffer: 174188
time spent in                flb_ml_flush_metadata_buffer: 0.027012 seconds. Current unix epoch 1727339877.465138702
...
number of loop iterations in flb_ml_flush_metadata_buffer: 255804
time spent in                flb_ml_flush_metadata_buffer: 0.041282 seconds. Current unix epoch 1727340334.109516327
number of loop iterations in flb_ml_flush_metadata_buffer: 255810
time spent in                flb_ml_flush_metadata_buffer: 0.040342 seconds. Current unix epoch 1727340334.149876032
number of loop iterations in flb_ml_flush_metadata_buffer: 255816
time spent in                flb_ml_flush_metadata_buffer: 0.041243 seconds. Current unix epoch 1727340334.191167722
```

I measured the time spent in the flb_ml_flush_metadata_buffer method and the number of iterations in the while loop https://github.com/fluent/fluent-bit/blob/f36c95620224b0a372e4ce481e3dd58b6670251f/src/multiline/flb_ml.c#L1288-L1292 
As you can see the number of iterations is constantly growing and the time in the method also rises constantly, which fully explains the rising CPU load over time for me.

Can you please review @leonardo-albertovich @edsiper 

Fluent Bit is licensed under Apache 2.0, by submitting this pull request I understand that this code will be released under the terms of that license.

### CODE REVIEW

File: src/multiline/flb_ml.c [hunk 1]
```diff
@@ -1443,6 +1443,7 @@ int flb_ml_flush_stream_group(struct flb_ml_parser *ml_parser,
         }
         msgpack_unpacked_destroy(&result);
         group->mp_sbuf.size = 0;
+        group->mp_md_sbuf.size = 0;
```
Comment (edsiper) [inline src/multiline/flb_ml.c:1446]: while I don't remember all the details of the implementation and it seems metadata buffer is newer, why needs to be set to zero at this stage ?

also, I don't see other part in the code where this is set to zero, maybe we are missing another fix around ?

just comments mostly.

**Comment by edsiper** [comment]
I read the thread info https://github.com/fluent/fluent-bit/issues/9262#issuecomment-2374334930, pretty good job :) 

Since it has been tested extensively I am moving forward to merge and do the backport before tomorrow's release

**Comment by edsiper** [comment]
@drbugfinder-work FYI: I cherry picked this fix into PR for 3.1 here: https://github.com/fluent/fluent-bit/pull/9433
