### PR TITLE
workflows: updates for automated PR creation

### LINKED ISSUE #7276: Auto-docs update for releases failing
See: https://github.com/fluent/fluent-bit/actions/runs/4807416936/jobs/8556507048

Screenshot from 2023-04-26 12-01-57

### PR DESCRIPTION
**Pull request by patrick-stephens**
Resolves #7276 and also a few other improvements.

- Releases now are only tagged as latest for 2.1 series.
- Automatically update the version and create a PR for it after a release.
- Fixes various issues with the script (it did not actually affect the container definition for example).
  - Dockerfiles were renamed in 1.9 and missed by this script
  - Assumes it is run from the root of the repo
  - Bitbake recipe file was wrong
- Updated the GH_PA_TOKEN secret using a dedicated PAT from the fluent-bot account.

----
Enter `[N/A]` in the box, if an item is not applicable to your change.

**Testing**

See https://github.com/fluent/fluent-bit/actions/runs/4807416936/jobs/8560407493 as a run post secret update to confirm it works: https://github.com/fluent/fluent-bit-docs/pull/1089

Ran script locally to test with 2.1.3 update - see the later commits direct from the script.

----

Fluent Bit is licensed under Apache 2.0, by submitting this pull request I understand that this code will be released under the terms of that license.

### CODE REVIEW

**Review by niedbalski — APPROVED** [review]

File: update_version.sh [hunk 1]
```diff
@@ -1,31 +1,80 @@
...
+
+if [[ "${DISABLE_COMMIT:-no}" != "no" ]]; then
+    if ! command -v git &> /dev/null ; then
+        echo "ERROR: Missing git CLI" >&2
+        exit 1
+    fi
+
+    git commit -s -m "build: bump to v$NEW_VERSION" -- CMakeLists.txt
+    git commit -s -m "dockerfile: bump to v$NEW_VERSION" -- dockerfiles/*
+    git commit -s -m "snap: bump to v$NEW_VERSION" snap/snapcraft.yaml
```
Comment (niedbalski) [inline update_version.sh:75]: is this being used?

**Review by niedbalski — DISMISSED** [review]
LGTM
