### PR TITLE
[gelf] Replace '/' with '_' in keys when converting from msgpack.

### LINKED ISSUE #1070: Error encoding to GELF message applied Kubernetes fileter
## Bug Report

**Describe the bug**
Error occured when message applied kubernetes filter encode to gelf message using gelf plugin.

**To Reproduce**
Created message is:

```
[159] kubernetes.fluent-bit-1.0.3-lstmf_kube-system_fluent-bit-ed3ada5ce94d2da9e98d762ed1b501b343ae86abbace8ed02734d80b751e6c08.log: [1548903233.004025739, {"log"=>"", "stream"=u003e"stderr", "time"=u003e"2019-01-31T02:53:48.869602266Z", "short_message"=u003e"short_message", "level"=u003e"5", "kubernetes"=u003e{"pod_name"=u003e"weave-net-m8xhq", "namespace_name"=u003e"kube-system", "pod_id"=u003e"81c1bd93-e4f9-11e8-81a0-005056151053", "labels"=u003e{"controller-revision-hash"=u003e"67692866", "name"=u003e"weave-net", "pod-template-generation"=u003e"6"}, "host"=u003e"worker-2", "container_name"=u003e"weave-npc", "docker_id"=u003e"0a96bd14e9f52cf4edd7ed93f3112a299bb3be03f100f1e42a677828fa684c31"}}]
```

Error message is: 

```
[error] [out_gelf] error encoding to GELF
```

I have no idea why error occured :thinking: 

Trace level log is: 

```
[engine] caught signal (SIGSEGV)
#0  0x7efd4c9ab830      in  ???() at ???:0
#1  0x7efd4c972db9      in  ???() at ???:0
#2  0x7efd4c99ae88      in  ???() at ???:0
#3  0x7efd4e60e643      in  flb_log_print() at src/flb_log.c:365
#4  0x7efd4e62c3a0      in  flb_msgpack_gelf_key() at src/flb_pack.c:801
#5  0x7efd4e62ce0e      in  flb_msgpack_gelf_flatten() at src/flb_pack.c:1060
#6  0x7efd4e62cd27      in  flb_msgpack_gelf_flatten() at src/flb_pack.c:1041
#7  0x7efd4e62d4ec      in  flb_msgpack_to_gelf() at src/flb_pack.c:1246
#8  0x7efd4e679711      in  cb_gelf_flush() at plugins/out_gelf/gelf.c:307
#9  0x7efd4e619f4a      in  output_pre_cb_flush() at include/fluent-bit/flb_output.h:314
#10 0x7efd4e928686      in  co_init() at lib/monkey/deps/flb_libco/amd64.c:117
#11 0xffffffffffffffff  in  ???() at ???:0
```

**Expected behavior**
Sending to gelf message via udp.

**Your Environment**
* Version used: 1.0.3
* Environment name and version: Kubernetes 1.10.3
* Server type and version: x86_64
* Operating System and version: centos7
* Filters and plugins:
```
  fluent-bit.conf: |
    [SERVICE]
        Flush             5
        Log_Level         trace
        Daemon            off
        Buffer_Path       /var/log/fluentd-buffers/kubernetes.system.buffer
        HTTP_Server       off
        Parsers_File      parsers.conf

    @INCLUDE input-kubernetes.conf
    @INCLUDE filter-kubernetes.conf
    @INCLUDE output-gelf.conf

  input-kubernetes.conf: |
    [INPUT]
        Name              tail
        Path              /var/log/containers/*.log
        Tag               kubernetes.*
        Parser            docker
        DB                /var/log/flb_kube.db
        Mem_Buf_Limit     5MB
        Skip_Long_Lines   On
        Refresh_Interval  10

  filter-kubernetes.conf: |

    [FILTER]
        Name record_modifier
        Match *
        Record short_message short_message

    [FILTER]
        Name                kubernetes
        Match               kubernetes.*
        Merge_Log           On
        K8S-Logging.Parser  On

  output-gelf.conf: |

    [OUTPUT]
        Name                     gelf
        Match                    kubernetes.*
        Host                     graylog.kube-system
        Port                     12201
        Mode                     udp
        Gelf_Short_Message_Key   short_message

  parsers.conf: |

    [PARSER]
        Name        docker
        Format      json
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
        Time_Keep   On
        Decode_Field_As   escaped_utf8    log
```

**Additional context**

I have no idea why error occured because no logs and no documents related `gelf` output plugin.

### PR DESCRIPTION
**Pull request by lbogdan**
Allows logs form Kubernetes pods having labels or annotations containing '/' in the name, which is not a valid GELF field name.

Also changes the log level to `error` and adds the invalid char position to "invalid key char" errors.

Fixes #1070 , #1291 .

### CODE REVIEW

**Comment by nigels-com** [comment]
Looks like it does as described.

Seems like there are potential leaks in the early-outs (out of memory situation).
Perhaps a `goto` cleanup block that centralises the cleanup of temporary copies?

**Comment by lbogdan** [comment]
Hey @nigels-com , thanks for the review! I was aware of the memory leaks, but I didn't have any obvious fix for it, other than just freeing the copies in every branch, which would get quite verbose (on the other hand, I agree that's not really a reason to ignore memory leaks 🙂 ). I'll look for a `goto` pattern in the codebase and update the PR.

P.S.: I have used this patch in production for a week now, without any issues (the leak didn't trigger, as there were no further encoding errors).

**Comment by nigels-com** [comment]
In C++ this tends to be less of an issue, of course.

The sort of pattern I suggest is something like:

```
  void * a = NULL;
  void * b = NULL;
  void * c = NULL;
  void * result = NULL;

  a = malloc(len+1);
  ...
  {
    if (!b) goto cleanup;
    ...
  }
  /* Normal path of execution gets here */
  result = ...  /* Not a, b or c! */

  /* Do the necessary cleanup, whether or not there was an error */

cleanup:
  free(a);
  free(b);
  free(c);
  return result;
```

It's one of the few remaining legitimate uses of `goto` but a good one, in my opinion.
Assuming `free(NULL)` is harmless.

**Comment by lbogdan** [comment]
Done. I also safe-guarded the `free`s with
```c
if (copy) {
  flb_free(copy);
}
```
, just in case.

**Comment by nigels-com** [comment]
For the sake of portability, I'd recommend the NULL check.  I do see NULL checks elsewhere in the codebase:

```
    if (ctx->merge_log_key) {
        flb_free(ctx->merge_log_key);
    }
```

**Comment by lbogdan** [comment]
@nigels-com I'm not sure I get what you mean, didn't I do just that?

File: src/flb_pack.c [hunk 1]
```diff
@@ -170,6 +170,28 @@ static char *tokens_to_msgpack(char *js,
     return buf;
 }
 
+static char *str_copy_replace(const char *src, int len, char search, char replace) {
+    char *dst = NULL;
+    int i;
+
+    dst = flb_malloc(len + 1);
```
Comment (edsiper) [inline src/flb_pack.c]: Please use flb_strndup() instead

**Comment by knackaron** [comment]
I applied this against our 1.1.0 image to fix the the same issue, works as intended.

@lbogdan Are you able to implement the modifications that @edsiper requested so this can get merged for the next release?

**Comment by lbogdan** [comment]
Hey @knackaron , sorry for the radio silence, I've been busy with work. I'll try to work on this next week, but feel free to take over, if you want.

File: src/flb_pack.c (hunk 1 above)
Comment (lbogdan) [reply src/flb_pack.c]: Done, PTAL.

**Comment by lbogdan** [comment]
Squashed the commits, updated the commit subject, should be ready for merge.

**Comment by PortaltechGithub** [comment]
Is there anything blocking the pull request? The requested change by @edsiper seems to be incorporated in the new commit.

**Comment by l-lotz** [comment]
@edsiper can you confirm that your requested change is now included?

**Comment by lbogdan** [comment]
There's also #1365 , which is replacing more than just `/` (although that's the only k8s "offending" character), so I guess only one of the two should be merged.

**Comment by isaacegglestone** [comment]
@lbogdan @edsiper This is definitely needed for kubernetes any chance we can get the slash tr merged since it appears to be done and only @edspiper needs to approve the change i think so its mergeable?

**Comment by edsiper** [comment]
thanks everyone!
