### PR TITLE
out_es: Prevent a SIGSEGV when ctx->index is NULL

### LINKED ISSUE #10339: the elastic output plugin sigsegvs trying to call strftime
## Bug Report

**Describe the bug**
Given a set of logs with varying formatting (these are the output from docker's container runtime, but this was originally observed when using AWS Firelens to forward container logs to fluent-bit running as a sidecar task)

<details>

</details>

The elasticsearch output plugin will sigsegv when trying to call `strftime`:

```
17:40:32 [2025/05/15 21:40:32] [engine] caught signal (SIGSEGV)
17:40:32 #0  0xffffa73013db      in  ???() at ???:0
17:40:32 #1  0xaaaabf4f2fcf      in  elasticsearch_format() at plugins/out_es/es.c:362
17:40:32 #2  0xaaaabf4f3703      in  cb_es_flush() at plugins/out_es/es.c:828
17:40:32 #3  0xaaaabf9b97d7      in  co_switch() at lib/monkey/deps/flb_libco/aarch64.c:133
17:40:32 #4  0xffffffffffffffff  in  ???() at ???:0
```

**To Reproduce**
- Rubular link if applicable:
- Example log message if applicable:
```
{"container_id":"d51a6872fa3d41a9bf3ac7af0f2756b9-0507563709","container_name":"template-builder","source":"stdout","log":""}
{"container_id":"d51a6872fa3d41a9bf3ac7af0f2756b9-0507563709","container_name":"template-builder","source":"stdout","log":"> template-builder-svc@1.1.0 start:instrumented"}
{"container_name":"template-builder","source":"stdout","log":"> node --import ./instrumentation.mjs server.js","container_id":"d51a6872fa3d41a9bf3ac7af0f2756b9-0507563709"}
{"container_id":"d51a6872fa3d41a9bf3ac7af0f2756b9-0507563709","container_name":"template-builder","source":"stdout","log":""}
{"container_id":"d51a6872fa3d41a9bf3ac7af0f2756b9-0507563709","container_name":"template-builder","source":"stdout","log":"Instrumentation started for template-builder-svc version template-builder-svc"}
{"container_id":"d51a6872fa3d41a9bf3ac7af0f2756b9-0507563709","container_name":"template-builder","source":"stdout","log":"Loading config for environment dev..."}
{"container_id":"d51a6872fa3d41a9bf3ac7af0f2756b9-0507563709","container_name":"template-builder","source":"stdout","log":"{\\"@timestamp\\":\\"2025-03-26T21:17:11.234Z\\",\\"ecs.version\\":\\"8.10.0\\",\\"log.level\\":\\"info\\",\\"message\\":\\"Logging loaded. LOGGING.SIMPLE: false, LOGGING.LEVEL: info\\",\\"service\\":{\\"_deployed_at\\":\\"2025-03-04T21:06:39Z\\",\\"_deployed_branch\\":\\"main\\",\\"_sha\\":\\"a97697d7\\",\\"environment\\":\\"dev\\",\\"name\\":\\"template-builder-svc\\",\\"version\\":\\"1.1.0\\"}}"}
```
- Steps to reproduce the problem:

Use `fluent-cat` to send these messages to a fluent-bit process with the following config

<details>
```yaml
service:
  flush: 1
  daemon: off
  log_level: ${FLUENT_BIT_LOG_LEVEL}

includes:
  - /opt/fluent-bit/conf/*yaml

parsers:
  - name: json
    format: json
    decode_field: json log
    time_key: "@timestamp"

pipeline:
  inputs:
    - name: forward
      unix_path: /var/run/fluent.sock
      tag: app_aws_firelens

      processors:
        logs:
          - name: parser
            parser: json
            key_name: log

  filters:
    - name: nest
      match: app_aws_firelens
      operation: lift
      nested_under: log
    # if an app emits a plain-text log, the lift operation will not work, and the log message will remain plaintext.
    # if we lift and `log` still exists, we rename it so that `log` remains an object.
    - name: modify
      match: app_aws_firelens
      condition: A_key_matches log
      hard_rename:
        - log log.message
    - name: modify
      match: app_aws_firelens
      condition: A_key_matches fields.timestamp
      hard_copy:
        - fields.timestamp "@timestamp"
    - name: modify
      match: app_aws_firelens
      condition: A_key_matches fields.message
      hard_copy:
        - fields.message "message"

  outputs:
    - name: es
      match: app_aws_firelens
      host: ${INGESTION_HOST}
      port: ${INGESTION_PORT}
      index: ${APP_LOGS_INDEX}
      pipeline: ${DEFAULT_PIPELINE}
      http_user: ${INGESTION_USER}
      http_passwd: ${INGESTION_USER_PASSWORD}
      suppress_type_name: true
      trace_error: true
      tls: true

```

**Expected behavior**
fluent-bit should continue operating correctly. perhaps show an error in the logs.

**Screenshots**

**Your Environment**

* Version used: 4.0.1
* Configuration: see details aboe
* Environment name and version (e.g. Kubernetes? What version?): Docker, AWS Fargate/ECS and "native" Mac OS 14.7.5
* Server type and version: Mac OS, ECS/Fargate
* Operating System and version:
* Filters and plugins: Elasticsearch, forward, nest, modify

**Additional context**
This seems to only happen when we have mixed message types AND are outputting to elasticsearch (well, since the error is in that output plugin). Testing this locally using `stdout` output plugin is fine.

### PR DESCRIPTION
**Pull request by tkennedy1-godaddy**
If `index` field is blank in the configuration, and `Logstash_Format` and `Generate_ID` are both `off`, a SIGSEGV can occur when trying to generate the index for a set of messages.

Fixes #10339 

----
Enter `[N/A]` in the box, if an item is not applicable to your change.

**Testing**
Before we can approve your change; please submit the following in a comment:

- [x] Example configuration file for the change
- [x] Debug log output from testing the change

- [x] Attached [Valgrind](https://valgrind.org/docs/manual/quick-start.html) output that shows no leaks or memory corruption was found

If this is a change to packaging of containers or native binaries then please confirm it works for all targets.

- [N/A] Run [local packaging test](./packaging/local-build-all.sh) showing all targets (including any new ones) build.
- [N/A] Set `ok-package-test` label to test for all targets (requires maintainer to do).

**Documentation**

- [N/A] Documentation required for this feature

**Backporting**

- [x] Backport to latest stable release.
- v4.0.1: #10356
- v4.0.2: #10357

----

Fluent Bit is licensed under Apache 2.0, by submitting this pull request I understand that this code will be released under the terms of that license.

### CODE REVIEW

**Comment by tkennedy1-godaddy** [comment]
configuration:

```yaml
  service:
    flush: 1
    daemon: off

  pipeline:
    inputs:
      - name: forward
        unix_path: /var/run/fluent.sock
        tag: log
  
    outputs:
      - name: es
        match: *
        host: valid_host
        port: valid_port
        index: 
        suppress_type_name: true
        trace_error: true
        tls: true
```

**Comment by tkennedy1-godaddy** [comment]
Debug log with failing configuration:

```
15:40:29❯ bin/fluent-bit -c config.yaml
Fluent Bit v4.0.2
* Copyright (C) 2015-2025 The Fluent Bit Authors
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io

______ _                  _    ______ _ _             ___  _____
|  ___| |                | |   | ___ (_) |           /   ||  _  |
| |_  | |_   _  ___ _ __ | |_  | |_/ /_| |_  __   __/ /| || |/' |
|  _| | | | | |/ _ \ '_ \| __| | ___ \ | __| \ \ / / /_| ||  /| |
| |   | | |_| |  __/ | | | |_  | |_/ / | |_   \ V /\___  |\ |_/ /
\_|   |_|\__,_|\___|_| |_|\__| \____/|_|\__|   \_/     |_(_)___/


[2025/05/19 15:40:30] [ info] Configuration:
[2025/05/19 15:40:30] [ info]  flush time     | 1.000000 seconds
[2025/05/19 15:40:30] [ info]  grace          | 5 seconds
[2025/05/19 15:40:30] [ info]  daemon         | 0
[2025/05/19 15:40:30] [ info] ___________
[2025/05/19 15:40:30] [ info]  inputs:
[2025/05/19 15:40:30] [ info]      forward
[2025/05/19 15:40:30] [ info] ___________
[2025/05/19 15:40:30] [ info]  filters:
[2025/05/19 15:40:30] [ info] ___________
[2025/05/19 15:40:30] [ info]  outputs:
[2025/05/19 15:40:30] [ info]      es.0
[2025/05/19 15:40:30] [ info] ___________
[2025/05/19 15:40:30] [ info]  collectors:
[2025/05/19 15:40:30] [ info] [fluent bit] version=4.0.2, commit=97f4915a6f, pid=77822
[2025/05/19 15:40:30] [debug] [engine] coroutine stack size: 36864 bytes (36.0K)
[2025/05/19 15:40:30] [ info] [storage] ver=1.5.3, type=memory, sync=normal, checksum=off, max_chunks_up=128
[2025/05/19 15:40:30] [ info] [simd    ] disabled
[2025/05/19 15:40:30] [ info] [cmetrics] version=1.0.2
[2025/05/19 15:40:30] [ info] [ctraces ] version=0.6.6
[2025/05/19 15:40:30] [ info] [input:forward:forward.0] initializing
[2025/05/19 15:40:30] [ info] [input:forward:forward.0] storage_strategy='memory' (memory only)
[2025/05/19 15:40:30] [debug] [forward:forward.0] created event channels: read=25 write=26
[2025/05/19 15:40:30] [debug] [downstream] listening on /tmp/fluent.sock:0
[2025/05/19 15:40:30] [ info] [input:forward:forward.0] listening on unix:///tmp/fluent.sock
[2025/05/19 15:40:30] [debug] [es:es.0] created event channels: read=28 write=29
[2025/05/19 15:40:30] [debug] [tls] attempting to load certificates from system keychain of macOS
[2025/05/19 15:40:30] [debug] [tls] certificate 0 details - subject: /C=US/ST=Arizona/L=Scottsdale/O=GoDaddy.com, Inc./CN=Go Daddy Root Certificate Authority - G2, issuer: /C=US/ST=Arizona/L=Scottsdale/O=GoDaddy.com, Inc./CN=Go Daddy Root Certificate Authority - G2
[2025/05/19 15:40:30] [debug] [tls] successfully loaded and added certificate 0 to trusted store
[2025/05/19 15:40:30] [debug] [tls] certificate 1 details - subject: /C=GR/O=Hellenic Academic and Research Institutions CA/CN=HARICA TLS ECC Root CA 2021, issuer: /C=GR/O=Hellenic Academic and Research Institutions CA/CN=HARICA TLS ECC Root CA 2021
[2025/05/19 15:40:30] [debug] [tls] successfully loaded and added certificate 1 to trusted store
[2025/05/19 15:40:30] [debug] [tls] certificate 2 details - subject: /C=KR/O=NAVER BUSINESS PLATFORM Corp./CN=NAVER Global Root Certification Authority, issuer: /C=KR/O=NAVER BUSINESS PLATFORM Corp./CN=NAVER Global Root Certification Authority
[2025/05/19 15:40:30] [debug] [tls] successfully loaded and added certificate 2 to trusted store
[2025/05/19 15:40:30] [debug] [tls] certificate 3 details - subject: /C=GB/O=Sectigo Limited/CN=Sectigo Public Time Stamping Root R46, issuer: /C=GB/O=Sectigo Limited/CN=Sectigo Public Time Stamping Root R46
[2025/05/19 15:40:30] [debug] [tls] successfully loaded and added certificate 3 to trusted store
[2025/05/19 15:40:30] [debug] [tls] certificate 4 details - subject: /C=CH/O=WISeKey/OU=Copyright (c) 2005/OU=OISTE Foundation Endorsed/CN=OISTE WISeKey Global Root GA CA, issuer: /C=CH/O=WISeKey/OU=Copyright (c) 2005/OU=OISTE Foundation Endorsed/CN=OISTE WISeKey Global Root GA CA
[2025/05/19 15:40:30] [debug] [tls] successfully loaded and added certificate 4 to trusted store
[2025/05/19 15:40:30] [debug] [tls] certificate 5 details - subject: /C=US/ST=Illinois/L=Chicago/O=Trustwave Holdings, Inc./CN=Trustwave Global ECC P384 Certification Authority, issuer: /C=US/ST=Illinois/L=Chicago/O=Trustwave Holdings, Inc./CN=Trustwave Global ECC P384 Certification Authority
[2025/05/19 15:40:30] [debug] [tls] successfully loaded and added certificate 5 to trusted store
[2025/05/19 15:40:30] [debug] [tls] certificate 6 details - subject: /C=IT/L=Milan/O=Actalis S.p.A.\/03358520967/CN=Actalis Authentication Root CA, issuer: /C=IT/L=Milan/O=Actalis S.p.A.\/03358520967/CN=Actalis Authentication Root CA
[2025/05/19 15:40:30] [debug] [tls] successfully loaded and added certificate 6 to trusted store
[2025/05/19 15:40:30] [debug] [tls] certificate 7 details - subject: /C=DE/O=D-Trust GmbH/CN=D-TRUST Root CA 3 2013, issuer: /C=DE/O=D-Trust GmbH/CN=D-TRUST Root CA 3 2013
[2025/05/19 15:40:30] [debug] [tls] successfully loaded and added certificate 7 to trusted store
[2025/05/19 15:40:30] [debug] [tls] certificate 8 details - subject: /CN=Apple Root CA - G2/OU=Apple Certification Authority/O=Apple Inc./C=US, issuer: /CN=Apple Root CA - G2/OU=Apple Certification Authority/O=Apple Inc./C=US
[2025/05/19 15:40:30] [debug] [tls] successfully loaded and added certificate 8 to trusted store
[2025/05/19 15:40:30] [debug] [tls] certificate 9 details - subject: /C=US/ST=Texas/L=Houston/O=SSL Corporation/CN=SSL.com EV Root Certification Authority ECC, issuer: /C=US/ST=Texas/L=Houston/O=SSL Corporation/CN=SSL.com EV Root Certification Authority ECC
[2025/05/19 15:40:30] [debug] [tls] successfully loaded and added certificate 9 to trusted store
[2025/05/19 15:40:30] [debug] [tls] certificate 10 details - subject: /OU=GlobalSign ECC Root CA - R4/O=GlobalSign/CN=GlobalSign, issuer: /OU=GlobalSign ECC Root CA - R4/O=GlobalSign/CN=GlobalSign
[2025/05/19 15:40:30] [debug] [tls] successfully loaded and added certificate 10 to trusted store
[2025/05/19 15:40:30] [debug] [tls] certificate 11 details - subject: /C=GR/L=Athens/O=Hellenic Academic and Research Institutions Cert. Authority/CN=Hellenic Academic and Research Institutions RootCA 2015, issuer: /C=GR/L=Athens/O=Hellenic Academic and Research Institutions Cert. Authority/CN=Hellenic Academic and Research Institutions RootCA 2015
[2025/05/19 15:40:30] [debug] [tls] successfully loaded and added certificate 11 to trusted store
[2025/05/19 15:40:30] [debug] [tls] certificate 12 details - subject: /C=TW/O=Chunghwa Telecom Co., Ltd./OU=ePKI Root Certification Authority, issuer: /C=TW/O=Chunghwa Telecom Co., Ltd./OU=ePKI Root Certification Authority
[2025/05/19 15:40:30] [debug] [tls] successfully loaded and added certificate 12 to trusted store
[2025/05/19 15:40:30] [debug] [tls] certificate 13 details - subject: /C=GB/ST=Greater Manchester/L=Salford/O=Comodo CA Limited/CN=AAA Certificate Services, issuer: /C=GB/ST=Greater Manchester/L=Salford/O=Comodo CA Limited/CN=AAA Certificate Services
[2025/05/19 15:40:30] [debug] [tls] successfully loaded and added certificate 13 to trusted store
[2025/05/19 15:40:30] [debug] [tls] certificate 14 details - subject: /C=US/O=VeriSign, Inc./OU=VeriSign Trust Network/OU=(c) 2006 VeriSign, Inc. - For authorized use only/CN=VeriSign Class 3 Public Primary Certification Authority - G5, issuer: /C=US/O=VeriSign, Inc./OU=VeriSign Trust Network/OU=(c) 2006 VeriSign, Inc. - For authorized use only/CN=VeriSign Class 3 Public Primary Certification Authority - G5
[2025/05/19 15:40:30] [debug] [tls] successfully loaded and added certificate 14 to trusted store
[2025/05/19 15:40:30] [debug] [tls] certificate 15 details - subject: /C=US/O=SSL Corporation/CN=SSL.com TLS RSA Root CA 2022, issuer: /C=US/O=SSL Corporation/CN=SSL.com TLS RSA Root CA 2022
[2025/05/19 15:40:30] [debug] [tls] successfully loaded and added certificate 15 to trusted store
[2025/05/19 15:40:30] [debug] [tls] certificate 16 details - subject: /CN=Apple Root CA - G3/OU=Apple Certification Authority/O=Apple Inc./C=US, issuer: /CN=Apple Root CA - G3/OU=Apple Certification Authority/O=Apple Inc./C=US
[2025/05/19 15:40:30] [debug] [tls] successfully loaded and added certificate 16 to trusted store
[2025/05/19 15:40:30] [debug] [tls] certificate 17 details - subject: /C=US/O=IdenTrust/CN=IdenTrust Public Sector Root CA 1, issuer: /C=US/O=IdenTrust/CN=IdenTrust Public Sector Root CA 1
[2025/05/19 15:40:30] [debug] [tls] successfully loaded and added certificate 17 to trusted store
[2025/05/19 15:40:30] [debug] [tls] certificate 18 details - subject: /C=BM/O=QuoVadis Limited/CN=QuoVadis Root CA 3 G3, issuer: /C=BM/O=QuoVadis Limited/CN=QuoVadis Root CA 3 G3
[2025/05/19 15:40:30] [debug] [tls] successfully loaded and added certificate 18 to trusted store
[2025/05/19 15:40:30] [debug] [tls] certificate 19 details - subject: /CN=ACCVRAIZ1/OU=PKIACCV/O=ACCV/C=ES, issuer: /CN=ACCVRAIZ1/OU=PKIACCV/O=ACCV/C=ES
[2025/05/19 15:40:30] [debug] [tls] successfully loaded and added certificate 19 to trusted store
[2025/05/19 15:40:30] [debug] [tls] certificate 20 details - subject: /C=NO/O=Buypass AS-983163327/CN=Buypass Class 3 Root CA, issuer: /C=NO/O=Buypass AS-983163327/CN=Buypass Class 3 Root CA
[2025/05/19 15:40:30] [debug] [tls] successfully loaded and added certificate 20 to trusted store
[2025/05/19 15:40:30] [debug] [tls] certificate 21 details - subject: /C=US/ST=Arizona/L=Scottsdale/O=Starfield Technologies, Inc./CN=Starfield Services Root Certificate Authority - G2, issuer: /C=US/ST=Arizona/L=Scottsdale/O=Starfield Technologies, Inc./CN=Starfield Services Root Certificate Authority - G2
[2025/05/19 15:40:30] [debug] [tls] successfully loaded and added certificate 21 to trusted store
[2025/05/19 15:40:30] [debug] [tls] certificate 22 details - subject: /CN=Atos TrustedRoot Root CA RSA TLS 2021/O=Atos/C=DE, issuer: /CN=Atos TrustedRoot Root CA RSA TLS 2021/O=Atos/C=DE
[2025/05/19 15:40:30] [debug] [tls] successfully loaded and added certificate 22 to trusted store
[2025/05/19 15:40:30] [debug] [tls] certificate 23 details - subject: /C=US/O=SSL Corporation/CN=SSL.com TLS ECC Root CA 2022, issuer: /C=US/O=SSL Corporation/CN=SSL.com TLS ECC Root CA 2022
[2025/05/19 15:40:30] [debug] [tls] successfully loaded and added certificate 23 to trusted store
[2025/05/19 15:40:30] [debug] [tls] certificate 24 details - subject: /C=PA/ST=Panama/L=Panama City/O=TrustCor Systems S. de R.L./OU=TrustCor Certificate Authority/CN=TrustCor ECA-1, issuer: /C=PA/ST=Panama/L=Panama City/O=TrustCor Systems S. de R.L./OU=TrustCor Certificate Authority/CN=TrustCor ECA-1
[2025/05/19 15:40:30] [debug] [tls] successfully loaded and added certificate 24 to trusted store
[2025/05/19 15:40:30] [debug] [tls] certificate 25 details - subject: /C=US/O=AffirmTrust/CN=AffirmTrust Commercial, issuer: /C=US/O=AffirmTrust/CN=AffirmTrust Commercial
[2025/05/19 15:40:30] [debug] [tls] successfully loaded and added certificate 25 to trusted store
[2025/05/19 15:40:30] [debug] [tls] certificate 26 details - subject: /C=BE/O=GlobalSign nv-sa/CN=GlobalSign Root E46, issuer: /C=BE/O=GlobalSign nv-sa/CN=GlobalSign Root E46
[2025/05/19 15:40:30] [debug] [tls] successfully loaded and added certificate 26 to trusted store
[2025/05/19 15:40:30] [debug] [tls] certificate 27 details - subject: /C=GR/O=Hellenic Academic and Research Institutions CA/CN=HARICA TLS RSA Root CA 2021, issuer: /C=GR/O=Hellenic Academic and Research Institutions CA/CN=HARICA TLS RSA Root CA 2021
[2025/05/19 15:40:30] [debug] [tls] successfully loaded and added certificate 27 to trusted store
[2025/05/19 15:40:30] [debug] [tls] certificate 28 details - subject: /C=HK/ST=Hong Kong/L=Hong Kong/O=Hongkong Post/CN=Hongkong Post Root CA 3, issuer: /C=HK/ST=Hong Kong/L=Hong Kong/O=Hongkong Post/CN=Hongkong Post Root CA 3
[2025/05/19 15:40:30] [debug] [tls] successfully loaded and added certificate 28 to trusted store
[2025/05/19 15:40:30] [debug] [tls] certificate 29 details - subject: /C=GB/O=Sectigo Limited/CN=Sectigo Public Server Authentication Root E46, issuer: /C=GB/O=Sectigo Limited/CN=Sectigo Public Server Authentication Root E46
[2025/05/19 15:40:30] [debug] [tls] successfully loaded and added certificate 29 to trusted store
[2025/05/19 15:40:30] [debug] [tls] certificate 30 details - subject: /C=US/O=Certainly/CN=Certainly Root R1, issuer: /C=US/O=Certainly/CN=Certainly Root R1
[2025/05/19 15:40:30] [debug] [tls] successfully loaded and added certificate 30 to trusted store
[2025/05/19 15:40:30] [debug] [tls] certificate 31 details - subject: /C=BM/O=QuoVadis Limited/CN=QuoVadis Root CA 1 G3, issuer: /C=BM/O=QuoVadis Limited/CN=QuoVadis Root CA 1 G3
[2025/05/19 15:40:30] [debug] [tls] successfully loaded and added certificate 31 to trusted store
[2025/05/19 15:40:30] [debug] [tls] certificate 32 details - subject: /C=BE/O=GlobalSign nv-sa/CN=GlobalSign Secure Mail Root E45, issuer: /C=BE/O=GlobalSign nv-sa/CN=GlobalSign Secure Mail Root E45
[2025/05/19 15:40:30] [debug] [tls] successfully loaded and added certificate 32 to trusted store
[2025/05/19 15:40:30] [debug] [tls] certificate 33 details - subject: /C=DE/O=Atos/CN=Atos TrustedRoot Root CA ECC G2 2020, issuer: /C=DE/O=Atos/CN=Atos TrustedRoot Root CA ECC G2 2020
[2025/05/19 15:40:30] [debug] [tls] successfully loaded and added certificate 33 to trusted store
[2025/05/19 15:40:30] [debug] [tls] certificate 34 details - subject: /C=US/O=Network Solutions L.L.C./CN=Network Solutions Certificate Authority, issuer: /C=US/O=Network Solutions L.L.C./CN=Network Solutions Certificate Authority
[2025/05/19 15:40:30] [debug] [tls] successfully loaded and added certificate 34 to trusted store
[2025/05/19 15:40:30] [debug] [tls] certificate 35 details - subject: /C=US/O=VISA/OU=Visa International Service Association/CN=Visa Information Delivery Root CA, issuer: /C=US/O=VISA/OU=Visa International Service Association/CN=Visa Information Delivery Root CA
[2025/05/19 15:40:30] [debug] [tls] successfully loaded and added certificate 35 to trusted store
[2025/05/19 15:40:30] [debug] [tls] certificate 36 details - subject: /C=US/O=Internet Security Research Group/CN=ISRG Root X1, issuer: /C=US/O=Internet Security Research Group/CN=ISRG Root X1
[2025/05/19 15:40:30] [debug] [tls] successfully loaded and added certificate 36 to trusted store
[2025/05/19 15:40:30] [debug] [tls] certificate 37 details - subject: /C=US/OU=www.xrampsecurity.com/O=XRamp Security Services Inc/CN=XRamp Global Certification Authority, issuer: /C=US/OU=www.xrampsecurity.com/O=XRamp Security Services Inc/CN=XRamp Global Certification Authority
[2025/05/19 15:40:30] [debug] [tls] successfully loaded and added certificate 37 to trusted store
[2025/05/19 15:40:30] [debug] [tls] certificate 38 details - subject: /C=PA/ST=Panama/L=Panama City/O=TrustCor Systems S. de R.L./OU=TrustCor Certificate Authority/CN=TrustCor RootCert CA-2, issuer: /C=PA/ST=Panama/L=Panama City/O=TrustCor Systems S. de R.L./OU=TrustCor Certificate Authority/CN=TrustCor RootCert CA-2
[2025/05/19 15:40:30] [debug] [tls] successfully loaded and added certificate 38 to trusted store
[2025/05/19 15:40:30] [debug] [tls] certificate 39 details - subject: /C=PL/O=Asseco Data Systems S.A./OU=Certum Certification Authority/CN=Certum EC-384 CA, issuer: /C=PL/O=Asseco Data Systems S.A./OU=Certum Certification Authority/CN=Certum EC-384 CA
[2025/05/19 15:40:30] [debug] [tls] successfully loaded and added certificate 39 to trusted store
[2025/05/19 15:40:30] [debug] [tls] certificate 40 details - subject: /C=US/O=SSL Corporation/CN=SSL.com Client RSA Root CA 2022, issuer: /C=US/O=SSL Corporation/CN=SSL.com Client RSA Root CA 2022
[2025/05/19 15:40:30] [debug] [tls] successfully loaded and added certificate 40 to trusted store
[2025/05/19 15:40:30] [debug] [tls] certificate 41 details - subject: /C=DE/O=D-Trust GmbH/CN=D-TRUST Root Class 3 CA 2 EV 2009, issuer: /C=DE/O=D-Trust GmbH/CN=D-TRUST Root Class 3 CA 2 EV 2009
[2025/05/19 15:40:30] [debug] [tls] successfully loaded and added certificate 41 to trusted store
[2025/05/19 15:40:30] [debug] [tls] certificate 42 details - subject: /C=GB/O=Sectigo Limited/CN=Sectigo Public Email Protection Root R46, issuer: /C=GB/O=Sectigo Limited/CN=Sectigo Public Email Protection Root R46
[2025/05/19 15:40:30] [debug] [tls] successfully loaded and added certificate 42 to trusted store
[2025/05/19 15:40:30] [debug] [tls] certificate 43 details - subject: /C=CH/O=WISeKey/OU=OISTE Foundation Endorsed/CN=OISTE WISeKey Global Root GB CA, issuer: /C=CH/O=WISeKey/OU=OISTE Foundation Endorsed/CN=OISTE WISeKey Global Root GB CA
[2025/05/19 15:40:30] [debug] [tls] successfully loaded and added certificate 43 to trusted store
[2025/05/19 15:40:30] [debug] [tls] certificate 44 details - subject: /CN=ComSign Global Root CA/O=ComSign Ltd./C=IL, issuer: /CN=ComSign Global Root CA/O=ComSign Ltd./C=IL
[2025/05/19 15:40:30] [debug] [tls] successfully loaded and added certificate 44 to trusted store
[2025/05/19 15:40:30] [debug] [tls] certificate 45 details - subject: /C=ES/O=IZENPE S.A./CN=Izenpe.com, issuer: /C=ES/O=IZENPE S.A./CN=Izenpe.com
[2025/05/19 15:40:30] [debug] [tls] successfully loaded and added certificate 45 to trusted store
[2025/05/19 15:40:30] [debug] [tls] certificate 46 details - subject: /C=GB/ST=Greater Manchester/L=Salford/O=COMODO CA Limited/CN=COMODO Certification Authority, issuer: /C=GB/ST=Greater Manchester/L=Salford/O=COMODO CA Limited/CN=COMODO Certification Authority
[2025/05/19 15:40:30] [debug] [tls] successfully loaded and added certificate 46 to trusted store
[2025/05/19 15:40:30] [debug] [tls] certificate 47 details - subject: /C=PA/ST=Panama/L=Panama City/O=TrustCor Systems S. de R.L./OU=TrustCor Certificate Authority/CN=TrustCor RootCert CA-1, issuer: /C=PA/ST=Panama/L=Panama City/O=TrustCor Systems S. de R.L./OU=TrustCor Certificate Authority/CN=TrustCor RootCert CA-1
[2025/05/19 15:40:30] [debug] [tls] successfully loaded and added certificate 47 to trusted store
[2025/05/19 15:40:30] [debug] [tls] certificate 48 details - subject: /OU=GlobalSign ECC Root CA - R5/O=GlobalSign/CN=GlobalSign, issuer: /OU=GlobalSign ECC Root CA - R5/O=GlobalSign/CN=GlobalSign
[2025/05/19 15:40:30] [debug] [tls] successfully loaded and added certificate 48 to trusted store
[2025/05/19 15:40:30] [debug] [tls] certificate 49 details - subject: /C=ES/O=FNMT-RCM/OU=AC RAIZ FNMT-RCM, issuer: /C=ES/O=FNMT-RCM/OU=AC RAIZ FNMT-RCM
[2025/05/19 15:40:30] [debug] [tls] successfully loaded and added certificate 49 to trusted store
[2025/05/19 15:40:30] [debug] [tls] certificate 50 details - subject: /OU=GlobalSign ECC Root CA - R4/O=GlobalSign/CN=GlobalSign, issuer: /OU=GlobalSign ECC Root CA - R4/O=GlobalSign/CN=GlobalSign
[2025/05/19 15:40:30] [debug] [tls] successfully loaded and added certificate 50 to trusted store
[2025/05/19 15:40:30] [debug] [tls] certificate 51 details - subject: /C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert Trusted Root G4, issuer: /C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert Trusted Root G4
[2025/05/19 15:40:30] [debug] [tls] successfully loaded and added certificate 51 to trusted store
[2025/05/19 15:40:30] [debug] [tls] certificate 52 details - subject: /C=TW/O=TAIWAN-CA/OU=Root CA/CN=TWCA Root Certification Authority, issuer: /C=TW/O=TAIWAN-CA/OU=Root CA/CN=TWCA Root Certification Authority
[2025/05/19 15:40:30] [debug] [tls] successfully loaded and added certificate 52 to trusted store
[2025/05/19 15:40:30] [debug] [tls] certificate 53 details - subject: /C=US/O=Starfield Technologies, Inc./OU=Starfield Class 2 Certification Authority, issuer: /C=US/O=Starfield Technologies, Inc./OU=Starfield Class 2 Certification Authority
[2025/05/19 15:40:30] [debug] [tls] successfully loaded and added certificate 53 to trusted store
[2025/05/19 15:40:30] [debug] [tls] certificate 54 details - subject: /C=GR/O=Hellenic Academic and Research Institutions CA/CN=HARICA Client RSA Root CA 2021, issuer: /C=GR/O=Hellenic Academic and Research Institutions CA/CN=HARICA Client RSA Root CA 2021
[2025/05/19 15:40:30] [debug] [tls] successfully loaded and added certificate 54 to trusted store
[2025/05/19 15:40:30] [debug] [tls] certificate 55 details - subject: /C=US/O=SecureTrust Corporation/CN=SecureTrust CA, issuer: /C=US/O=SecureTrust Corporation/CN=SecureTrust CA
[2025/05/19 15:40:30] [debug] [tls] successfully loaded and added certificate 55 to trusted store
[2025/05/19 15:40:30] [debug] [tls] certificate 56 details - subject: /C=US/O=Entrust, Inc./OU=See www.entrust.net\/legal-terms/OU=(c) 2009 Entrust, Inc. - for authorized use only/CN=Entrust Root Certification Authority - G2, issuer: /C=US/O=Entrust, Inc./OU=See www.entrust.net\/legal-terms/OU=(c) 2009 Entrust, Inc. - for authorized use only/CN=Entrust Root Certification Authority - G2
[2025/05/19 15:40:30] [debug] [tls] successfully loaded and added certificate 56 to trusted store
[2025/05/19 15:40:30] [debug] [tls] certificate 57 details - subject: /C=IE/O=Baltimore/OU=CyberTrust/CN=Baltimore CyberTrust Root, issuer: /C=IE/O=Baltimore/OU=CyberTrust/CN=Baltimore CyberTrust Root
[2025/05/19 15:40:30] [debug] [tls] successfully loaded and added certificate 57 to trusted store
[2025/05/19 15:40:30] [debug] [tls] certificate 58 details - subject: /C=GR/O=Hellenic Academic and Research Institutions CA/CN=HARICA Client ECC Root CA 2021, issuer: /C=GR/O=Hellenic Academic and Research Institutions CA/CN=HARICA Client ECC Root CA 2021
[2025/05/19 15:40:30] [debug] [tls] successfully loaded and added certificate 58 to trusted store
[2025/05/19 15:40:30] [debug] [tls] certificate 59 details - subject: /C=SK/L=Bratislava/O=Disig a.s./CN=CA Disig Root R2, issuer: /C=SK/L=Bratislava/O=Disig a.s./CN=CA Disig Root R2
[2025/05/19 15:40:30] [debug] [tls] successfully loaded and added certificate 59 to trusted store
[2025/05/19 15:40:30] [debug] [tls] certificate 60 details - subject: /C=BE/O=GlobalSign nv-sa/OU=Root CA/CN=GlobalSign Root CA, issuer: /C=BE/O=GlobalSign nv-sa/OU=Root CA/CN=GlobalSign Root CA
[2025/05/19 15:40:30] [debug] [tls] successfully loaded and added certificate 60 to trusted store
[2025/05/19 15:40:30] [debug] [tls] certificate 61 details - subject: /C=BM/O=QuoVadis Limited/CN=QuoVadis Root CA 2 G3, issuer: /C=BM/O=QuoVadis Limited/CN=QuoVadis Root CA 2 G3
[2025/05/19 15:40:30] [debug] [tls] successfully loaded and added certificate 61 to trusted store
[2025/05/19 15:40:30] [debug] [tls] certificate 62 details - subject: /C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert Assured ID Root CA, issuer: /C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert Assured ID Root CA
[2025/05/19 15:40:30] [debug] [tls] successfully loaded and added certificate 62 to trusted store
[2025/05/19 15:40:30] [debug] [tls] certificate 63 details - subject: /C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert Assured ID Root G3, issuer: /C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert Assured ID Root G3
[2025/05/19 15:40:30] [debug] [tls] successfully loaded and added certificate 63 to trusted store
[2025/05/19 15:40:30] [debug] [tls] certificate 64 details - subject: /C=US/ST=Illinois/L=Chicago/O=Trustwave Holdings, Inc./CN=Trustwave Global Certification Authority, issuer: /C=US/ST=Illinois/L=Chicago/O=Trustwave Holdings, Inc./CN=Trustwave Global Certification Authority
[2025/05/19 15:40:30] [debug] [tls] successfully loaded and added certificate 64 to trusted store
[2025/05/19 15:40:30] [debug] [tls] certificate 65 details - subject: /C=US/O=SSL Corporation/CN=SSL.com Client ECC Root CA 2022, issuer: /C=US/O=SSL Corporation/CN=SSL.com Client ECC Root CA 2022
[2025/05/19 15:40:30] [debug] [tls] successfully loaded and added certificate 65 to trusted store
[2025/05/19 15:40:30] [debug] [tls] certificate 66 details - subject: /C=CN/O=GUANG DONG CERTIFICATE AUTHORITY CO.,LTD./CN=GDCA TrustAUTH R5 ROOT, issuer: /C=CN/O=GUANG DONG CERTIFICATE AUTHORITY CO.,LTD./CN=GDCA TrustAUTH R5 ROOT
[2025/05/19 15:40:30] [debug] [tls] successfully loaded and added certificate 66 to trusted store
[2025/05/19 15:40:30] [debug] [tls] certificate 67 details - subject: /C=DE/O=T-Systems Enterprise Services GmbH/OU=T-Systems Trust Center/CN=T-TeleSec GlobalRoot Class 2, issuer: /C=DE/O=T-Systems Enterprise Services GmbH/OU=T-Systems Trust Center/CN=T-TeleSec GlobalRoot Class 2
[2025/05/19 15:40:30] [debug] [tls] successfully loaded and added certificate 67 to trusted store
[2025/05/19 15:40:30] [debug] [tls] certificate 68 details - subject: /C=DE/O=T-Systems Enterprise Services GmbH/OU=T-Systems Trust Center/CN=T-TeleSec GlobalRoot Class 3, issuer: /C=DE/O=T-Systems Enterprise Services GmbH/OU=T-Systems Trust Center/CN=T-TeleSec GlobalRoot Class 3
[2025/05/19 15:40:30] [debug] [tls] successfully loaded and added certificate 68 to trusted store
[2025/05/19 15:40:30] [debug] [tls] certificate 69 details - subject: /C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert Assured ID Root G2, issuer: /C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert Assured ID Root G2
[2025/05/19 15:40:30] [debug] [tls] successfully loaded and added certificate 69 to trusted store
[2025/05/19 15:40:30] [debug] [tls] certificate 70 details - subject: /C=JP/O=SECOM Trust Systems CO.,LTD./OU=Security Communication RootCA2, issuer: /C=JP/O=SECOM Trust Systems CO.,LTD./OU=Security Communication RootCA2
[2025/05/19 15:40:30] [debug] [tls] successfully loaded and added certificate 70 to trusted store
[2025/05/19 15:40:30] [debug] [tls] certificate 71 details - subject: /O=Entrust.net/OU=www.entrust.net\/CPS_2048 incorp. by ref. (limits liab.)/OU=(c) 1999 Entrust.net Limited/CN=Entrust.net Certification Authority (2048), issuer: /O=Entrust.net/OU=www.entrust.net\/CPS_2048 incorp. by ref. (limits liab.)/OU=(c) 1999 Entrust.net Limited/CN=Entrust.net Certification Authority (2048)
[2025/05/19 15:40:30] [debug] [tls] successfully loaded and added certificate 71 to trusted store
[2025/05/19 15:40:30] [debug] [tls] certificate 72 details - subject: /C=US/O=AffirmTrust/CN=AffirmTrust Networking, issuer: /C=US/O=AffirmTrust/CN=AffirmTrust Networking
[2025/05/19 15:40:30] [debug] [tls] successfully loaded and added certificate 72 to trusted store
[2025/05/19 15:40:30] [debug] [tls] certificate 73 details - subject: /C=ES/CN=Autoridad de Certificacion Firmaprofesional CIF A62634068, issuer: /C=ES/CN=Autoridad de Certificacion Firmaprofesional CIF A62634068
[2025/05/19 15:40:30] [debug] [tls] successfully loaded and added certificate 73 to trusted store
[2025/05/19 15:40:30] [debug] [tls] certificate 74 details - subject: /C=US/O=Amazon/CN=Amazon Root CA 3, issuer: /C=US/O=Amazon/CN=Amazon Root CA 3
[2025/05/19 15:40:30] [debug] [tls] successfully loaded and added certificate 74 to trusted store
[2025/05/19 15:40:30] [debug] [tls] certificate 75 details - subject: /C=US/O=Amazon/CN=Amazon Root CA 2, issuer: /C=US/O=Amazon/CN=Amazon Root CA 2
[2025/05/19 15:40:30] [debug] [tls] successfully loaded and added certificate 75 to trusted store
[2025/05/19 15:40:30] [debug] [tls] certificate 76 details - subject: /CN=Atos TrustedRoot Root CA ECC TLS 2021/O=Atos/C=DE, issuer: /CN=Atos TrustedRoot Root CA ECC TLS 2021/O=Atos/C=DE
[2025/05/19 15:40:30] [debug] [tls] successfully loaded and added certificate 76 to trusted store
[2025/05/19 15:40:30] [debug] [tls] certificate 77 details - subject: /C=US/O=AffirmTrust/CN=AffirmTrust Premium ECC, issuer: /C=US/O=AffirmTrust/CN=AffirmTrust Premium ECC
[2025/05/19 15:40:30] [debug] [tls] successfully loaded and added certificate 77 to trusted store
[2025/05/19 15:40:30] [debug] [tls] certificate 78 details - subject: /C=US/O=Apple Computer, Inc./OU=Apple Computer Certificate Authority/CN=Apple Root Certificate Authority, issuer: /C=US/O=Apple Computer, Inc./OU=Apple Computer Certificate Authority/CN=Apple Root Certificate Authority
[2025/05/19 15:40:30] [debug] [tls] successfully loaded and added certificate 78 to trusted store
[2025/05/19 15:40:30] [debug] [tls] certificate 79 details - subject: /C=CH/O=SwissSign AG/CN=SwissSign Gold CA - G2, issuer: /C=CH/O=SwissSign AG/CN=SwissSign Gold CA - G2
[2025/05/19 15:40:30] [debug] [tls] successfully loaded and added certificate 79 to trusted store
[2025/05/19 15:40:30] [debug] [tls] certificate 80 details - subject: /C=US/O=The Go Daddy Group, Inc./OU=Go Daddy Class 2 Certification Authority, issuer: /C=US/O=The Go Daddy Group, Inc./OU=Go Daddy Class 2 Certification Authority
[2025/05/19 15:40:30] [debug] [tls] successfully loaded and added certificate 80 to trusted store
[2025/05/19 15:40:30] [debug] [tls] certificate 81 details - subject: /C=US/ST=Texas/L=Houston/O=SSL Corporation/CN=SSL.com Root Certification Authority ECC, issuer: /C=US/ST=Texas/L=Houston/O=SSL Corporation/CN=SSL.com Root Certification Authority ECC
[2025/05/19 15:40:30] [debug] [tls] successfully loaded and added certificate 81 to trusted store
[2025/05/19 15:40:30] [debug] [tls] certificate 82 details - subject: /C=CN/O=China Financial Certification Authority/CN=CFCA EV ROOT, issuer: /C=CN/O=China Financial Certification Authority/CN=CFCA EV ROOT
[2025/05/19 15:40:30] [debug] [tls] successfully loaded and added certificate 82 to trusted store
[2025/05/19 15:40:30] [debug] [tls] certificate 83 details - subject: /C=RO/O=CERTSIGN SA/OU=certSIGN ROOT CA G2, issuer: /C=RO/O=CERTSIGN SA/OU=certSIGN ROOT CA G2
[2025/05/19 15:40:30] [debug] [tls] successfully loaded and added certificate 83 to trusted store
[2025/05/19 15:40:30] [debug] [tls] certificate 84 details - subject: /C=CH/O=WISeKey/OU=OISTE Foundation Endorsed/CN=OISTE WISeKey Global Root GC CA, issuer: /C=CH/O=WISeKey/OU=OISTE Foundation Endorsed/CN=OISTE WISeKey Global Root GC CA
[2025/05/19 15:40:30] [debug] [tls] successfully loaded and added certificate 84 to trusted store
[2025/05/19 15:40:30] [debug] [tls] certificate 85 details - subject: /C=US/O=Amazon/CN=Amazon Root CA 1, issuer: /C=US/O=Amazon/CN=Amazon Root CA 1
[2025/05/19 15:40:30] [debug] [tls] successfully loaded and added certificate 85 to trusted store
[2025/05/19 15:40:30] [debug] [tls] certificate 86 details - subject: /C=NO/O=Buypass AS-983163327/CN=Buypass Class 2 Root CA, issuer: /C=NO/O=Buypass AS-983163327/CN=Buypass Class 2 Root CA
[2025/05/19 15:40:30] [debug] [tls] successfully loaded and added certificate 86 to trusted store
[2025/05/19 15:40:30] [debug] [tls] certificate 87 details - subject: /C=US/O=Internet Security Research Group/CN=ISRG Root X2, issuer: /C=US/O=Internet Security Research Group/CN=ISRG Root X2
[2025/05/19 15:40:30] [debug] [tls] successfully loaded and added certificate 87 to trusted store
[2025/05/19 15:40:30] [debug] [tls] certificate 88 details - subject: /C=IN/OU=emSign PKI/O=eMudhra Technologies Limited/CN=emSign Root CA - G1, issuer: /C=IN/OU=emSign PKI/O=eMudhra Technologies Limited/CN=emSign Root CA - G1
[2025/05/19 15:40:30] [debug] [tls] successfully loaded and added certificate 88 to trusted store
[2025/05/19 15:40:30] [debug] [tls] certificate 89 details - subject: /C=US/O=GeoTrust Inc./OU=(c) 2007 GeoTrust Inc. - For authorized use only/CN=GeoTrust Primary Certification Authority - G2, issuer: /C=US/O=GeoTrust Inc./OU=(c) 2007 GeoTrust Inc. - For authorized use only/CN=GeoTrust Primary Certification Authority - G2
[2025/05/19 15:40:30] [debug] [tls] successfully loaded and added certificate 89 to trusted store
[2025/05/19 15:40:30] [debug] [tls] certificate 90 details - subject: /C=TW/O=TAIWAN-CA/OU=Root CA/CN=TWCA Global Root CA, issuer: /C=TW/O=TAIWAN-CA/OU=Root CA/CN=TWCA Global Root CA
[2025/05/19 15:40:30] [debug] [tls] successfully loaded and added certificate 90 to trusted store
[2025/05/19 15:40:30] [debug] [tls] certificate 91 details - subject: /C=US/O=SecureTrust Corporation/CN=Secure Global CA, issuer: /C=US/O=SecureTrust Corporation/CN=Secure Global CA
[2025/05/19 15:40:30] [debug] [tls] successfully loaded and added certificate 91 to trusted store
[2025/05/19 15:40:30] [debug] [tls] certificate 92 details - subject: /C=US/O=Amazon/CN=Amazon Root CA 4, issuer: /C=US/O=Amazon/CN=Amazon Root CA 4
[2025/05/19 15:40:30] [debug] [tls] successfully loaded and added certificate 92 to trusted store
[2025/05/19 15:40:30] [debug] [tls] certificate 93 details - subject: /C=PL/O=Unizeto Technologies S.A./OU=Certum Certification Authority/CN=Certum Trusted Network CA 2, issuer: /C=PL/O=Unizeto Technologies S.A./OU=Certum Certification Authority/CN=Certum Trusted Network CA 2
[2025/05/19 15:40:30] [debug] [tls] successfully loaded and added certificate 93 to trusted store
[2025/05/19 15:40:30] [debug] [tls] certificate 94 details - subject: /C=US/O=AffirmTrust/CN=AffirmTrust Premium, issuer: /C=US/O=AffirmTrust/CN=AffirmTrust Premium
[2025/05/19 15:40:30] [debug] [tls] successfully loaded and added certificate 94 to trusted store
[2025/05/19 15:40:30] [debug] [tls] certificate 95 details - subject: /C=CH/O=SwissSign AG/CN=SwissSign Silver CA - G2, issuer: /C=CH/O=SwissSign AG/CN=SwissSign Silver CA - G2
[2025/05/19 15:40:30] [debug] [tls] successfully loaded and added certificate 95 to trusted store
[2025/05/19 15:40:30] [debug] [tls] certificate 96 details - subject: /C=DE/O=Atos/CN=Atos TrustedRoot Root CA RSA G2 2020, issuer: /C=DE/O=Atos/CN=Atos TrustedRoot Root CA RSA G2 2020
[2025/05/19 15:40:30] [debug] [tls] successfully loaded and added certificate 96 to trusted store
[2025/05/19 15:40:30] [debug] [tls] certificate 97 details - subject: /C=HU/L=Budapest/O=NetLock Kft./OU=Tan\xC3\xBAs\xC3\xADtv\xC3\xA1nykiad\xC3\xB3k (Certification Services)/CN=NetLock Arany (Class Gold) F\xC5\x91tan\xC3\xBAs\xC3\xADtv\xC3\xA1ny, issuer: /C=HU/L=Budapest/O=NetLock Kft./OU=Tan\xC3\xBAs\xC3\xADtv\xC3\xA1nykiad\xC3\xB3k (Certification Services)/CN=NetLock Arany (Class Gold) F\xC5\x91tan\xC3\xBAs\xC3\xADtv\xC3\xA1ny
[2025/05/19 15:40:30] [debug] [tls] successfully loaded and added certificate 97 to trusted store
[2025/05/19 15:40:30] [debug] [tls] certificate 98 details - subject: /C=IN/OU=emSign PKI/O=eMudhra Technologies Limited/CN=emSign ECC Root CA - G3, issuer: /C=IN/OU=emSign PKI/O=eMudhra Technologies Limited/CN=emSign ECC Root CA - G3
[2025/05/19 15:40:30] [debug] [tls] successfully loaded and added certificate 98 to trusted store
[2025/05/19 15:40:30] [debug] [tls] certificate 99 details - subject: /C=GB/O=Sectigo Limited/CN=Sectigo Public Email Protection Root E46, issuer: /C=GB/O=Sectigo Limited/CN=Sectigo Public Email Protection Root E46
[2025/05/19 15:40:30] [debug] [tls] successfully loaded and added certificate 99 to trusted store
[2025/05/19 15:40:30] [debug] [tls] certificate 100 details - subject: /C=TW/O=Chunghwa Telecom Co., Ltd./CN=HiPKI Root CA - G1, issuer: /C=TW/O=Chunghwa Telecom Co., Ltd./CN=HiPKI Root CA - G1
[2025/05/19 15:40:30] [debug] [tls] successfully loaded and added certificate 100 to trusted store
[2025/05/19 15:40:30] [debug] [tls] certificate 101 details - subject: /C=US/O=Apple Inc./OU=Apple Certification Authority/CN=Apple Root CA, issuer: /C=US/O=Apple Inc./OU=Apple Certification Authority/CN=Apple Root CA
[2025/05/19 15:40:30] [debug] [tls] successfully loaded and added certificate 101 to trusted store
[2025/05/19 15:40:30] [debug] [tls] certificate 102 details - subject: /C=EU/L=Madrid (see current address at www.camerfirma.com\/address)/serialNumber=A82743287/O=AC Camerfirma S.A./CN=Chambers of Commerce Root - 2008, issuer: /C=EU/L=Madrid (see current address at www.camerfirma.com\/address)/serialNumber=A82743287/O=AC Camerfirma S.A./CN=Chambers of Commerce Root - 2008
[2025/05/19 15:40:30] [debug] [tls] successfully loaded and added certificate 102 to trusted store
[2025/05/19 15:40:30] [debug] [tls] certificate 103 details - subject: /C=PL/O=Asseco Data Systems S.A./OU=Certum Certification Authority/CN=Certum Trusted Root CA, issuer: /C=PL/O=Asseco Data Systems S.A./OU=Certum Certification Authority/CN=Certum Trusted Root CA
[2025/05/19 15:40:30] [debug] [tls] successfully loaded and added certificate 103 to trusted store
[2025/05/19 15:40:30] [debug] [tls] certificate 104 details - subject: /C=GB/ST=Greater Manchester/L=Salford/O=COMODO CA Limited/CN=COMODO ECC Certification Authority, issuer: /C=GB/ST=Greater Manchester/L=Salford/O=COMODO CA Limited/CN=COMODO ECC Certification Authority
[2025/05/19 15:40:30] [debug] [tls] successfully loaded and added certificate 104 to trusted store
[2025/05/19 15:40:30] [debug] [tls] certificate 105 details - subject: /C=BE/O=GlobalSign nv-sa/CN=GlobalSign Secure Mail Root R45, issuer: /C=BE/O=GlobalSign nv-sa/CN=GlobalSign Secure Mail Root R45
[2025/05/19 15:40:30] [debug] [tls] successfully loaded and added certificate 105 to trusted store
[2025/05/19 15:40:30] [debug] [tls] certificate 106 details - subject: /C=US/O=Google Trust Services LLC/CN=GTS Root R1, issuer: /C=US/O=Google Trust Services LLC/CN=GTS Root R1
[2025/05/19 15:40:30] [debug] [tls] successfully loaded and added certificate 106 to trusted store
[2025/05/19 15:40:30] [debug] [tls] certificate 107 details - subject: /C=TR/L=Gebze - Kocaeli/O=Turkiye Bilimsel ve Teknolojik Arastirma Kurumu - TUBITAK/OU=Kamu Sertifikasyon Merkezi - Kamu SM/CN=TUBITAK Kamu SM SSL Kok Sertifikasi - Surum 1, issuer: /C=TR/L=Gebze - Kocaeli/O=Turkiye Bilimsel ve Teknolojik Arastirma Kurumu - TUBITAK/OU=Kamu Sertifikasyon Merkezi - Kamu SM/CN=TUBITAK Kamu SM SSL Kok Sertifikasi - Surum 1
[2025/05/19 15:40:30] [debug] [tls] successfully loaded and added certificate 107 to trusted store
[2025/05/19 15:40:30] [debug] [tls] certificate 108 details - subject: /C=US/ST=Illinois/L=Chicago/O=Trustwave Holdings, Inc./CN=Trustwave Global ECC P256 Certification Authority, issuer: /C=US/ST=Illinois/L=Chicago/O=Trustwave Holdings, Inc./CN=Trustwave Global ECC P256 Certification Authority
[2025/05/19 15:40:30] [debug] [tls] successfully loaded and added certificate 108 to trusted store
[2025/05/19 15:40:30] [debug] [tls] certificate 109 details - subject: /C=US/O=Entrust, Inc./OU=See www.entrust.net\/legal-terms/OU=(c) 2012 Entrust, Inc. - for authorized use only/CN=Entrust Root Certification Authority - EC1, issuer: /C=US/O=Entrust, Inc./OU=See www.entrust.net\/legal-terms/OU=(c) 2012 Entrust, Inc. - for authorized use only/CN=Entrust Root Certification Authority - EC1
[2025/05/19 15:40:30] [debug] [tls] successfully loaded and added certificate 109 to trusted store
[2025/05/19 15:40:30] [debug] [tls] certificate 110 details - subject: /C=US/O=Entrust, Inc./OU=www.entrust.net\/CPS is incorporated by reference/OU=(c) 2006 Entrust, Inc./CN=Entrust Root Certification Authority, issuer: /C=US/O=Entrust, Inc./OU=www.entrust.net\/CPS is incorporated by reference/OU=(c) 2006 Entrust, Inc./CN=Entrust Root Certification Authority
[2025/05/19 15:40:30] [debug] [tls] successfully loaded and added certificate 110 to trusted store
[2025/05/19 15:40:30] [debug] [tls] certificate 111 details - subject: /CN=Atos TrustedRoot 2011/O=Atos/C=DE, issuer: /CN=Atos TrustedRoot 2011/O=Atos/C=DE
[2025/05/19 15:40:30] [debug] [tls] successfully loaded and added certificate 111 to trusted store
[2025/05/19 15:40:30] [debug] [tls] certificate 112 details - subject: /C=DE/O=D-Trust GmbH/CN=D-TRUST Root Class 3 CA 2 2009, issuer: /C=DE/O=D-Trust GmbH/CN=D-TRUST Root Class 3 CA 2 2009
[2025/05/19 15:40:30] [debug] [tls] successfully loaded and added certificate 112 to trusted store
[2025/05/19 15:40:30] [debug] [tls] certificate 113 details - subject: /C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert High Assurance EV Root CA, issuer: /C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert High Assurance EV Root CA
[2025/05/19 15:40:30] [debug] [tls] successfully loaded and added certificate 113 to trusted store
[2025/05/19 15:40:30] [debug] [tls] certificate 114 details - subject: /C=PL/O=Unizeto Technologies S.A./OU=Certum Certification Authority/CN=Certum Trusted Network CA, issuer: /C=PL/O=Unizeto Technologies S.A./OU=Certum Certification Authority/CN=Certum Trusted Network CA
[2025/05/19 15:40:30] [debug] [tls] successfully loaded and added certificate 114 to trusted store
[2025/05/19 15:40:30] [debug] [tls] certificate 115 details - subject: /C=GB/O=Sectigo Limited/CN=Sectigo Public Server Authentication Root R46, issuer: /C=GB/O=Sectigo Limited/CN=Sectigo Public Server Authentication Root R46
[2025/05/19 15:40:30] [debug] [tls] successfully loaded and added certificate 115 to trusted store
[2025/05/19 15:40:30] [debug] [tls] certificate 116 details - subject: /C=US/O=Google Trust Services LLC/CN=GTS Root R4, issuer: /C=US/O=Google Trust Services LLC/CN=GTS Root R4
[2025/05/19 15:40:30] [debug] [tls] successfully loaded and added certificate 116 to trusted store
[2025/05/19 15:40:30] [debug] [tls] certificate 117 details - subject: /C=BE/O=GlobalSign nv-sa/CN=GlobalSign Root R46, issuer: /C=BE/O=GlobalSign nv-sa/CN=GlobalSign Root R46
[2025/05/19 15:40:30] [debug] [tls] successfully loaded and added certificate 117 to trusted store
[2025/05/19 15:40:30] [debug] [tls] certificate 118 details - subject: /C=EU/L=Madrid (see current address at www.camerfirma.com\/address)/serialNumber=A82743287/O=AC Camerfirma S.A./CN=Global Chambersign Root - 2008, issuer: /C=EU/L=Madrid (see current address at www.camerfirma.com\/address)/serialNumber=A82743287/O=AC Camerfirma S.A./CN=Global Chambersign Root - 2008
[2025/05/19 15:40:30] [debug] [tls] successfully loaded and added certificate 118 to trusted store
[2025/05/19 15:40:30] [debug] [tls] certificate 119 details - subject: /C=FI/O=Telia Finland Oyj/CN=Telia Root CA v2, issuer: /C=FI/O=Telia Finland Oyj/CN=Telia Root CA v2
[2025/05/19 15:40:30] [debug] [tls] successfully loaded and added certificate 119 to trusted store
[2025/05/19 15:40:30] [debug] [tls] certificate 120 details - subject: /C=US/O=IdenTrust/CN=IdenTrust Commercial Root CA 1, issuer: /C=US/O=IdenTrust/CN=IdenTrust Commercial Root CA 1
[2025/05/19 15:40:30] [debug] [tls] successfully loaded and added certificate 120 to trusted store
[2025/05/19 15:40:30] [debug] [tls] certificate 121 details - subject: /C=US/O=Google Trust Services LLC/CN=GTS Root R2, issuer: /C=US/O=Google Trust Services LLC/CN=GTS Root R2
[2025/05/19 15:40:30] [debug] [tls] successfully loaded and added certificate 121 to trusted store
[2025/05/19 15:40:30] [debug] [tls] certificate 122 details - subject: /OU=GlobalSign Root CA - R3/O=GlobalSign/CN=GlobalSign, issuer: /OU=GlobalSign Root CA - R3/O=GlobalSign/CN=GlobalSign
[2025/05/19 15:40:30] [debug] [tls] successfully loaded and added certificate 122 to trusted store
[2025/05/19 15:40:30] [debug] [tls] certificate 123 details - subject: /C=US/O=Entrust, Inc./OU=See www.entrust.net\/legal-terms/OU=(c) 2015 Entrust, Inc. - for authorized use only/CN=Entrust Root Certification Authority - G4, issuer: /C=US/O=Entrust, Inc./OU=See www.entrust.net\/legal-terms/OU=(c) 2015 Entrust, Inc. - for authorized use only/CN=Entrust Root Certification Authority - G4
[2025/05/19 15:40:30] [debug] [tls] successfully loaded and added certificate 123 to trusted store
[2025/05/19 15:40:30] [debug] [tls] certificate 124 details - subject: /OU=GlobalSign Root CA - R6/O=GlobalSign/CN=GlobalSign, issuer: /OU=GlobalSign Root CA - R6/O=GlobalSign/CN=GlobalSign
[2025/05/19 15:40:30] [debug] [tls] successfully loaded and added certificate 124 to trusted store
[2025/05/19 15:40:30] [debug] [tls] certificate 125 details - subject: /O=TeliaSonera/CN=TeliaSonera Root CA v1, issuer: /O=TeliaSonera/CN=TeliaSonera Root CA v1
[2025/05/19 15:40:30] [debug] [tls] successfully loaded and added certificate 125 to trusted store
[2025/05/19 15:40:30] [debug] [tls] certificate 126 details - subject: /C=GB/ST=Greater Manchester/L=Salford/O=COMODO CA Limited/CN=COMODO RSA Certification Authority, issuer: /C=GB/ST=Greater Manchester/L=Salford/O=COMODO CA Limited/CN=COMODO RSA Certification Authority
[2025/05/19 15:40:30] [debug] [tls] successfully loaded and added certificate 126 to trusted store
[2025/05/19 15:40:30] [debug] [tls] certificate 127 details - subject: /C=US/O=Google Trust Services LLC/CN=GTS Root R3, issuer: /C=US/O=Google Trust Services LLC/CN=GTS Root R3
[2025/05/19 15:40:30] [debug] [tls] successfully loaded and added certificate 127 to trusted store
[2025/05/19 15:40:30] [debug] [tls] certificate 128 details - subject: /C=US/ST=Texas/L=Houston/O=SSL Corporation/CN=SSL.com Root Certification Authority RSA, issuer: /C=US/ST=Texas/L=Houston/O=SSL Corporation/CN=SSL.com Root Certification Authority RSA
[2025/05/19 15:40:30] [debug] [tls] successfully loaded and added certificate 128 to trusted store
[2025/05/19 15:40:30] [debug] [tls] certificate 129 details - subject: /O=Cisco Systems/CN=Cisco Root CA 2048, issuer: /O=Cisco Systems/CN=Cisco Root CA 2048
[2025/05/19 15:40:30] [debug] [tls] successfully loaded and added certificate 129 to trusted store
[2025/05/19 15:40:30] [debug] [tls] certificate 130 details - subject: /C=RO/O=certSIGN/OU=certSIGN ROOT CA, issuer: /C=RO/O=certSIGN/OU=certSIGN ROOT CA
[2025/05/19 15:40:30] [debug] [tls] successfully loaded and added certificate 130 to trusted store
[2025/05/19 15:40:30] [debug] [tls] certificate 131 details - subject: /C=US/ST=Texas/L=Houston/O=SSL Corporation/CN=SSL.com EV Root Certification Authority RSA R2, issuer: /C=US/ST=Texas/L=Houston/O=SSL Corporation/CN=SSL.com EV Root Certi
fication Authority RSA R2
[2025/05/19 15:40:30] [debug] [tls] successfully loaded and added certificate 131 to trusted store
[2025/05/19 15:40:30] [debug] [tls] certificate 132 details - subject: /C=US/O=Google Trust Services LLC/CN=GTS Root R3, issuer: /C=US/O=Google Trust Services LLC/CN=GTS Root R3
[2025/05/19 15:40:30] [debug] [tls] successfully loaded and added certificate 132 to trusted store
[2025/05/19 15:40:30] [debug] [tls] certificate 133 details - subject: /C=US/ST=New Jersey/L=Jersey City/O=The USERTRUST Network/CN=USERTrust ECC Certification Authority, issuer: /C=US/ST=New Jersey/L=Jersey City/O=The USERTRUST Network/CN=USERTrust ECC Certification Authority
[2025/05/19 15:40:30] [debug] [tls] successfully loaded and added certificate 133 to trusted store
[2025/05/19 15:40:30] [debug] [tls] certificate 134 details - subject: /C=HU/L=Budapest/O=Microsec Ltd./CN=Microsec e-Szigno Root CA 2009/emailAddress=info@e-szigno.hu, issuer: /C=HU/L=Budapest/O=Microsec Ltd./CN=Microsec e-Szigno Root CA 2009/emailAddress=info@e-szigno.hu
[2025/05/19 15:40:30] [debug] [tls] successfully loaded and added certificate 134 to trusted store
[2025/05/19 15:40:30] [debug] [tls] certificate 135 details - subject: /C=US/O=Microsoft Corporation/CN=Microsoft ECC Root Certificate Authority 2017, issuer: /C=US/O=Microsoft Corporation/CN=Microsoft ECC Root Certificate Authority 2017
[2025/05/19 15:40:30] [debug] [tls] successfully loaded and added certificate 135 to trusted store
[2025/05/19 15:40:30] [debug] [tls] certificate 136 details - subject: /C=US/O=Google Trust Services LLC/CN=GTS Root R2, issuer: /C=US/O=Google Trust Services LLC/CN=GTS Root R2
[2025/05/19 15:40:30] [debug] [tls] successfully loaded and added certificate 136 to trusted store
[2025/05/19 15:40:30] [debug] [tls] certificate 137 details - subject: /C=FR/O=Dhimyotis/CN=Certigna, issuer: /C=FR/O=Dhimyotis/CN=Certigna
[2025/05/19 15:40:30] [debug] [tls] successfully loaded and added certificate 137 to trusted store
[2025/05/19 15:40:30] [debug] [tls] certificate 138 details - subject: /C=AT/O=e-commerce monitoring GmbH/CN=GLOBALTRUST 2020, issuer: /C=AT/O=e-commerce monitoring GmbH/CN=GLOBALTRUST 2020
[2025/05/19 15:40:30] [debug] [tls] successfully loaded and added certificate 138 to trusted store
[2025/05/19 15:40:30] [debug] [tls] certificate 139 details - subject: /C=US/O=Google Trust Services LLC/CN=GTS Root R4, issuer: /C=US/O=Google Trust Services LLC/CN=GTS Root R4
[2025/05/19 15:40:30] [debug] [tls] successfully loaded and added certificate 139 to trusted store
[2025/05/19 15:40:30] [debug] [tls] certificate 140 details - subject: /C=BM/O=QuoVadis Limited/CN=QuoVadis Root CA 3, issuer: /C=BM/O=QuoVadis Limited/CN=QuoVadis Root CA 3
[2025/05/19 15:40:30] [debug] [tls] successfully loaded and added certificate 140 to trusted store
[2025/05/19 15:40:30] [debug] [tls] certificate 141 details - subject: /C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert Global Root G2, issuer: /C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert Global Root G2
[2025/05/19 15:40:30] [debug] [tls] successfully loaded and added certificate 141 to trusted store
[2025/05/19 15:40:30] [debug] [tls] certificate 142 details - subject: /C=GB/O=Sectigo Limited/CN=Sectigo Public Time Stamping Root E46, issuer: /C=GB/O=Sectigo Limited/CN=Sectigo Public Time Stamping Root E46
[2025/05/19 15:40:30] [debug] [tls] successfully loaded and added certificate 142 to trusted store
[2025/05/19 15:40:30] [debug] [tls] certificate 143 details - subject: /C=US/ST=Arizona/L=Scottsdale/O=Starfield Technologies, Inc./CN=Starfield Root Certificate Authority - G2, issuer: /C=US/ST=Arizona/L=Scottsdale/O=Starfield Technologies, Inc./CN=Starfield Root Certificate Authority - G2
[2025/05/19 15:40:30] [debug] [tls] successfully loaded and added certificate 143 to trusted store
[2025/05/19 15:40:30] [debug] [tls] certificate 144 details - subject: /C=GR/L=Athens/O=Hellenic Academic and Research Institutions Cert. Authority/CN=Hellenic Academic and Research Institutions ECC RootCA 2015, issuer: /C=GR/L=Athens/O=Hellenic Academic and Research Institutions Cert. Authority/CN=Hellenic Academic and Research Institutions ECC RootCA 2015
[2025/05/19 15:40:30] [debug] [tls] successfully loaded and added certificate 144 to trusted store
[2025/05/19 15:40:30] [debug] [tls] certificate 145 details - subject: /C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert Global Root CA, issuer: /C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert Global Root CA
[2025/05/19 15:40:30] [debug] [tls] successfully loaded and added certificate 145 to trusted store
[2025/05/19 15:40:30] [debug] [tls] certificate 146 details - subject: /C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert Global Root G3, issuer: /C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert Global Root G3
[2025/05/19 15:40:30] [debug] [tls] successfully loaded and added certificate 146 to trusted store
[2025/05/19 15:40:30] [debug] [tls] certificate 147 details - subject: /C=US/O=Google Trust Services LLC/CN=GTS Root R1, issuer: /C=US/O=Google Trust Services LLC/CN=GTS Root R1
[2025/05/19 15:40:30] [debug] [tls] successfully loaded and added certificate 147 to trusted store
[2025/05/19 15:40:30] [debug] [tls] certificate 148 details - subject: /C=US/O=Certainly/CN=Certainly Root E1, issuer: /C=US/O=Certainly/CN=Certainly Root E1
[2025/05/19 15:40:30] [debug] [tls] successfully loaded and added certificate 148 to trusted store
[2025/05/19 15:40:30] [debug] [tls] certificate 149 details - subject: /C=BM/O=QuoVadis Limited/CN=QuoVadis Root CA 2, issuer: /C=BM/O=QuoVadis Limited/CN=QuoVadis Root CA 2
[2025/05/19 15:40:30] [debug] [tls] successfully loaded and added certificate 149 to trusted store
[2025/05/19 15:40:30] [debug] [tls] certificate 150 details - subject: /C=PL/O=Unizeto Sp. z o.o./CN=Certum CA, issuer: /C=PL/O=Unizeto Sp. z o.o./CN=Certum CA
[2025/05/19 15:40:30] [debug] [tls] successfully loaded and added certificate 150 to trusted store
[2025/05/19 15:40:30] [debug] [tls] certificate 151 details - subject: /C=US/ST=New Jersey/L=Jersey City/O=The USERTRUST Network/CN=USERTrust RSA Certification Authority, issuer: /C=US/ST=New Jersey/L=Jersey City/O=The USERTRUST Network/CN=USERTrust RSA Certification Authority
[2025/05/19 15:40:30] [debug] [tls] successfully loaded and added certificate 151 to trusted store
[2025/05/19 15:40:30] [debug] [tls] certificate 152 details - subject: /C=US/O=Microsoft Corporation/CN=Microsoft RSA Root Certificate Authority 2017, issuer: /C=US/O=Microsoft Corporation/CN=Microsoft RSA Root Certificate Authority 2017
[2025/05/19 15:40:30] [debug] [tls] successfully loaded and added certificate 152 to trusted store
[2025/05/19 15:40:30] [debug] [tls] finished loading keychain certificates, total loaded: 153
[2025/05/19 15:40:30] [error] [output:es:es.0] cannot initialize plugin, index is not set and logstash_format and generate_id are both off
[2025/05/19 15:40:30] [error] [output] failed to initialize 'es' plugin
[2025/05/19 15:40:30] [error] [engine] output initialization failed
[2025/05/19 15:40:30] [ info] [input] pausing forward.0
```

**Comment by tkennedy1-godaddy** [comment]
Log from successful configuration:

```
Fluent Bit v4.0.2
* Copyright (C) 2015-2025 The Fluent Bit Authors
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io

______ _                  _    ______ _ _             ___  _____
|  ___| |                | |   | ___ (_) |           /   ||  _  |
| |_  | |_   _  ___ _ __ | |_  | |_/ /_| |_  __   __/ /| || |/' |
|  _| | | | | |/ _ \ '_ \| __| | ___ \ | __| \ \ / / /_| ||  /| |
| |   | | |_| |  __/ | | | |_  | |_/ / | |_   \ V /\___  |\ |_/ /
\_|   |_|\__,_|\___|_| |_|\__| \____/|_|\__|   \_/     |_(_)___/


[2025/05/19 15:40:23] [ info] Configuration:
[2025/05/19 15:40:23] [ info]  flush time     | 1.000000 seconds
[2025/05/19 15:40:23] [ info]  grace          | 5 seconds
[2025/05/19 15:40:23] [ info]  daemon         | 0
[2025/05/19 15:40:23] [ info] ___________
[2025/05/19 15:40:23] [ info]  inputs:
[2025/05/19 15:40:23] [ info]      forward
[2025/05/19 15:40:23] [ info] ___________
[2025/05/19 15:40:23] [ info]  filters:
[2025/05/19 15:40:23] [ info] ___________
[2025/05/19 15:40:23] [ info]  outputs:
[2025/05/19 15:40:23] [ info]      es.0
[2025/05/19 15:40:23] [ info] ___________
[2025/05/19 15:40:23] [ info]  collectors:
[2025/05/19 15:40:23] [ info] [fluent bit] version=4.0.2, commit=97f4915a6f, pid=77479
[2025/05/19 15:40:23] [debug] [engine] coroutine stack size: 36864 bytes (36.0K)
[2025/05/19 15:40:23] [ info] [storage] ver=1.5.3, type=memory, sync=normal, checksum=off, max_chunks_up=128
[2025/05/19 15:40:23] [ info] [simd    ] disabled
[2025/05/19 15:40:23] [ info] [cmetrics] version=1.0.2
[2025/05/19 15:40:23] [ info] [ctraces ] version=0.6.6
[2025/05/19 15:40:23] [ info] [input:forward:forward.0] initializing
[2025/05/19 15:40:23] [ info] [input:forward:forward.0] storage_strategy='memory' (memory only)
[2025/05/19 15:40:23] [debug] [forward:forward.0] created event channels: read=25 write=26
[2025/05/19 15:40:23] [debug] [downstream] listening on /tmp/fluent.sock:0
[2025/05/19 15:40:23] [ info] [input:forward:forward.0] listening on unix:///tmp/fluent.sock
[2025/05/19 15:40:23] [debug] [es:es.0] created event channels: read=28 write=29
[2025/05/19 15:40:23] [debug] [tls] attempting to load certificates from system keychain of macOS
[2025/05/19 15:40:23] [debug] [tls] certificate 0 details - subject: /C=US/ST=Arizona/L=Scottsdale/O=GoDaddy.com, Inc./CN=Go Daddy Root Certificate Authority - G2, issuer: /C=US/ST=Arizona/L=Scottsdale/O=GoDaddy.com, Inc./CN=Go Daddy Root Certificate Authority - G2
[2025/05/19 15:40:23] [debug] [tls] successfully loaded and added certificate 0 to trusted store
[2025/05/19 15:40:23] [debug] [tls] certificate 1 details - subject: /C=GR/O=Hellenic Academic and Research Institutions CA/CN=HARICA TLS ECC Root CA 2021, issuer: /C=GR/O=Hellenic Academic and Research Institutions CA/CN=HARICA TLS ECC Root CA 2021
[2025/05/19 15:40:23] [debug] [tls] successfully loaded and added certificate 1 to trusted store
[2025/05/19 15:40:23] [debug] [tls] certificate 2 details - subject: /C=KR/O=NAVER BUSINESS PLATFORM Corp./CN=NAVER Global Root Certification Authority, issuer: /C=KR/O=NAVER BUSINESS PLATFORM Corp./CN=NAVER Global Root Certification Authority
[2025/05/19 15:40:23] [debug] [tls] successfully loaded and added certificate 2 to trusted store
[2025/05/19 15:40:23] [debug] [tls] certificate 3 details - subject: /C=GB/O=Sectigo Limited/CN=Sectigo Public Time Stamping Root R46, issuer: /C=GB/O=Sectigo Limited/CN=Sectigo Public Time Stamping Root R46
[2025/05/19 15:40:23] [debug] [tls] successfully loaded and added certificate 3 to trusted store
[2025/05/19 15:40:23] [debug] [tls] certificate 4 details - subject: /C=CH/O=WISeKey/OU=Copyright (c) 2005/OU=OISTE Foundation Endorsed/CN=OISTE WISeKey Global Root GA CA, issuer: /C=CH/O=WISeKey/OU=Copyright (c) 2005/OU=OISTE Foundation Endorsed/CN=OISTE WISeKey Global Root GA CA
[2025/05/19 15:40:23] [debug] [tls] successfully loaded and added certificate 4 to trusted store
[2025/05/19 15:40:23] [debug] [tls] certificate 5 details - subject: /C=US/ST=Illinois/L=Chicago/O=Trustwave Holdings, Inc./CN=Trustwave Global ECC P384 Certification Authority, issuer: /C=US/ST=Illinois/L=Chicago/O=Trustwave Holdings, Inc./CN=Trustwave Global ECC P384 Certification Authority
[2025/05/19 15:40:23] [debug] [tls] successfully loaded and added certificate 5 to trusted store
[2025/05/19 15:40:23] [debug] [tls] certificate 6 details - subject: /C=IT/L=Milan/O=Actalis S.p.A.\/03358520967/CN=Actalis Authentication Root CA, issuer: /C=IT/L=Milan/O=Actalis S.p.A.\/03358520967/CN=Actalis Authentication Root CA
[2025/05/19 15:40:23] [debug] [tls] successfully loaded and added certificate 6 to trusted store
[2025/05/19 15:40:23] [debug] [tls] certificate 7 details - subject: /C=DE/O=D-Trust GmbH/CN=D-TRUST Root CA 3 2013, issuer: /C=DE/O=D-Trust GmbH/CN=D-TRUST Root CA 3 2013
[2025/05/19 15:40:23] [debug] [tls] successfully loaded and added certificate 7 to trusted store
[2025/05/19 15:40:23] [debug] [tls] certificate 8 details - subject: /CN=Apple Root CA - G2/OU=Apple Certification Authority/O=Apple Inc./C=US, issuer: /CN=Apple Root CA - G2/OU=Apple Certification Authority/O=Apple Inc./C=US
[2025/05/19 15:40:23] [debug] [tls] successfully loaded and added certificate 8 to trusted store
[2025/05/19 15:40:23] [debug] [tls] certificate 9 details - subject: /C=US/ST=Texas/L=Houston/O=SSL Corporation/CN=SSL.com EV Root Certification Authority ECC, issuer: /C=US/ST=Texas/L=Houston/O=SSL Corporation/CN=SSL.com EV Root Certification Authority ECC
[2025/05/19 15:40:23] [debug] [tls] successfully loaded and added certificate 9 to trusted store
[2025/05/19 15:40:23] [debug] [tls] certificate 10 details - subject: /OU=GlobalSign ECC Root CA - R4/O=GlobalSign/CN=GlobalSign, issuer: /OU=GlobalSign ECC Root CA - R4/O=GlobalSign/CN=GlobalSign
[2025/05/19 15:40:23] [debug] [tls] successfully loaded and added certificate 10 to trusted store
[2025/05/19 15:40:23] [debug] [tls] certificate 11 details - subject: /C=GR/L=Athens/O=Hellenic Academic and Research Institutions Cert. Authority/CN=Hellenic Academic and Research Institutions RootCA 2015, issuer: /C=GR/L=Athens/O=Hellenic Academic and Research Institutions Cert. Authority/CN=Hellenic Academic and Research Institutions RootCA 2015
[2025/05/19 15:40:23] [debug] [tls] successfully loaded and added certificate 11 to trusted store
[2025/05/19 15:40:23] [debug] [tls] certificate 12 details - subject: /C=TW/O=Chunghwa Telecom Co., Ltd./OU=ePKI Root Certification Authority, issuer: /C=TW/O=Chunghwa Telecom Co., Ltd./OU=ePKI Root Certification Authority
[2025/05/19 15:40:23] [debug] [tls] successfully loaded and added certificate 12 to trusted store
[2025/05/19 15:40:23] [debug] [tls] certificate 13 details - subject: /C=GB/ST=Greater Manchester/L=Salford/O=Comodo CA Limited/CN=AAA Certificate Services, issuer: /C=GB/ST=Greater Manchester/L=Salford/O=Comodo CA Limited/CN=AAA Certificate Services
[2025/05/19 15:40:23] [debug] [tls] successfully loaded and added certificate 13 to trusted store
[2025/05/19 15:40:23] [debug] [tls] certificate 14 details - subject: /C=US/O=VeriSign, Inc./OU=VeriSign Trust Network/OU=(c) 2006 VeriSign, Inc. - For authorized use only/CN=VeriSign Class 3 Public Primary Certification Authority - G5, issuer: /C=US/O=VeriSign, Inc./OU=VeriSign Trust Network/OU=(c) 2006 VeriSign, Inc. - For authorized use only/CN=VeriSign Class 3 Public Primary Certification Authority - G5
[2025/05/19 15:40:23] [debug] [tls] successfully loaded and added certificate 14 to trusted store
[2025/05/19 15:40:23] [debug] [tls] certificate 15 details - subject: /C=US/O=SSL Corporation/CN=SSL.com TLS RSA Root CA 2022, issuer: /C=US/O=SSL Corporation/CN=SSL.com TLS RSA Root CA 2022
[2025/05/19 15:40:23] [debug] [tls] successfully loaded and added certificate 15 to trusted store
[2025/05/19 15:40:23] [debug] [tls] certificate 16 details - subject: /CN=Apple Root CA - G3/OU=Apple Certification Authority/O=Apple Inc./C=US, issuer: /CN=Apple Root CA - G3/OU=Apple Certification Authority/O=Apple Inc./C=US
[2025/05/19 15:40:23] [debug] [tls] successfully loaded and added certificate 16 to trusted store
[2025/05/19 15:40:23] [debug] [tls] certificate 17 details - subject: /C=US/O=IdenTrust/CN=IdenTrust Public Sector Root CA 1, issuer: /C=US/O=IdenTrust/CN=IdenTrust Public Sector Root CA 1
[2025/05/19 15:40:23] [debug] [tls] successfully loaded and added certificate 17 to trusted store
[2025/05/19 15:40:23] [debug] [tls] certificate 18 details - subject: /C=BM/O=QuoVadis Limited/CN=QuoVadis Root CA 3 G3, issuer: /C=BM/O=QuoVadis Limited/CN=QuoVadis Root CA 3 G3
[2025/05/19 15:40:23] [debug] [tls] successfully loaded and added certificate 18 to trusted store
[2025/05/19 15:40:23] [debug] [tls] certificate 19 details - subject: /CN=ACCVRAIZ1/OU=PKIACCV/O=ACCV/C=ES, issuer: /CN=ACCVRAIZ1/OU=PKIACCV/O=ACCV/C=ES
[2025/05/19 15:40:23] [debug] [tls] successfully loaded and added certificate 19 to trusted store
[2025/05/19 15:40:23] [debug] [tls] certificate 20 details - subject: /C=NO/O=Buypass AS-983163327/CN=Buypass Class 3 Root CA, issuer: /C=NO/O=Buypass AS-983163327/CN=Buypass Class 3 Root CA
[2025/05/19 15:40:23] [debug] [tls] successfully loaded and added certificate 20 to trusted store
[2025/05/19 15:40:23] [debug] [tls] certificate 21 details - subject: /C=US/ST=Arizona/L=Scottsdale/O=Starfield Technologies, Inc./CN=Starfield Services Root Certificate Authority - G2, issuer: /C=US/ST=Arizona/L=Scottsdale/O=Starfield Technologies, Inc./CN=Starfield Services Root Certificate Authority - G2
[2025/05/19 15:40:23] [debug] [tls] successfully loaded and added certificate 21 to trusted store
[2025/05/19 15:40:23] [debug] [tls] certificate 22 details - subject: /CN=Atos TrustedRoot Root CA RSA TLS 2021/O=Atos/C=DE, issuer: /CN=Atos TrustedRoot Root CA RSA TLS 2021/O=Atos/C=DE
[2025/05/19 15:40:23] [debug] [tls] successfully loaded and added certificate 22 to trusted store
[2025/05/19 15:40:23] [debug] [tls] certificate 23 details - subject: /C=US/O=SSL Corporation/CN=SSL.com TLS ECC Root CA 2022, issuer: /C=US/O=SSL Corporation/CN=SSL.com TLS ECC Root CA 2022
[2025/05/19 15:40:23] [debug] [tls] successfully loaded and added certificate 23 to trusted store
[2025/05/19 15:40:23] [debug] [tls] certificate 24 details - subject: /C=PA/ST=Panama/L=Panama City/O=TrustCor Systems S. de R.L./OU=TrustCor Certificate Authority/CN=TrustCor ECA-1, issuer: /C=PA/ST=Panama/L=Panama City/O=TrustCor Systems S. de R.L./OU=TrustCor Certificate Authority/CN=TrustCor ECA-1
[2025/05/19 15:40:23] [debug] [tls] successfully loaded and added certificate 24 to trusted store
[2025/05/19 15:40:23] [debug] [tls] certificate 25 details - subject: /C=US/O=AffirmTrust/CN=AffirmTrust Commercial, issuer: /C=US/O=AffirmTrust/CN=AffirmTrust Commercial
[2025/05/19 15:40:23] [debug] [tls] successfully loaded and added certificate 25 to trusted store
[2025/05/19 15:40:23] [debug] [tls] certificate 26 details - subject: /C=BE/O=GlobalSign nv-sa/CN=GlobalSign Root E46, issuer: /C=BE/O=GlobalSign nv-sa/CN=GlobalSign Root E46
[2025/05/19 15:40:23] [debug] [tls] successfully loaded and added certificate 26 to trusted store
[2025/05/19 15:40:23] [debug] [tls] certificate 27 details - subject: /C=GR/O=Hellenic Academic and Research Institutions CA/CN=HARICA TLS RSA Root CA 2021, issuer: /C=GR/O=Hellenic Academic and Research Institutions CA/CN=HARICA TLS RSA Root CA 2021
[2025/05/19 15:40:23] [debug] [tls] successfully loaded and added certificate 27 to trusted store
[2025/05/19 15:40:23] [debug] [tls] certificate 28 details - subject: /C=HK/ST=Hong Kong/L=Hong Kong/O=Hongkong Post/CN=Hongkong Post Root CA 3, issuer: /C=HK/ST=Hong Kong/L=Hong Kong/O=Hongkong Post/CN=Hongkong Post Root CA 3
[2025/05/19 15:40:23] [debug] [tls] successfully loaded and added certificate 28 to trusted store
[2025/05/19 15:40:23] [debug] [tls] certificate 29 details - subject: /C=GB/O=Sectigo Limited/CN=Sectigo Public Server Authentication Root E46, issuer: /C=GB/O=Sectigo Limited/CN=Sectigo Public Server Authentication Root E46
[2025/05/19 15:40:23] [debug] [tls] successfully loaded and added certificate 29 to trusted store
[2025/05/19 15:40:23] [debug] [tls] certificate 30 details - subject: /C=US/O=Certainly/CN=Certainly Root R1, issuer: /C=US/O=Certainly/CN=Certainly Root R1
[2025/05/19 15:40:23] [debug] [tls] successfully loaded and added certificate 30 to trusted store
[2025/05/19 15:40:23] [debug] [tls] certificate 31 details - subject: /C=BM/O=QuoVadis Limited/CN=QuoVadis Root CA 1 G3, issuer: /C=BM/O=QuoVadis Limited/CN=QuoVadis Root CA 1 G3
[2025/05/19 15:40:23] [debug] [tls] successfully loaded and added certificate 31 to trusted store
[2025/05/19 15:40:23] [debug] [tls] certificate 32 details - subject: /C=BE/O=GlobalSign nv-sa/CN=GlobalSign Secure Mail Root E45, issuer: /C=BE/O=GlobalSign nv-sa/CN=GlobalSign Secure Mail Root E45
[2025/05/19 15:40:23] [debug] [tls] successfully loaded and added certificate 32 to trusted store
[2025/05/19 15:40:23] [debug] [tls] certificate 33 details - subject: /C=DE/O=Atos/CN=Atos TrustedRoot Root CA ECC G2 2020, issuer: /C=DE/O=Atos/CN=Atos TrustedRoot Root CA ECC G2 2020
[2025/05/19 15:40:23] [debug] [tls] successfully loaded and added certificate 33 to trusted store
[2025/05/19 15:40:23] [debug] [tls] certificate 34 details - subject: /C=US/O=Network Solutions L.L.C./CN=Network Solutions Certificate Authority, issuer: /C=US/O=Network Solutions L.L.C./CN=Network Solutions Certificate Authority
[2025/05/19 15:40:23] [debug] [tls] successfully loaded and added certificate 34 to trusted store
[2025/05/19 15:40:23] [debug] [tls] certificate 35 details - subject: /C=US/O=VISA/OU=Visa International Service Association/CN=Visa Information Delivery Root CA, issuer: /C=US/O=VISA/OU=Visa International Service Association/CN=Visa Information Delivery Root CA
[2025/05/19 15:40:23] [debug] [tls] successfully loaded and added certificate 35 to trusted store
[2025/05/19 15:40:23] [debug] [tls] certificate 36 details - subject: /C=US/O=Internet Security Research Group/CN=ISRG Root X1, issuer: /C=US/O=Internet Security Research Group/CN=ISRG Root X1
[2025/05/19 15:40:23] [debug] [tls] successfully loaded and added certificate 36 to trusted store
[2025/05/19 15:40:23] [debug] [tls] certificate 37 details - subject: /C=US/OU=www.xrampsecurity.com/O=XRamp Security Services Inc/CN=XRamp Global Certification Authority, issuer: /C=US/OU=www.xrampsecurity.com/O=XRamp Security Services Inc/CN=XRamp Global Certification Authority
[2025/05/19 15:40:23] [debug] [tls] successfully loaded and added certificate 37 to trusted store
[2025/05/19 15:40:23] [debug] [tls] certificate 38 details - subject: /C=PA/ST=Panama/L=Panama City/O=TrustCor Systems S. de R.L./OU=TrustCor Certificate Authority/CN=TrustCor RootCert CA-2, issuer: /C=PA/ST=Panama/L=Panama City/O=TrustCor Systems S. de R.L./OU=TrustCor Certificate Authority/CN=TrustCor RootCert CA-2
[2025/05/19 15:40:23] [debug] [tls] successfully loaded and added certificate 38 to trusted store
[2025/05/19 15:40:23] [debug] [tls] certificate 39 details - subject: /C=PL/O=Asseco Data Systems S.A./OU=Certum Certification Authority/CN=Certum EC-384 CA, issuer: /C=PL/O=Asseco Data Systems S.A./OU=Certum Certification Authority/CN=Certum EC-384 CA
[2025/05/19 15:40:23] [debug] [tls] successfully loaded and added certificate 39 to trusted store
[2025/05/19 15:40:23] [debug] [tls] certificate 40 details - subject: /C=US/O=SSL Corporation/CN=SSL.com Client RSA Root CA 2022, issuer: /C=US/O=SSL Corporation/CN=SSL.com Client RSA Root CA 2022
[2025/05/19 15:40:23] [debug] [tls] successfully loaded and added certificate 40 to trusted store
[2025/05/19 15:40:23] [debug] [tls] certificate 41 details - subject: /C=DE/O=D-Trust GmbH/CN=D-TRUST Root Class 3 CA 2 EV 2009, issuer: /C=DE/O=D-Trust GmbH/CN=D-TRUST Root Class 3 CA 2 EV 2009
[2025/05/19 15:40:23] [debug] [tls] successfully loaded and added certificate 41 to trusted store
[2025/05/19 15:40:23] [debug] [tls] certificate 42 details - subject: /C=GB/O=Sectigo Limited/CN=Sectigo Public Email Protection Root R46, issuer: /C=GB/O=Sectigo Limited/CN=Sectigo Public Email Protection Root R46
[2025/05/19 15:40:23] [debug] [tls] successfully loaded and added certificate 42 to trusted store
[2025/05/19 15:40:23] [debug] [tls] certificate 43 details - subject: /C=CH/O=WISeKey/OU=OISTE Foundation Endorsed/CN=OISTE WISeKey Global Root GB CA, issuer: /C=CH/O=WISeKey/OU=OISTE Foundation Endorsed/CN=OISTE WISeKey Global Root GB CA
[2025/05/19 15:40:23] [debug] [tls] successfully loaded and added certificate 43 to trusted store
[2025/05/19 15:40:23] [debug] [tls] certificate 44 details - subject: /CN=ComSign Global Root CA/O=ComSign Ltd./C=IL, issuer: /CN=ComSign Global Root CA/O=ComSign Ltd./C=IL
[2025/05/19 15:40:23] [debug] [tls] successfully loaded and added certificate 44 to trusted store
[2025/05/19 15:40:23] [debug] [tls] certificate 45 details - subject: /C=ES/O=IZENPE S.A./CN=Izenpe.com, issuer: /C=ES/O=IZENPE S.A./CN=Izenpe.com
[2025/05/19 15:40:23] [debug] [tls] successfully loaded and added certificate 45 to trusted store
[2025/05/19 15:40:23] [debug] [tls] certificate 46 details - subject: /C=GB/ST=Greater Manchester/L=Salford/O=COMODO CA Limited/CN=COMODO Certification Authority, issuer: /C=GB/ST=Greater Manchester/L=Salford/O=COMODO CA Limited/CN=COMODO Certification Authority
[2025/05/19 15:40:23] [debug] [tls] successfully loaded and added certificate 46 to trusted store
[2025/05/19 15:40:23] [debug] [tls] certificate 47 details - subject: /C=PA/ST=Panama/L=Panama City/O=TrustCor Systems S. de R.L./OU=TrustCor Certificate Authority/CN=TrustCor RootCert CA-1, issuer: /C=PA/ST=Panama/L=Panama City/O=TrustCor Systems S. de R.L./OU=TrustCor Certificate Authority/CN=TrustCor RootCert CA-1
[2025/05/19 15:40:23] [debug] [tls] successfully loaded and added certificate 47 to trusted store
[2025/05/19 15:40:23] [debug] [tls] certificate 48 details - subject: /OU=GlobalSign ECC Root CA - R5/O=GlobalSign/CN=GlobalSign, issuer: /OU=GlobalSign ECC Root CA - R5/O=GlobalSign/CN=GlobalSign
[2025/05/19 15:40:23] [debug] [tls] successfully loaded and added certificate 48 to trusted store
[2025/05/19 15:40:23] [debug] [tls] certificate 49 details - subject: /C=ES/O=FNMT-RCM/OU=AC RAIZ FNMT-RCM, issuer: /C=ES/O=FNMT-RCM/OU=AC RAIZ FNMT-RCM
[2025/05/19 15:40:23] [debug] [tls] successfully loaded and added certificate 49 to trusted store
[2025/05/19 15:40:23] [debug] [tls] certificate 50 details - subject: /OU=GlobalSign ECC Root CA - R4/O=GlobalSign/CN=GlobalSign, issuer: /OU=GlobalSign ECC Root CA - R4/O=GlobalSign/CN=GlobalSign
[2025/05/19 15:40:23] [debug] [tls] successfully loaded and added certificate 50 to trusted store
[2025/05/19 15:40:23] [debug] [tls] certificate 51 details - subject: /C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert Trusted Root G4, issuer: /C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert Trusted Root G4
[2025/05/19 15:40:23] [debug] [tls] successfully loaded and added certificate 51 to trusted store
[2025/05/19 15:40:23] [debug] [tls] certificate 52 details - subject: /C=TW/O=TAIWAN-CA/OU=Root CA/CN=TWCA Root Certification Authority, issuer: /C=TW/O=TAIWAN-CA/OU=Root CA/CN=TWCA Root Certification Authority
[2025/05/19 15:40:23] [debug] [tls] successfully loaded and added certificate 52 to trusted store
[2025/05/19 15:40:23] [debug] [tls] certificate 53 details - subject: /C=US/O=Starfield Technologies, Inc./OU=Starfield Class 2 Certification Authority, issuer: /C=US/O=Starfield Technologies, Inc./OU=Starfield Class 2 Certification Authority
[2025/05/19 15:40:23] [debug] [tls] successfully loaded and added certificate 53 to trusted store
[2025/05/19 15:40:23] [debug] [tls] certificate 54 details - subject: /C=GR/O=Hellenic Academic and Research Institutions CA/CN=HARICA Client RSA Root CA 2021, issuer: /C=GR/O=Hellenic Academic and Research Institutions CA/CN=HARICA Client RSA Root CA 2021
[2025/05/19 15:40:23] [debug] [tls] successfully loaded and added certificate 54 to trusted store
[2025/05/19 15:40:23] [debug] [tls] certificate 55 details - subject: /C=US/O=SecureTrust Corporation/CN=SecureTrust CA, issuer: /C=US/O=SecureTrust Corporation/CN=SecureTrust CA
[2025/05/19 15:40:23] [debug] [tls] successfully loaded and added certificate 55 to trusted store
[2025/05/19 15:40:23] [debug] [tls] certificate 56 details - subject: /C=US/O=Entrust, Inc./OU=See www.entrust.net\/legal-terms/OU=(c) 2009 Entrust, Inc. - for authorized use only/CN=Entrust Root Certification Authority - G2, issuer: /C=US/O=Entrust, Inc./OU=See www.entrust.net\/legal-terms/OU=(c) 2009 Entrust, Inc. - for authorized use only/CN=Entrust Root Certification Authority - G2
[2025/05/19 15:40:23] [debug] [tls] successfully loaded and added certificate 56 to trusted store
[2025/05/19 15:40:23] [debug] [tls] certificate 57 details - subject: /C=IE/O=Baltimore/OU=CyberTrust/CN=Baltimore CyberTrust Root, issuer: /C=IE/O=Baltimore/OU=CyberTrust/CN=Baltimore CyberTrust Root
[2025/05/19 15:40:23] [debug] [tls] successfully loaded and added certificate 57 to trusted store
[2025/05/19 15:40:23] [debug] [tls] certificate 58 details - subject: /C=GR/O=Hellenic Academic and Research Institutions CA/CN=HARICA Client ECC Root CA 2021, issuer: /C=GR/O=Hellenic Academic and Research Institutions CA/CN=HARICA Client ECC Root CA 2021
[2025/05/19 15:40:23] [debug] [tls] successfully loaded and added certificate 58 to trusted store
[2025/05/19 15:40:23] [debug] [tls] certificate 59 details - subject: /C=SK/L=Bratislava/O=Disig a.s./CN=CA Disig Root R2, issuer: /C=SK/L=Bratislava/O=Disig a.s./CN=CA Disig Root R2
[2025/05/19 15:40:23] [debug] [tls] successfully loaded and added certificate 59 to trusted store
[2025/05/19 15:40:23] [debug] [tls] certificate 60 details - subject: /C=BE/O=GlobalSign nv-sa/OU=Root CA/CN=GlobalSign Root CA, issuer: /C=BE/O=GlobalSign nv-sa/OU=Root CA/CN=GlobalSign Root CA
[2025/05/19 15:40:23] [debug] [tls] successfully loaded and added certificate 60 to trusted store
[2025/05/19 15:40:23] [debug] [tls] certificate 61 details - subject: /C=BM/O=QuoVadis Limited/CN=QuoVadis Root CA 2 G3, issuer: /C=BM/O=QuoVadis Limited/CN=QuoVadis Root CA 2 G3
[2025/05/19 15:40:23] [debug] [tls] successfully loaded and added certificate 61 to trusted store
[2025/05/19 15:40:23] [debug] [tls] certificate 62 details - subject: /C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert Assured ID Root CA, issuer: /C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert Assured ID Root CA
[2025/05/19 15:40:23] [debug] [tls] successfully loaded and added certificate 62 to trusted store
[2025/05/19 15:40:23] [debug] [tls] certificate 63 details - subject: /C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert Assured ID Root G3, issuer: /C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert Assured ID Root G3
[2025/05/19 15:40:23] [debug] [tls] successfully loaded and added certificate 63 to trusted store
[2025/05/19 15:40:23] [debug] [tls] certificate 64 details - subject: /C=US/ST=Illinois/L=Chicago/O=Trustwave Holdings, Inc./CN=Trustwave Global Certification Authority, issuer: /C=US/ST=Illinois/L=Chicago/O=Trustwave Holdings, Inc./CN=Trustwave Global Certification Authority
[2025/05/19 15:40:23] [debug] [tls] successfully loaded and added certificate 64 to trusted store
[2025/05/19 15:40:23] [debug] [tls] certificate 65 details - subject: /C=US/O=SSL Corporation/CN=SSL.com Client ECC Root CA 2022, issuer: /C=US/O=SSL Corporation/CN=SSL.com Client ECC Root CA 2022
[2025/05/19 15:40:23] [debug] [tls] successfully loaded and added certificate 65 to trusted store
[2025/05/19 15:40:23] [debug] [tls] certificate 66 details - subject: /C=CN/O=GUANG DONG CERTIFICATE AUTHORITY CO.,LTD./CN=GDCA TrustAUTH R5 ROOT, issuer: /C=CN/O=GUANG DONG CERTIFICATE AUTHORITY CO.,LTD./CN=GDCA TrustAUTH R5 ROOT
[2025/05/19 15:40:23] [debug] [tls] successfully loaded and added certificate 66 to trusted store
[2025/05/19 15:40:23] [debug] [tls] certificate 67 details - subject: /C=DE/O=T-Systems Enterprise Services GmbH/OU=T-Systems Trust Center/CN=T-TeleSec GlobalRoot Class 2, issuer: /C=DE/O=T-Systems Enterprise Services GmbH/OU=T-Systems Trust Center/CN=T-TeleSec GlobalRoot Class 2
[2025/05/19 15:40:23] [debug] [tls] successfully loaded and added certificate 67 to trusted store
[2025/05/19 15:40:23] [debug] [tls] certificate 68 details - subject: /C=DE/O=T-Systems Enterprise Services GmbH/OU=T-Systems Trust Center/CN=T-TeleSec GlobalRoot Class 3, issuer: /C=DE/O=T-Systems Enterprise Services GmbH/OU=T-Systems Trust Center/CN=T-TeleSec GlobalRoot Class 3
[2025/05/19 15:40:23] [debug] [tls] successfully loaded and added certificate 68 to trusted store
[2025/05/19 15:40:23] [debug] [tls] certificate 69 details - subject: /C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert Assured ID Root G2, issuer: /C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert Assured ID Root G2
[2025/05/19 15:40:23] [debug] [tls] successfully loaded and added certificate 69 to trusted store
[2025/05/19 15:40:23] [debug] [tls] certificate 70 details - subject: /C=JP/O=SECOM Trust Systems CO.,LTD./OU=Security Communication RootCA2, issuer: /C=JP/O=SECOM Trust Systems CO.,LTD./OU=Security Communication RootCA2
[2025/05/19 15:40:23] [debug] [tls] successfully loaded and added certificate 70 to trusted store
[2025/05/19 15:40:23] [debug] [tls] certificate 71 details - subject: /O=Entrust.net/OU=www.entrust.net\/CPS_2048 incorp. by ref. (limits liab.)/OU=(c) 1999 Entrust.net Limited/CN=Entrust.net Certification Authority (2048), issuer: /O=Entrust.net/OU=www.entrust.net\/CPS_2048 incorp. by ref. (limits liab.)/OU=(c) 1999 Entrust.net Limited/CN=Entrust.net Certification Authority (2048)
[2025/05/19 15:40:23] [debug] [tls] successfully loaded and added certificate 71 to trusted store
[2025/05/19 15:40:23] [debug] [tls] certificate 72 details - subject: /C=US/O=AffirmTrust/CN=AffirmTrust Networking, issuer: /C=US/O=AffirmTrust/CN=AffirmTrust Networking
[2025/05/19 15:40:23] [debug] [tls] successfully loaded and added certificate 72 to trusted store
[2025/05/19 15:40:23] [debug] [tls] certificate 73 details - subject: /C=ES/CN=Autoridad de Certificacion Firmaprofesional CIF A62634068, issuer: /C=ES/CN=Autoridad de Certificacion Firmaprofesional CIF A62634068
[2025/05/19 15:40:23] [debug] [tls] successfully loaded and added certificate 73 to trusted store
[2025/05/19 15:40:23] [debug] [tls] certificate 74 details - subject: /C=US/O=Amazon/CN=Amazon Root CA 3, issuer: /C=US/O=Amazon/CN=Amazon Root CA 3
[2025/05/19 15:40:23] [debug] [tls] successfully loaded and added certificate 74 to trusted store
[2025/05/19 15:40:23] [debug] [tls] certificate 75 details - subject: /C=US/O=Amazon/CN=Amazon Root CA 2, issuer: /C=US/O=Amazon/CN=Amazon Root CA 2
[2025/05/19 15:40:23] [debug] [tls] successfully loaded and added certificate 75 to trusted store
[2025/05/19 15:40:23] [debug] [tls] certificate 76 details - subject: /CN=Atos TrustedRoot Root CA ECC TLS 2021/O=Atos/C=DE, issuer: /CN=Atos TrustedRoot Root CA ECC TLS 2021/O=Atos/C=DE
[2025/05/19 15:40:23] [debug] [tls] successfully loaded and added certificate 76 to trusted store
[2025/05/19 15:40:23] [debug] [tls] certificate 77 details - subject: /C=US/O=AffirmTrust/CN=AffirmTrust Premium ECC, issuer: /C=US/O=AffirmTrust/CN=AffirmTrust Premium ECC
[2025/05/19 15:40:23] [debug] [tls] successfully loaded and added certificate 77 to trusted store
[2025/05/19 15:40:23] [debug] [tls] certificate 78 details - subject: /C=US/O=Apple Computer, Inc./OU=Apple Computer Certificate Authority/CN=Apple Root Certificate Authority, issuer: /C=US/O=Apple Computer, Inc./OU=Apple Computer Certificate Authority/CN=Apple Root Certificate Authority
[2025/05/19 15:40:23] [debug] [tls] successfully loaded and added certificate 78 to trusted store
[2025/05/19 15:40:23] [debug] [tls] certificate 79 details - subject: /C=CH/O=SwissSign AG/CN=SwissSign Gold CA - G2, issuer: /C=CH/O=SwissSign AG/CN=SwissSign Gold CA - G2
[2025/05/19 15:40:23] [debug] [tls] successfully loaded and added certificate 79 to trusted store
[2025/05/19 15:40:23] [debug] [tls] certificate 80 details - subject: /C=US/O=The Go Daddy Group, Inc./OU=Go Daddy Class 2 Certification Authority, issuer: /C=US/O=The Go Daddy Group, Inc./OU=Go Daddy Class 2 Certification Authority
[2025/05/19 15:40:23] [debug] [tls] successfully loaded and added certificate 80 to trusted store
[2025/05/19 15:40:23] [debug] [tls] certificate 81 details - subject: /C=US/ST=Texas/L=Houston/O=SSL Corporation/CN=SSL.com Root Certification Authority ECC, issuer: /C=US/ST=Texas/L=Houston/O=SSL Corporation/CN=SSL.com Root Certification Authority ECC
[2025/05/19 15:40:23] [debug] [tls] successfully loaded and added certificate 81 to trusted store
[2025/05/19 15:40:23] [debug] [tls] certificate 82 details - subject: /C=CN/O=China Financial Certification Authority/CN=CFCA EV ROOT, issuer: /C=CN/O=China Financial Certification Authority/CN=CFCA EV ROOT
[2025/05/19 15:40:23] [debug] [tls] successfully loaded and added certificate 82 to trusted store
[2025/05/19 15:40:23] [debug] [tls] certificate 83 details - subject: /C=RO/O=CERTSIGN SA/OU=certSIGN ROOT CA G2, issuer: /C=RO/O=CERTSIGN SA/OU=certSIGN ROOT CA G2
[2025/05/19 15:40:23] [debug] [tls] successfully loaded and added certificate 83 to trusted store
[2025/05/19 15:40:23] [debug] [tls] certificate 84 details - subject: /C=CH/O=WISeKey/OU=OISTE Foundation Endorsed/CN=OISTE WISeKey Global Root GC CA, issuer: /C=CH/O=WISeKey/OU=OISTE Foundation Endorsed/CN=OISTE WISeKey Global Root GC CA
[2025/05/19 15:40:23] [debug] [tls] successfully loaded and added certificate 84 to trusted store
[2025/05/19 15:40:23] [debug] [tls] certificate 85 details - subject: /C=US/O=Amazon/CN=Amazon Root CA 1, issuer: /C=US/O=Amazon/CN=Amazon Root CA 1
[2025/05/19 15:40:23] [debug] [tls] successfully loaded and added certificate 85 to trusted store
[2025/05/19 15:40:23] [debug] [tls] certificate 86 details - subject: /C=NO/O=Buypass AS-983163327/CN=Buypass Class 2 Root CA, issuer: /C=NO/O=Buypass AS-983163327/CN=Buypass Class 2 Root CA
[2025/05/19 15:40:23] [debug] [tls] successfully loaded and added certificate 86 to trusted store
[2025/05/19 15:40:23] [debug] [tls] certificate 87 details - subject: /C=US/O=Internet Security Research Group/CN=ISRG Root X2, issuer: /C=US/O=Internet Security Research Group/CN=ISRG Root X2
[2025/05/19 15:40:23] [debug] [tls] successfully loaded and added certificate 87 to trusted store
[2025/05/19 15:40:23] [debug] [tls] certificate 88 details - subject: /C=IN/OU=emSign PKI/O=eMudhra Technologies Limited/CN=emSign Root CA - G1, issuer: /C=IN/OU=emSign PKI/O=eMudhra Technologies Limited/CN=emSign Root CA - G1
[2025/05/19 15:40:23] [debug] [tls] successfully loaded and added certificate 88 to trusted store
[2025/05/19 15:40:23] [debug] [tls] certificate 89 details - subject: /C=US/O=GeoTrust Inc./OU=(c) 2007 GeoTrust Inc. - For authorized use only/CN=GeoTrust Primary Certification Authority - G2, issuer: /C=US/O=GeoTrust Inc./OU=(c) 2007 GeoTrust Inc. - For authorized use only/CN=GeoTrust Primary Certification Authority - G2
[2025/05/19 15:40:23] [debug] [tls] successfully loaded and added certificate 89 to trusted store
[2025/05/19 15:40:23] [debug] [tls] certificate 90 details - subject: /C=TW/O=TAIWAN-CA/OU=Root CA/CN=TWCA Global Root CA, issuer: /C=TW/O=TAIWAN-CA/OU=Root CA/CN=TWCA Global Root CA
[2025/05/19 15:40:23] [debug] [tls] successfully loaded and added certificate 90 to trusted store
[2025/05/19 15:40:23] [debug] [tls] certificate 91 details - subject: /C=US/O=SecureTrust Corporation/CN=Secure Global CA, issuer: /C=US/O=SecureTrust Corporation/CN=Secure Global CA
[2025/05/19 15:40:23] [debug] [tls] successfully loaded and added certificate 91 to trusted store
[2025/05/19 15:40:23] [debug] [tls] certificate 92 details - subject: /C=US/O=Amazon/CN=Amazon Root CA 4, issuer: /C=US/O=Amazon/CN=Amazon Root CA 4
[2025/05/19 15:40:23] [debug] [tls] successfully loaded and added certificate 92 to trusted store
[2025/05/19 15:40:23] [debug] [tls] certificate 93 details - subject: /C=PL/O=Unizeto Technologies S.A./OU=Certum Certification Authority/CN=Certum Trusted Network CA 2, issuer: /C=PL/O=Unizeto Technologies S.A./OU=Certum Certification Authority/CN=Certum Trusted Network CA 2
[2025/05/19 15:40:23] [debug] [tls] successfully loaded and added certificate 93 to trusted store
[2025/05/19 15:40:23] [debug] [tls] certificate 94 details - subject: /C=US/O=AffirmTrust/CN=AffirmTrust Premium, issuer: /C=US/O=AffirmTrust/CN=AffirmTrust Premium
[2025/05/19 15:40:23] [debug] [tls] successfully loaded and added certificate 94 to trusted store
[2025/05/19 15:40:23] [debug] [tls] certificate 95 details - subject: /C=CH/O=SwissSign AG/CN=SwissSign Silver CA - G2, issuer: /C=CH/O=SwissSign AG/CN=SwissSign Silver CA - G2
[2025/05/19 15:40:23] [debug] [tls] successfully loaded and added certificate 95 to trusted store
[2025/05/19 15:40:23] [debug] [tls] certificate 96 details - subject: /C=DE/O=Atos/CN=Atos TrustedRoot Root CA RSA G2 2020, issuer: /C=DE/O=Atos/CN=Atos TrustedRoot Root CA RSA G2 2020
[2025/05/19 15:40:23] [debug] [tls] successfully loaded and added certificate 96 to trusted store
[2025/05/19 15:40:23] [debug] [tls] certificate 97 details - subject: /C=HU/L=Budapest/O=NetLock Kft./OU=Tan\xC3\xBAs\xC3\xADtv\xC3\xA1nykiad\xC3\xB3k (Certification Services)/CN=NetLock Arany (Class Gold) F\xC5\x91tan\xC3\xBAs\xC3\xADtv\xC3\xA1ny, issuer: /C=HU/L=Budapest/O=NetLock Kft./OU=Tan\xC3\xBAs\xC3\xADtv\xC3\xA1nykiad\xC3\xB3k (Certification Services)/CN=NetLock Arany (Class Gold) F\xC5\x91tan\xC3\xBAs\xC3\xADtv\xC3\xA1ny
[2025/05/19 15:40:23] [debug] [tls] successfully loaded and added certificate 97 to trusted store
[2025/05/19 15:40:23] [debug] [tls] certificate 98 details - subject: /C=IN/OU=emSign PKI/O=eMudhra Technologies Limited/CN=emSign ECC Root CA - G3, issuer: /C=IN/OU=emSign PKI/O=eMudhra Technologies Limited/CN=emSign ECC Root CA - G3
[2025/05/19 15:40:23] [debug] [tls] successfully loaded and added certificate 98 to trusted store
[2025/05/19 15:40:23] [debug] [tls] certificate 99 details - subject: /C=GB/O=Sectigo Limited/CN=Sectigo Public Email Protection Root E46, issuer: /C=GB/O=Sectigo Limited/CN=Sectigo Public Email Protection Root E46
[2025/05/19 15:40:23] [debug] [tls] successfully loaded and added certificate 99 to trusted store
[2025/05/19 15:40:23] [debug] [tls] certificate 100 details - subject: /C=TW/O=Chunghwa Telecom Co., Ltd./CN=HiPKI Root CA - G1, issuer: /C=TW/O=Chunghwa Telecom Co., Ltd./CN=HiPKI Root CA - G1
[2025/05/19 15:40:23] [debug] [tls] successfully loaded and added certificate 100 to trusted store
[2025/05/19 15:40:23] [debug] [tls] certificate 101 details - subject: /C=US/O=Apple Inc./OU=Apple Certification Authority/CN=Apple Root CA, issuer: /C=US/O=Apple Inc./OU=Apple Certification Authority/CN=Apple Root CA
[2025/05/19 15:40:23] [debug] [tls] successfully loaded and added certificate 101 to trusted store
[2025/05/19 15:40:23] [debug] [tls] certificate 102 details - subject: /C=EU/L=Madrid (see current address at www.camerfirma.com\/address)/serialNumber=A82743287/O=AC Camerfirma S.A./CN=Chambers of Commerce Root - 2008, issuer: /C=EU/L=Madrid (see current address at www.camerfirma.com\/address)/serialNumber=A82743287/O=AC Camerfirma S.A./CN=Chambers of Commerce Root - 2008
[2025/05/19 15:40:23] [debug] [tls] successfully loaded and added certificate 102 to trusted store
[2025/05/19 15:40:23] [debug] [tls] certificate 103 details - subject: /C=PL/O=Asseco Data Systems S.A./OU=Certum Certification Authority/CN=Certum Trusted Root CA, issuer: /C=PL/O=Asseco Data Systems S.A./OU=Certum Certification Authority/CN=Certum Trusted Root CA
[2025/05/19 15:40:23] [debug] [tls] successfully loaded and added certificate 103 to trusted store
[2025/05/19 15:40:23] [debug] [tls] certificate 104 details - subject: /C=GB/ST=Greater Manchester/L=Salford/O=COMODO CA Limited/CN=COMODO ECC Certification Authority, issuer: /C=GB/ST=Greater Manchester/L=Salford/O=COMODO CA Limited/CN=COMODO ECC Certification Authority
[2025/05/19 15:40:23] [debug] [tls] successfully loaded and added certificate 104 to trusted store
[2025/05/19 15:40:23] [debug] [tls] certificate 105 details - subject: /C=BE/O=GlobalSign nv-sa/CN=GlobalSign Secure Mail Root R45, issuer: /C=BE/O=GlobalSign nv-sa/CN=GlobalSign Secure Mail Root R45
[2025/05/19 15:40:23] [debug] [tls] successfully loaded and added certificate 105 to trusted store
[2025/05/19 15:40:23] [debug] [tls] certificate 106 details - subject: /C=US/O=Google Trust Services LLC/CN=GTS Root R1, issuer: /C=US/O=Google Trust Services LLC/CN=GTS Root R1
[2025/05/19 15:40:23] [debug] [tls] successfully loaded and added certificate 106 to trusted store
[2025/05/19 15:40:23] [debug] [tls] certificate 107 details - subject: /C=TR/L=Gebze - Kocaeli/O=Turkiye Bilimsel ve Teknolojik Arastirma Kurumu - TUBITAK/OU=Kamu Sertifikasyon Merkezi - Kamu SM/CN=TUBITAK Kamu SM SSL Kok Sertifikasi - Surum 1, issuer: /C=TR/L=Gebze - Kocaeli/O=Turkiye Bilimsel ve Teknolojik Arastirma Kurumu - TUBITAK/OU=Kamu Sertifikasyon Merkezi - Kamu SM/CN=TUBITAK Kamu SM SSL Kok Sertifikasi - Surum 1
[2025/05/19 15:40:23] [debug] [tls] successfully loaded and added certificate 107 to trusted store
[2025/05/19 15:40:23] [debug] [tls] certificate 108 details - subject: /C=US/ST=Illinois/L=Chicago/O=Trustwave Holdings, Inc./CN=Trustwave Global ECC P256 Certification Authority, issuer: /C=US/ST=Illinois/L=Chicago/O=Trustwave Holdings, Inc./CN=Trustwave Global ECC P256 Certification Authority
[2025/05/19 15:40:23] [debug] [tls] successfully loaded and added certificate 108 to trusted store
[2025/05/19 15:40:23] [debug] [tls] certificate 109 details - subject: /C=US/O=Entrust, Inc./OU=See www.entrust.net\/legal-terms/OU=(c) 2012 Entrust, Inc. - for authorized use only/CN=Entrust Root Certification Authority - EC1, issuer: /C=US/O=Entrust, Inc./OU=See www.entrust.net\/legal-terms/OU=(c) 2012 Entrust, Inc. - for authorized use only/CN=Entrust Root Certification Authority - EC1
[2025/05/19 15:40:23] [debug] [tls] successfully loaded and added certificate 109 to trusted store
[2025/05/19 15:40:23] [debug] [tls] certificate 110 details - subject: /C=US/O=Entrust, Inc./OU=www.entrust.net\/CPS is incorporated by reference/OU=(c) 2006 Entrust, Inc./CN=Entrust Root Certification Authority, issuer: /C=US/O=Entrust, Inc./OU=www.entrust.net\/CPS is incorporated by reference/OU=(c) 2006 Entrust, Inc./CN=Entrust Root Certification Authority
[2025/05/19 15:40:23] [debug] [tls] successfully loaded and added certificate 110 to trusted store
[2025/05/19 15:40:23] [debug] [tls] certificate 111 details - subject: /CN=Atos TrustedRoot 2011/O=Atos/C=DE, issuer: /CN=Atos TrustedRoot 2011/O=Atos/C=DE
[2025/05/19 15:40:23] [debug] [tls] successfully loaded and added certificate 111 to trusted store
[2025/05/19 15:40:23] [debug] [tls] certificate 112 details - subject: /C=DE/O=D-Trust GmbH/CN=D-TRUST Root Class 3 CA 2 2009, issuer: /C=DE/O=D-Trust GmbH/CN=D-TRUST Root Class 3 CA 2 2009
[2025/05/19 15:40:23] [debug] [tls] successfully loaded and added certificate 112 to trusted store
[2025/05/19 15:40:23] [debug] [tls] certificate 113 details - subject: /C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert High Assurance EV Root CA, issuer: /C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert High Assurance EV Root CA
[2025/05/19 15:40:23] [debug] [tls] successfully loaded and added certificate 113 to trusted store
[2025/05/19 15:40:23] [debug] [tls] certificate 114 details - subject: /C=PL/O=Unizeto Technologies S.A./OU=Certum Certification Authority/CN=Certum Trusted Network CA, issuer: /C=PL/O=Unizeto Technologies S.A./OU=Certum Certification Authority/CN=Certum Trusted Network CA
[2025/05/19 15:40:23] [debug] [tls] successfully loaded and added certificate 114 to trusted store
[2025/05/19 15:40:23] [debug] [tls] certificate 115 details - subject: /C=GB/O=Sectigo Limited/CN=Sectigo Public Server Authentication Root R46, issuer: /C=GB/O=Sectigo Limited/CN=Sectigo Public Server Authentication Root R46
[2025/05/19 15:40:23] [debug] [tls] successfully loaded and added certificate 115 to trusted store
[2025/05/19 15:40:23] [debug] [tls] certificate 116 details - subject: /C=US/O=Google Trust Services LLC/CN=GTS Root R4, issuer: /C=US/O=Google Trust Services LLC/CN=GTS Root R4
[2025/05/19 15:40:23] [debug] [tls] successfully loaded and added certificate 116 to trusted store
[2025/05/19 15:40:23] [debug] [tls] certificate 117 details - subject: /C=BE/O=GlobalSign nv-sa/CN=GlobalSign Root R46, issuer: /C=BE/O=GlobalSign nv-sa/CN=GlobalSign Root R46
[2025/05/19 15:40:23] [debug] [tls] successfully loaded and added certificate 117 to trusted store
[2025/05/19 15:40:23] [debug] [tls] certificate 118 details - subject: /C=EU/L=Madrid (see current address at www.camerfirma.com\/address)/serialNumber=A82743287/O=AC Camerfirma S.A./CN=Global Chambersign Root - 2008, issuer: /C=EU/L=Madrid (see current address at www.camerfirma.com\/address)/serialNumber=A82743287/O=AC Camerfirma S.A./CN=Global Chambersign Root - 2008
[2025/05/19 15:40:23] [debug] [tls] successfully loaded and added certificate 118 to trusted store
[2025/05/19 15:40:23] [debug] [tls] certificate 119 details - subject: /C=FI/O=Telia Finland Oyj/CN=Telia Root CA v2, issuer: /C=FI/O=Telia Finland Oyj/CN=Telia Root CA v2
[2025/05/19 15:40:23] [debug] [tls] successfully loaded and added certificate 119 to trusted store
[2025/05/19 15:40:23] [debug] [tls] certificate 120 details - subject: /C=US/O=IdenTrust/CN=IdenTrust Commercial Root CA 1, issuer: /C=US/O=IdenTrust/CN=IdenTrust Commercial Root CA 1
[2025/05/19 15:40:23] [debug] [tls] successfully loaded and added certificate 120 to trusted store
[2025/05/19 15:40:23] [debug] [tls] certificate 121 details - subject: /C=US/O=Google Trust Services LLC/CN=GTS Root R2, issuer: /C=US/O=Google Trust Services LLC/CN=GTS Root R2
[2025/05/19 15:40:23] [debug] [tls] successfully loaded and added certificate 121 to trusted store
[2025/05/19 15:40:23] [debug] [tls] certificate 122 details - subject: /OU=GlobalSign Root CA - R3/O=GlobalSign/CN=GlobalSign, issuer: /OU=GlobalSign Root CA - R3/O=GlobalSign/CN=GlobalSign
[2025/05/19 15:40:23] [debug] [tls] successfully loaded and added certificate 122 to trusted store
[2025/05/19 15:40:23] [debug] [tls] certificate 123 details - subject: /C=US/O=Entrust, Inc./OU=See www.entrust.net\/legal-terms/OU=(c) 2015 Entrust, Inc. - for authorized use only/CN=Entrust Root Certification Authority - G4, issuer: /C=US/O=Entrust, Inc./OU=See www.entrust.net\/legal-terms/OU=(c) 2015 Entrust, Inc. - for authorized use only/CN=Entrust Root Certification Authority - G4
[2025/05/19 15:40:23] [debug] [tls] successfully loaded and added certificate 123 to trusted store
[2025/05/19 15:40:23] [debug] [tls] certificate 124 details - subject: /OU=GlobalSign Root CA - R6/O=GlobalSign/CN=GlobalSign, issuer: /OU=GlobalSign Root CA - R6/O=GlobalSign/CN=GlobalSign
[2025/05/19 15:40:23] [debug] [tls] successfully loaded and added certificate 124 to trusted store
[2025/05/19 15:40:23] [debug] [tls] certificate 125 details - subject: /O=TeliaSonera/CN=TeliaSonera Root CA v1, issuer: /O=TeliaSonera/CN=TeliaSonera Root CA v1
[2025/05/19 15:40:23] [debug] [tls] successfully loaded and added certificate 125 to trusted store
[2025/05/19 15:40:23] [debug] [tls] certificate 126 details - subject: /C=GB/ST=Greater Manchester/L=Salford/O=COMODO CA Limited/CN=COMODO RSA Certification Authority, issuer: /C=GB/ST=Greater Manchester/L=Salford/O=COMODO CA Limited/CN=COMODO RSA Certification Authority
[2025/05/19 15:40:23] [debug] [tls] successfully loaded and added certificate 126 to trusted store
[2025/05/19 15:40:23] [debug] [tls] certificate 127 details - subject: /C=US/O=Google Trust Services LLC/CN=GTS Root R3, issuer: /C=US/O=Google Trust Services LLC/CN=GTS Root R3
[2025/05/19 15:40:23] [debug] [tls] successfully loaded and added certificate 127 to trusted store
[2025/05/19 15:40:23] [debug] [tls] certificate 128 details - subject: /C=US/ST=Texas/L=Houston/O=SSL Corporation/CN=SSL.com Root Certification Authority RSA, issuer: /C=US/ST=Texas/L=Houston/O=SSL Corporation/CN=SSL.com Root Certification Authority RSA
[2025/05/19 15:40:23] [debug] [tls] successfully loaded and added certificate 128 to trusted store
[2025/05/19 15:40:23] [debug] [tls] certificate 129 details - subject: /O=Cisco Systems/CN=Cisco Root CA 2048, issuer: /O=Cisco Systems/CN=Cisco Root CA 2048
[2025/05/19 15:40:23] [debug] [tls] successfully loaded and added certificate 129 to trusted store
[2025/05/19 15:40:23] [debug] [tls] certificate 130 details - subject: /C=RO/O=certSIGN/OU=certSIGN ROOT CA, issuer: /C=RO/O=certSIGN/OU=certSIGN ROOT CA
[2025/05/19 15:40:23] [debug] [tls] successfully loaded and added certificate 130 to trusted store
[2025/05/19 15:40:23] [debug] [tls] certificate 131 details - subject: /C=US/ST=Texas/L=Houston/O=SSL Corporation/CN=SSL.com EV Root Certification Authority RSA R2, issuer: /C=US/ST=Texas/L=Houston/O=SSL Corporation/CN=SSL.com EV Root Certification Authority RSA R2
[2025/05/19 15:40:23] [debug] [tls] successfully loaded and added certificate 131 to trusted store
[2025/05/19 15:40:23] [debug] [tls] certificate 132 details - subject: /C=US/O=Google Trust Services LLC/CN=GTS Root R3, issuer: /C=US/O=Google Trust Services LLC/CN=GTS Root R3
[2025/05/19 15:40:23] [debug] [tls] successfully loaded and added certificate 132 to trusted store
[2025/05/19 15:40:23] [debug] [tls] certificate 133 details - subject: /C=US/ST=New Jersey/L=Jersey City/O=The USERTRUST Network/CN=USERTrust ECC Certification Authority, issuer: /C=US/ST=New Jersey/L=Jersey City/O=The USERTRUST Network/CN=USERTrust ECC Certification Authority
[2025/05/19 15:40:23] [debug] [tls] successfully loaded and added certificate 133 to trusted store
[2025/05/19 15:40:23] [debug] [tls] certificate 134 details - subject: /C=HU/L=Budapest/O=Microsec Ltd./CN=Microsec e-Szigno Root CA 2009/emailAddress=info@e-szigno.hu, issuer: /C=HU/L=Budapest/O=Microsec Ltd./CN=Microsec e-Szigno Root CA 2009/emailAddress=info@e-szigno.hu
[2025/05/19 15:40:23] [debug] [tls] successfully loaded and added certificate 134 to trusted store
[2025/05/19 15:40:23] [debug] [tls] certificate 135 details - subject: /C=US/O=Microsoft Corporation/CN=Microsoft ECC Root Certificate Authority 2017, issuer: /C=US/O=Microsoft Corporation/CN=Microsoft ECC Root Certificate Authority 2017
[2025/05/19 15:40:23] [debug] [tls] successfully loaded and added certificate 135 to trusted store
[2025/05/19 15:40:23] [debug] [tls] certificate 136 details - subject: /C=US/O=Google Trust Services LLC/CN=GTS Root R2, issuer: /C=US/O=Google Trust Services LLC/CN=GTS Root R2
[2025/05/19 15:40:23] [debug] [tls] successfully loaded and added certificate 136 to trusted store
[2025/05/19 15:40:23] [debug] [tls] certificate 137 details - subject: /C=FR/O=Dhimyotis/CN=Certigna, issuer: /C=FR/O=Dhimyotis/CN=Certigna
[2025/05/19 15:40:23] [debug] [tls] successfully loaded and added certificate 137 to trusted store
[2025/05/19 15:40:23] [debug] [tls] certificate 138 details - subject: /C=AT/O=e-commerce monitoring GmbH/CN=GLOBALTRUST 2020, issuer: /C=AT/O=e-commerce monitoring GmbH/CN=GLOBALTRUST 2020
[2025/05/19 15:40:23] [debug] [tls] successfully loaded and added certificate 138 to trusted store
[2025/05/19 15:40:23] [debug] [tls] certificate 139 details - subject: /C=US/O=Google Trust Services LLC/CN=GTS Root R4, issuer: /C=US/O=Google Trust Services LLC/CN=GTS Root R4
[2025/05/19 15:40:23] [debug] [tls] successfully loaded and added certificate 139 to trusted store
[2025/05/19 15:40:23] [debug] [tls] certificate 140 details - subject: /C=BM/O=QuoVadis Limited/CN=QuoVadis Root CA 3, issuer: /C=BM/O=QuoVadis Limited/CN=QuoVadis Root CA 3
[2025/05/19 15:40:23] [debug] [tls] successfully loaded and added certificate 140 to trusted store
[2025/05/19 15:40:23] [debug] [tls] certificate 141 details - subject: /C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert Global Root G2, issuer: /C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert Global Root G2
[2025/05/19 15:40:23] [debug] [tls] successfully loaded and added certificate 141 to trusted store
[2025/05/19 15:40:23] [debug] [tls] certificate 142 details - subject: /C=GB/O=Sectigo Limited/CN=Sectigo Public Time Stamping Root E46, issuer: /C=GB/O=Sectigo Limited/CN=Sectigo Public Time Stamping Root E46
[2025/05/19 15:40:23] [debug] [tls] successfully loaded and added certificate 142 to trusted store
[2025/05/19 15:40:23] [debug] [tls] certificate 143 details - subject: /C=US/ST=Arizona/L=Scottsdale/O=Starfield Technologies, Inc./CN=Starfield Root Certificate Authority - G2, issuer: /C=US/ST=Arizona/L=Scottsdale/O=Starfield Technologies, Inc./CN=Starfield Root Certificate Authority - G2
[2025/05/19 15:40:23] [debug] [tls] successfully loaded and added certificate 143 to trusted store
[2025/05/19 15:40:23] [debug] [tls] certificate 144 details - subject: /C=GR/L=Athens/O=Hellenic Academic and Research Institutions Cert. Authority/CN=Hellenic Academic and Research Institutions ECC RootCA 2015, issuer: /C=GR/L=Athens/O=Hellenic Academic and Research Institutions Cert. Authority/CN=Hellenic Academic and Research Institutions ECC RootCA 2015
[2025/05/19 15:40:23] [debug] [tls] successfully loaded and added certificate 144 to trusted store
[2025/05/19 15:40:23] [debug] [tls] certificate 145 details - subject: /C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert Global Root CA, issuer: /C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert Global Root CA
[2025/05/19 15:40:23] [debug] [tls] successfully loaded and added certificate 145 to trusted store
[2025/05/19 15:40:23] [debug] [tls] certificate 146 details - subject: /C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert Global Root G3, issuer: /C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert Global Root G3
[2025/05/19 15:40:23] [debug] [tls] successfully loaded and added certificate 146 to trusted store
[2025/05/19 15:40:23] [debug] [tls] certificate 147 details - subject: /C=US/O=Google Trust Services LLC/CN=GTS Root R1, issuer: /C=US/O=Google Trust Services LLC/CN=GTS Root R1
[2025/05/19 15:40:23] [debug] [tls] successfully loaded and added certificate 147 to trusted store
[2025/05/19 15:40:23] [debug] [tls] certificate 148 details - subject: /C=US/O=Certainly/CN=Certainly Root E1, issuer: /C=US/O=Certainly/CN=Certainly Root E1
[2025/05/19 15:40:23] [debug] [tls] successfully loaded and added certificate 148 to trusted store
[2025/05/19 15:40:23] [debug] [tls] certificate 149 details - subject: /C=BM/O=QuoVadis Limited/CN=QuoVadis Root CA 2, issuer: /C=BM/O=QuoVadis Limited/CN=QuoVadis Root CA 2
[2025/05/19 15:40:23] [debug] [tls] successfully loaded and added certificate 149 to trusted store
[2025/05/19 15:40:23] [debug] [tls] certificate 150 details - subject: /C=PL/O=Unizeto Sp. z o.o./CN=Certum CA, issuer: /C=PL/O=Unizeto Sp. z o.o./CN=Certum CA
[2025/05/19 15:40:23] [debug] [tls] successfully loaded and added certificate 150 to trusted store
[2025/05/19 15:40:23] [debug] [tls] certificate 151 details - subject: /C=US/ST=New Jersey/L=Jersey City/O=The USERTRUST Network/CN=USERTrust RSA Certification Authority, issuer: /C=US/ST=New Jersey/L=Jersey City/O=The USERTRUST Network/CN=USERTrust RSA Certification Authority
[2025/05/19 15:40:23] [debug] [tls] successfully loaded and added certificate 151 to trusted store
[2025/05/19 15:40:23] [debug] [tls] certificate 152 details - subject: /C=US/O=Microsoft Corporation/CN=Microsoft RSA Root Certificate Authority 2017, issuer: /C=US/O=Microsoft Corporation/CN=Microsoft RSA Root Certificate Authority 2017
[2025/05/19 15:40:23] [debug] [tls] successfully loaded and added certificate 152 to trusted store
[2025/05/19 15:40:23] [debug] [tls] finished loading keychain certificates, total loaded: 153
[2025/05/19 15:40:23] [debug] [output:es:es.0] host=[redacted] port=[redacted] uri=/_bulk index=any-index type=_doc
[2025/05/19 15:40:23] [ info] [output:es:es.0] worker #0 started
[2025/05/19 15:40:23] [ info] [output:es:es.0] worker #1 started
[2025/05/19 15:40:23] [ info] [sp] stream processor started
^C[2025/05/19 15:40:24] [engine] caught signal (SIGINT)
[2025/05/19 15:40:24] [ info] [input] pausing forward.0
[2025/05/19 15:40:24] [ info] [output:es:es.0] thread worker #0 stopping...
[2025/05/19 15:40:24] [ info] [output:es:es.0] thread worker #0 stopped
[2025/05/19 15:40:24] [ info] [output:es:es.0] thread worker #1 stopping...
[2025/05/19 15:40:24] [ info] [output:es:es.0] thread worker #1 stopped

```

**Comment by tkennedy1-godaddy** [comment]
valgrind:

```
==212661== Memcheck, a memory error detector
==212661== Copyright (C) 2002-2022, and GNU GPL'd, by Julian Seward et al.
==212661== Using Valgrind-3.19.0 and LibVEX; rerun with -h for copyright info
==212661== Command: ./bin/fluent-bit -c config.yaml
==212661==
Fluent Bit v4.0.2
* Copyright (C) 2015-2025 The Fluent Bit Authors
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io

______ _                  _    ______ _ _             ___  _____
|  ___| |                | |   | ___ (_) |           /   ||  _  |
| |_  | |_   _  ___ _ __ | |_  | |_/ /_| |_  __   __/ /| || |/' |
|  _| | | | | |/ _ \ '_ \| __| | ___ \ | __| \ \ / / /_| ||  /| |
| |   | | |_| |  __/ | | | |_  | |_/ / | |_   \ V /\___  |\ |_/ /
\_|   |_|\__,_|\___|_| |_|\__| \____/|_|\__|   \_/     |_(_)___/


[2025/05/19 15:58:57] [ info] Configuration:
[2025/05/19 15:58:57] [ info]  flush time     | 1.000000 seconds
[2025/05/19 15:58:57] [ info]  grace          | 5 seconds
[2025/05/19 15:58:57] [ info]  daemon         | 0
[2025/05/19 15:58:57] [ info] ___________
[2025/05/19 15:58:57] [ info]  inputs:
[2025/05/19 15:58:57] [ info]      forward
[2025/05/19 15:58:57] [ info] ___________
[2025/05/19 15:58:57] [ info]  filters:
[2025/05/19 15:58:57] [ info] ___________
[2025/05/19 15:58:57] [ info]  outputs:
[2025/05/19 15:58:57] [ info]      es.0
[2025/05/19 15:58:57] [ info] ___________
[2025/05/19 15:58:57] [ info]  collectors:
[2025/05/19 15:58:57] [ info] [fluent bit] version=4.0.2, commit=0c81ebdd86, pid=212661
[2025/05/19 15:58:57] [debug] [engine] coroutine stack size: 196608 bytes (192.0K)
[2025/05/19 15:58:57] [ info] [storage] ver=1.5.3, type=memory, sync=normal, checksum=off, max_chunks_up=128
[2025/05/19 15:58:57] [ info] [simd    ] disabled
[2025/05/19 15:58:57] [ info] [cmetrics] version=1.0.2
[2025/05/19 15:58:57] [ info] [ctraces ] version=0.6.6
[2025/05/19 15:58:57] [ info] [input:forward:forward.0] initializing
[2025/05/19 15:58:57] [ info] [input:forward:forward.0] storage_strategy='memory' (memory only)
[2025/05/19 15:58:57] [debug] [forward:forward.0] created event channels: read=25 write=26
[2025/05/19 15:58:57] [debug] [downstream] listening on /tmp/fluent.sock:0
[2025/05/19 15:58:57] [ info] [input:forward:forward.0] listening on unix:///tmp/fluent.sock
[2025/05/19 15:58:57] [debug] [es:es.0] created event channels: read=28 write=29
[2025/05/19 15:58:57] [error] [output:es:es.0] cannot initialize plugin, index is not set and logstash_format and generate_id are both off
[2025/05/19 15:58:57] [error] [output] failed to initialize 'es' plugin
[2025/05/19 15:58:57] [error] [engine] output initialization failed
[2025/05/19 15:58:58] [ info] [input] pausing forward.0
==212661==
==212661== HEAP SUMMARY:
==212661==     in use at exit: 1,064 bytes in 8 blocks
==212661==   total heap usage: 10,834 allocs, 10,826 frees, 1,238,896 bytes allocated
==212661==
==212661== LEAK SUMMARY:
==212661==    definitely lost: 575 bytes in 2 blocks
==212661==    indirectly lost: 489 bytes in 6 blocks
==212661==      possibly lost: 0 bytes in 0 blocks
==212661==    still reachable: 0 bytes in 0 blocks
==212661==         suppressed: 0 bytes in 0 blocks
==212661== Rerun with --leak-check=full to see details of leaked memory
==212661==
==212661== For lists of detected and suppressed errors, rerun with: -s
==212661== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
```

**Comment by patrick-stephens** [comment]
Probably worth adding a simple unit test to exercise the check and also prevent future regressions.

Does the opensearch output have the same issue? If so we should fix it too

**Comment by tkennedy1-godaddy** [comment]
@patrick-stephens the fix for opensearch is in https://github.com/fluent/fluent-bit/pull/10365.

Do you want me to replicate the artifacts (output logs, configuration, etc) in that PR as well, or is the similarity enough in the platforms/tests?

**Comment by cosmo0920** [comment]
```
==212661==
==212661== HEAP SUMMARY:
==212661==     in use at exit: 1,064 bytes in 8 blocks
==212661==   total heap usage: 10,834 allocs, 10,826 frees, 1,238,896 bytes allocated
==212661==
==212661== LEAK SUMMARY:
==212661==    definitely lost: 575 bytes in 2 blocks
==212661==    indirectly lost: 489 bytes in 6 blocks
==212661==      possibly lost: 0 bytes in 0 blocks
==212661==    still reachable: 0 bytes in 0 blocks
==212661==         suppressed: 0 bytes in 0 blocks
==212661== Rerun with --leak-check=full to see details of leaked memory
==212661==
==212661== For lists of detected and suppressed errors, rerun with: -s
==212661== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
```

This indicates that some of the part of Fluent Bit should cause memory leaks.
Did you run valgrind with `--leak-check=full` option?

**Comment by patrick-stephens** [comment]
> @patrick-stephens the fix for opensearch is in #10365.
> 
> Do you want me to replicate the artifacts (output logs, configuration, etc) in that PR as well, or is the similarity enough in the platforms/tests?

For completeness I would replicate or at least link but I think you've done that already? Main thing is if we look at the PR in isolation is it complete enough.

**Review by cosmo0920 — APPROVED** [review]

File: plugins/out_es/es.c [hunk 1]
```diff
@@ -36,6 +36,7 @@
 #include "es.h"
 #include "es_conf.h"
 #include "es_bulk.h"
+#include "fluent-bit/flb_macros.h"
```
Comment (edsiper) [inline plugins/out_es/es.c:39]: It seems this is not necessary (and when we do, we use #include <fluent-bit/flb_macros.h> )

**Review by edsiper — CHANGES_REQUESTED** [review]
please split the changes in 2 commits, one for the plugin and the other for the runtime test case, e.g:

- out_es:  ...
- tests: runtime: out_elasticsearch: ...

File: plugins/out_es/es.c (hunk 1 above)
Comment (tkennedy1-godaddy) [reply plugins/out_es/es.c]: oops overzealous editor inclusion. fixed and force pushed to keep commit message correct.

**Comment by edsiper** [comment]
thank you!

File: tests/runtime/out_elasticsearch.c [hunk 2]
```diff
@@ -347,6 +347,47 @@ void flb_test_write_operation_upsert()
     flb_destroy(ctx);
 }
 
+void flb_test_null_index()
```
Comment (mabrarov) [inline tests/runtime/out_elasticsearch.c:350]: Does this test need to be added into [TEST_LIST](https://github.com/tkennedy1-godaddy/fluent-bit/blob/8107bf412e87c41cf3d38eac445845c315a3653b/tests/runtime/out_elasticsearch.c#L1002)?
