### PR TITLE
in_docker_events: re-initialize docker socket when dockerd is restarted(#3439)

### LINKED ISSUE #3439: Docker_events input plugin does not recover from a docker daemon restart
## Bug Report

**Describe the bug**
Docker_events input plugin does not recover from a docker daemon restart.

**Error logs**
```
~/fluent-bit/build/bin$ sudo ./fluent-bit -i docker_events -o stdout
Fluent Bit v1.7.4
* Copyright (C) 2019-2021 The Fluent Bit Authors
* Copyright (C) 2015-2018 Treasure Data
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io

[2021/04/30 19:46:09] [ info] [engine] started (pid=10741)
[2021/04/30 19:46:09] [ info] [storage] version=1.1.1, initializing...
[2021/04/30 19:46:09] [ info] [storage] in-memory
[2021/04/30 19:46:09] [ info] [storage] normal synchronization mode, checksum disabled, max_chunks_up=128
[2021/04/30 19:46:09] [ info] [input:docker_events:docker_events.0] listening for events on /var/run/docker.sock
[2021/04/30 19:46:09] [ info] [sp] stream processor started
[2021/04/30 19:46:59] [error] [input:docker_events:docker_events.0] read returned error: 0, Success
[2021/04/30 19:46:59] [error] [input:docker_events:docker_events.0] read returned error: 0, Success
[2021/04/30 19:46:59] [error] [input:docker_events:docker_events.0] read returned error: 0, Success
[2021/04/30 19:46:59] [error] [input:docker_events:docker_events.0] read returned error: 0, Success
[2021/04/30 19:46:59] [error] [input:docker_events:docker_events.0] read returned error: 0, Success
[2021/04/30 19:46:59] [error] [input:docker_events:docker_events.0] read returned error: 0, Success
[2021/04/30 19:46:59] [error] [input:docker_events:docker_events.0] read returned error: 0, Success
[2021/04/30 19:46:59] [error] [input:docker_events:docker_events.0] read returned error: 0, Success
[2021/04/30 19:46:59] [error] [input:docker_events:docker_events.0] read returned error: 0, Success
[2021/04/30 19:46:59] [error] [input:docker_events:docker_events.0] read returned error: 0, Success
[2021/04/30 19:46:59] [error] [input:docker_events:docker_events.0] read returned error: 0, Success
[2021/04/30 19:46:59] [error] [input:docker_events:docker_events.0] read returned error: 0, Success
[2021/04/30 19:46:59] [error] [input:docker_events:docker_events.0] read returned error: 0, Success
[2021/04/30 19:46:59] [error] [input:docker_events:docker_events.0] read returned error: 0, Success
[2021/04/30 19:46:59] [error] [input:docker_events:docker_events.0] read returned error: 0, Success
[2021/04/30 19:46:59] [error] [input:docker_events:docker_events.0] read returned error: 0, Success
[2021/04/30 19:46:59] [error] [input:docker_events:docker_events.0] read returned error: 0, Success
[2021/04/30 19:46:59] [error] [input:docker_events:docker_events.0] read returned error: 0, Success
[2021/04/30 19:46:59] [error] [input:docker_events:docker_events.0] read returned error: 0, Success
[2021/04/30 19:46:59] [error] [input:docker_events:docker_events.0] read returned error: 0, Success
[2021/04/30 19:46:59] [error] [input:docker_events:docker_events.0] read returned error: 0, Success
[2021/04/30 19:46:59] [error] [input:docker_events:docker_events.0] read returned error: 0, Success
[2021/04/30 19:46:59] [error] [input:docker_events:docker_events.0] read returned error: 0, Success
[2021/04/30 19:46:59] [error] [input:docker_events:docker_events.0] read returned error: 0, Success
[2021/04/30 19:46:59] [error] [input:docker_events:docker_events.0] read returned error: 0, Success
[2021/04/30 19:46:59] [error] [input:docker_events:docker_events.0] read returned error: 0, Success
[2021/04/30 19:46:59] [error] [input:docker_events:docker_events.0] read returned error: 0, Success
[2021/04/30 19:46:59] [error] [input:docker_events:docker_events.0] read returned error: 0, Success
[2021/04/30 19:46:59] [error] [input:docker_events:docker_events.0] read returned error: 0, Success
[2021/04/30 19:46:59] [error] [input:docker_events:docker_events.0] read returned error: 0, Success
[2021/04/30 19:46:59] [error] [input:docker_events:docker_events.0] read returned error: 0, Success
[2021/04/30 19:46:59] [error] [input:docker_events:docker_events.0] read returned error: 0, Success
[2021/04/30 19:46:59] [error] [input:docker_events:docker_events.0] read returned error: 0, Success
[2021/04/30 19:46:59] [error] [input:docker_events:docker_events.0] read returned error: 0, Success
[2021/04/30 19:46:59] [error] [input:docker_events:docker_events.0] read returned error: 0, Success
[2021/04/30 19:46:59] [error] [input:docker_events:docker_events.0] read returned error: 0, Success
[2021/04/30 19:46:59] [error] [input:docker_events:docker_events.0] read returned error: 0, Success
[2021/04/30 19:46:59] [error] [input:docker_events:docker_events.0] read returned error: 0, Success
[2021/04/30 19:46:59] [error] [input:docker_events:docker_events.0] read returned error: 0, Success
[2021/04/30 19:46:59] [error] [input:docker_events:docker_events.0] read returned error: 0, Success
[2021/04/30 19:46:59] [error] [input:docker_events:docker_events.0] read returned error: 0, Success
[2021/04/30 19:46:59] [error] [input:docker_events:docker_events.0] read returned error: 0, Success
[2021/04/30 19:46:59] [error] [input:docker_events:docker_events.0] read returned error: 0, Success
[2021/04/30 19:46:59] [error] [input:docker_events:docker_events.0] read returned error: 0, Success
[2021/04/30 19:46:59] [error] [input:docker_events:docker_events.0] read returned error: 0, Success
[2021/04/30 19:46:59] [error] [input:docker_events:docker_events.0] read returned error: 0, Success
[2021/04/30 19:46:59] [error] [input:docker_events:docker_events.0] read returned error: 0, Success
[2021/04/30 19:46:59] [error] [input:docker_events:docker_events.0] read returned error: 0, Success
[2021/04/30 19:46:59] [error] [input:docker_events:docker_events.0] read returned error: 0, Success
[2021/04/30 19:46:59] [error] [input:docker_events:docker_events.0] read returned error: 0, Success
[2021/04/30 19:46:59] [error] [input:docker_events:docker_events.0] read returned error: 0, Success
[2021/04/30 19:46:59] [error] [input:docker_events:docker_events.0] read returned error: 0, Success
[2021/04/30 19:46:59] [error] [input:docker_events:docker_events.0] read returned error: 0, Success
[2021/04/30 19:46:59] [error] [input:docker_events:docker_events.0] read returned error: 0, Success
[2021/04/30 19:46:59] [error] [input:docker_events:docker_events.0] read returned error: 0, Success
[2021/04/30 19:46:59] [error] [input:docker_events:docker_events.0] read returned error: 0, Success
[2021/04/30 19:46:59] [error] [input:docker_events:docker_events.0] read returned error: 0, Success
[2021/04/30 19:46:59] [error] [input:docker_events:docker_events.0] read returned error: 0, Success
[2021/04/30 19:46:59] [error] [input:docker_events:docker_events.0] read returned error: 0, Success
[2021/04/30 19:46:59] [error] [input:docker_events:docker_events.0] read returned error: 0, Success
[2021/04/30 19:46:59] [error] [input:docker_events:docker_events.0] read returned error: 0, Success
[2021/04/30 19:46:59] [error] [input:docker_events:docker_events.0] read returned error: 0, Success
[2021/04/30 19:46:59] [error] [input:docker_events:docker_events.0] read returned error: 0, Success
[2021/04/30 19:46:59] [error] [input:docker_events:docker_events.0] read returned error: 0, Success
[2021/04/30 19:46:59] [error] [input:docker_events:docker_events.0] read returned error: 0, Success
[2021/04/30 19:46:59] [error] [input:docker_events:docker_events.0] read returned error: 0, Success
[2021/04/30 19:46:59] [error] [input:docker_events:docker_events.0] read returned error: 0, Success
[2021/04/30 19:46:59] [error] [input:docker_events:docker_events.0] read returned error: 0, Success
[2021/04/30 19:46:59] [error] [input:docker_events:docker_events.0] read returned error: 0, Success
[2021/04/30 19:46:59] [error] [input:docker_events:docker_events.0] read returned error: 0, Success
[2021/04/30 19:46:59] [error] [input:docker_events:docker_events.0] read returned error: 0, Success
[2021/04/30 19:46:59] [error] [input:docker_events:docker_events.0] read returned error: 0, Success
[2021/04/30 19:46:59] [error] [input:docker_events:docker_events.0] read returned error: 0, Success
[2021/04/30 19:46:59] [error] [input:docker_events:docker_events.0] read returned error: 0, Success
[2021/04/30 19:46:59] [error] [input:docker_events:docker_events.0] read returned error: 0, Success
[2021/04/30 19:46:59] [error] [input:docker_events:docker_events.0] read returned error: 0, Success
```

Sometimes the error no can be different:
```
 [error] [input:docker_events:INPUT_dockerevents] read returned error: 25, Inappropriate ioctl for device    
```

**Steps to reproduce the problem**

At one terminal start fluentbit with docker_events input plugin:
```
fluent-bit -i docker_events -o stdout
```

At another terminal restart docker daemon:
```
sudo systemctl restart docker
```
Then there will be huge amounts of error messages as shown above.

**Expected behavior**
- During docker daemon restart, there shouldn't be flooding of error messages. I have seen hundreds if not thousands of error messages in one second.
- After docker daemon successfully restarted, the docker_events input plugin should be able to reconnect to docker.sock.

**Your Environment**
* Version used: Fluent Bit v1.7.4
* Operating System and version: 18.04.5 LTS (Bionic Beaver)

**Additional context**

The error comes from: 
https://github.com/fluent/fluent-bit/blob/master/plugins/in_docker_events/docker_events.c

I have tried to add a work-around (in case of read error, recreate a new fd and connect it to docker.sock), but then the scheduling seems broken, in_de_collect is never called back after error happened. It doesn't help neither to call flb_input_set_collector_event().

Our environment is quite resource-consuming, which leads to docker daemon not responsive at sometimes. It's critical for us to have the docker_events input plugin be able to recover a docker daemon restart. 

Any advice is welcome.

### PR DESCRIPTION
**Pull request by nokute78**
Fixes #3439 

This patch is 
- Add new api `flb_input_collector_delete`
   -  It is to delete specific collector event from plugin instance.
- Re-initialize docker socket and collector event when dockerd is restarted

----
Enter `[N/A]` in the box, if an item is not applicable to your change.

**Testing**
Before we can approve your change; please submit the following in a comment:
- [X] Example configuration file for the change
- [X] Debug log output from testing the change

- [X] Attached [Valgrind](https://valgrind.org/docs/manual/quick-start.html) output that shows no leaks or memory corruption was found

**Documentation**

- [N/A] Documentation required for this feature

## Example configuration

```
[INPUT]
    Name docker_events

[OUTPUT]
    Name stdout
```

## Debug log

1. Exec fluent-bit `sudo fluent-bit -c a.conf`
2. Restart docker `sudo systemctl restart docker`
3. Docker run. e.g. `sudo docker run -it --rm ubuntu`

```
$ sudo ../bin/fluent-bit -c a.conf 
[sudo] password for taka: 
Fluent Bit v1.8.0
* Copyright (C) 2019-2021 The Fluent Bit Authors
* Copyright (C) 2015-2018 Treasure Data
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io

[2021/05/01 14:16:08] [ info] [engine] started (pid=54300)
[2021/05/01 14:16:08] [ info] [storage] version=1.1.1, initializing...
[2021/05/01 14:16:08] [ info] [storage] in-memory
[2021/05/01 14:16:08] [ info] [storage] normal synchronization mode, checksum disabled, max_chunks_up=128
[2021/05/01 14:16:08] [ info] [input:docker_events:docker_events.0] listening for events on /var/run/docker.sock
[2021/05/01 14:16:08] [ info] [sp] stream processor started
[2021/05/01 14:17:15] [ info] [input:docker_events:docker_events.0] EOF detected. Re-initialize
[0] docker_events.0: [1619846285.408147542, {"message"=>"{"status":"create","id":"3073fe3e9cf2fe9946abceefcf0e299a0d3edc6d42f18c51ed700b501aa93407","from":"ubuntu","Type":"container","Action":"create","Actor":{"ID":"3073fe3e9cf2fe9946abceefcf0e299a0d3edc6d42f18c51ed700b501aa93407","Attributes":{"image":"ubuntu","name":"vigorous_agnesi"}},"scope":"local","time":1619846285,"timeNano":1619846285407895145}
"}]
[1] docker_events.0: [1619846285.409072590, {"message"=>"{"status":"attach","id":"3073fe3e9cf2fe9946abceefcf0e299a0d3edc6d42f18c51ed700b501aa93407","from":"ubuntu","Type":"container","Action":"attach","Actor":{"ID":"3073fe3e9cf2fe9946abceefcf0e299a0d3edc6d42f18c51ed700b501aa93407","Attributes":{"image":"ubuntu","name":"vigorous_agnesi"}},"scope":"local","time":1619846285,"timeNano":1619846285408974871}
"}]
[2] docker_events.0: [1619846285.492730679, {"message"=>"{"Type":"network","Action":"connect","Actor":{"ID":"2dac3f973aa4f6f917ad48eea6e768111888b3e4df68a90c868f278cfc6ae3f5","Attributes":{"container":"3073fe3e9cf2fe9946abceefcf0e299a0d3edc6d42f18c51ed700b501aa93407","name":"bridge","type":"bridge"}},"scope":"local","time":1619846285,"timeNano":1619846285492314514}
"}]
[3] docker_events.0: [1619846285.904044998, {"message"=>"{"status":"start","id":"3073fe3e9cf2fe9946abceefcf0e299a0d3edc6d42f18c51ed700b501aa93407","from":"ubuntu","Type":"container","Action":"start","Actor":{"ID":"3073fe3e9cf2fe9946abceefcf0e299a0d3edc6d42f18c51ed700b501aa93407","Attributes":{"image":"ubuntu","name":"vigorous_agnesi"}},"scope":"local","time":1619846285,"timeNano":1619846285903525922}
"}]
[4] docker_events.0: [1619846285.906679025, {"message"=>"{"status":"resize","id":"3073fe3e9cf2fe9946abceefcf0e299a0d3edc6d42f18c51ed700b501aa93407","from":"ubuntu","Type":"container","Action":"resize","Actor":{"ID":"3073fe3e9cf2fe9946abceefcf0e299a0d3edc6d42f18c51ed700b501aa93407","Attributes":{"height":"23","image":"ubuntu","name":"vigorous_agnesi","width":"79"}},"scope":"local","time":1619846285,"timeNano":1619846285906205732}
"}]
```

## Valgrind output

```
$ sudo valgrind ../bin/fluent-bit -c a.conf 
==54639== Memcheck, a memory error detector
==54639== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==54639== Using Valgrind-3.15.0 and LibVEX; rerun with -h for copyright info
==54639== Command: ../bin/fluent-bit -c a.conf
==54639== 
Fluent Bit v1.8.0
* Copyright (C) 2019-2021 The Fluent Bit Authors
* Copyright (C) 2015-2018 Treasure Data
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io

[2021/05/01 14:19:16] [ info] [engine] started (pid=54639)
[2021/05/01 14:19:16] [ info] [storage] version=1.1.1, initializing...
[2021/05/01 14:19:16] [ info] [storage] in-memory
[2021/05/01 14:19:16] [ info] [storage] normal synchronization mode, checksum disabled, max_chunks_up=128
[2021/05/01 14:19:16] [ info] [input:docker_events:docker_events.0] listening for events on /var/run/docker.sock
[2021/05/01 14:19:16] [ info] [sp] stream processor started
[2021/05/01 14:19:19] [ info] [input:docker_events:docker_events.0] EOF detected. Re-initialize
==54639== Warning: client switching stacks?  SP change: 0x57e48b8 --> 0x4c88be0
==54639==          to suppress, use: --max-stackframe=11910360 or greater
==54639== Warning: client switching stacks?  SP change: 0x4c88b58 --> 0x57e48b8
==54639==          to suppress, use: --max-stackframe=11910496 or greater
==54639== Warning: client switching stacks?  SP change: 0x57e48b8 --> 0x4c88b58
==54639==          to suppress, use: --max-stackframe=11910496 or greater
==54639==          further instances of this message will not be shown.
[0] docker_events.0: [1619846362.018934707, {"message"=>"{"status":"create","id":"8cfc888175821f91691c6f9b8afba19a679fb7fe9630bb602c066e181e14f762","from":"ubuntu","Type":"container","Action":"create","Actor":{"ID":"8cfc888175821f91691c6f9b8afba19a679fb7fe9630bb602c066e181e14f762","Attributes":{"image":"ubuntu","name":"strange_proskuriakova"}},"scope":"local","time":1619846362,"timeNano":1619846362013127638}
"}]
[1] docker_events.0: [1619846362.129677329, {"message"=>"{"status":"attach","id":"8cfc888175821f91691c6f9b8afba19a679fb7fe9630bb602c066e181e14f762","from":"ubuntu","Type":"container","Action":"attach","Actor":{"ID":"8cfc888175821f91691c6f9b8afba19a679fb7fe9630bb602c066e181e14f762","Attributes":{"image":"ubuntu","name":"strange_proskuriakova"}},"scope":"local","time":1619846362,"timeNano":1619846362029205169}
{"Type":"network","Action":"connect","Actor":{"ID":"f8b3b92be36d36a843b11cb89c03b6881a19da226f3ac25622c998509c8305b2","Attributes":{"container":"8cfc888175821f91691c6f9b8afba19a679fb7fe9630bb602c066e181e14f762","name":"bridge","type":"bridge"}},"scope":"local","time":1619846362,"timeNano":1619846362114320257}
"}]
[2] docker_events.0: [1619846362.759425227, {"message"=>"{"status":"start","id":"8cfc888175821f91691c6f9b8afba19a679fb7fe9630bb602c066e181e14f762","from":"ubuntu","Type":"container","Action":"start","Actor":{"ID":"8cfc888175821f91691c6f9b8afba19a679fb7fe9630bb602c066e181e14f762","Attributes":{"image":"ubuntu","name":"strange_proskuriakova"}},"scope":"local","time":1619846362,"timeNano":1619846362759094459}
"}]
[3] docker_events.0: [1619846362.762086460, {"message"=>"{"status":"resize","id":"8cfc888175821f91691c6f9b8afba19a679fb7fe9630bb602c066e181e14f762","from":"ubuntu","Type":"container","Action":"resize","Actor":{"ID":"8cfc888175821f91691c6f9b8afba19a679fb7fe9630bb602c066e181e14f762","Attributes":{"height":"23","image":"ubuntu","name":"strange_proskuriakova","width":"79"}},"scope":"local","time":1619846362,"timeNano":1619846362761838688}
"}]
^C[2021/05/01 14:19:26] [engine] caught signal (SIGINT)
[2021/05/01 14:19:26] [ warn] [engine] service will stop in 5 seconds
[2021/05/01 14:19:31] [ info] [engine] service stopped
==54639== 
==54639== HEAP SUMMARY:
==54639==     in use at exit: 0 bytes in 0 blocks
==54639==   total heap usage: 318 allocs, 318 frees, 808,218 bytes allocated
==54639== 
==54639== All heap blocks were freed -- no leaks are possible
==54639== 
==54639== For lists of detected and suppressed errors, rerun with: -s
==54639== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
```

----

Fluent Bit is licensed under Apache 2.0, by submitting this pull request I understand that this code will be released under the terms of that license.

### CODE REVIEW

File: plugins/in_docker_events/docker_events.c [hunk 1]
```diff
@@ -153,6 +155,39 @@ static int in_de_collect(struct flb_input_instance *ins,
...
+        flb_plg_info(ctx->ins, "EOF detected. Re-initialize");
+        /* remove old socket collector */
+        ret = flb_input_collector_delete(ctx->coll_id, ins);
+        close(ctx->fd);
+        if (ret < 0) {
+            flb_plg_error(ctx->ins, "failed to pause event");
+            return -1;
+        }
+        ctx->fd = -1;
+        /* create socket again */
```
Comment (MengmengZHANG) [inline plugins/in_docker_events/docker_events.c:170]: Hi @nokute78 ,

Thanks so much for proposing this fix. 
I have tried to play with your PR in my machine, however I have seen this error after rebooting docker daemon. 
Seems the first retry failed and it never re-try again.
I have encountered similar issues when trying different workarounds on my side, not sure how to resolve this.

```
~/nokute78/fluent-bit/build$ sudo bin/fluent-bit -i docker_events -o stdout
Fluent Bit v1.8.0
* Copyright (C) 2019-2021 The Fluent Bit Authors
* Copyright (C) 2015-2018 Treasure Data
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io

[2021/05/03 17:17:15] [ info] [engine] started (pid=3592)
[2021/05/03 17:17:15] [ info] [storage] version=1.1.1, initializing...
[2021/05/03 17:17:15] [ info] [storage] in-memory
[2021/05/03 17:17:15] [ info] [storage] normal synchronization mode, checksum disabled, max_chunks_up=128
[2021/05/03 17:17:15] [ info] [input:docker_events:docker_events.0] listening for events on /var/run/docker.sock
[2021/05/03 17:17:15] [ info] [sp] stream processor started
[2021/05/03 17:17:24] [ info] [input:docker_events:docker_events.0] EOF detected. Re-initialize
[2021/05/03 17:17:24] [error] [plugins/in_docker_events/docker_events.c:71 errno=104] Connection reset by peer
[2021/05/03 17:17:24] [ info] [input:docker_events:docker_events.0] EOF detected. Re-initialize
[2021/05/03 17:17:24] [error] [plugins/in_docker_events/docker_events.c:59 errno=111] Connection refused
[2021/05/03 17:17:24] [error] [input:docker_events:docker_events.0] failed to re-initialize socket
```

File: plugins/in_docker_events/docker_events.c [hunk 2]
```diff
@@ -153,6 +155,39 @@ static int in_de_collect(struct flb_input_instance *ins,
             }
         }
     }
+    else if (ret == 0) {
```
Comment (MengmengZHANG) [inline plugins/in_docker_events/docker_events.c:158]: Could we also add the case for ret == 25?
When using the fluentbit inside a container, the error will be 25 instead of 0:
```
[2021/05/03 17:42:17] [error] [input:docker_events:docker_events.0] read returned error: 25, Inappropriate ioctl for device
```
I have updated the issue description https://github.com/fluent/fluent-bit/issues/3439 to include this error and how to reproduce:

File: plugins/in_docker_events/docker_events.c (hunk 1 above)
Comment (nokute78) [reply plugins/in_docker_events/docker_events.c:170]: Could you check docker/systemd logs ?

> [plugins/in_docker_events/docker_events.c:71 errno=104] Connection reset by peer

This means destination resets the connection. (e.g. docker or linux kernel)

FYI, Apparmor causes this errno in this case.
https://github.com/moby/moby/issues/14504

Comment (MengmengZHANG) [reply plugins/in_docker_events/docker_events.c:170]: Thanks @nokute78  for the hint, I didn't see any errors in the dockerd logs though.

~/nokute78/fluent-bit/build$ sudo bin/fluent-bit -i docker_events -o stdout
```
Fluent Bit v1.8.0
* Copyright (C) 2019-2021 The Fluent Bit Authors
* Copyright (C) 2015-2018 Treasure Data
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io

[2021/05/03 23:24:44] [ info] [engine] started (pid=10336)
[2021/05/03 23:24:44] [ info] [storage] version=1.1.1, initializing...
[2021/05/03 23:24:44] [ info] [storage] in-memory
[2021/05/03 23:24:44] [ info] [storage] normal synchronization mode, checksum disabled, max_chunks_up=128
[2021/05/03 23:24:44] [ info] [input:docker_events:docker_events.0] listening for events on /var/run/docker.sock
[2021/05/03 23:24:44] [ info] [sp] stream processor started
[2021/05/03 23:25:08] [ info] [input:docker_events:docker_events.0] EOF detected. Re-initialize
[2021/05/03 23:25:08] [error] [plugins/in_docker_events/docker_events.c:71 errno=104] Connection reset by peer
[2021/05/03 23:25:08] [ info] [input:docker_events:docker_events.0] EOF detected. Re-initialize
[2021/05/03 23:25:08] [error] [plugins/in_docker_events/docker_events.c:59 errno=111] Connection refused
[2021/05/03 23:25:08] [error] [input:docker_events:docker_events.0] failed to re-initialize socket
```
~/nokute78/fluent-bit/build$ systemctl status docker
```
● docker.service - Docker Application Container Engine
   Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
  Drop-In: /etc/systemd/system/docker.service.d
           └─override.conf
   Active: active (running) since Mon 2021-05-03 23:25:10 UTC; 7s ago
     Docs: https://docs.docker.com
  Process: 10591 ExecStartPre=/bin/sh -c  cd /datadrive   (code=exited, status=0/SUCCESS)
 Main PID: 10594 (dockerd)
    Tasks: 26
   CGroup: /system.slice/docker.service
           └─10594 /usr/bin/dockerd -H fd:// --containerd /var/run/containerd/containerd.sock

May 03 23:25:09 c22f0b9ef342 dockerd[10594]: time="2021-05-03T23:25:09.334860190Z" level=warning msg="Your kernel does not support cgroup blkio weight"
May 03 23:25:09 c22f0b9ef342 dockerd[10594]: time="2021-05-03T23:25:09.334867790Z" level=warning msg="Your kernel does not support cgroup blkio weight_device"
May 03 23:25:09 c22f0b9ef342 dockerd[10594]: time="2021-05-03T23:25:09.335061591Z" level=info msg="Loading containers: start."
May 03 23:25:10 c22f0b9ef342 dockerd[10594]: fluent#New: AsyncConnect is now deprecated, please use Async insteadfluent#New: AsyncConnect is now deprecated, please use Async insteadfluent#New: AsyncConnect is now deprecated, please use Async insteadtime="2021-05-03T23:25:10.163716322Z" level=info msg="Ther
May 03 23:25:10 c22f0b9ef342 dockerd[10594]: time="2021-05-03T23:25:10.207732489Z" level=info msg="Loading containers: done."
May 03 23:25:10 c22f0b9ef342 dockerd[10594]: time="2021-05-03T23:25:10.411914628Z" level=warning msg="Not using native diff for overlay2, this may cause degraded performance for building images: kernel has CONFIG_OVERLAY_FS_REDIRECT_DIR enabled" storage-driver=overlay2
May 03 23:25:10 c22f0b9ef342 dockerd[10594]: time="2021-05-03T23:25:10.412652133Z" level=info msg="Docker daemon" commit=8728dd246c3ab53105434eef8ffe997b6fd14dc6 graphdriver(s)=overlay2 version=20.10.6+azure
May 03 23:25:10 c22f0b9ef342 dockerd[10594]: time="2021-05-03T23:25:10.412991435Z" level=info msg="Daemon has completed initialization"
May 03 23:25:10 c22f0b9ef342 systemd[1]: Started Docker Application Container Engine.
May 03 23:25:10 c22f0b9ef342 dockerd[10594]: time="2021-05-03T23:25:10.457327504Z" level=info msg="API listen on /var/run/docker.sock"
```

~/nokute78/fluent-bit/build$ journalctl -u docker.service
```
journalctl -u docker.service
-- Logs begin at Mon 2021-05-03 23:21:54 UTC, end at Mon 2021-05-03 23:25:35 UTC. --
May 03 23:25:08 c22f0b9ef342 systemd[1]: Stopping Docker Application Container Engine...
May 03 23:25:08 c22f0b9ef342 dockerd[5305]: time="2021-05-03T23:25:08.899503647Z" level=info msg="Processing signal 'terminated'"
May 03 23:25:08 c22f0b9ef342 dockerd[5305]: time="2021-05-03T23:25:08.905368783Z" level=info msg="Daemon shutdown complete"
May 03 23:25:08 c22f0b9ef342 dockerd[5305]: time="2021-05-03T23:25:08.905514284Z" level=info msg="stopping event stream following graceful shutdown" error="context canceled" module=libcontainerd namespace=plugins.moby
May 03 23:25:08 c22f0b9ef342 systemd[1]: Stopped Docker Application Container Engine.
May 03 23:25:08 c22f0b9ef342 systemd[1]: Starting Docker Application Container Engine...
May 03 23:25:09 c22f0b9ef342 dockerd[10594]: time="2021-05-03T23:25:09.021033485Z" level=info msg="Starting up"
May 03 23:25:09 c22f0b9ef342 dockerd[10594]: time="2021-05-03T23:25:09.023844002Z" level=info msg="detected 127.0.0.53 nameserver, assuming systemd-resolved, so using resolv.conf: /run/systemd/resolve/resolv.conf"
May 03 23:25:09 c22f0b9ef342 dockerd[10594]: time="2021-05-03T23:25:09.032957858Z" level=info msg="parsed scheme: \"unix\"" module=grpc
May 03 23:25:09 c22f0b9ef342 dockerd[10594]: time="2021-05-03T23:25:09.032998058Z" level=info msg="scheme \"unix\" not registered, fallback to default scheme" module=grpc
May 03 23:25:09 c22f0b9ef342 dockerd[10594]: time="2021-05-03T23:25:09.033043058Z" level=info msg="ccResolverWrapper: sending update to cc: {[{unix:///var/run/containerd/containerd.sock  <nil> 0 <nil>}] <nil> <nil>}" module=grpc
May 03 23:25:09 c22f0b9ef342 dockerd[10594]: time="2021-05-03T23:25:09.033062258Z" level=info msg="ClientConn switching balancer to \"pick_first\"" module=grpc
May 03 23:25:09 c22f0b9ef342 dockerd[10594]: time="2021-05-03T23:25:09.034334066Z" level=info msg="parsed scheme: \"unix\"" module=grpc
May 03 23:25:09 c22f0b9ef342 dockerd[10594]: time="2021-05-03T23:25:09.034361266Z" level=info msg="scheme \"unix\" not registered, fallback to default scheme" module=grpc
May 03 23:25:09 c22f0b9ef342 dockerd[10594]: time="2021-05-03T23:25:09.034382166Z" level=info msg="ccResolverWrapper: sending update to cc: {[{unix:///var/run/containerd/containerd.sock  <nil> 0 <nil>}] <nil> <nil>}" module=grpc
May 03 23:25:09 c22f0b9ef342 dockerd[10594]: time="2021-05-03T23:25:09.034402466Z" level=info msg="ClientConn switching balancer to \"pick_first\"" module=grpc
May 03 23:25:09 c22f0b9ef342 dockerd[10594]: time="2021-05-03T23:25:09.334826690Z" level=warning msg="Your kernel does not support CPU realtime scheduler"
May 03 23:25:09 c22f0b9ef342 dockerd[10594]: time="2021-05-03T23:25:09.334860190Z" level=warning msg="Your kernel does not support cgroup blkio weight"
May 03 23:25:09 c22f0b9ef342 dockerd[10594]: time="2021-05-03T23:25:09.334867790Z" level=warning msg="Your kernel does not support cgroup blkio weight_device"
May 03 23:25:09 c22f0b9ef342 dockerd[10594]: time="2021-05-03T23:25:09.335061591Z" level=info msg="Loading containers: start."
May 03 23:25:10 c22f0b9ef342 dockerd[10594]: fluent#New: AsyncConnect is now deprecated, please use Async insteadfluent#New: AsyncConnect is now deprecated, please use Async insteadfluent#New: AsyncConnect is now deprecated, please use Async insteadtime="2021-05-03T23:25:10.163716322Z" level=info msg="Ther
May 03 23:25:10 c22f0b9ef342 dockerd[10594]: time="2021-05-03T23:25:10.207732489Z" level=info msg="Loading containers: done."
May 03 23:25:10 c22f0b9ef342 dockerd[10594]: time="2021-05-03T23:25:10.411914628Z" level=warning msg="Not using native diff for overlay2, this may cause degraded performance for building images: kernel has CONFIG_OVERLAY_FS_REDIRECT_DIR enabled" storage-driver=overlay2
May 03 23:25:10 c22f0b9ef342 dockerd[10594]: time="2021-05-03T23:25:10.412652133Z" level=info msg="Docker daemon" commit=8728dd246c3ab53105434eef8ffe997b6fd14dc6 graphdriver(s)=overlay2 version=20.10.6+azure
May 03 23:25:10 c22f0b9ef342 dockerd[10594]: time="2021-05-03T23:25:10.412991435Z" level=info msg="Daemon has completed initialization"
May 03 23:25:10 c22f0b9ef342 systemd[1]: Started Docker Application Container Engine.
May 03 23:25:10 c22f0b9ef342 dockerd[10594]: time="2021-05-03T23:25:10.457327504Z" level=info msg="API listen on /var/run/docker.sock"
```

Comment (nokute78) [reply plugins/in_docker_events/docker_events.c:170]: Thank you for quick response. 
Hmm...

1.  can you share `dmesg` ?
2. Is there any logs before restarting at `/var/log` ?

`systemctl` and `journalctl` logs seems to be logs after restarting docker.
In my environment, `/var/log/syslog` is it.

```
May  4 08:42:27 locals dockerd[14165]: time="2021-05-04T08:42:27.266660436+09:00" level=info msg="Processing signal 'terminated'"
May  4 08:42:27 locals dockerd[14165]: time="2021-05-04T08:42:27.268357743+09:00" level=info msg="Daemon shutdown complete"
May  4 08:42:27 locals systemd[1]: Stopping Docker Application Container Engine...
May  4 08:42:27 locals systemd[1]: docker.service: Succeeded.
May  4 08:42:27 locals systemd[1]: Stopped Docker Application Container Engine.
May  4 08:42:27 locals systemd[1]: Starting Docker Application Container Engine...
May  4 08:42:27 locals dockerd[14804]: time="2021-05-04T08:42:27.342604910+09:00" level=info msg="Starting up"
May  4 08:42:27 locals dockerd[14804]: time="2021-05-04T08:42:27.344636256+09:00" level=info msg="detected 127.0.0.53 nameserver, assuming systemd-resolved, so using resolv.conf: /run/systemd/resolve/resolv.conf"
```

Comment (MengmengZHANG) [reply plugins/in_docker_events/docker_events.c:170]: This is the dmesg output, will check in syslog.
[dmesg.txt](https://github.com/fluent/fluent-bit/files/6418409/dmesg.txt)

Comment (MengmengZHANG) [reply plugins/in_docker_events/docker_events.c:170]: This is the syslog:
```
May  3 23:25:08 c22f0b9ef342 systemd[1]: Stopping Docker Application Container Engine...
May  3 23:25:08 c22f0b9ef342 dockerd[5305]: time="2021-05-03T23:25:08.899503647Z" level=info msg="Processing signal 'terminated'"
May  3 23:25:08 c22f0b9ef342 dockerd[5305]: time="2021-05-03T23:25:08.905368783Z" level=info msg="Daemon shutdown complete"
May  3 23:25:08 c22f0b9ef342 dockerd[5305]: time="2021-05-03T23:25:08.905514284Z" level=info msg="stopping event stream following graceful shutdown" error="context canceled" module=libcontainerd namespace=plugins.moby
May  3 23:25:08 c22f0b9ef342 systemd[1]: Stopped Docker Application Container Engine.
May  3 23:25:08 c22f0b9ef342 systemd[1]: Closed Docker Socket for the API.
May  3 23:25:08 c22f0b9ef342 systemd[1]: Stopping Docker Socket for the API.
May  3 23:25:08 c22f0b9ef342 systemd[1]: Starting Docker Socket for the API.
May  3 23:25:08 c22f0b9ef342 systemd[1]: Listening on Docker Socket for the API.
May  3 23:25:08 c22f0b9ef342 systemd[1]: Starting Docker Application Container Engine...
May  3 23:25:09 c22f0b9ef342 dockerd[10594]: time="2021-05-03T23:25:09.021033485Z" level=info msg="Starting up"
May  3 23:25:09 c22f0b9ef342 dockerd[10594]: time="2021-05-03T23:25:09.023844002Z" level=info msg="detected 127.0.0.53 nameserver, assuming systemd-resolved, so using resolv.conf: /run/systemd/resolve/resolv.conf"
May  3 23:25:09 c22f0b9ef342 dockerd[10594]: time="2021-05-03T23:25:09.032957858Z" level=info msg="parsed scheme: \"unix\"" module=grpc
May  3 23:25:09 c22f0b9ef342 dockerd[10594]: time="2021-05-03T23:25:09.032998058Z" level=info msg="scheme \"unix\" not registered, fallback to default scheme" module=grpc
May  3 23:25:09 c22f0b9ef342 dockerd[10594]: time="2021-05-03T23:25:09.033043058Z" level=info msg="ccResolverWrapper: sending update to cc: {[{unix:///var/run/containerd/containerd.sock  <nil> 0 <nil>}] <nil> <nil>}" module=grpc
May  3 23:25:09 c22f0b9ef342 dockerd[10594]: time="2021-05-03T23:25:09.033062258Z" level=info msg="ClientConn switching balancer to \"pick_first\"" module=grpc
May  3 23:25:09 c22f0b9ef342 dockerd[10594]: time="2021-05-03T23:25:09.034334066Z" level=info msg="parsed scheme: \"unix\"" module=grpc
May  3 23:25:09 c22f0b9ef342 dockerd[10594]: time="2021-05-03T23:25:09.034361266Z" level=info msg="scheme \"unix\" not registered, fallback to default scheme" module=grpc
May  3 23:25:09 c22f0b9ef342 dockerd[10594]: time="2021-05-03T23:25:09.034382166Z" level=info msg="ccResolverWrapper: sending update to cc: {[{unix:///var/run/containerd/containerd.sock  <nil> 0 <nil>}] <nil> <nil>}" module=grpc
May  3 23:25:09 c22f0b9ef342 dockerd[10594]: time="2021-05-03T23:25:09.034402466Z" level=info msg="ClientConn switching balancer to \"pick_first\"" module=grpc
May  3 23:25:09 c22f0b9ef342 dockerd[10594]: time="2021-05-03T23:25:09.334826690Z" level=warning msg="Your kernel does not support CPU realtime scheduler"
May  3 23:25:09 c22f0b9ef342 dockerd[10594]: time="2021-05-03T23:25:09.334860190Z" level=warning msg="Your kernel does not support cgroup blkio weight"
May  3 23:25:09 c22f0b9ef342 dockerd[10594]: time="2021-05-03T23:25:09.334867790Z" level=warning msg="Your kernel does not support cgroup blkio weight_device"
May  3 23:25:09 c22f0b9ef342 dockerd[10594]: time="2021-05-03T23:25:09.335061591Z" level=info msg="Loading containers: start."
May  3 23:25:10 c22f0b9ef342 dockerd[10594]: fluent#New: AsyncConnect is now deprecated, please use Async insteadfluent#New: AsyncConnect is now deprecated, please use Async insteadfluent#New: AsyncConnect is now deprecated, please use Async insteadtime="2021-05-03T23:25:10.163716322Z" level=info msg="There are old running containers, the network config will not take affect"
May  3 23:25:10 c22f0b9ef342 dockerd[10594]: time="2021-05-03T23:25:10.207732489Z" level=info msg="Loading containers: done."
May  3 23:25:10 c22f0b9ef342 dockerd[10594]: time="2021-05-03T23:25:10.411914628Z" level=warning msg="Not using native diff for overlay2, this may cause degraded performance for building images: kernel has CONFIG_OVERLAY_FS_REDIRECT_DIR enabled" storage-driver=overlay2
May  3 23:25:10 c22f0b9ef342 dockerd[10594]: time="2021-05-03T23:25:10.412652133Z" level=info msg="Docker daemon" commit=8728dd246c3ab53105434eef8ffe997b6fd14dc6 graphdriver(s)=overlay2 version=20.10.6+azure
May  3 23:25:10 c22f0b9ef342 dockerd[10594]: time="2021-05-03T23:25:10.412991435Z" level=info msg="Daemon has completed initialization"
May  3 23:25:10 c22f0b9ef342 systemd[1]: Started Docker Application Container Engine.
May  3 23:25:10 c22f0b9ef342 dockerd[10594]: time="2021-05-03T23:25:10.457327504Z" level=info msg="API listen on /var/run/docker.sock"
```

**Comment by nokute78** [comment]
I committed patch to add 2 options.

|Name|Description|Default|
|------|-------------|--------|
|reconnect.retry_limits| The maximum number of retries allowed. | 5 |
|reconnect.retry_interval| The retrying interval (sec) | 1 |

Default: 1s x 5 = 5sec.( Try to reconnect every second.)

I tested 
```
sudo systemctl stop docker
```
and
```
sudo systemctl restart docker
```
(Each commands may need to be executed several times)

## Valgrind output 
```
$ sudo valgrind ../bin/fluent-bit -c a.conf  -vvv
==23736== Memcheck, a memory error detector
==23736== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==23736== Using Valgrind-3.15.0 and LibVEX; rerun with -h for copyright info
==23736== Command: ../bin/fluent-bit -c a.conf -vvv
==23736== 
Fluent Bit v1.8.0
* Copyright (C) 2019-2021 The Fluent Bit Authors
* Copyright (C) 2015-2018 Treasure Data
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io

[2021/05/04 16:54:42] [ info] Configuration:
[2021/05/04 16:54:42] [ info]  flush time     | 5.000000 seconds
[2021/05/04 16:54:42] [ info]  grace          | 5 seconds
[2021/05/04 16:54:42] [ info]  daemon         | 0
[2021/05/04 16:54:42] [ info] ___________
[2021/05/04 16:54:42] [ info]  inputs:
[2021/05/04 16:54:42] [ info]      docker_events
[2021/05/04 16:54:42] [ info] ___________
[2021/05/04 16:54:42] [ info]  filters:
[2021/05/04 16:54:42] [ info] ___________
[2021/05/04 16:54:42] [ info]  outputs:
[2021/05/04 16:54:42] [ info]      stdout.0
[2021/05/04 16:54:42] [ info] ___________
[2021/05/04 16:54:42] [ info]  collectors:
[2021/05/04 16:54:42] [ info] [engine] started (pid=23736)
[2021/05/04 16:54:42] [debug] [engine] coroutine stack size: 24576 bytes (24.0K)
[2021/05/04 16:54:42] [debug] [storage] [cio stream] new stream registered: docker_events.0
[2021/05/04 16:54:42] [ info] [storage] version=1.1.1, initializing...
[2021/05/04 16:54:42] [ info] [storage] in-memory
[2021/05/04 16:54:42] [ info] [storage] normal synchronization mode, checksum disabled, max_chunks_up=128
[2021/05/04 16:54:42] [trace] [input:docker_events:docker_events.0 at plugins/in_docker_events/docker_events.c:65] writing to socket GET /events HTTP/1.0


[2021/05/04 16:54:42] [debug] [input:docker_events:docker_events.0] read 182 bytes from socket
[2021/05/04 16:54:42] [ info] [input:docker_events:docker_events.0] listening for events on /var/run/docker.sock
[2021/05/04 16:54:42] [debug] [stdout:stdout.0] created event channels: read=19 write=20
[2021/05/04 16:54:42] [debug] [router] default match rule docker_events.0:stdout.0
[2021/05/04 16:54:42] [ info] [sp] stream processor started
[2021/05/04 16:54:55] [ info] [input:docker_events:docker_events.0] EOF detected. Re-initialize
[2021/05/04 16:54:55] [trace] [input:docker_events:docker_events.0 at plugins/in_docker_events/docker_events.c:65] writing to socket GET /events HTTP/1.0


[2021/05/04 16:54:56] [debug] [input:docker_events:docker_events.0] read 182 bytes from socket
[2021/05/04 16:54:58] [ info] [input:docker_events:docker_events.0] EOF detected. Re-initialize
[2021/05/04 16:54:58] [trace] [input:docker_events:docker_events.0 at plugins/in_docker_events/docker_events.c:65] writing to socket GET /events HTTP/1.0


[2021/05/04 16:54:58] [debug] [input:docker_events:docker_events.0] read 182 bytes from socket
[2021/05/04 16:54:59] [ info] [input:docker_events:docker_events.0] EOF detected. Re-initialize
[2021/05/04 16:54:59] [trace] [input:docker_events:docker_events.0 at plugins/in_docker_events/docker_events.c:65] writing to socket GET /events HTTP/1.0


[2021/05/04 16:54:59] [error] [plugins/in_docker_events/docker_events.c:71 errno=104] Connection reset by peer
[2021/05/04 16:54:59] [debug] [input:docker_events:docker_events.0] read 18446744073709551615 bytes from socket
[2021/05/04 16:54:59] [ info] [input:docker_events:docker_events.0] EOF detected. Re-initialize
[2021/05/04 16:54:59] [error] [plugins/in_docker_events/docker_events.c:59 errno=111] Connection refused
[2021/05/04 16:54:59] [error] [input:docker_events:docker_events.0] failed to re-initialize socket
[2021/05/04 16:54:59] [ info] [input:docker_events:docker_events.0] Retry(1) after 5 seconds.
[2021/05/04 16:55:04] [error] [plugins/in_docker_events/docker_events.c:59 errno=111] Connection refused
[2021/05/04 16:55:04] [error] [input:docker_events:docker_events.0] failed to re-initialize socket
[2021/05/04 16:55:04] [ info] [input:docker_events:docker_events.0] Retry(2) after 5 seconds.
[2021/05/04 16:55:09] [error] [plugins/in_docker_events/docker_events.c:59 errno=111] Connection refused
[2021/05/04 16:55:09] [error] [input:docker_events:docker_events.0] failed to re-initialize socket
[2021/05/04 16:55:09] [ info] [input:docker_events:docker_events.0] Retry(3) after 5 seconds.
[2021/05/04 16:55:14] [error] [plugins/in_docker_events/docker_events.c:59 errno=111] Connection refused
[2021/05/04 16:55:14] [error] [input:docker_events:docker_events.0] failed to re-initialize socket
[2021/05/04 16:55:14] [ info] [input:docker_events:docker_events.0] Retry(4) after 5 seconds.
[2021/05/04 16:55:19] [error] [plugins/in_docker_events/docker_events.c:59 errno=111] Connection refused
[2021/05/04 16:55:19] [error] [input:docker_events:docker_events.0] failed to re-initialize socket
[2021/05/04 16:55:19] [ info] [input:docker_events:docker_events.0] Retry(5) after 5 seconds.
[2021/05/04 16:55:24] [error] [plugins/in_docker_events/docker_events.c:59 errno=111] Connection refused
[2021/05/04 16:55:24] [error] [input:docker_events:docker_events.0] failed to re-initialize socket
[2021/05/04 16:55:24] [ info] [input:docker_events:docker_events.0] Retry(6) after 5 seconds.
[2021/05/04 16:55:29] [error] [plugins/in_docker_events/docker_events.c:59 errno=111] Connection refused
[2021/05/04 16:55:29] [error] [input:docker_events:docker_events.0] failed to re-initialize socket
[2021/05/04 16:55:29] [ info] [input:docker_events:docker_events.0] Retry(7) after 5 seconds.
[2021/05/04 16:55:34] [trace] [input:docker_events:docker_events.0 at plugins/in_docker_events/docker_events.c:65] writing to socket GET /events HTTP/1.0


[2021/05/04 16:55:34] [debug] [input:docker_events:docker_events.0] read 182 bytes from socket
[2021/05/04 16:55:47] [debug] [task] created task=0x4d02280 id=0 OK
==23736== Warning: client switching stacks?  SP change: 0x57e48b8 --> 0x4d086d0
==23736==          to suppress, use: --max-stackframe=11387368 or greater
==23736== Warning: client switching stacks?  SP change: 0x4d08648 --> 0x57e48b8
==23736==          to suppress, use: --max-stackframe=11387504 or greater
==23736== Warning: client switching stacks?  SP change: 0x57e48b8 --> 0x4d08648
==23736==          to suppress, use: --max-stackframe=11387504 or greater
==23736==          further instances of this message will not be shown.
[0] docker_events.0: [1620114943.166891383, {"message"=>"{"status":"create","id":"aa9c59dcd0f74df2fc0f18d66188bd393f0128b18751c2ae453114d9b5ea221e","from":"docker.elastic.co/elasticsearch/elasticsearch:7.11.1","Type":"container","Action":"create","Actor":{"ID":"aa9c59dcd0f74df2fc0f18d66188bd393f0128b18751c2ae453114d9b5ea221e","Attributes":{"image":"docker.elastic.co/elasticsearch/elasticsearch:7.11.1","name":"adoring_germain","org.label-schema.build-date":"2021-02-15T13:44:09.394032Z","org.label-schema.license":"Elastic-License-2.0","org.label-schema.name":"Elasticsearch","org.label-schema.schema-version":"1.0","org.label-schema.url":"https://www.elastic.co/products/elasticsearch","org.label-schema.usage":"https://www.elastic.co/guide/en/elasticsearch/reference/index.html","org.label-schema.vcs-ref":"ff17057114c2199c9c1bbecc727003a907c0db7a","org.label-schema.vcs-url":"https://github.com/elastic/elasticsearch","org.label-schema.vendor":"Elastic","org.label-schema.version":"7.11.1","org.opencontainers.image.created":"2021-02-15T13:44:09.394032Z","org.opencontainers.image.documentation":"https://www.elastic.co/guide/en/elasticsearch/reference/index.html","org.opencontainers.image.licenses":"Elastic-License-2.0","org.opencontainers.image.revision":"ff17057114c2199c9c1bbecc727003a907c0db7a","org.opencontainers.image.source":"https://github.com/elastic/elasticsearch","org.opencontainers.image.title":"Elasticsearch","org.opencontainers.image.url":"https://www.elastic.co/products/elasticsearch","org.opencontainers.image.vendor":"Elastic","org.opencontainers.image.version":"7.11.1"}},"scope":"local","time":1620114943,"timeNano":1620114943162150251}
"}]
[1] docker_events.0: [1620114943.331784988, {"message"=>"{"status":"attach","id":"aa9c59dcd0f74df2fc0f18d66188bd393f0128b18751c2ae453114d9b5ea221e","from":"docker.elastic.co/elasticsearch/elasticsearch:7.11.1","Type":"container","Action":"attach","Actor":{"ID":"aa9c59dcd0f74df2fc0f18d66188bd393f0128b18751c2ae453114d9b5ea221e","Attributes":{"image":"docker.elastic.co/elasticsearch/elasticsearch:7.11.1","name":"adoring_germain","org.label-schema.build-date":"2021-02-15T13:44:09.394032Z","org.label-schema.license":"Elastic-License-2.0","org.label-schema.name":"Elasticsearch","org.label-schema.schema-version":"1.0","org.label-schema.url":"https://www.elastic.co/products/elasticsearch","org.label-schema.usage":"https://www.elastic.co/guide/en/elasticsearch/reference/index.html","org.label-schema.vcs-ref":"ff17057114c2199c9c1bbecc727003a907c0db7a","org.label-schema.vcs-url":"https://github.com/elastic/elasticsearch","org.label-schema.vendor":"Elastic","org.label-schema.version":"7.11.1","org.opencontainers.image.created":"2021-02-15T13:44:09.394032Z","org.opencontainers.image.documentation":"https://www.elastic.co/guide/en/elasticsearch/reference/index.html","org.opencontainers.image.licenses":"Elastic-License-2.0","org.opencontainers.image.revision":"ff17057114c2199c9c1bbecc727003a907c0db7a","org.opencontainers.image.source":"https://github.com/elastic/elasticsearch","org.opencontainers.image.title":"Elasticsearch","org.opencontainers.image.url":"https://www.elastic.co/products/elasticsearch","org.opencontainers.image.vendor":"Elastic","org.opencontainers.image.version":"7.11.1"}},"scope":"local","time":1620114943,"timeNano":1620114943180489736}
"}]
[2] docker_events.0: [1620114943.341128450, {"message"=>"{"Type":"network","Action":"connect","Actor":{"ID":"0a5d502aec14ccf6dd7b1066721cc2af6bb870e90cd3559a969eab79dac2d8f2","Attributes":{"container":"aa9c59dcd0f74df2fc0f18d66188bd393f0128b18751c2ae453114d9b5ea221e","name":"bridge","type":"bridge"}},"scope":"local","time":1620114943,"timeNano":1620114943340664531}
"}]
[3] docker_events.0: [1620114943.579408218, {"message"=>"{"status":"start","id":"aa9c59dcd0f74df2fc0f18d66188bd393f0128b18751c2ae453114d9b5ea221e","from":"docker.elastic.co/elasticsearch/elasticsearch:7.11.1","Type":"container","Action":"start","Actor":{"ID":"aa9c59dcd0f74df2fc0f18d66188bd393f0128b18751c2ae453114d9b5ea221e","Attributes":{"image":"docker.elastic.co/elasticsearch/elasticsearch:7.11.1","name":"adoring_germain","org.label-schema.build-date":"2021-02-15T13:44:09.394032Z","org.label-schema.license":"Elastic-License-2.0","org.label-schema.name":"Elasticsearch","org.label-schema.schema-version":"1.0","org.label-schema.url":"https://www.elastic.co/products/elasticsearch","org.label-schema.usage":"https://www.elastic.co/guide/en/elasticsearch/reference/index.html","org.label-schema.vcs-ref":"ff17057114c2199c9c1bbecc727003a907c0db7a","org.label-schema.vcs-url":"https://github.com/elastic/elasticsearch","org.label-schema.vendor":"Elastic","org.label-schema.version":"7.11.1","org.opencontainers.image.created":"2021-02-15T13:44:09.394032Z","org.opencontainers.image.documentation":"https://www.elastic.co/guide/en/elasticsearch/reference/index.html","org.opencontainers.image.licenses":"Elastic-License-2.0","org.opencontainers.image.revision":"ff17057114c2199c9c1bbecc727003a907c0db7a","org.opencontainers.image.source":"https://github.com/elastic/elasticsearch","org.opencontainers.image.title":"Elasticsearch","org.opencontainers.image.url":"https://www.elastic.co/products/elasticsearch","org.opencontainers.image.vendor":"Elastic","org.opencontainers.image.version":"7.11.1"}},"scope":"local","time":1620114943,"timeNano":1620114943579143296}
"}]
[2021/05/04 16:55:47] [debug] [out coro] cb_destroy coro_id=0
[2021/05/04 16:55:47] [debug] [task] destroy task=0x4d02280 (task_id=0)
^C[2021/05/04 16:55:56] [engine] caught signal (SIGINT)
[2021/05/04 16:55:56] [ warn] [engine] service will stop in 5 seconds
[2021/05/04 16:56:01] [ info] [engine] service stopped
==23736== 
==23736== HEAP SUMMARY:
==23736==     in use at exit: 0 bytes in 0 blocks
==23736==   total heap usage: 433 allocs, 433 frees, 1,546,576 bytes allocated
==23736== 
==23736== All heap blocks were freed -- no leaks are possible
==23736== 
==23736== For lists of detected and suppressed errors, rerun with: -s
==23736== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
```

File: plugins/in_docker_events/docker_events.c (hunk 1 above)
Comment (nokute78) [reply plugins/in_docker_events/docker_events.c]: I sent a patch to fix this `Connection reset by peer` issue.
Please test `reconnect.retry_limits` and `reconnect.retry_interval`.

**Comment by MengmengZHANG** [comment]
Thanks for adding the re-try, it worked!
I have tried with different parameters and it also worked.
```
# docker_events.conf
[SERVICE]
    Flush           5
    Daemon          off
    Log_Level       debug

[INPUT]
    Name docker_events
    Tag  docker_events
    Reconnect.Retry_limits 10
    Reconnect.Retry_interval 2

[OUTPUT]
    Name  stdout
    Match *
```

**Comment by nokute78** [comment]
Thank you for testing.

Is `errno=25` issue resolved?
I can't reproduce it with this procedure.
https://github.com/fluent/fluent-bit/issues/3439#issuecomment-831424674

**Comment by MengmengZHANG** [comment]
> Thank you for testing.
> 
> Is `errno=25` issue resolved?
> I can't reproduce it with this procedure.
> [#3439 (comment)](https://github.com/fluent/fluent-bit/issues/3439#issuecomment-831424674)

Hi @nokute78 ,

I can still see the errno=25 when using fluentbit under a container.
Note enable-live-restore is needed to let container continuing running when docker daemon is down:
https://docs.docker.com/config/containers/live-restore/#enable-live-restore

Here is how I reproduced using your branch:
```
~/nokute78/fluent-bit/dockerfiles$ sudo docker build --no-cache -t fluent/fluent-bit:1.8.1 -f Dockerfile.x86_64 .

boba@c22f0b9ef342:~/nokute78/fluent-bit/dockerfiles$ sudo docker images
REPOSITORY                                                         TAG                                IMAGE ID       CREATED          SIZE
fluent/fluent-bit                                                  1.8.1                              65a6f6782db8   2 minutes ago    78.8MB

sudo docker run -v /var/run:/var/run --name fluent-bit-nokute78 -d fluent/fluent-bit:1.8.1 /fluent-bit/bin/fluent-bit -i docker_events -o stdout -vvv



boba@c22f0b9ef342:~/nokute78/fluent-bit/build$ sudo docker logs -f  fluent-bit-nokute78
Fluent Bit v1.7.1
* Copyright (C) 2019-2021 The Fluent Bit Authors
* Copyright (C) 2015-2018 Treasure Data
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io

[2021/05/04 22:49:05] [ info] Configuration:
[2021/05/04 22:49:05] [ info]  flush time     | 5.000000 seconds
[2021/05/04 22:49:05] [ info]  grace          | 5 seconds
[2021/05/04 22:49:05] [ info]  daemon         | 0
[2021/05/04 22:49:05] [ info] ___________
[2021/05/04 22:49:05] [ info]  inputs:
[2021/05/04 22:49:05] [ info]      docker_events
[2021/05/04 22:49:05] [ info] ___________
[2021/05/04 22:49:05] [ info]  filters:
[2021/05/04 22:49:05] [ info] ___________
[2021/05/04 22:49:05] [ info]  outputs:
[2021/05/04 22:49:05] [ info]      stdout.0
[2021/05/04 22:49:05] [ info] ___________
[2021/05/04 22:49:05] [ info]  collectors:
[2021/05/04 22:49:05] [ info] [engine] started (pid=1)
[2021/05/04 22:49:05] [debug] [engine] coroutine stack size: 24576 bytes (24.0K)
[2021/05/04 22:49:05] [debug] [storage] [cio stream] new stream registered: docker_events.0
[2021/05/04 22:49:05] [ info] [storage] version=1.1.0, initializing...
[2021/05/04 22:49:05] [ info] [storage] in-memory
[2021/05/04 22:49:05] [ info] [storage] normal synchronization mode, checksum disabled, max_chunks_up=128
[2021/05/04 22:49:05] [trace] [input:docker_events:docker_events.0 at plugins/in_docker_events/docker_events.c:65] writing to socket GET /events HTTP/1.0


[2021/05/04 22:49:05] [debug] [input:docker_events:docker_events.0] read 188 bytes from socket
[2021/05/04 22:49:05] [ info] [input:docker_events:docker_events.0] listening for events on /var/run/docker.sock
[2021/05/04 22:49:05] [debug] [stdout:stdout.0] created event channels: read=19 write=20
[2021/05/04 22:49:05] [debug] [router] default match rule docker_events.0:stdout.0
[2021/05/04 22:49:05] [ info] [sp] stream processor started
unexpected EOF

sudo systemctl restart docker

boba@c22f0b9ef342:~/nokute78/fluent-bit/build$ sudo docker logs -f  fluent-bit-nokute78
[2021/05/04 22:49:44] [error] [input:docker_events:docker_events.0] read returned error: 25, Inappropriate ioctl for device
[2021/05/04 22:49:44] [error] [input:docker_events:docker_events.0] read returned error: 25, Inappropriate ioctl for device
[2021/05/04 22:49:44] [error] [input:docker_events:docker_events.0] read returned error: 25, Inappropriate ioctl for device
[2021/05/04 22:49:44] [error] [input:docker_events:docker_events.0] read returned error: 25, Inappropriate ioctl for device
[2021/05/04 22:49:44] [error] [input:docker_events:docker_events.0] read returned error: 25, Inappropriate ioctl for device
[2021/05/04 22:49:44] [error] [input:docker_events:docker_events.0] read returned error: 25, Inappropriate ioctl for device
```

**Comment by nokute78** [comment]
Thank you for information.

I can reproduce errno=25 issue using live restore.

File: plugins/in_docker_events/docker_events.c [hunk 3]
```diff
@@ -75,6 +75,78 @@ static int de_unix_create(struct flb_in_de_config *ctx)
...
+    int i;
+    int ret;
+    for (i=0; i<ctx->reconnect_retry_limits; i++) {
+        ret = reconnect_docker_sock(ins, config, ctx);
+        if (ret >= 0) {
+            return ret;
+        }
+        flb_plg_info(ctx->ins, "Retry(%d) after %d seconds.",i+1,
+                     ctx->reconnect_retry_interval);
+        sleep(ctx->reconnect_retry_interval);
```
Comment (MengmengZHANG) [inline plugins/in_docker_events/docker_events.c:143]: My understanding is that this sleep() will only block a dedicated thread for this docker_events plugin, it will not block the main loop, is that correct?

If that's the case, does it simplify to do a infinite loop / waiting here?

Comment (nokute78) [reply plugins/in_docker_events/docker_events.c:143]: Oops, it blocks main loop.
We need to create timer event..

**Comment by nokute78** [comment]
I updated not to block main loop.

We can test following command.
Fluent-bit outputs periodically during retrying re-connection.
```
$ sudo  bin/fluent-bit -i cpu -i docker_events -p reconnect.retry_interval=20 -p reconnect.retry_limits=5 -o stdout -m '*'
```

## Valgrind 
```
$ sudo valgrind bin/fluent-bit -i docker_events -p reconnect.retry_interval=30 -o stdout
==118689== Memcheck, a memory error detector
==118689== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==118689== Using Valgrind-3.15.0 and LibVEX; rerun with -h for copyright info
==118689== Command: bin/fluent-bit -i docker_events -p reconnect.retry_interval=30 -o stdout
==118689== 
Fluent Bit v1.8.0
* Copyright (C) 2019-2021 The Fluent Bit Authors
* Copyright (C) 2015-2018 Treasure Data
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io

[2021/05/05 17:38:57] [ info] [engine] started (pid=118689)
[2021/05/05 17:38:57] [ info] [storage] version=1.1.1, initializing...
[2021/05/05 17:38:57] [ info] [storage] in-memory
[2021/05/05 17:38:57] [ info] [storage] normal synchronization mode, checksum disabled, max_chunks_up=128
[2021/05/05 17:38:57] [ info] [input:docker_events:docker_events.0] listening for events on /var/run/docker.sock
[2021/05/05 17:38:57] [ info] [sp] stream processor started
[2021/05/05 17:39:00] [ info] [input:docker_events:docker_events.0] EOF detected. Re-initialize
[2021/05/05 17:39:00] [error] [plugins/in_docker_events/docker_events.c:71 errno=104] Connection reset by peer
[2021/05/05 17:39:00] [ info] [input:docker_events:docker_events.0] Reconnect successful
[2021/05/05 17:39:00] [ info] [input:docker_events:docker_events.0] EOF detected. Re-initialize
[2021/05/05 17:39:00] [error] [plugins/in_docker_events/docker_events.c:59 errno=111] Connection refused
[2021/05/05 17:39:00] [error] [input:docker_events:docker_events.0] failed to re-initialize socket
[2021/05/05 17:39:00] [ info] [input:docker_events:docker_events.0] create reconnect event. interval=30 second
[2021/05/05 17:39:30] [ info] [input:docker_events:docker_events.0] Retry(1/5)
[2021/05/05 17:39:30] [ info] [input:docker_events:docker_events.0] Reconnect successful
==118689== Warning: client switching stacks?  SP change: 0x57e48b8 --> 0x4d42e00
==118689==          to suppress, use: --max-stackframe=11147960 or greater
==118689== Warning: client switching stacks?  SP change: 0x4d42d78 --> 0x57e48b8
==118689==          to suppress, use: --max-stackframe=11148096 or greater
==118689== Warning: client switching stacks?  SP change: 0x57e48b8 --> 0x4d42d78
==118689==          to suppress, use: --max-stackframe=11148096 or greater
==118689==          further instances of this message will not be shown.
[0] docker_events.0: [1620203973.315766132, {"message"=>"{"status":"create","id":"b34f75fd452568553bbcdc77d7c4c1613094b2d89450c2ed7cdf9f3890fc2805","from":"grafana/loki:2.2.0","Type":"container","Action":"create","Actor":{"ID":"b34f75fd452568553bbcdc77d7c4c1613094b2d89450c2ed7cdf9f3890fc2805","Attributes":{"image":"grafana/loki:2.2.0","name":"romantic_bose","org.opencontainers.image.created":"2021-03-11T14:02:55Z","org.opencontainers.image.revision":"a27c79913c43d02b62a4b2f479bd77e9aa6b3617","org.opencontainers.image.source":"https://github.com/grafana/loki.git","org.opencontainers.image.url":"https://github.com/grafana/loki"}},"scope":"local","time":1620203973,"timeNano":1620203973308996673}
"}]
[1] docker_events.0: [1620203973.449143054, {"message"=>"{"status":"attach","id":"b34f75fd452568553bbcdc77d7c4c1613094b2d89450c2ed7cdf9f3890fc2805","from":"grafana/loki:2.2.0","Type":"container","Action":"attach","Actor":{"ID":"b34f75fd452568553bbcdc77d7c4c1613094b2d89450c2ed7cdf9f3890fc2805","Attributes":{"image":"grafana/loki:2.2.0","name":"romantic_bose","org.opencontainers.image.created":"2021-03-11T14:02:55Z","org.opencontainers.image.revision":"a27c79913c43d02b62a4b2f479bd77e9aa6b3617","org.opencontainers.image.source":"https://github.com/grafana/loki.git","org.opencontainers.image.url":"https://github.com/grafana/loki"}},"scope":"local","time":1620203973,"timeNano":1620203973322545741}
"}]
[2] docker_events.0: [1620203973.470832302, {"message"=>"{"Type":"network","Action":"connect","Actor":{"ID":"18cdef8f37a933f45015dbfa1676d4968b09ea0685fa63c98d140c6182114586","Attributes":{"container":"b34f75fd452568553bbcdc77d7c4c1613094b2d89450c2ed7cdf9f3890fc2805","name":"bridge","type":"bridge"}},"scope":"local","time":1620203973,"timeNano":1620203973470252515}
"}]
[3] docker_events.0: [1620203973.729943297, {"message"=>"{"status":"start","id":"b34f75fd452568553bbcdc77d7c4c1613094b2d89450c2ed7cdf9f3890fc2805","from":"grafana/loki:2.2.0","Type":"container","Action":"start","Actor":{"ID":"b34f75fd452568553bbcdc77d7c4c1613094b2d89450c2ed7cdf9f3890fc2805","Attributes":{"image":"grafana/loki:2.2.0","name":"romantic_bose","org.opencontainers.image.created":"2021-03-11T14:02:55Z","org.opencontainers.image.revision":"a27c79913c43d02b62a4b2f479bd77e9aa6b3617","org.opencontainers.image.source":"https://github.com/grafana/loki.git","org.opencontainers.image.url":"https://github.com/grafana/loki"}},"scope":"local","time":1620203973,"timeNano":1620203973729653995}
"}]
[4] docker_events.0: [1620203975.061173121, {"message"=>"{"status":"kill","id":"b34f75fd452568553bbcdc77d7c4c1613094b2d89450c2ed7cdf9f3890fc2805","from":"grafana/loki:2.2.0","Type":"container","Action":"kill","Actor":{"ID":"b34f75fd452568553bbcdc77d7c4c1613094b2d89450c2ed7cdf9f3890fc2805","Attributes":{"image":"grafana/loki:2.2.0","name":"romantic_bose","org.opencontainers.image.created":"2021-03-11T14:02:55Z","org.opencontainers.image.revision":"a27c79913c43d02b62a4b2f479bd77e9aa6b3617","org.opencontainers.image.source":"https://github.com/grafana/loki.git","org.opencontainers.image.url":"https://github.com/grafana/loki","signal":"2"}},"scope":"local","time":1620203975,"timeNano":1620203975060950032}
"}]
[5] docker_events.0: [1620203977.302238597, {"message"=>"{"status":"die","id":"b34f75fd452568553bbcdc77d7c4c1613094b2d89450c2ed7cdf9f3890fc2805","from":"grafana/loki:2.2.0","Type":"container","Action":"die","Actor":{"ID":"b34f75fd452568553bbcdc77d7c4c1613094b2d89450c2ed7cdf9f3890fc2805","Attributes":{"exitCode":"0","image":"grafana/loki:2.2.0","name":"romantic_bose","org.opencontainers.image.created":"2021-03-11T14:02:55Z","org.opencontainers.image.revision":"a27c79913c43d02b62a4b2f479bd77e9aa6b3617","org.opencontainers.image.source":"https://github.com/grafana/loki.git","org.opencontainers.image.url":"https://github.com/grafana/loki"}},"scope":"local","time":1620203977,"timeNano":1620203977297920437}
"}]
[6] docker_events.0: [1620203977.405145083, {"message"=>"{"Type":"network","Action":"disconnect","Actor":{"ID":"18cdef8f37a933f45015dbfa1676d4968b09ea0685fa63c98d140c6182114586","Attributes":{"container":"b34f75fd452568553bbcdc77d7c4c1613094b2d89450c2ed7cdf9f3890fc2805","name":"bridge","type":"bridge"}},"scope":"local","time":1620203977,"timeNano":1620203977386293079}
"}]
[7] docker_events.0: [1620203977.478593730, {"message"=>"{"status":"destroy","id":"b34f75fd452568553bbcdc77d7c4c1613094b2d89450c2ed7cdf9f3890fc2805","from":"grafana/loki:2.2.0","Type":"container","Action":"destroy","Actor":{"ID":"b34f75fd452568553bbcdc77d7c4c1613094b2d89450c2ed7cdf9f3890fc2805","Attributes":{"image":"grafana/loki:2.2.0","name":"romantic_bose","org.opencontainers.image.created":"2021-03-11T14:02:55Z","org.opencontainers.image.revision":"a27c79913c43d02b62a4b2f479bd77e9aa6b3617","org.opencontainers.image.source":"https://github.com/grafana/loki.git","org.opencontainers.image.url":"https://github.com/grafana/loki"}},"scope":"local","time":1620203977,"timeNano":1620203977475575198}
"}]
^C[2021/05/05 17:39:38] [engine] caught signal (SIGINT)
[2021/05/05 17:39:38] [ warn] [engine] service will stop in 5 seconds
[2021/05/05 17:39:42] [ info] [engine] service stopped
==118689== 
==118689== HEAP SUMMARY:
==118689==     in use at exit: 0 bytes in 0 blocks
==118689==   total heap usage: 404 allocs, 404 frees, 1,598,802 bytes allocated
==118689== 
==118689== All heap blocks were freed -- no leaks are possible
==118689== 
==118689== For lists of detected and suppressed errors, rerun with: -s
==118689== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
```

**Comment by nokute78** [comment]
I built dockerimage from source and tested.
```
sudo docker build  --no-cache -t flb -f dockerfiles/Dockerfile.x86_64-master .
sudo docker run -v /var/run:/var/run --name flb_test -d flb /fluent-bit/bin/fluent-bit -i docker_events -p reconnect.retry_interval=30 -o stdout
sudo systemctl restart docker
```

In my environment, errno=25 issue is not reproducible.
The testcase also causes EOF issue.
```
$ sudo docker logs -f flb_test
Fluent Bit v1.8.0
* Copyright (C) 2019-2021 The Fluent Bit Authors
* Copyright (C) 2015-2018 Treasure Data
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io

[2021/05/05 09:20:37] [ info] [engine] started (pid=1)
[2021/05/05 09:20:37] [ info] [storage] version=1.1.1, initializing...
[2021/05/05 09:20:37] [ info] [storage] in-memory
[2021/05/05 09:20:37] [ info] [storage] normal synchronization mode, checksum disabled, max_chunks_up=128
[2021/05/05 09:20:37] [ info] [input:docker_events:docker_events.0] listening for events on /var/run/docker.sock
[2021/05/05 09:20:37] [ info] [sp] stream processor started
[2021/05/05 09:20:43] [ info] [input:docker_events:docker_events.0] EOF detected. Re-initialize
[2021/05/05 09:20:44] [ info] [input:docker_events:docker_events.0] Reconnect successful
```

**Comment by MengmengZHANG** [comment]
Thanks @nokute78 for the updated fix.
I tested and the fix working fine for bare-metral or inside a contianer.
With your fix I cannot reproduce errno=25 more, so I think the logs I provided is truncated, errno=25 may not be the first err.

**Review by MengmengZHANG — APPROVED** [review]

**Review by MengmengZHANG — APPROVED** [review]

**Comment by edsiper** [comment]
thanks!
