### PR TITLE
Fixing memleak in do_glob.

### LINKED ISSUE #2096: Memory leak in do_glob on platforms without GLOB_TILDE
## Bug Report

**Describe the bug**
Comparing tmp and pattern pointers before freeing memory potentially allocated by extend_tilde function is not correct: in case extend_tilde allocates memory and returns a pointer different than pattern, we make pattern equal to tmp, therefore the check for whether these pointers are not equal is never  satisfied. It's better to add a boolean local variable explicitly indicating that the memory was allocated and needs deallocation.

**To Reproduce**
To reproduce observe in the debugger that on a platform where GLOB_TILDE is not defined in case the first character of the pattern is the symbol '~'.
 
**Expected behavior**
Memory allocated by extend_tilde is freed.

**Screenshots**
Not applicable

**Your Environment**
Not applicable

**Additional context**
Not applicable

### PR DESCRIPTION
**Pull request by diplodok-oleg**
Comparing tmp and pattern pointers before freeing memory potentially allocated by extend_tilde function is not correct: in case extend_tilde allocates memory and returns a pointer different than pattern, we make pattern equal to tmp, therefore the check for whether these pointers are not equal is never  satisfied. To avoid memory leak on platforms without GLOBE_TILDE I added additional "boolean" variable tmp_needs_free.

Fixes #2096 

----
Enter `[N/A]` in the box, if an item is not applicable to your change.

**Testing**
Before we can approve your change; please submit the following in a comment:
- [N/A] Example configuration file for the change
- [N/A] Debug log output from testing the change (this piece of code doesn't have debug logging)

- [N/A] Attached [Valgrind](https://valgrind.org/docs/manual/quick-start.html) output that shows no leaks or memory corruption was found (it's not possible to run valgrind on the platform I'm working on due to free memory restrictions)

**Documentation**
Documentation update is not required

----

Fluent Bit is licensed under Apache 2.0, by submitting this pull request I understand that this code will be released under the terms of that license.

### CODE REVIEW

**Comment by edsiper** [comment]
thanks for catching up on the problem and providing a fix.

I will add a minor change request so we can merge this PR.

File: plugins/in_tail/tail_scan_glob.c [hunk 1]
```diff
@@ -120,6 +120,7 @@ static inline int do_glob(const char *pattern, int flags,
     int ret;
     int new_flags;
     char *tmp = NULL;
+    int tmp_needs_free = 0;
```
Comment (edsiper) [inline plugins/in_tail/tail_scan_glob.c:123]: please initialize using ```FLB_FALSE```.

File: plugins/in_tail/tail_scan_glob.c [hunk 2]
```diff
@@ -142,6 +143,7 @@ static inline int do_glob(const char *pattern, int flags,
         if (tmp != pattern) {
             /* the path was expanded */
             pattern = tmp;
+            tmp_needs_free = 1;
```
Comment (edsiper) [inline plugins/in_tail/tail_scan_glob.c:146]: use ```FLB_TRUE``` instead of 1

File: plugins/in_tail/tail_scan_glob.c [hunk 3]
```diff
@@ -155,7 +157,7 @@ static inline int do_glob(const char *pattern, int flags,
     /* remove temporary buffer, if allocated by expand_tilde above.
      * Note that this buffer is only used for libc implementations
      * that do not support the GLOB_TILDE flag, like musl. */
-    if (tmp != NULL && tmp != pattern) {
+    if ((tmp != NULL) && (tmp_needs_free == 1)) {
```
Comment (edsiper) [inline plugins/in_tail/tail_scan_glob.c:160]: use ```FLB_TRUE``` instead of 1

**Comment by diplodok-oleg** [comment]
@edsiper I fixed issues you've pointed out, but now some tests are broken. Seems that my PR shouldn't affect them. Furthermore I've seen these tests green in the very same PR and my changes since were not essential in this regard. Therefore I assume that these tests are not stable. What should I do now?

**Comment by edsiper** [comment]
@diplodok-oleg thanks for the changes.

all good now, we are having some issues with the CI system (infra provisioning I think), so no worries.,

thanks again!
