### PR TITLE
out_stackdriver: increase auth token size limit

### LINKED ISSUE #3316: out_stackdriver: Authorization header is truncated to 512 bytes
## Bug Report

**Describe the bug**

When the stackdriver plugin is sending logs to upstream, it's `Authorization` http header is [limited to 512 bytes](https://github.com/fluent/fluent-bit/blob/1.7/plugins/out_stackdriver/stackdriver.c#L1940) and will be truncated if the Bearer token is longer, resulting in failure.

Most of the GCP tokens are shorter than 512 bytes however there're cases when the token can be longer. In my case it's a [federated access token](https://cloud.google.com/iam/docs/workload-identity-federation) returned form a GCP metadata server. 

**To Reproduce**

Setup a IAM environment that the token size is longer than 512 bytes. The fluent-bit log has many entries like the following:

```
2021-04-01T19:31:41.332580184Z stderr F [2021/04/01 19:31:41] [ warn] [engine] chunk '1-1617302185.420006054.flb' cannot be retried: task_id=120, input=storage_backlog.3 > output=stackdriver.0
2021-04-01T19:31:41.333659995Z stderr F [2021/04/01 19:31:41] [ warn] [output:stackdriver:stackdriver.0] error
2021-04-01T19:31:41.333672295Z stderr F <html><title>Error 400 (Bad Request)!!1</title></html>
```

**Expected behavior**

A longer token with reasonable length should not be truncated.  Maybe we should change the limit from `512` to `1024`.

**Your Environment**
* Version used: 1.7.*

### PR DESCRIPTION
**Pull request by leonzz**
Increase the token size limit from 512Bytes to 14KB in out_stackdriver

- When fetching token from metadata server, increase the payload buffer to 14KB (12KB for token, 2KB for other fields in the response and json overhead)
- Removed the string copy step of `set_authorization_header` and directly use the sds string from `get_google_token` with added token type.

This is to accommodate GCP [federated access token](https://cloud.google.com/iam/docs/workload-identity-federation), usually in the size of 700-900 bytes for the example tokens in my test environment.

Fixes #3316
 
----

**Testing**
Before we can approve your change; please submit the following in a comment:
- [x] Example configuration file for the change
- [x] Debug log output from testing the change

- [ ] Attached [Valgrind](https://valgrind.org/docs/manual/quick-start.html) output that shows no leaks or memory corruption was found

**Example Configuration**
```
[SERVICE]
    Flush                     1
    Log_Level                 debug
    Parsers_File              parsers.conf
    storage.path              /var/log/flb-storage/
    storage.sync              normal
    storage.checksum           off
    storage.backlog.mem_limit  10M

[INPUT]
    Name               tail
    Tag                k8s_container.test1.test2.test3
    Path               /var/log/containers/*.log 
    Parser             docker
    Buffer_Chunk_Size  512KB
    Buffer_Max_Size    5M
    Rotate_Wait        30
    Mem_Buf_Limit      30MB
    Skip_Long_Lines    On
    Refresh_Interval   10
    storage.type       filesystem
    
[FILTER]
    Name    record_modifier
    Match   *
    Record  gke.googleapis.com/log_type system
    
[OUTPUT]
    Name        stackdriver
    Match       k8s_container.*
    Resource    k8s_container
    k8s_cluster_name test_cluster_name
    k8s_cluster_location  test_cluster_location
    # a METADATA_SERVER env var is set to retrieve project ID and auth token 
```

**Debug log output**
```
[2021/04/06 20:30:22] [debug] [http_client] not using http_proxy for header
[2021/04/06 20:30:22] [debug] [http_client] header=POST /v2/entries:write HTTP/1.1
Host: logging.googleapis.com
Content-Length: 34685
User-Agent: Fluent-Bit
Content-Type: application/json
Authorization: Bearer *****token string of length 790 is omitted. Before the change, this string was truncated*****
```

**Documentation**
- [ ] Documentation required for this feature

----

Fluent Bit is licensed under Apache 2.0, by submitting this pull request I understand that this code will be released under the terms of that license.

### CODE REVIEW

**Comment by edsiper** [comment]
@hsmatulisgoogle @qingling128  @igorpeshansky

File: plugins/out_stackdriver/stackdriver.c [hunk 1]
```diff
@@ -1937,7 +1937,7 @@ static void set_authorization_header(struct flb_http_client *c,
                                      char *token)
 {
     int len;
-    char header[512];
+    char header[1024];
```
Comment (qingling128) [inline plugins/out_stackdriver/stackdriver.c:1940]: According to the Metadata API team, the size could potentially be larger than 1024. See a similar PR at https://github.com/Stackdriver/collectd/pull/192/files

Comment (leonzz) [reply plugins/out_stackdriver/stackdriver.c]: Thanks Ling for the reference, they are very useful!

I think 4096 will be a good fit here based on the following considerations:

- There's follow-up PR193 in the collectd repo that revert 65536 back to 4096, with a reference for token size: https://developers.google.com/identity/protocols/oauth2#size, where the current max size for access token is 2048 bytes.

- There's a 4096 bytes buffer when the stackdriver plugin is retrieving token from the metadata server, ref: https://github.com/fluent/fluent-bit/blob/v1.7.3/plugins/out_stackdriver/gce_metadata.c#L72

**Review by erain — APPROVED** [review]
LGTM

**Comment by edsiper** [comment]
@erain @qingling128 is this one ready to be merged ?

**Comment by erain** [comment]
Yes from me

File: plugins/out_stackdriver/stackdriver.c (hunk 1 above)
Comment (qingling128) [reply plugins/out_stackdriver/stackdriver.c]: Sorry for the confusion. There was a https://github.com/Stackdriver/collectd/pull/194 that reverted the revert of https://github.com/Stackdriver/collectd/pull/193. Ultimately we decided to leave it as 65536 for the monitoring agent.

The suggestion from the Metadata API team is that:

```
Starting on January 2022, Access token size limit will be set to 12K to match our Public API limits in http://cloud/iam/docs/reference/sts/rest/v1beta/TopLevel/token#response-body.

This does not mean that we are going to start responding with 12KB access tokens. It only means that an access token can be as large as 12KB.

In compliance with http://go/rfc/6749#section-4.2.2 We strongly recommend that customers do not to make any assumptions about the maximum access token size.
```

So something larger than `12KB` as the buffer size might reduce potential issues in the future.

Comment (edsiper) [reply plugins/out_stackdriver/stackdriver.c]: thanks for the info @qlingling128

@leonzz In that case, besides the size change, I'd suggest allocating the buffer from the heap instead of using the stack.

Comment (leonzz) [reply plugins/out_stackdriver/stackdriver.c]: Thanks Ling and Eduardo. Will make the update to 12KB then:
- when talking to metadata server to fetch token, the http read buffer also need to increase (maybe to 12KB + 256B for other smaller fields);
- It looks to me the extra `snprintf` string copy step can be removed by directly using the sds string: `flb_http_add_header(c, "Authorization", 13, token, flb_sds_len(token));`

Will do the test and update this PR accordingly.

**Review by qingling128 — APPROVED** [review]
LGTM

**Comment by edsiper** [comment]
thanks!

**Comment by leonzz** [comment]
@edsiper Thanks! Do I need to cherry pick the commit and create PR to the 1.7 branch in order for it to appear in the next 1.7.* patch release?

**Comment by edsiper** [comment]
we will do it, not need it. thanks
