### PR TITLE
out_s3: fix tag corruption with preserve_data_ordering

### LINKED ISSUE #6933: S3 output intermittently fails with errors SignatureDoesNotMatch, broken pipe, or HTTP version error
## Bug Report

**Describe the bug**
I have Fluent Bit deployed in a kubernetes cluster sending a large volume of logs to an S3 bucket. Most logs are transmitted successfully, however Fluent Bit regularly logs the "PutObject request failed" error. (This is odd because `use_put_object` is set to `false`) Fluent Bit logs the HTTP 403 response it got from S3, which has this error text: "The request signature we calculated does not match the signature you provided. Check your key and signing method."

There are also a lot of "broken pipe" errors although it is unclear if they are related.

Even more bizarrely, there are intermittent HTTP 505 Version not supported errors. I have no idea how these could be intermittent, surely the HTTP version is always the same?

**To Reproduce**
- Rubular link if applicable: N/A
- Example log message if applicable:
```
[2023/02/28 23:16:52] [error] [output:s3:s3.1] PutObject request failed
[2023/02/28 23:16:52] [error] [output:s3:s3.1] PutObject API responded with error='SignatureDoesNotMatch', message='The request signature we calculated does not match the signature you provided. Check your key and signing method.'

[2023/02/28 23:16:52] [error] [/src/fluent-bit/src/flb_http_client.c:1201 errno=32] Broken pipe

[2023/02/28 23:31:05] [error] [output:s3:s3.1] PutObject API responded with error='HttpVersionNotSupported', message='The HTTP version specified is not supported.'
[2023/02/28 23:31:05] [error] [output:s3:s3.1] Raw PutObject response: HTTP/1.1 505 HTTP Version not supported
```
- Steps to reproduce the problem:
I'm afraid I don't have a concise set of steps to reproduce, our environment is fairly large and complex and this issue only seems to appear under heavy load.

**Expected behavior**
Fluent Bit sends log files to S3 bucket

**Screenshots**
N/A

**Your Environment**
* Version used: 2.0.9
* Configuration:
```
    [OUTPUT]
        Name s3
        Match *
        bucket ${log_bucket_name}
        region ${log_bucket_region}
        total_file_size 10M
        s3_key_format /${cluster_name}/$TAG/%Y/%m/%d/%H/%M/%S
        use_put_object false
```
* Environment name and version (e.g. Kubernetes? What version?): AWS EKS cluster, Kubernetes 1.22
* Server type and version: EC2 instances of various types
* Operating System and version: Bottlerocket 1.12.0
* Filters and plugins: tail input, modify filter, kubernetes filter

**Additional context**
I know that Fluent Bit retries requests to S3 but I am seeing occasional messages like this:
```
[2023/02/28 23:30:56] [ warn] [output:s3:s3.1] Chunk file failed to send 5 times, will not retry
```
So I am concerned that I am losing log messages.

I realize that these could be 3 different issues however they seem to occur together and I'm wondering if they could have a common cause.

Incidentally, I found this comment (over a year old) which reports the same behavior: https://github.com/fluent/fluent-bit/issues/4505#issuecomment-1000376903

### PR DESCRIPTION
**Pull request by PettitWesley**
Fixes #6933

----
Enter `[N/A]` in the box, if an item is not applicable to your change.

**Testing**
Before we can approve your change; please submit the following in a comment:
- [ ] Example configuration file for the change
- [ ] Debug log output from testing the change

- [ ] Attached [Valgrind](https://valgrind.org/docs/manual/quick-start.html) output that shows no leaks or memory corruption was found

If this is a change to packaging of containers or native binaries then please confirm it works for all targets.
- [ ] Run [local packaging test](./packaging/local-build-all.sh) showing all targets (including any new ones) build.
- [ ] Set `ok-package-test` label to test for all targets (requires maintainer to do).

**Documentation**

- [ ] Documentation required for this feature

**Backporting**

- [ ] Backport to latest stable release.

----

Fluent Bit is licensed under Apache 2.0, by submitting this pull request I understand that this code will be released under the terms of that license.

### CODE REVIEW

File: plugins/out_s3/s3.c [hunk 1]
```diff
@@ -105,7 +105,7 @@ static char *mock_error_response(char *error_env_var)
 
     err_val = getenv(error_env_var);
     if (err_val != NULL && strlen(err_val) > 0) {
-        error = flb_malloc(strlen(err_val) + sizeof(char));
+        error = flb_calloc(strlen(err_val) + sizeof(char));
```
Comment (leonardo-albertovich) [inline plugins/out_s3/s3.c:108]: `flb_calloc` requires 2 paramters : element count and element size

In this case I'd suggest writing `flb_calloc(strlen(err_val) + 1, sizeof(char))`

File: plugins/out_s3/s3.c [hunk 2]
```diff
@@ -158,7 +158,7 @@ int create_headers(struct flb_s3 *ctx, char *body_md5,
         return 0;
     }
 
-    s3_headers = flb_malloc(sizeof(struct flb_aws_header) * headers_len);
+    s3_headers = flb_calloc(sizeof(struct flb_aws_header) * headers_len);
```
Comment (leonardo-albertovich) [inline plugins/out_s3/s3.c:161]: Same as 108, use headers_len as element count and the sizeof as element size

**Review by leonardo-albertovich — CHANGES_REQUESTED** [review]
Please address the `flb_calloc`  errors.

**Comment by leonardo-albertovich** [comment]
I just commented a few of those but there are quite a few. Additionally, I can't really review the string replacement modifications right now, it's too late and my brain is fried so either somebody else reviews it or I'll do it in the morning.

File: plugins/out_s3/s3.c (hunk 1 above)
Comment (PettitWesley) [reply plugins/out_s3/s3.c]: Fixed/Thanks!!!!

It is concerning that I
1) have known how calloc works in the past
2) self-code-reviewed this code to avoid embarrassing mistakes
3) didn't catch it

:/

**Comment by PettitWesley** [comment]
@leonardo-albertovich Sorry/thanks... I have fixed that calloc mistake... :/

**Review by matthewfala — APPROVED** [review]
Looks good to me.

**Review by leonardo-albertovich — APPROVED** [review]

**Comment by leonardo-albertovich** [comment]
Looks good to me too, all we are missing right now is a 2.0 backport, will you do it or should we? it'd be good if we merged the three of them at the same time just to keep things tidy

**Comment by PettitWesley** [comment]
@leonardo-albertovich Sorry, when you said backport earlier I didn't realize we now have a 2.0 backport branch for 2.0 instead of 2.1. Sorry.

**Comment by leonardo-albertovich** [comment]
No worries I've already done it and merged all three of them together, thanks a lot!
