### PR TITLE
mp: sort flb_record_accessor by a number of subkeys(#5546)

### LINKED ISSUE #5546: Loki Output - remove_keys skipped if used in labels
## Bug Report

**Describe the bug**
Using Loki output, `remove_keys` don't work as expected when values within `remove_keys` are used by `labels`

using `fluent/fluent-bit:1.9.4`

**To Reproduce**

```yaml
# docker-compose.yaml
version: "3.7"

services:
  fluent-bit:
    image: fluent/fluent-bit
    network_mode: "host"
    volumes:
      - ./fluent-bit.yaml:/fluent-bit/etc/fluent-bit.yaml
    command: "/fluent-bit/bin/fluent-bit -c /fluent-bit/etc/fluent-bit.yaml"
```

```yaml
# fluent-bit.yaml
env:
  log_level: debug
  flush_interval: 5

pipeline:
  inputs:
  - dummy:
      dummy: '{"log":"blahblah","kubernetes":{"pod_name":"nginx", "namespace_name":"default"}}'

  outputs:
  - loki:
      match: '*'
      auto_kubernetes_labels: off
      labels: pod=$kubernetes['pod_name']
      remove_keys: kubernetes
```

```bash
$ docker-compose up

$ nc -l 3100
POST /loki/api/v1/push HTTP/1.1
Host: 127.0.0.1:3100
Content-Length: 148
User-Agent: Fluent-Bit
Content-Type: application/json

{"streams":[{"stream":{"pod":"nginx"},"values":[["1654686265055834768","{\"log\":\"blahblah\",\"kubernetes\":{\"namespace_name\":\"default\"}}"]]}]}
```

- Steps to reproduce the problem:

**Expected behavior**
```
# expected
{"streams":[{"stream":{"pod":"nginx"},"values":[["1654686265055834768","{\"log\":\"blahblah\"}"]]}]}

# actual
{"streams":[{"stream":{"pod":"nginx"},"values":[["1654686265055834768","{\"log\":\"blahblah\",\"kubernetes\":{\"namespace_name\":\"default\"}}"]]}]}
```

**Your Environment**
* Version used: 1.9.4
* Configuration: given above
* Environment name and version: docker
* Server type and version:
* Operating System and version: ubuntu 20.04
* Filters and plugins: Loki

**Additional context**
using `tail` input and `kubernetes` filter and `loki` output in kubernetes environment, and ran into this problem. There are a lot of useless labels and annotations included in logs. I want only relevant information and remove key `kubernetes`

### PR DESCRIPTION
**Pull request by nokute78**
Fixes #5546 

out_loki tries to remove key/value using flb_mp_accessor_keys_remove.
The API needs a key lists to indicate which key should be removed.

I tested the API and I found that the list should be sorted if it is passed nested key/value.
However the lists is not sorted at current master. It may not work if user passes nested key/value.

This patch is to fix it.
- Add test code
- Add API to get subkey number
- Insert record_accessor sorted by subkey number

----
Enter `[N/A]` in the box, if an item is not applicable to your change.

**Testing**
Before we can approve your change; please submit the following in a comment:
- [X] Example configuration file for the change
- [X] Debug log output from testing the change

- [X] Attached [Valgrind](https://valgrind.org/docs/manual/quick-start.html) output that shows no leaks or memory corruption was found

If this is a change to packaging of containers or native binaries then please confirm it works for all targets.
- [N/A] Attached [local packaging test](./packaging/local-build-all.sh) output showing all targets (including any new ones) build.

**Documentation**

- [N/A] Documentation required for this feature

**Backporting**

- [N/A] Backport to latest stable release.

## Configuration

```
[INPUT]
    Name dummy
    dummy {"log":"blahblah","kubernetes":{"pod_name":"nginx", "namespace_name":"default"}}

[OUTPUT]
    Name loki
    auto_kubernetes_labels off
    labels pod=$kubernetes['pod_name']
    remove_keys kubernetes
    port 9200
    Log_Level debug
```

http_server.go:
```go
package main

import (
	"fmt"
	"io"
	"log"
	"net/http"
	"strconv"
)

func main() {
	port := 9200
	ps := strconv.Itoa(port)

	http.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		defer r.Body.Close()
		b, err := io.ReadAll(r.Body)
		if err != nil {
			log.Printf("ReadAll error=%s\n", err)
		} else {
			log.Printf("%+v\n", string(b))
		}
		//w.WriteHeader(400)
	})
	fmt.Printf("Listen port=%s\n", ps)
	err := http.ListenAndServe(":"+ps, nil)
	if err != nil {
		log.Printf("ListenAndServe err=%s\n", err)
	}
}
```

## Debug log

```
$ ../bin/fluent-bit -c a.conf 
Fluent Bit v1.9.5
* Copyright (C) 2015-2022 The Fluent Bit Authors
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io

[2022/06/26 12:37:40] [ info] [fluent bit] version=1.9.5, commit=71e53850ab, pid=40379
[2022/06/26 12:37:40] [ info] [storage] version=1.2.0, type=memory-only, sync=normal, checksum=disabled, max_chunks_up=128
[2022/06/26 12:37:40] [ info] [cmetrics] version=0.3.4
[2022/06/26 12:37:40] [debug] [output:loki:loki.0] remove_mpa size: 2
[2022/06/26 12:37:40] [ info] [output:loki:loki.0] configured, hostname=127.0.0.1:9200
[2022/06/26 12:37:40] [ info] [sp] stream processor started
[2022/06/26 12:37:41] [debug] [output:loki:loki.0] 127.0.0.1:9200, HTTP status=200
[2022/06/26 12:37:42] [debug] [output:loki:loki.0] 127.0.0.1:9200, HTTP status=200
^C[2022/06/26 12:37:42] [engine] caught signal (SIGINT)
[2022/06/26 12:37:42] [ warn] [engine] service will shutdown in max 5 seconds
[2022/06/26 12:37:42] [debug] [output:loki:loki.0] 127.0.0.1:9200, HTTP status=200
[2022/06/26 12:37:43] [ info] [engine] service has stopped (0 pending tasks)
```

"kubernetes" field is removed.
```
$ go run http_server.go 
Listen port=9200
2022/06/26 12:37:41 {"streams":[{"stream":{"pod":"nginx"},"values":[["1656214660553074560","{\"log\":\"blahblah\"}"]]}]}
2022/06/26 12:37:42 {"streams":[{"stream":{"pod":"nginx"},"values":[["1656214661552289828","{\"log\":\"blahblah\"}"]]}]}
```

## Valgrind output

```
$ valgrind --leak-check=full ../bin/fluent-bit -c a.conf 
==40385== Memcheck, a memory error detector
==40385== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==40385== Using Valgrind-3.15.0 and LibVEX; rerun with -h for copyright info
==40385== Command: ../bin/fluent-bit -c a.conf
==40385== 
Fluent Bit v1.9.5
* Copyright (C) 2015-2022 The Fluent Bit Authors
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io

[2022/06/26 12:38:56] [ info] [fluent bit] version=1.9.5, commit=71e53850ab, pid=40385
[2022/06/26 12:38:56] [ info] [storage] version=1.2.0, type=memory-only, sync=normal, checksum=disabled, max_chunks_up=128
[2022/06/26 12:38:56] [ info] [cmetrics] version=0.3.4
[2022/06/26 12:38:56] [debug] [output:loki:loki.0] remove_mpa size: 2
[2022/06/26 12:38:56] [ info] [output:loki:loki.0] configured, hostname=127.0.0.1:9200
[2022/06/26 12:38:56] [ info] [sp] stream processor started
[2022/06/26 12:38:57] [debug] [output:loki:loki.0] 127.0.0.1:9200, HTTP status=200
[2022/06/26 12:38:58] [debug] [output:loki:loki.0] 127.0.0.1:9200, HTTP status=200
^C[2022/06/26 12:38:58] [engine] caught signal (SIGINT)
[2022/06/26 12:38:58] [ warn] [engine] service will shutdown in max 5 seconds
[2022/06/26 12:38:58] [debug] [output:loki:loki.0] 127.0.0.1:9200, HTTP status=200
[2022/06/26 12:38:59] [ info] [engine] service has stopped (0 pending tasks)
==40385== 
==40385== HEAP SUMMARY:
==40385==     in use at exit: 0 bytes in 0 blocks
==40385==   total heap usage: 1,399 allocs, 1,399 frees, 1,439,096 bytes allocated
==40385== 
==40385== All heap blocks were freed -- no leaks are possible
==40385== 
==40385== For lists of detected and suppressed errors, rerun with: -s
==40385== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
```

----

Fluent Bit is licensed under Apache 2.0, by submitting this pull request I understand that this code will be released under the terms of that license.

### CODE REVIEW

File: tests/internal/mp.c [hunk 1]
```diff
@@ -145,9 +145,97 @@ void test_accessor_keys_remove()
...
+    msgpack_unpacked_init(&result);
+    msgpack_unpack_next(&result, buf, size, &off);
+    map = result.data;
+
+    /* Create list of patterns */
+    flb_slist_create(&patterns);
+
+    /* sub key -> key */
+    flb_slist_add(&patterns, "$kubernetes[2]['annotations']['fluentbit.io/tag']");
+    flb_slist_add(&patterns, "$kubernetes");
```
Comment (nokute78) [inline tests/internal/mp.c:197]: Note: 
If it calls like below, the test will work correctly.
```c
   flb_slist_add(&patterns, "$kubernetes");
   flb_slist_add(&patterns, "$kubernetes[2]['annotations']['fluentbit.io/tag']");
```

**Comment by nokute78** [comment]
Hmm, mk_list API can't add new value to head of the list.
I think it doesn't expect a head is changed.

**Comment by nokute78** [comment]
It is ready to review.

File: src/flb_mp.c [hunk 2]
```diff
@@ -350,6 +350,61 @@ void flb_mp_array_header_end(struct flb_mp_map_header *mh)
...
+        mk_list_add(_new, head);
+        return;
+    }
+
+    prev = next->prev;
+    _new->next = next;
+    _new->prev = prev;
+    prev->next = _new;
+    next->prev = _new;
+}
```
Comment (nokute78) [inline src/flb_mp.c:375]: I added this local function since mk_list API doesn't support below operation3.

1. head `mk_list_init(&head)`
2. head -> val1 `mk_list_add(&val1, &head)`
3. head -> val2 -> val1 (???)


It may be better to move this codes to mk_list.h. However it will take long time. 
Send PR to monkey -> (waiting to merge) -> Send PR to fluent-bit -> (Waiting to merge).

I will send PR to monkey if this patch will work correctly and I will remove this local function.

**Comment by nokute78** [comment]
@edsiper  I sent a patch https://github.com/monkey/monkey/pull/371.
Could you review it ?

**Comment by nokute78** [comment]
@edsiper @leonardo-albertovich ping.

**Comment by nokute78** [comment]
https://github.com/monkey/monkey/pull/371 was updated.
Unit test was OK using above patch.

```
$ bin/flb-it-mp
Test count...                                   [ OK ]
(snip)
Test accessor_keys_remove_subkey_key...         
=== ORIGINAL  ===
[0] {"key1"=>"something", "kubernetes"=>[true, false, {"a"=>false, "annotations"=>{"fluentbit.io/tag"=>"thetag", "extra"=>false}}]}
=== FINAL MAP ===
[0] {"key1"=>"something"}
[ OK ]
Test accessor_keys_remove_subkey_keys...        
=== ORIGINAL  ===
[0] {"key1"=>"something", "kubernetes"=>[true, false, {"a"=>false, "annotations"=>{"fluentbit.io/tag"=>"thetag", "extra"=>false}}]}
=== FINAL MAP ===
[0] {"key1"=>"something"}

=== ORIGINAL  ===
[0] {"key1"=>"something", "kubernetes"=>[true, false, {"a"=>false, "annotations"=>{"fluentbit.io/tag"=>"thetag", "extra"=>false}}]}
=== FINAL MAP ===
[0] {"key1"=>"something"}

=== ORIGINAL  ===
[0] {"key1"=>"something", "kubernetes"=>[true, false, {"a"=>false, "annotations"=>{"fluentbit.io/tag"=>"thetag", "extra"=>false}}]}
=== FINAL MAP ===
[0] {"key1"=>"something"}

=== ORIGINAL  ===
[0] {"key1"=>"something", "kubernetes"=>[true, false, {"a"=>false, "annotations"=>{"fluentbit.io/tag"=>"thetag", "extra"=>false}}]}
=== FINAL MAP ===
[0] {"key1"=>"something"}

=== ORIGINAL  ===
[0] {"key1"=>"something", "kubernetes"=>[true, false, {"a"=>false, "annotations"=>{"fluentbit.io/tag"=>"thetag", "extra"=>false}}]}
=== FINAL MAP ===
[0] {"key1"=>"something"}

=== ORIGINAL  ===
[0] {"key1"=>"something", "kubernetes"=>[true, false, {"a"=>false, "annotations"=>{"fluentbit.io/tag"=>"thetag", "extra"=>false}}]}
=== FINAL MAP ===
[0] {"key1"=>"something"}
[ OK ]
SUCCESS: All unit tests have passed.
```

**Comment by DevSusu** [comment]
@edsiper @leonardo-albertovich ping.

File: src/flb_mp.c (hunk 2 above)
Comment (leonardo-albertovich) [reply src/flb_mp.c:375]: Hah, funny enough I both Hiroshi and I added prepend to monkey a while ago but we still haven't updated monkey in fluent-bit.

File: src/record_accessor/flb_ra_parser.c [hunk 3]
```diff
@@ -27,6 +27,21 @@
...
+        return -1;
+    }
+    else if (rp->type != FLB_RA_PARSER_KEYMAP) {
+        return 0;
+    }
+    else if(rp->key->subkeys == NULL) {
+        return -1;
+    }
+
+    return mk_list_size(rp->key->subkeys);
```
Comment (leonardo-albertovich) [inline src/record_accessor/flb_ra_parser.c:42]: Beware of `mk_list_size`, it iterates the entire list in order to calculate the size each time. At this point I think we might just waste 8 bytes per node and add a counter that's only used in the head node but I haven't properly assessed the impact of it yet.

Comment (nokute78) [reply src/record_accessor/flb_ra_parser.c:42]: I'm glad monkey API supports that feature.

However we don't pass a head node pointer to `mk_list_del` function.
I think we need to seek the head node from a entry pointer or create a new API to pass a head node to decrement list size.

Comment (leonardo-albertovich) [reply src/record_accessor/flb_ra_parser.c:42]: That's true and the possible side effect could be a lot worse than the original issue, you're right.

**Comment by updogliu** [comment]
Any updates or blockers at here?

File: src/flb_mp.c (hunk 2 above)
Comment (nokute78) [reply src/flb_mp.c]: https://github.com/fluent/fluent-bit/pull/6135 was merged and we can use `mk_list_add_before`.

**Comment by nokute78** [comment]
I rebased master and modified to use `mk_list_add_before`.
Ready to review.

**Comment by DevSusu** [comment]
@edsiper @leonardo-albertovich 
I'm really happy to see the fluent-bit 2.0 release, and changes about the Loki Plugin https://github.com/fluent/fluent-bit/releases/tag/v2.0.0
with this PR merged, it'll be perfect!

**Comment by nokute78** [comment]
@edsiper @leonardo-albertovich Ping. It is ready for review.

**Comment by nokute78** [comment]
@edsiper @leonardo-albertovich Ping.
It is ready for reviewing.

File: src/flb_mp.c [hunk 4]
```diff
@@ -382,7 +413,13 @@ struct flb_mp_accessor *flb_mp_accessor_create(struct mk_list *slist_patterns)
             flb_mp_accessor_destroy(mpa);
             return NULL;
         }
-        mk_list_add(&ra->_head, &mpa->ra_list);
+
+        /* first time */
+        if (mk_list_size(&mpa->ra_list) == 0) {
```
Comment (leonardo-albertovich) [inline src/flb_mp.c:418]: I think you could skip this block if becaise the `mk_list_foreach` in `insert_by_subkey_num` would not satisfy the condition in the for loop when the list is empty so it would skip straight to the `mk_list_add` fallback right?

File: include/fluent-bit/flb_record_accessor.h [hunk 5]
```diff
@@ -34,6 +34,7 @@ struct flb_record_accessor {
     struct mk_list _head;        /* Head to custom list (only used by flb_mp.h) */
 };
 
+int flb_ra_subkey_num(struct flb_record_accessor *ra);
```
Comment (leonardo-albertovich) [inline include/fluent-bit/flb_record_accessor.h:37]: Could you replace `num` with `count` everywhere? that would be much clearer.

File: src/flb_record_accessor.c [hunk 6]
```diff
@@ -247,6 +247,27 @@ void flb_ra_destroy(struct flb_record_accessor *ra)
...
 }
 
+int flb_ra_subkey_num(struct flb_record_accessor *ra)
+{
+    struct mk_list *head;
+    struct flb_ra_parser *rp;
+    int ret = -1;
+    int tmp;
+
+    if (ra == NULL) {
```
Comment (leonardo-albertovich) [inline src/flb_record_accessor.c:257]: Maybe returning 0 in this case would be better even if that would make it undistinguishable from legitimate empty ra it would be it less error prone (ie. someone using a size_t without paying attention) since at the moment the result is not being checked.

**Review by leonardo-albertovich — APPROVED** [review]
I don;'t see anything wrong with the code and considering it fixes a longstanding issue I think it should be merged ASAP.

File: include/fluent-bit/flb_record_accessor.h (hunk 5 above)
Comment (nokute78) [reply include/fluent-bit/flb_record_accessor.h]: Thank you for reviewing.
I pushed following commit.
https://github.com/fluent/fluent-bit/pull/5590/commits/c9ece8302b5c3a72f3c1743a820a7b0470651292

File: src/flb_record_accessor.c (hunk 6 above)
Comment (nokute78) [reply src/flb_record_accessor.c:257]: I prefer returning negative value.

In a future, the result can be checked.

File: src/flb_mp.c (hunk 4 above)
Comment (nokute78) [reply src/flb_mp.c]: Thank you for reviewing. You are right.

I sent a following commit.
https://github.com/fluent/fluent-bit/pull/5590/commits/b98c0633054cb8381de007b4acdcbcfd0c4e3e28

**Comment by nokute78** [comment]
CI failed, but I think it is not related this PR.
https://github.com/fluent/fluent-bit/actions/runs/4148684951/jobs/7176918184#step:2:41
```
Get:25 https://packages.microsoft.com/ubuntu/20.04/prod focal/main armhf Packages [12.3 kB]
Fetched 11.3 MB in 2s (5398 kB/s)
Reading package lists...
E: Failed to fetch https://packages.microsoft.com/ubuntu/20.04/prod/dists/focal/main/binary-amd64/Packages.gz  File has unexpected size (173872 != 173717). Mirror sync in progress? [IP: 13.82.67.141 443]
   Hashes of expected file:
    - Filesize:173717 [weak]
    - SHA512:e787843d9c76dd8fd521e59acb0894d4711a1c17715b20b70369a3954f17188e8bdc0b21628f259dcc3870153de65b3d0d3111bf567d5875a5ed1520a26474aa
    - SHA256:8056429dc12e244a28498fffe18243d5a45f524ea9ed826913dff60750f1d485
   Release file created at: Fri, 10 Feb 2023 23:59:47 +0000
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

**Review by leonardo-albertovich — APPROVED** [review]

**Comment by edsiper** [comment]
thanks everyone!
