### PR TITLE
in_tail: fix st_mtime timestamp format

### LINKED ISSUE #6294: in_tail: Ignore_Older does not work properly on Windows
## Bug Report

**Describe the bug**
The configuration option `Ignore_Older` for `in_tail` has no effect. It still registers files older than what is configured.

**To Reproduce**
*Windows only*
If you add a new file that matches the Path pattern in your `in_tail` config, you will see while debugging the application that [this](https://github.com/fluent/fluent-bit/blob/master/plugins/in_tail/tail_file.h#L46) line does not *"return the file modification time in seconds since epoch"* as expected, but rather an 18-digit long LDAP timestamp.

**Expected behavior**
The `Ignore_Older` configuration should work. The function mentioned above should return a Unix epoch timestamp for Windows.

**Your Environment**

* Version used: 2.0.0
* Configuration:
```
[SERVICE]
    flush 5
    log_level debug

[INPUT]
    name tail
    path Path/To/Folder/*.log
    ignore_older 60

[OUTPUT]
    name stdout
    match *
```
* Environment name and version (e.g. Kubernetes? What version?): N/A
* Server type and version: N/A
* Operating System and version: Any Windows (tried on 10 and Windows Server 2019)
* Filters and plugins: in_tail

**Additional context**

This issue has caused fluent-bit on the server to open all the log files from ages ago until it gets an error `Too many files open`. Then it can't open the files I actually want it to open and my logs don't get forwarded.

### PR DESCRIPTION
**Pull request by davsan-0**
This patch fixes an issue where st_mtime for Windows platforms was set directly from `ftLastWriteTime` without converting it to a Unix epoch timestamp first. This caused checks against `st_mtime` to not behave as expected.

For instance, this caused the `Ignore_Older` configuration option for in_tail to not work properly as it still registered files that it shouldn't have. 

How to reproduce the issue on Windows without this fix: Using in_tail, if you add a new file that matches the `Path` pattern you will see while debugging the application that [this](https://github.com/fluent/fluent-bit/blob/master/plugins/in_tail/tail_file.h#L46) line does not *"return the file modification time in seconds since epoch"* as expected, but rather an 18-digit long LDAP timestamp.

Fixes #6294

----
Enter `[N/A]` in the box, if an item is not applicable to your change.

**Testing**
Before we can approve your change; please submit the following in a comment:
- [x] Example configuration file for the change
- [ N/A ] Debug log output from testing the change

- [ N/A ] Attached [Valgrind](https://valgrind.org/docs/manual/quick-start.html) output that shows no leaks or memory corruption was found

If this is a change to packaging of containers or native binaries then please confirm it works for all targets.
- [ N/A ] Attached [local packaging test](./packaging/local-build-all.sh) output showing all targets (including any new ones) build.

**Documentation**

- [ N/A ] Documentation required for this feature

**Backporting**

- [ N/A ] Backport to latest stable release.

----

Fluent Bit is licensed under Apache 2.0, by submitting this pull request I understand that this code will be released under the terms of that license.

### CODE REVIEW

**Comment by davsan-0** [comment]
## Configuration
```
[SERVICE]
    flush 5
    log_level debug

[INPUT]
    name tail
    path Path/To/Folder/*.log
    ignore_older 60

[OUTPUT]
    name stdout
    match *
```

File: plugins/in_tail/win32/stat.c [hunk 1]
```diff
@@ -44,6 +46,18 @@ static int get_mode(unsigned int attr)
     return WIN32_S_IFREG;
 }
 
+static int64_t filetime_to_epoch(FILETIME ft)
+{
+    int64_t ldap;
```
Comment (leonardo-albertovich) [inline plugins/in_tail/win32/stat.c:51]: Please use a [ULARGE_INTEGER](https://learn.microsoft.com/en-us/windows/win32/api/winnt/ns-winnt-ularge_integer-r1) to store the QWORD instead of that custom cast.

File: plugins/in_tail/win32/stat.c [hunk 2]
```diff
@@ -35,6 +35,8 @@
  */
 
 #define UINT64(high, low) ((uint64_t) (high) << 32 | (low))
+#define LDAP_TO_SECONDS_DIVISOR 10000000
```
Comment (leonardo-albertovich) [inline plugins/in_tail/win32/stat.c:38]: Please rename this constant so it's clear at first sight that it's the conversion ratio between windows ticks and seconds.

File: plugins/in_tail/win32/stat.c [hunk 3]
```diff
@@ -35,6 +35,8 @@
...
+#define LDAP_TO_EPOCH_DIFF_SECONDS 11644473600
```
Comment (leonardo-albertovich) [inline plugins/in_tail/win32/stat.c:39]: Please rename this constant so it's clear that it reflects the delta between windows' value for epoch and unixs' value for epoch.

**Review by leonardo-albertovich — CHANGES_REQUESTED** [review]
Additionally, please remove the LDAP name from those constants, those values are specific to windows but not LDAP.

**Comment by davsan-0** [comment]
@leonardo-albertovich I added the comment to my patch and things like the null check. If you want me to straight up take anything more from your commit into here to fit your code style then I can do that of course.

**Comment by leonardo-albertovich** [comment]
> @leonardo-albertovich I added the comment to my patch and things like the null check. If you want me to straight up take anything more from your commit into here to fit your code style then I can do that of course.

It's perfect, thanks for making those changes, I didn't request them because your code was functional as it was but I appreciate the effort. We will merge this as soon as CI passes. 

Once again, thanks a lot, I'm glad we will be able to merge this one instead of the copy.

**Comment by davsan-0** [comment]
Great, thank you!

**Comment by davsan-0** [comment]
I missed changing the operator when changing the `ft` variable to a pointer so the tests failed, fixed now.

**Comment by edsiper** [comment]
thanks!
