### PR TITLE
pack: modify to determine how many JSON messages are OK(#5336)

### LINKED ISSUE #5336: TCP input plugin dropping records
## Bug Report

**Describe the bug**
The 1.9.x releases contain a regression that makes TCP input plugin dropping records. The actual breaking commit is [f3ac138b0](https://github.com/fluent/fluent-bit/commit/f3ac138b0)

**To Reproduce**
1. Create a test data set having 64k records:
```
for i in $(seq 1 65535); do echo '{"foo":"bar"}'; done > tcp.log
```

2. Create `fluent-bit.conf`:
```
[SERVICE]
  Flush         10
  Log_Level     debug
  Daemon        off
[INPUT]
  Name          tcp
  Listen        0.0.0.0
  Port          5170
  Chunk_Size    32
  Buffer_Size   64
  Format        json
  Mem_Buf_Limit 30MB
[OUTPUT]
  Name stdout
  Match *
```

3. Start **working** 1.8.15 daemon:
```
docker run -it --rm -p 5170:5170 -v /path/to/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf fluent/fluent-bit:1.8.15
```

4. Send test data:
```
cat tcp.log | nc localhost 5170
```
```
Fluent Bit v1.8.15
* Copyright (C) 2015-2021 The Fluent Bit Authors
...
[2022/04/21 15:42:58] [debug] [input chunk] update output instances with new chunk size diff=46800
[2022/04/21 15:42:58] [debug] [input chunk] update output instances with new chunk size diff=14920
[2022/04/21 15:43:05] [debug] [task] created task=0x7fea70637280 id=0 OK
[2022/04/21 15:43:05] [debug] [output:stdout:stdout.0] task_id=0 assigned to thread #0
[0] tcp.0: [1650555777.674115534, {"foo"=>"bar"}]
[1] tcp.0: [1650555777.674137953, {"foo"=>"bar"}]
...
[65533] tcp.0: [1650555778.342504882, {"foo"=>"bar"}]
[65534] tcp.0: [1650555778.342512844, {"foo"=>"bar"}]
[2022/04/21 15:43:06] [debug] [out coro] cb_destroy coro_id=0
```
> All records reach the output!

5. Start **non-working** 1.9.2 daemon:
```
docker run -it --rm -p 5170:5170 -v /path/to/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf fluent/fluent-bit:1.9.2
```

6. Send test data:
```
cat tcp.log | nc localhost 5170
```
```
Fluent Bit v1.9.2
* Copyright (C) 2015-2022 The Fluent Bit Authors
...
[2022/04/21 15:46:36] [debug] [tcp:tcp.0] created event channels: read=21 write=22
[2022/04/21 15:46:36] [ info] [input:tcp:tcp.0] listening on 0.0.0.0:5170
[2022/04/21 15:46:36] [debug] [stdout:stdout.0] created event channels: read=24 write=25
[2022/04/21 15:46:36] [debug] [router] match rule tcp.0:stdout.0
[2022/04/21 15:46:36] [ info] [sp] stream processor started
[2022/04/21 15:46:36] [ info] [output:stdout:stdout.0] worker #0 started
[2022/04/21 15:47:11] [debug] [input:tcp:tcp.0] JSON incomplete, waiting for more data...
[2022/04/21 15:47:11] [debug] [input:tcp:tcp.0] JSON incomplete, waiting for more data...
[2022/04/21 15:47:11] [debug] [input:tcp:tcp.0] JSON incomplete, waiting for more data...
[2022/04/21 15:47:11] [debug] [input:tcp:tcp.0] JSON incomplete, waiting for more data...
```
> I've seen processed record count varying between 0, 512, 1024, but never the amount of input.

7.  Revert the mentioned commit and rebuild image
```
git checkout -b v1.9.2-patched v1.9.2
git revert f3ac138b0
docker buildx build --no-cache --load --platform "linux/amd64" --target=production -f dockerfiles/Dockerfile -t fluent/fluent-bit:1.9.2-patched .
```

8. Start **patched** 1.9.2 daemon:
```
docker run -it --rm -p 5170:5170 -v /path/to/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf fluent/fluent-bit:1.9.2-patched
``` 

9. Send test data:
```
cat tcp.log | nc localhost 5170
```
```
Fluent Bit v1.9.2
* Copyright (C) 2015-2022 The Fluent Bit Authors
...
[2022/04/21 15:56:29] [debug] [tcp:tcp.0] created event channels: read=21 write=22
[2022/04/21 15:56:29] [ info] [input:tcp:tcp.0] listening on 0.0.0.0:5170
[2022/04/21 15:56:29] [debug] [stdout:stdout.0] created event channels: read=24 write=25
[2022/04/21 15:56:29] [debug] [router] match rule tcp.0:stdout.0
[2022/04/21 15:56:29] [ info] [sp] stream processor started
[2022/04/21 15:56:29] [ info] [output:stdout:stdout.0] worker #0 started
[2022/04/21 15:56:34] [debug] [input chunk] update output instances with new chunk size diff=21940
[2022/04/21 15:56:34] [debug] [input chunk] update output instances with new chunk size diff=46800
...
[2022/04/21 15:56:34] [debug] [input chunk] update output instances with new chunk size diff=46800
[2022/04/21 15:56:34] [debug] [input chunk] update output instances with new chunk size diff=46800
[2022/04/21 15:56:34] [debug] [input chunk] update output instances with new chunk size diff=25160
[2022/04/21 15:56:38] [debug] [task] created task=0x7f7a05e423f0 id=0 OK
[2022/04/21 15:56:38] [debug] [output:stdout:stdout.0] task_id=0 assigned to thread #0
[0] tcp.0: [1650556594.057870047, {"foo"=>"bar"}]
[1] tcp.0: [1650556594.057911742, {"foo"=>"bar"}]
...
[65533] tcp.0: [1650556594.703312414, {"foo"=>"bar"}]
[65534] tcp.0: [1650556594.703320516, {"foo"=>"bar"}]
[2022/04/21 15:56:39] [debug] [out flush] cb_destroy coro_id=0
[2022/04/21 15:56:39] [debug] [task] destroy task=0x7f7a05e423f0 (task_id=0)
```
> Works again just like in 1.8 releases!

**Expected behavior**

1.9 releases should behave in a similar way as the earlier 1.8 releases. 

**Additional context**

Especially systems using TCP keepalive sessions with TCP input plugin are badly misbehaving at the moment.

The following patch is enough to fix the issue (but it might have some other issues):
```
diff --git a/src/flb_pack.c b/src/flb_pack.c
index 40e1bde5d..e7f33a1bd 100644
--- a/src/flb_pack.c
+++ b/src/flb_pack.c
@@ -364,9 +364,13 @@ int flb_pack_json_state(const char *js, size_t len,
         int i;
         int found = 0;

-        for (i = 1; i < state->tokens_count; i++) {
+        for (i = 1; i < state->tokens_size; i++) {
             t = &state->tokens[i];

+            if (t->start < (state->tokens[i - 1]).start) {
+                break;
+            }
+
             if (t->parent == -1 && (t->end != 0)) {
                 found++;
                 delim = i;
```

### PR DESCRIPTION
**Pull request by nokute78**
Fixes #5336 
Root cause: https://github.com/fluent/fluent-bit/issues/5336#issuecomment-1115513183

`jsmn_parse` updates `jsmn_parser` members even if a JSON is incomplete. (state->parser is updated)
In this case, a member `toknext` points next incomplete object token.

This patch is to use `toknext` as an index of last member of complete JSON.
This patch also changes a loop to descending.

----
Enter `[N/A]` in the box, if an item is not applicable to your change.

**Testing**
Before we can approve your change; please submit the following in a comment:
- [X] Example configuration file for the change
- [X] Debug log output from testing the change

- [X] Attached [Valgrind](https://valgrind.org/docs/manual/quick-start.html) output that shows no leaks or memory corruption was found

If this is a change to packaging of containers or native binaries then please confirm it works for all targets.
- [N/A] Attached [local packaging test](./packaging/local-build-all.sh) output showing all targets (including any new ones) build.

**Documentation**

- [N/A] Documentation required for this feature

**Backporting**

- [N/A] Backport to latest stable release.

## Configuration

https://github.com/fluent/fluent-bit/issues/5336#issue-1211251079

```
for i in $(seq 1 65535); do echo '{"foo":"bar"}'; done > tcp.log
```

```
[SERVICE]
  Flush         10
  Log_Level     debug
  Daemon        off
[INPUT]
  Name          tcp
  Listen        0.0.0.0
  Port          5170
  Chunk_Size    32
  Buffer_Size   64
  Format        json
  Mem_Buf_Limit 30MB
[OUTPUT]
  Name stdout
  Match *
```

flb-rt-in_tcp:
```
$ bin/flb-rt-in_tcp 
Test tcp...                                     [ OK ]
Test format_none...                             [ OK ]
Test format_none_separator...                   [ OK ]
Test 65535_records_issue_5336...                [ OK ]
SUCCESS: All unit tests have passed.
```

flb-it-pack:
```
$ bin/flb-it-pack 
Test json_pack...                               [ OK ]
Test json_pack_iter...                          [ OK ]
Test json_pack_mult...                          [ OK ]
Test json_pack_mult_iter...                     [ OK ]
Test json_macros...                             [ OK ]
Test json_dup_keys...                           [ OK ]
Test json_pack_bug342...                        [ OK ]
Test json_pack_bug1278...                       
test 0 out => "one\u0007two"
test 1 out => "one\btwo"
test 2 out => "one\ttwo"
test 3 out => "one\ntwo"
test 4 out => "one\u000btwo"
test 5 out => "one\ftwo"
test 6 out => "one\rtwo"
test 7 out => "\\n"
[ OK ]
Test json_pack_bug5336...                       [ OK ]
Test utf8_to_json...                            [ OK ]
SUCCESS: All unit tests have passed.
```

## Debug log

```
6$ ../bin/fluent-bit -c a.conf 
Fluent Bit v1.9.4
* Copyright (C) 2015-2022 The Fluent Bit Authors
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io

[2022/05/05 21:09:28] [ info] Configuration:
[2022/05/05 21:09:28] [ info]  flush time     | 10.000000 seconds
[2022/05/05 21:09:28] [ info]  grace          | 5 seconds
[2022/05/05 21:09:28] [ info]  daemon         | 0
[2022/05/05 21:09:28] [ info] ___________
(snip)
[65531] tcp.0: [1651752589.579062568, {"foo"=>"bar"}]
[65532] tcp.0: [1651752589.579062909, {"foo"=>"bar"}]
[65533] tcp.0: [1651752589.579063209, {"foo"=>"bar"}]
[65534] tcp.0: [1651752589.579063540, {"foo"=>"bar"}]
[2022/05/05 21:09:58] [debug] [out flush] cb_destroy coro_id=0
[2022/05/05 21:09:58] [debug] [task] destroy task=0x7f9f9c014690 (task_id=0)
```

## Valgrind output

```
[65534] tcp.0: [1651752638.008761239, {"foo"=>"bar"}]
[2022/05/05 21:10:54] [debug] [out flush] cb_destroy coro_id=0
[2022/05/05 21:10:54] [debug] [task] destroy task=0x4e67bd0 (task_id=0)
^C[2022/05/05 21:10:55] [engine] caught signal (SIGINT)
[2022/05/05 21:10:55] [ warn] [engine] service will shutdown in max 5 seconds
[2022/05/05 21:10:55] [ info] [engine] service has stopped (0 pending tasks)
[2022/05/05 21:10:55] [ info] [output:stdout:stdout.0] thread worker #0 stopping...
[2022/05/05 21:10:55] [ info] [output:stdout:stdout.0] thread worker #0 stopped
==115272== 
==115272== HEAP SUMMARY:
==115272==     in use at exit: 0 bytes in 0 blocks
==115272==   total heap usage: 263,593 allocs, 263,593 frees, 1,108,922,588 bytes allocated
==115272== 
==115272== All heap blocks were freed -- no leaks are possible
==115272== 
==115272== For lists of detected and suppressed errors, rerun with: -s
==115272== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
```

----

Fluent Bit is licensed under Apache 2.0, by submitting this pull request I understand that this code will be released under the terms of that license.

### CODE REVIEW

File: tests/runtime/in_tcp.c [hunk 1]
```diff
@@ -354,10 +376,77 @@ void flb_test_format_none_separator()
...
+        w_size = send(fd, buf, size, 0);
+        if (!TEST_CHECK(w_size == size)) {
+            TEST_MSG("failed to send, count=%d errno=%d",i, errno);
+            flb_socket_close(fd);
+            exit(EXIT_FAILURE);
+        }
+    }
+
+    /* waiting to flush */
+    flb_time_msleep(2500);
```
Comment (nokute78) [inline tests/runtime/in_tcp.c:434]: This test takes a few seconds.
We may need to increase waiting time.

**Comment by edsiper** [comment]
thanks!
