### PR TITLE
tail plugin on win: don't repeatedly add symlinks to scan queue

### LINKED ISSUE #1806: on Windows, tail reads lines repeatedly from symlinked source
## Bug Report

**Describe the bug**

On Windows, lines read from a symlink by the tail plugin get read over and over again, ad infinitum. I do not see the same behavior on Linux.

**To Reproduce**

C:\fluent-bit\data\test-data.txt:
```
aaa
bbb
ccc
```

Make a symlink:

```powershell
$ New-Item -Path C:\fluent-bit\data\test-data-link.txt -ItemType SymbolicLink -Value C:\fluent-bit\data\test-data.txt
```

Reference that in some simple configuration:

C:\fluent-bit\conf\fluent-bit.conf:
```
[SERVICE]
    Flush         1
    Log_Level     debug
    Daemon        off

[INPUT]
    Name              tail
    Tag               test
    Path              C:\fluent-bit\data\test-data-link.txt
    Mem_Buf_Limit     5MB
    Skip_Long_Lines   On
    Refresh_Interval  10

[OUTPUT]
    Name          stdout
    Match         test
```

Let 'er rip:

```powershell
$ C:\fluent-bit\bin\fluent-bit.exe -c C:\fluent-bit\conf\fluent-bit.conf
```

**Let this run for a few minutes.**

Observe the following output:
```
Fluent Bit v1.3.3
Copyright (C) Treasure Data

[2019/12/12 05:59:08] [debug] [storage] [cio stream] new stream registered: tail.0
[2019/12/12 05:59:08] [ info] [storage] initializing...
[2019/12/12 05:59:08] [ info] [storage] in-memory
[2019/12/12 05:59:08] [ info] [storage] normal synchronization mode, checksum disabled, max_chunks_up=128
[2019/12/12 05:59:08] [ info] [engine] started (pid=2768)
[2019/12/12 05:59:08] [debug] [engine] coroutine stack size: 98302 bytes (96.0K)
[2019/12/12 05:59:08] [debug] [in_tail] scanning path c:\fluent-bit\data\test-data-link.txt
[2019/12/12 05:59:08] [debug] [in_tail] add to scan queue c:\fluent-bit\data\test-data-link.txt, offset=0
[2019/12/12 05:59:08] [debug] [router] match rule tail.0:stdout.0
[2019/12/12 05:59:08] [ info] [sp] stream processor started
[2019/12/12 05:59:08] [debug] [in_tail] file=c:\fluent-bit\data\test-data-link.txt read=15 lines=3
[2019/12/12 05:59:08] [debug] [in_tail] file=c:\fluent-bit\data\test-data-link.txt promote to TAIL_EVENT
[2019/12/12 05:59:09] [debug] [task] created task=00000262409EF0F0 id=0 OK
[0] test: [1576130348.092644900, {"log"=>"aaa"}]
[1] test: [1576130348.092663400, {"log"=>"bbb"}]
[2] test: [1576130348.092663800, {"log"=>"ccc"}]
[2019/12/12 05:59:09] [debug] [task] destroy task=00000262409EF0F0 (task_id=0)
[2019/12/12 05:59:18] [debug] [in_tail] append new file: c:\fluent-bit\data\test-data-link.txt
[2019/12/12 05:59:18] [debug] [in_tail] add to scan queue c:\fluent-bit\data\test-data-link.txt, offset=0
[2019/12/12 05:59:18] [debug] [in_tail] file=c:\fluent-bit\data\test-data-link.txt read=15 lines=3
[2019/12/12 05:59:18] [debug] [in_tail] file=c:\fluent-bit\data\test-data-link.txt promote to TAIL_EVENT
[2019/12/12 05:59:19] [debug] [task] created task=00000262409EF0F0 id=0 OK
[0] test: [1576130358.114188100, {"log"=>"aaa"}]
[1] test: [1576130358.114193700, {"log"=>"bbb"}]
[2] test: [1576130358.114194000, {"log"=>"ccc"}]
[2019/12/12 05:59:19] [debug] [task] destroy task=00000262409EF0F0 (task_id=0)
[2019/12/12 05:59:28] [debug] [in_tail] append new file: c:\fluent-bit\data\test-data-link.txt
[2019/12/12 05:59:28] [debug] [in_tail] add to scan queue c:\fluent-bit\data\test-data-link.txt, offset=0
[2019/12/12 05:59:28] [debug] [in_tail] file=c:\fluent-bit\data\test-data-link.txt read=15 lines=3
[2019/12/12 05:59:28] [debug] [in_tail] file=c:\fluent-bit\data\test-data-link.txt promote to TAIL_EVENT
[2019/12/12 05:59:29] [debug] [task] created task=00000262409EF0F0 id=0 OK
[0] test: [1576130368.094498000, {"log"=>"aaa"}]
[1] test: [1576130368.094501900, {"log"=>"bbb"}]
[2] test: [1576130368.094502100, {"log"=>"ccc"}]
[2019/12/12 05:59:29] [debug] [task] destroy task=00000262409EF0F0 (task_id=0)
```

**Expected behavior**

I expect that each line is read only once.

**Your Environment**

* Version used: 1.3.3 

* I've been able to replicate this problem in the following environments:

    * Windows nodes in Kubernetes v1.14.8 on AKS
    * Plain Docker, in containers based on `mcr.microsoft.com/windows/servercore:ltsc2019`
    * A Windows 10 Pro VM

**Additional context**

I'm trying to get fuent-bit cranking on the Windows nodes in my mixed node Kubernetes cluster. Container logs, are of course, symlinks. 🤷‍♂

### PR DESCRIPTION
**Pull request by krancour**
Fixes #1806

When deciding whether a path should be added to the scan queue or not, a superficial comparison on path/name is the correct behavior for all OSes. Only operations that actually touch the files in question may need to do a deeper comparison that accounts for `real_name` on applicable OSes. 

cc @fujimotos

### CODE REVIEW

**Comment by krancour** [comment]
I don't understand the test failures. They don't appear related to this change. I also see that many recent PRs and builds of master have also had failures lately.

**Comment by fujimotos** [comment]
@krancour Thanks for working on it!

> When deciding whether a path should be added to the scan queue or not, a superficial comparison on path/name is the correct behavior for all OSes. Only operations that actually touch the files in question may need to do a deeper comparison that accounts for real_name on applicable OSes.

I will review your fix soon; I need to confirm that changing the name comparison
won't break any integrity, so please give me a bit of time.

> I don't understand the test failures. They don't appear related to this change. I also see that many recent PRs and builds of master have also had failures lately.

Yes, the test is failing due to an irrelevant issue on HEAD. I'm going to
take a look at that too.

File: plugins/in_tail/tail_file.c [hunk 1]
```diff
@@ -979,7 +979,12 @@ int flb_tail_file_to_event(struct flb_tail_file *file)
         return -1;
     }
 
-    if (flb_tail_file_name_cmp(name, file) != 0) {
+    /*
+     * flb_tail_target_file_name_cmp is a deeper compare than
+     * flb_tail_file_name_cmp. If applicable, it compares to the underying
```
Comment (fujimotos) [inline plugins/in_tail/tail_file.c]: Not related to the logic, but your comment has a typo:

`underying -> underlying`

**Comment by fujimotos** [comment]
More comments on this PR:

> When deciding whether a path should be added to the scan queue or not, a superficial comparison on path/name is the correct behavior for all OSes. Only operations that actually touch the files in question may need to do a deeper comparison that accounts for real_name on applicable OSes.

This observation is correct. Basically, there are two different cases
where we need to do filename comparison.

 1. Path scanning for new files.
 2. Rotation detection.

For (1), we just need to compare literal paths, regardless of whether
they are files or symlinks.

For (2), we need to compare "real" paths. This is because a symbolic
link can be rotated by having its target file renamed. For instance,
consider the following case:

```bash
# Prepare a symlink
$ echo foo > test.txt && ln -s test.txt test.lnk

# Make Fluent Bit follow it
$ fluent-bit -i tail -p Path=test.lnk -o stdout

# Rotate symlink behind its back
$ mv test.txt test.txt.1 && echo baa > test.txt
```

And Rancourt's solution is to use `flb_tail_file_name_cmp` for (1)
and `flb_tail_target_file_name_cmp` for (2). IMO, this is the right
way to go (and indeed worked in my testing).

@krancour I appreciate if you can add some explanation to the commit
message on why this patch fixes the bug (for later references).

File: plugins/in_tail/tail_file.c (hunk 1 above)
Comment (krancour) [reply plugins/in_tail/tail_file.c]: I will fix!

**Comment by krancour** [comment]
@fujimotos, sure. I will reuse some of your comments above even.

Thank you for taking the time to look at this!

**Comment by krancour** [comment]
@fujimotos the comment typos have been fixed and I have also updated the commit text as you have suggested.

Let me know if there is anything else I can do to have this PR in shape.

Thanks!

**Comment by fujimotos** [comment]
OK. Now I pulled this patch to win32-next.

@edsiper I believe this is comittable. My signed-off version is available at
a4ee594c which I fixed up the commit message to follow our convention.
I don't mind either one is pulled to the mainline.

**Comment by krancour** [comment]
@fujimotos to make things easier, I updated the commit message in this PR to match your conventions (which I was previously unaware of). Hope that helps.

**Comment by edsiper** [comment]
thanks!
