### PR TITLE
out_es: fix replace_dots in array values

### LINKED ISSUE #2093: [es output] Replace_Dots not working in array elements
## Bug Report

**Describe the bug**

Replace_Dots works to replace dots in fields with underscores. However there is an edge case where it does not seem to work, that is when the dotted field name is in an array as follow:

`'{"foo": [{".dotted": "bar"}]}'`

- Steps to reproduce the problem:

The method I use requires docker.
Please save the following file as `docker-compose.yaml` and run `docker-compose up`:

```yaml
version: "3.7"

services:
  fluent-bit:
    image: fluent/fluent-bit
    command:
      - /fluent-bit/bin/fluent-bit
      - -i
      - dummy
      - -p
      - 'Dummy={"top": [{".dotted": "value"}]}'
      - -o
      - es
      - -p
      - "Host=elasticsearch"
      - -p
      - "Replace_Dots=On"
    depends_on:
      - elasticsearch
  elasticsearch:
    image: elasticsearch:7.6.2
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
```

Notice the elasticsearch container emit:

```text
elasticsearch_1  | "Caused by: java.lang.IllegalArgumentException: object field starting or ending with a [.] makes object resolution ambiguous: [.dotted]",
```

However if the dummy input is configured as `'Dummy={"top": {".dotted": "value"}}'` (without the array), there is no such error, and `Replace_Dots` works as expected.

Furthermore if the dot is elsewhere than the beggining, ES does ingest the log, but the dot is not replaced.

e.g. `[{"d.otted": "value"}, {"foo": "bar"}]`

yields a document in ES as:

```json
      {
        "_index" : "fluent-bit",
        "_type" : "flb_type",
        "_id" : "u_LhW3EBY51yOSkZgGsJ",
        "_score" : 1.0,
        "_source" : {
          "@timestamp" : "2020-04-08T22:20:36.001Z",
          "top" : [
            {
              "d.otted" : "value"
            },
            {
              "foo" : "bar"
            }
          ]
        }
      }
```

**Expected behavior**
I would expect a document as such to show up in ES, with the fist char dot replaced:

```json
     {
        "_index" : "fluent-bit",
        "_type" : "flb_type",
        "_id" : "bdPdW3EBCJwJktcCD1kS",
        "_score" : 1.0,
        "_source" : {
          "@timestamp" : "2020-04-08T22:15:45.004Z",
          "top" : [
            {
              "_dotted" : "value"
            },
            {
              "foo" : "bar"
            }
          ]
        }
```

Similarly, if the dot is in the middle of the field, the following would be expected:

```json
      {
        "_index" : "fluent-bit",
        "_type" : "flb_type",
        "_id" : "u_LhW3EBY51yOSkZgGsJ",
        "_score" : 1.0,
        "_source" : {
          "@timestamp" : "2020-04-08T22:20:36.001Z",
          "top" : [
            {
              "d_otted" : "value"
            },
            {
              "foo" : "bar"
            }
          ]
        }
      }
```

PS you can see es documents by running:

```sh
curl "localhost:9200/_search?pretty" \
  -H 'Content-Type: application/json' \
  -d'{ "query": { "match_all": {} }}'
```

You can delete this index by running:
```sh
curl -X DELETE "localhost:9200/fluent-bit?pretty"
```

**Screenshots**

image

**Your Environment**
As per docker-compose.yaml above.

**Additional context**
For reasons beyond my control, there are services that emit json logs, that have fields in arrays that begin with `.`, they are not being output to elasticsearch due to this bug.

Sidenote: I've made a PR for local pipeline setup with docker as per above via https://github.com/fluent/fluent-bit-docs/pull/288

### PR DESCRIPTION
**Pull request by naseemkullah**
By creating `es_pack_array_content` function and using it to deal with map values that are arrays, replace dots now runs on the elements of arrays.

`es_pack_array_content` function created and used on map values if they are arrays. It is mutually recursive with `es_pack_map_content`, i.e. if an element of the array is a map, run `es_pack_map_content` on it, if an value of a map is an array, run `es_pack_array_content` on it.

Fixes #2093 

----
Enter `[N/A]` in the box, if an item is not applicable to your change.

**Testing**
Before we can approve your change; please submit the following in a comment:
- [n/a] Example configuration file for the change

- [x] Debug log output from testing the change

`Dummy {".le.vel":"error", ".fo.o":[{".o.k": [{".b.ar": "baz"}]}]}`

yields:

```
      {
        "_index" : "fluent-bit",
        "_type" : "flb_type",
        "_id" : "HZ0PmXEBZm-eHs2kSTYK",
        "_score" : 1.0,
        "_source" : {
          "@timestamp" : "2020-04-20T19:27:27.002Z",
          "_le_vel" : "error",
          "_fo_o" : [
            {
              "_o_k" : [
                {
                  "_b_ar" : "baz"
                }
              ]
            }
          ]
        }
      }
```

😄 

- [N/A] Attached [Valgrind](https://valgrind.org/docs/manual/quick-start.html) output that shows no leaks or memory corruption was found

**Documentation**

- [N/A] Documentation required for this feature

----

major thanks to @npaun for advice on this one.

cc @edsiper @PettitWesley 

PS @PettitWesley worth noting I used the docker compose method to build, run and test a container upon code changes since my local environment is not setup for C.

Fluent Bit is licensed under Apache 2.0, by submitting this pull request I understand that this code will be released under the terms of that license.

### CODE REVIEW

**Comment by PettitWesley** [comment]
> PS @PettitWesley worth noting I used the docker compose method to build, run and test a container upon code changes since my local environment is not setup for C.

@naseemkullah Hmmmm. May be it is worth mentioning developing with docker in the dev guide? If you want to put up a new PR, I'm open to it. I lean towards saying though that may be in the dev guide (or readme) you just note that instead of running the usual build commands, you could also run `docker build`

**Comment by naseemkullah** [comment]
bump

**Comment by naseemkullah** [comment]
My pleasure @PettitWesley , happy it's finally been approved! :) Looking forward to seeing this be merged.

**Comment by fujimotos** [comment]
@naseemkullah I basically agree with @PettitWesley that it is a good
patch to merge ... but can I beg you one thing to modify?

This is because I see GCC 8.3.0 failing to compile the code with your
patch applied.

```bash
$ git pull https://github.com/fluent/fluent-bit/ refs/pull/2119/head
$ make
...
/usr/bin/ld: ../library/libflb-plugin-out_es.a(es.c.o): in function `es_pack_map_content':
es.c:(.text+0xeb9): undefined reference to `es_pack_array_content'
$ gcc --version
```

I think what breaks the compilation is the use of `inline`.

As you commit message says, your patch introduces a _mutual_ recursion.
It conflicts with the `inline` keyword, since there is no streight forward
way to expand such function calls.

It seems to fool some version of GCC and causes the error above.
So I propose you to:

 1. Drop "inline" keyword from es_pack_array_content and es_pack_map_content.
 2. Add "static" to es_pack_map_array so that the symbol gets not leaked to
    other plugins.

Other than this, I'm fine with this patch.

**Comment by naseemkullah** [comment]
> It seems to fool some version of GCC and causes the error above.

Thanks @fujimotos for the advice, basically never use `inline` keyword with mutual recursion if I understand correctly now. Change applied! Please let me know if there are any further improvements that could be made.

**Comment by fujimotos** [comment]
@naseemkullah  Thank you.  Now I'm fine with this patch.

FWIW, I have tested this patch using the following configuration.

```ini
[INPUT]
  Name              dummy
  Dummy             {".a":[{".b.c":0}],".d.e":{".f.g": 0}}

[OUTPUT]
  Name              es
  Replace_Dots      on
  Match             *
```

Before this patch, the JSON data contained `.` in the array items even though
`Replace_Dots` is enabled:

```json
{"@timestamp":"2020-05-25T09:29:28.264Z","_a":[{".b.c":0}],"_d_e":{"_f_g":0}}
```

... and after this patch:

```json
{"@timestamp":"2020-05-25T09:25:08.264Z","_a":[{"_b_c":0}],"_d_e":{"_f_g":0}}
```

File: plugins/out_es/es.c [hunk 1]
```diff
@@ -159,14 +163,53 @@ static inline int es_pack_map_content(msgpack_packer *tmp_pck,
             msgpack_pack_map(tmp_pck, v->via.map.size);
             es_pack_map_content(tmp_pck, *v, ctx);
         }
+        /*
+         * The value can be any data type, if it's an array we need to
+         * pass it to es_pack_array_content.
+         */
+        else if (v->type == MSGPACK_OBJECT_ARRAY)
```
Comment (edsiper) [inline plugins/out_es/es.c:170]: fix brace: https://github.com/fluent/fluent-bit/blob/master/CONTRIBUTING.md#braces-usage-on-conditionals-loops-and-functions

File: plugins/out_es/es.c [hunk 2]
```diff
@@ -159,14 +163,53 @@ static inline int es_pack_map_content(msgpack_packer *tmp_pck,
...
 
+/*
+  * Iterate through the array and sanitize elements.
+  * Mutual recursion with es_pack_map_content.
+  */
+static int es_pack_array_content(msgpack_packer *tmp_pck,
+                                 msgpack_object array,
+                                 struct flb_elasticsearch *ctx)
+{
+  msgpack_object *e;
```
Comment (edsiper) [inline plugins/out_es/es.c:190]: indentation must be 4 spaces: https://github.com/fluent/fluent-bit/blob/master/CONTRIBUTING.md#coding-style

File: plugins/out_es/es.c [hunk 3]
```diff
@@ -159,14 +163,53 @@ static inline int es_pack_map_content(msgpack_packer *tmp_pck,
...
+
+  for (int i = 0; i < array.via.array.size; i++)
+  {
```
Comment (edsiper) [inline plugins/out_es/es.c:193]: opening brace must go in previous line

**Comment by naseemkullah** [comment]
Thanks @edsiper, I've applied the stylistic changes.

**Comment by naseemkullah** [comment]
bump

**Comment by edsiper** [comment]
please fix the conflicts

**Comment by naseemkullah** [comment]
> please fix the conflicts

done! please merge

**Comment by edsiper** [comment]
thanks everyone!

FYI: I've adjusted the runtime test accordingly
