### PR TITLE
parser: fix time zone offsets being dropped on Windows

### LINKED ISSUE #2941: Parser ignoring timezone
I'm using windows release td-agent-bit-1.6.10-win32. The parser is ignoring the timezone set in the logs.

Here a simple example using the default apache parser:
```
[PARSER]
    Name   apache
    Format regex
    Regex  ^(?<host>[^ ]*) [^ ]* (?<user>[^ ]*) \[(?<time>[^\]]*)\] "(?<method>\S+)(?: +(?<path>[^\"]*?)(?: +\S*)?)?" (?<code>[^ ]*) (?<size>[^ ]*)(?: "(?<referer>[^\"]*)" "(?<agent>[^\"]*)")?$
    Time_Key time
    Time_Format %d/%b/%Y:%H:%M:%S %z

[INPUT]
    name tail
    path /path/to/test.log
    parser apache
    tag  accesslog

[OUTPUT]
    name stdout
    match *
```

My logs:
```
192.168.178.23 test - [13/Jan/2021:10:30:31 -0100] "GET /rest HTTP/1.1" 200 59 "http://localhost/" "Mozilla/5.0"
192.168.178.23 test - [13/Jan/2021:10:30:31 +0000] "GET /rest HTTP/1.1" 200 59 "http://localhost/" "Mozilla/5.0"
192.168.178.23 test - [13/Jan/2021:10:30:31 +0100] "GET /rest HTTP/1.1" 200 59 "http://localhost/" "Mozilla/5.0"
192.168.178.23 test - [13/Jan/2021:10:30:31 +0200] "GET /rest HTTP/1.1" 200 59 "http://localhost/" "Mozilla/5.0"
```

The result:
```
[0] accesslog: [1610533831.000000000, {"host"=>"192.168.178.23", "user"=>"-", "method"=>"GET", "path"=>"/rest", "code"=>"200", "size"=>"59", "referer"=>"http://localhost/", "agent"=>"Mozilla/5.0"}]
[1] accesslog: [1610533831.000000000, {"host"=>"192.168.178.23", "user"=>"-", "method"=>"GET", "path"=>"/rest", "code"=>"200", "size"=>"59", "referer"=>"http://localhost/", "agent"=>"Mozilla/5.0"}]
[2] accesslog: [1610533831.000000000, {"host"=>"192.168.178.23", "user"=>"-", "method"=>"GET", "path"=>"/rest", "code"=>"200", "size"=>"59", "referer"=>"http://localhost/", "agent"=>"Mozilla/5.0"}]
[3] accesslog: [1610533831.000000000, {"host"=>"192.168.178.23", "user"=>"-", "method"=>"GET", "path"=>"/rest", "code"=>"200", "size"=>"59", "referer"=>"http://localhost/", "agent"=>"Mozilla/5.0"}]
```

As you can see, every entry was treated as if it was in "+0000".

### PR DESCRIPTION
**Pull request by jefferbrecht**
Fix time zone offsets being lost on Windows when parsing time stamps.

Fixes #2941.

----

**Testing**
Before we can approve your change; please submit the following in a comment:
- [x] Example configuration file for the change
- [x] Debug log output from testing the change

- [x] Attached [Valgrind](https://valgrind.org/docs/manual/quick-start.html) output that shows no leaks or memory corruption was found

If this is a change to packaging of containers or native binaries then please confirm it works for all targets.
- [ ] Attached [local packaging test](./packaging/local-build-all.sh) output showing all targets (including any new ones) build.

**Documentation**

- [ ] Documentation required for this feature

**Backporting**

- [ ] Backport to latest stable release.

----

Fluent Bit is licensed under Apache 2.0, by submitting this pull request I understand that this code will be released under the terms of that license.

### CODE REVIEW

**Comment by jefferbrecht** [comment]
Looks like the unit tests failed because `flb-rt-out_tcp` timed out on one of the runs. I don't think that test depends on these changes, and the unit tests all pass locally for me too. Maybe it was a fluke? Can we re-run the check?

**Comment by edsiper** [comment]
assigned to @leonardo-albertovich

File: tests/runtime/filter_parser.c [hunk 1]
```diff
@@ -709,10 +789,11 @@ TEST_LIST = {
     {"filter_parser_extract_fields", flb_test_filter_parser_extract_fields },
     {"filter_parser_reserve_data_off", flb_test_filter_parser_reserve_data_off },
     {"filter_parser_handle_time_key", flb_test_filter_parser_handle_time_key },
+    {"filter_parser_handle_time_key_with_time_zone", flb_test_filter_parser_handle_time_key_with_time_zone },
     {"filter_parser_ignore_malformed_time", flb_test_filter_parser_ignore_malformed_time },
     {"filter_parser_preserve_original_field", flb_test_filter_parser_preserve_original_field },
     {"filter_parser_first_matched_when_multiple_parser", flb_test_filter_parser_first_matched_when_mutilple_parser },
-    {"filter_parser_skip_empty_values_false", flb_test_filter_parser_skip_empty_values_false},
+    {"filter_parser_skip_empty_values_false", flb_test_filter_parser_skip_empty_values_false },
```
Comment (cosmo0920) [inline tests/runtime/filter_parser.c:796]: Unexpected adding trailing space here?

**Review by cosmo0920 — COMMENTED** [review]
I added a nitpick comment for style.

File: tests/runtime/filter_parser.c (hunk 1 above)
Comment (jefferbrecht) [reply tests/runtime/filter_parser.c:796]: I was intending to make that one consistent with the other since they all have spaces, but I can remove this to make the diff simpler.
