### PR TITLE
out_http: don't retry non retryable 4xx status codes

### LINKED ISSUE #8860: out_http: don't retry non retryable 4xx status codes
## Bug Report

**Describe the bug**
Currently, the http output plugin retries all requests that respond with an 4xx status code: https://github.com/fluent/fluent-bit/blob/910009855636921dfeabd7defe1cae5c494a4bea/plugins/out_http/http.c#L268 Nevertheless, most 4xx status codes are non retryable and will keep retrying forever.

**To Reproduce**
- Steps to reproduce the problem:
1. Configure fluent-bit with an http output
2. Make the http output return a 400 status code
3. The chunks are retried forever

**Expected behavior**
Don't retry 4xx status codes, except for 429.

**Your Environment**

* Version used: 3.0.4
* Configuration: 
```
[INPUT]
    Name  cpu
    Tag   cpu

[OUTPUT]
    Name  http
    Match *
    Host  192.168.2.3
    Port  80
    URI   /something
```
* Environment name and version (e.g. Kubernetes? What version?): Docker
* Filters and plugins: out_http

### PR DESCRIPTION
**Pull request by IsraelZeromski**
Fix a problem that http output plugin retries all requests that respond with an 4xx status code excepting 429 status code

Fixes #8860

----
Enter `[N/A]` in the box, if an item is not applicable to your change.

**Testing**
Before we can approve your change; please submit the following in a comment:

- [N/A] Example configuration file for the change
- [N/A] Debug log output from testing the change

- [N/A] Attached [Valgrind](https://valgrind.org/docs/manual/quick-start.html) output that shows no leaks or memory corruption was found

If this is a change to packaging of containers or native binaries then please confirm it works for all targets.

- [N/A] Run [local packaging test](./packaging/local-build-all.sh) showing all targets (including any new ones) build.
- [ ] Set `ok-package-test` label to test for all targets (requires maintainer to do).

**Documentation**

- [N/A] Documentation required for this feature

**Backporting**

- [ ] Backport to latest stable release.

----

Fluent Bit is licensed under Apache 2.0, by submitting this pull request I understand that this code will be released under the terms of that license.

### CODE REVIEW

File: plugins/out_http/http.c [hunk 1]
```diff
@@ -276,7 +276,15 @@ static int http_post(struct flb_out_http *ctx,
                 flb_plg_error(ctx->ins, "%s:%i, HTTP status=%i",
                               ctx->host, ctx->port, c->resp.status);
             }
-            out_ret = FLB_RETRY;
+            if (c->resp.status >= 400 && c->resp.status < 500 && c->resp.status != 429) {
+                flb_plg_warn(ctx->ins, "could not flush records to %s:%i (http_do=%i), "
+                                "chunk will not be retried",
+                                ctx->host, ctx->port, ret);
+                out_ret = FLB_ERROR;
```
Comment (mrueg) [inline plugins/out_http/http.c:283]: Does that mean logs will be lost when the endpoint is unavailable?

Comment (IsraelZeromski) [reply plugins/out_http/http.c:283]: if return a code in 4xx range except 429, this means that the are an error in client side in consequence that records will not be retried.

Comment (mrueg) [reply plugins/out_http/http.c:283]: Fluentd has a setting for retryable response codes: https://docs.fluentd.org/output/http#retryable_response_codes maybe we could add this as well?
