### PR TITLE
pack: do not multiply out_size by realloc_size

### LINKED ISSUE #8993: [out_splunk] SIGSEGV with specific chunks
## Bug Report

**Describe the bug**

We're running a set up where we run fluent-bit with a forward input and filesystem buffering. Periodically a chunk lands on the filesystem that upon read crashes fluent-bit. That means every time it restarts it crashes as it tries to replay this chunk from backlog. We haven't been able to reproduce this issue reliably (apart from trying to load it with the faulty chunk, in which case it crashes). I unfortunately can't share the chunk as it contains customer data.

Here's the log line we're seeing upon the crash:
```
[2024/06/21 10:16:25] [engine] caught signal (SIGSEGV)
#0  0x55ae116e4ad3      in  msgpack2json() at src/flb_pack.c:731
#1  0x55ae116e4ad3      in  msgpack2json() at src/flb_pack.c:731
#2  0x55ae116e4ad3      in  msgpack2json() at src/flb_pack.c:731
#3  0x55ae116e4ad3      in  msgpack2json() at src/flb_pack.c:731
#4  0x55ae116e533a      in  flb_msgpack_to_json() at src/flb_pack.c:768
#5  0x55ae116e5457      in  flb_msgpack_raw_to_json_sds() at src/flb_pack.c:808
#6  0x55ae117e5bc3      in  splunk_format() at plugins/out_splunk/splunk.c:500
#7  0x55ae117e6424      in  cb_splunk_flush() at plugins/out_splunk/splunk.c:658
#8  0x55ae11c03ae6      in  co_init() at lib/monkey/deps/flb_libco/amd64.c:117
#9  0xffffffffffffffff  in  ???() at ???:0
```

**Your Environment**

* Version used: 3.0.6
* Configuration:
```
 [SERVICE]
        HTTP_Server On
        Health_Check On

        Storage.max_chunks_up 512
        Storage.backlog.mem_limit 100M

        Storage.path /var/log/flb-storage/

        Storage.sync normal
        Storage.metrics On
    [INPUT]
        Name Forward
        Storage.type filesystem

    [OUTPUT]
        Name Splunk
        Match *
        Host <our host>
        Port 443
        Splunk_Token ${SPLUNK_TOKEN}
        TLS On
        TLS.Verify On
        Event_index <index>
        Event_sourcetype fluentd

        Retry_Limit False
        Storage.total_limit_size 10GB


```
* Environment name and version (e.g. Kubernetes? What version?): Kubernetes (but we can also reproduce locally if we offload the same chunk). We're using eks kubernetes v1.28
* Server type and version:
* Operating System and version: 
* Filters and plugins: 

**Additional context**

We tried adjusting the chunk to determine which lines specifically in it might cause the crash, but were unable to manipulate the chunks in a way that would make them readable.

Please advise what we could try to assist with solving this somehow. 

We have a strong suspicion that this appeared after we bumped to v3. the only somewhat relevant code change we found was here: https://github.com/fluent/fluent-bit/pull/8589/files

### LINKED ISSUE #9192: Buffer overrun when reallocating JSON buffer in `flb_msgpack_raw_to_json_sds`
## Bug Report

**Describe the bug**
Starting in at least Fluent Bit v3.0.4 (discovered after upgrading from v2.1.2) Fluent Bit will occasionally crash with buffer overruns stemming from the `flb_msgpack_raw_to_json_sds` function.

**To Reproduce**
The way I reproduced this was by triggering this through `out_stackdriver`, which calls this function to convert msgpack data to a JSON string representing our Cloud Logging HTTP request. The way to consistently make this occur is when logging binary data through `in_tail` (a bad idea that isn't supported, but it is the most consistent way to trigger the bug). On a linux machine, I tailed `/var/log/wtmp` to reproduce.

Configuration:
```
[SERVICE]
    Daemon                    off
    Flush                     1
    Log_Level                 info
    dns.resolver              legacy

[INPUT]
    Buffer_Chunk_Size 512k
    Buffer_Max_Size   2M
    Key               message
    Mem_Buf_Limit     10M
    Name              tail
    Path              /var/log/wtmp
    Read_from_Head    True
    Rotate_Wait       30
    Skip_Long_Lines   On
    Tag               x

[OUTPUT]
    Match                         x
    Name                          stackdriver
    Retry_Limit                   3
    net.connect_timeout_log_error False
    resource                      gce_instance
    storage.total_limit_size      2G
    tls                           On
    tls.verify                    Off
    workers                       8
```

This configuration works only on a GCE instance. There may be another easier way to reproduce, as the root cause seems to be upon reallocating the buffer in `flb_msgpack_raw_to_json_sds`, so any method to cause that.

When using this configuration, it oughta crash with a segfault. We've seen some other examples in production of having random malloc errors from glibc like `size mismatch` and `malloc invalid size unsorted` among others.

**Expected behavior**
Fluent Bit should not crash.

**Screenshots**

**Your Environment**

* Version used: 3.0.4
* Configuration: See repro steps
* Environment name and version (e.g. Kubernetes? What version?): I tested largely on a GCE VM. Does not seem relevant to the bug
* Server type and version:
* Operating System and version: Debian Bookworm
* Filters and plugins: See repro steps

**Additional context**

Following a `git bisect` using the reproduction steps, the bad commit turned out to be: https://github.com/fluent/fluent-bit/commit/22f25c5395a2efbe6f83f71366bb8399623c1364

### PR DESCRIPTION
**Pull request by braydonk**
In `flb_msgpack_raw_to_json_sds`, when the buffer is reallocated it calls `flb_sds_increase`. This increases the length by adding the `len` argument to the length and reallocating the sds object. After doing this, the `out_size` is multiplied by `realloc_size`. This does not match reality, as what happened in the reallocation was additive not multiplicative. This commit corrects the inconsistency.

Fixes #9192.
Fixes #8993.

----
Enter `[N/A]` in the box, if an item is not applicable to your change.

**Testing**
Before we can approve your change; please submit the following in a comment:

- [ ] Example configuration file for the change
- [ ] Debug log output from testing the change

- [ ] Attached [Valgrind](https://valgrind.org/docs/manual/quick-start.html) output that shows no leaks or memory corruption was found

If this is a change to packaging of containers or native binaries then please confirm it works for all targets.

- [ ] Run [local packaging test](./packaging/local-build-all.sh) showing all targets (including any new ones) build.
- [ ] Set `ok-package-test` label to test for all targets (requires maintainer to do).

**Documentation**

- [ ] Documentation required for this feature

**Backporting**

- [ ] Backport to latest stable release.

----

Fluent Bit is licensed under Apache 2.0, by submitting this pull request I understand that this code will be released under the terms of that license.

### CODE REVIEW

File: src/flb_pack.c [hunk 1]
```diff
@@ -810,7 +810,7 @@ flb_sds_t flb_msgpack_raw_to_json_sds(const void *in_buf, size_t in_size)
             tmp_buf = flb_sds_increase(out_buf, realloc_size);
             if (tmp_buf) {
                 out_buf = tmp_buf;
-                out_size *= realloc_size;
+                out_size += realloc_size;
```
Comment (edsiper) [inline src/flb_pack.c:813]: good catch. what about to setting `out_size` with `flb_sds_alloc()` ?

https://github.com/fluent/fluent-bit/blob/master/include/fluent-bit/flb_sds.h#L67-L70

Comment (braydonk) [reply src/flb_pack.c]: Done in [087ccda](https://github.com/fluent/fluent-bit/pull/9193/commits/087ccda70f195852319f46a11951e7af64216741). Tested and it seems to work as expected.

**Comment by edsiper** [comment]
thank you
