### PR TITLE
out_s3: fix memory leak when gzip is on

### LINKED ISSUE #3204: Possible Memory leak when using S3 output
## Bug Report

**Describe the bug**
When using 2 configurations, with all else being equal except for one outputting to null and the other to s3,
fluentbit memory usage balloons up to 5gb and then dies.

**To Reproduce**
here is the output config:
```
[OUTPUT]
    Name                         s3
    Alias                        something_logs
    Match                        something_logs.*
    bucket                       devnulluseast1
    region                       us-east-1
    total_file_size              50M
    upload_timeout               2m
    store_dir                    /var/lib/td-agent-bit/s3_envoy
    s3_key_format                /fluentbit-envoy/<%= @dc %>/<%= @fqdn %>/%Y/%m/%d/%H/%M/%S/$TAG
    s3_key_format_tag_delimiters .-_
    compression                  gzip
    use_put_object               On
```

- Steps to reproduce the problem:
get lots of logs
use this output

**Expected behavior**
For it to use at most 2gb memory

**Screenshots**
not applicable

**Your Environment**

* Version used: 1.6, 1.7.2
* Configuration:
```
[SERVICE]
    Log_Level                 info
    Daemon                    off
    HTTP_Server               On
    HTTP_Listen               0.0.0.0
    HTTP_Port                 2020
    mem_buf_limit             2G
    storage.path              /var/lib/td-agent-bit/storage
    storage.sync              normal
    storage.checksum          off
    storage.backlog.mem_limit 200M
    Parsers_File              /etc/td-agent-bit/parsers.conf
    storage.metrics           on
    tls.verify                false
    tls                       off

[INPUT]
    name                tail
    path                /var/log/nginx/dispatcher.access.json.log,/var/log/nginx/dispatcher.access.json.log.*
    Ignore_Older        6h
    parser              json_parser
    Path_Key            filename
    Alias               nginx_logs_input
    Buffer_Max_Size     64k
    Exclude_Path        *.gz,*.zip
    Tag                 nginx_logs.*
    Refresh_Interval    5
    Skip_Long_Lines     On
    DB                  /var/lib/td-agent-bit/nginx_logs.db
    DB.locking          true
    Mem_Buf_Limit       50M
    storage.type        filesystem
    Key                 event

[INPUT]
    name                tail
    path                /var/log/envoy/egress.json
    Ignore_Older        6h
    parser              json_parser
    Path_Key            filename
    Alias               envoy_logs_input
    Buffer_Max_Size     64k
    Exclude_Path        *.gz,*.zip
    Tag                 envoy_logs.*
    Refresh_Interval    5
    Skip_Long_Lines     On
    DB                  /var/lib/td-agent-bit/envoy_logs.db
    DB.locking          true
    Mem_Buf_Limit       50M
    storage.type        filesystem
    Key                 event
    
[FILTER]
    Name    lua
    Alias   lua_nginx_logs
    Match   nginx_logs.*
    script  /etc/td-agent-bit/transforms.lua
    call    nginx_log

[FILTER]
    Name    lua
    Alias   lua_envoy_logs
    Match   envoy_logs.*
    script  /etc/td-agent-bit/transforms.lua
    call    fix_envoy_log

[FILTER]
    Name    record_modifier
    Alias   record_modifier_envoy_logs_hostname
    Match   envoy_logs.*
    Record  hostname <%= @fqdn %>

[OUTPUT]
    Name                         null
    Alias                        nginx_logs
    Match                        nginx_logs.*

[OUTPUT]
    Name                         null
    Alias                        envoy_logs
    Match                        envoy_logs.*
```

* Environment name and version (e.g. Kubernetes? What version?):
happens both in k8s and in plain debian9
* Server type and version:
happens both in k8s and in plain debian9
* Operating System and version:
debian 9
* Filters and plugins:
Listed in configuration

**Additional context**

### PR DESCRIPTION
**Pull request by zhonghui12**
Signed-off-by: Zhonghui Hu <zh0512xx@gmail.com>

Fix the memory leak problem when gzip is enabled.

fixes #3204 
----
Enter `[N/A]` in the box, if an item is not applicable to your change.

**Testing**
Before we can approve your change; please submit the following in a comment:
- [ ] Example configuration file for the change
- [x] Debug log output from testing the change

- [x] Attached [Valgrind](https://valgrind.org/docs/manual/quick-start.html) output that shows no leaks or memory corruption was found
```
==20787== HEAP SUMMARY:
==20787==     in use at exit: 102,608 bytes in 3,429 blocks
==20787==   total heap usage: 91,100 allocs, 87,671 frees, 16,588,826 bytes allocated
==20787== 
==20787== LEAK SUMMARY:
==20787==    definitely lost: 0 bytes in 0 blocks
==20787==    indirectly lost: 0 bytes in 0 blocks
==20787==      possibly lost: 368 bytes in 1 blocks
==20787==    still reachable: 102,240 bytes in 3,428 blocks
==20787==         suppressed: 0 bytes in 0 blocks
==20787== Rerun with --leak-check=full to see details of leaked memory
==20787== 
```

**Documentation**

- [ ] Documentation required for this feature

----

Fluent Bit is licensed under Apache 2.0, by submitting this pull request I understand that this code will be released under the terms of that license.

### CODE REVIEW

**Comment by zhonghui12** [comment]
@PettitWesley

File: plugins/out_s3/s3.c [hunk 1]
```diff
@@ -1098,6 +1098,7 @@ static int s3_put_object(struct flb_s3 *ctx, const char *tag, time_t create_time
             return -1;
         }
         final_body = (char *) compressed_body;
+        flb_free(compressed_body);
```
Comment (PettitWesley) [inline plugins/out_s3/s3.c:1101]: this doesn't work. The line above does not copy memory, it copies the address.

You need to write code after the call to S3 API which frees the compressed body IFF compression is turned on. Some solution like that.

**Review by PettitWesley — APPROVED** [review]
