### PR TITLE
in_winevtlog: properly pass the log encoder arg

### LINKED ISSUE #7270: Fluentbit 2.1.1 with winevtlog as input crashes when new event arrives
## Bug Report

**Describe the bug**
Using wineventlog as an input to get some eventviewer entries crashes the application.

**To Reproduce**
Download the zip file for Fluentbit 2.1.1 for Windows 64 bits
Extract the content whatever you want
Run the following command in command prompt with administrative privileges
``fluent-bit.exe -v -i winevtlog -p "channels=Microsoft-Windows-Time-Service/Operational" -o stdout``
Start/Stop Windows Time service in services manager

**Logs**
```
D:\Downloads\fluent-bit-2.1.1-win64\bin>fluent-bit.exe -v -i winevtlog -p "channels=Microsoft-Windows-Time-Service/Operational" -o stdout
Fluent Bit v2.1.1
* Copyright (C) 2015-2022 The Fluent Bit Authors
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io

[2023/04/25 15:31:48] [ info] Configuration:
[2023/04/25 15:31:48] [ info]  flush time     | 1.000000 seconds
[2023/04/25 15:31:48] [ info]  grace          | 5 seconds
[2023/04/25 15:31:48] [ info]  daemon         | 0
[2023/04/25 15:31:48] [ info] ___________
[2023/04/25 15:31:48] [ info]  inputs:
[2023/04/25 15:31:48] [ info]      winevtlog
[2023/04/25 15:31:48] [ info] ___________
[2023/04/25 15:31:48] [ info]  filters:
[2023/04/25 15:31:48] [ info] ___________
[2023/04/25 15:31:48] [ info]  outputs:
[2023/04/25 15:31:48] [ info]      stdout.0
[2023/04/25 15:31:48] [ info] ___________
[2023/04/25 15:31:48] [ info]  collectors:
[2023/04/25 15:31:48] [ info] [fluent bit] version=2.1.1, commit=8144c1f4f3, pid=11140
[2023/04/25 15:31:48] [debug] [engine] coroutine stack size: 98302 bytes (96.0K)
[2023/04/25 15:31:48] [ info] [storage] ver=1.4.0, type=memory, sync=normal, checksum=off, max_chunks_up=128
[2023/04/25 15:31:48] [ info] [cmetrics] version=0.6.1
[2023/04/25 15:31:48] [ info] [ctraces ] version=0.3.0
[2023/04/25 15:31:48] [ info] [input:winevtlog:winevtlog.0] initializing
[2023/04/25 15:31:48] [ info] [input:winevtlog:winevtlog.0] storage_strategy='memory' (memory only)
[2023/04/25 15:31:48] [debug] [winevtlog:winevtlog.0] created event channels: read=800 write=804
[2023/04/25 15:31:48] [debug] [stdout:stdout.0] created event channels: read=852 write=856
[2023/04/25 15:31:48] [ info] [sp] stream processor started
[2023/04/25 15:31:48] [ info] [output:stdout:stdout.0] worker #0 started

D:\Downloads\fluent-bit-2.1.1-win64\bin>
```

In EventViewer/Application the following errors appear.

Log Name:      Application
Source:        Application Error
Date:          4/25/2023 2:44:23 PM
Event ID:      1000
Task Category: (100)
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      
Description:
Faulting application name: fluent-bit.exe, version: 2.1.1.0, time stamp: 0x64416e2d
Faulting module name: fluent-bit.exe, version: 2.1.1.0, time stamp: 0x64416e2d
Exception code: 0xc0000005
Fault offset: 0x00000000000b7620
Faulting process id: 0x47f0
Faulting application start time: 0x01d9779d759cc01d
Faulting application path: D:\Downloads\fluent-bit-2.1.1-win64\bin\fluent-bit.exe
Faulting module path: D:\Downloads\fluent-bit-2.1.1-win64\bin\fluent-bit.exe
Report Id: 10992ee7-b5ec-46af-8e08-1076afce3d6b
Faulting package full name: 
Faulting package-relative application ID: 

And

Log Name:      Application
Source:        Windows Error Reporting
Date:          4/25/2023 2:44:26 PM
Event ID:      1001
Task Category: None
Level:         Information
Keywords:      Classic
User:          N/A
Computer:      
Description:
Fault bucket 1317598245555443454, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: fluent-bit.exe
P2: 2.1.1.0
P3: 64416e2d
P4: fluent-bit.exe
P5: 2.1.1.0
P6: 64416e2d
P7: c0000005
P8: 00000000000b7620
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER16FF.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER173E.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER175F.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER176C.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER17BB.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_fluent-bit.exe_c0fe8187dea40a23d30a6d030e3ff1d95519257_a3b28f93_cfa2acd7-802e-4af5-b42b-3ca3374e3b38

Analysis symbol: 
Rechecking for solution: 0
Report Id: 10992ee7-b5ec-46af-8e08-1076afce3d6b
Report Status: 268435456
Hashed bucket: 2930a8dd6871a36712490c9f970296fe
Cab Guid: 0

**Expected behavior**
New events captured for processing

**Your Environment**
* Version used: 2.1.1
* Configuration: Default configuration provided with the package
* Operating System and version:
OS Name:                   Microsoft Windows 10 Enterprise
OS Version:                10.0.19045 N/A Build 19045

* Filters and plugins:
Default configuration provided with the package

**Additional context**
This issue does not occur in version 2.0.9
Steps to reproduce the expected behavion in version 2.0.9
Download and extract the package;
Run a command prompt with administrative rights
Execute the same command as before
Start/Stop the Windows Time Service

**Execution Log version 2.0.9**
No events are created in Event Viewer

D:\Downloads\fluent-bit-2.0.9-win64\fluent-bit-2.0.9-win64\bin>fluent-bit.exe -v -i winevtlog -p "channels=Microsoft-Windows-Time-Service/Operational" -o stdout
```
Fluent Bit v2.0.9
* Copyright (C) 2015-2022 The Fluent Bit Authors
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io

[2023/04/25 15:31:38] [ info] Configuration:
[2023/04/25 15:31:38] [ info]  flush time     | 1.000000 seconds
[2023/04/25 15:31:38] [ info]  grace          | 5 seconds
[2023/04/25 15:31:38] [ info]  daemon         | 0
[2023/04/25 15:31:38] [ info] ___________
[2023/04/25 15:31:38] [ info]  inputs:
[2023/04/25 15:31:38] [ info]      winevtlog
[2023/04/25 15:31:38] [ info] ___________
[2023/04/25 15:31:38] [ info]  filters:
[2023/04/25 15:31:38] [ info] ___________
[2023/04/25 15:31:38] [ info]  outputs:
[2023/04/25 15:31:38] [ info]      stdout.0
[2023/04/25 15:31:38] [ info] ___________
[2023/04/25 15:31:38] [ info]  collectors:
[2023/04/25 15:31:38] [ info] [fluent bit] version=2.0.9, commit=4c0ca4fc5f, pid=10120
[2023/04/25 15:31:38] [debug] [engine] coroutine stack size: 98302 bytes (96.0K)
[2023/04/25 15:31:38] [ info] [storage] ver=1.4.0, type=memory, sync=normal, checksum=off, max_chunks_up=128
[2023/04/25 15:31:38] [ info] [cmetrics] version=0.5.8
[2023/04/25 15:31:38] [ info] [ctraces ] version=0.2.7
[2023/04/25 15:31:38] [ info] [input:winevtlog:winevtlog.0] initializing
[2023/04/25 15:31:38] [ info] [input:winevtlog:winevtlog.0] storage_strategy='memory' (memory only)
[2023/04/25 15:31:38] [debug] [winevtlog:winevtlog.0] created event channels: read=808 write=812
[2023/04/25 15:31:38] [debug] [stdout:stdout.0] created event channels: read=860 write=864
[2023/04/25 15:31:38] [ info] [sp] stream processor started
[2023/04/25 15:31:38] [ info] [output:stdout:stdout.0] worker #0 started
[2023/04/25 15:31:54] [debug] [input:winevtlog:winevtlog.0] read 648 bytes from 'Microsoft-Windows-Time-Service/Operational'
[2023/04/25 15:31:54] [debug] [input chunk] update output instances with new chunk size diff=674
[2023/04/25 15:31:55] [debug] [task] created task=000002AA8675E4B0 id=0 OK
[2023/04/25 15:31:55] [debug] [output:stdout:stdout.0] task_id=0 assigned to thread #0
[0] winevtlog.0: [1682447514.718930100, {"ProviderName"=>"Microsoft-Windows-Time-Service", "ProviderGuid"=>"{06EDCFEB-0FD0-4E53-ACCA-A6F8BBF81BCB}", "Qualifiers"=>"", "EventID"=>258, "Version"=>0, "Level"=>4, "Task"=>0, "Opcode"=>0, "Keywords"=>"0x4000000000000000", "TimeCreated"=>"2023-04-25 15:31:53 -0300", "EventRecordID"=>844, "ActivityID"=>"", "RelatedActivityID"=>"", "ProcessID"=>15752, "ThreadID"=>25140, "Channel"=>"Microsoft-Windows-Time-Service/Operational", "Computer"=>"DESKTOP-9P94437", "UserID"=>"S-1-5-19", "Message"=>"W32time service is stopping at 2023-04-25T18:31:53.90Z (UTC), System Tick Count 109613703 with return code: 0x00000000: Success.
For more information, see https://go.microsoft.com/fwlink/?linkid=845961.", "StringInserts"=>["2023-04-25T18:31:53.90Z", 109613703, "0x00000000: Success."]}]
[2023/04/25 15:31:55] [debug] [out flush] cb_destroy coro_id=0
[2023/04/25 15:31:55] [debug] [task] destroy task=000002AA8675E4B0 (task_id=0)
[2023/04/25 15:32:18] [engine] caught signal (SIGINT)
[2023/04/25 15:32:18] [ warn] [engine] service will shutdown in max 5 seconds
[2023/04/25 15:32:18] [ info] [input] pausing winevtlog.0
[2023/04/25 15:32:19] [ info] [engine] service has stopped (0 pending tasks)
[2023/04/25 15:32:19] [ info] [input] pausing winevtlog.0
[2023/04/25 15:32:19] [ info] [output:stdout:stdout.0] thread worker #0 stopping...
```

### PR DESCRIPTION
**Pull request by braydonk**
In this particular function, we were accidentally passing in the actual `winevtlog_config` instead of the log_encoder field of the config. This caused Fluent Bit to crash with an access violation error, since it gets a completely unexpected shape of data.

Fixes #7270

----
Enter `[N/A]` in the box, if an item is not applicable to your change.

**Testing**
Before we can approve your change; please submit the following in a comment:
- [N/A] Example configuration file for the change
- [x] Debug log output from testing the change

- [N/A] Attached [Valgrind](https://valgrind.org/docs/manual/quick-start.html) output that shows no leaks or memory corruption was found

If this is a change to packaging of containers or native binaries then please confirm it works for all targets.
- [N/A] Run [local packaging test](./packaging/local-build-all.sh) showing all targets (including any new ones) build.
- [N/A] Set `ok-package-test` label to test for all targets (requires maintainer to do).

**Documentation**

- [N/A] Documentation required for this feature

**Backporting**

- [N/A] Backport to latest stable release.

No need to backport because this is a bug introduced in 2.1.

----

Fluent Bit is licensed under Apache 2.0, by submitting this pull request I understand that this code will be released under the terms of that license.

### CODE REVIEW

File: plugins/in_winevtlog/pack.c [hunk 1]
```diff
@@ -301,45 +301,45 @@ static void pack_string_inserts(struct winevtlog_config *ctx, PEVT_VARIANT value
             }
             break;
         case EvtVarTypeSByte:
-            flb_log_event_encoder_append_body_int8(ctx, values[i].SByteVal);
+            flb_log_event_encoder_append_body_int8(ctx->log_encoder, values[i].SByteVal);
```
Comment (igorpeshansky) [inline plugins/in_winevtlog/pack.c:304]: Are there any tests that need to be updated?

**Review by igorpeshansky — DISMISSED** [review]
LGTM :shipit:

File: plugins/in_winevtlog/pack.c (hunk 1 above)
Comment (braydonk) [reply plugins/in_winevtlog/pack.c:304]: I was going to, but there appear not to be any unit tests for this plugin. They would be a great thing to have though...

**Comment by braydonk** [comment]
Debug log output (does GitHub shorten this? let's find out)
```
PS C:\Users\braydonk\Git\fluent-bit\build\bin\Release> ./fluent-bit.exe -v -i winevtlog -p "channels=Microsoft-Windows-Time-Service/Operational" -o stdout
Fluent Bit v2.1.1
* Copyright (C) 2015-2022 The Fluent Bit Authors
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io

[2023/04/26 03:04:49] [ info] Configuration:
[2023/04/26 03:04:49] [ info]  flush time     | 1.000000 seconds
[2023/04/26 03:04:49] [ info]  grace          | 5 seconds
[2023/04/26 03:04:49] [ info]  daemon         | 0
[2023/04/26 03:04:49] [ info] ___________
[2023/04/26 03:04:49] [ info]  inputs:
[2023/04/26 03:04:49] [ info]      winevtlog
[2023/04/26 03:04:49] [ info] ___________
[2023/04/26 03:04:49] [ info]  filters:
[2023/04/26 03:04:49] [ info] ___________
[2023/04/26 03:04:49] [ info]  outputs:
[2023/04/26 03:04:49] [ info]      stdout.0
[2023/04/26 03:04:49] [ info] ___________
[2023/04/26 03:04:49] [ info]  collectors:
[2023/04/26 03:04:49] [ info] [fluent bit] version=2.1.1, commit=7e0bbec8b6, pid=1204
[2023/04/26 03:04:49] [debug] [engine] coroutine stack size: 98302 bytes (96.0K)
[2023/04/26 03:04:49] [ info] [storage] ver=1.4.0, type=memory, sync=normal, checksum=off, max_chunks_up=128
[2023/04/26 03:04:49] [ info] [cmetrics] version=0.6.1
[2023/04/26 03:04:49] [ info] [ctraces ] version=0.3.0
[2023/04/26 03:04:49] [ info] [input:winevtlog:winevtlog.0] initializing
[2023/04/26 03:04:49] [ info] [input:winevtlog:winevtlog.0] storage_strategy='memory' (memory only)
[2023/04/26 03:04:49] [debug] [winevtlog:winevtlog.0] created event channels: read=824 write=828
[2023/04/26 03:04:49] [debug] [stdout:stdout.0] created event channels: read=864 write=868
[2023/04/26 03:04:49] [ info] [sp] stream processor started
[2023/04/26 03:04:49] [ info] [output:stdout:stdout.0] worker #0 started
[2023/04/26 03:04:54] [debug] [input:winevtlog:winevtlog.0] read 1336 bytes from 'Microsoft-Windows-Time-Service/Operational'
[2023/04/26 03:04:54] [debug] [input chunk] update output instances with new chunk size diff=1425
[2023/04/26 03:04:55] [debug] [task] created task=000001CF97B9F990 id=0 OK
[0] winevtlog.0: [[1682478294.261799300, {}], {[2023/04/26 03:04:55] [debug] [output:stdout:stdout.0] task_id=0 assigned to thread #0
"ProviderName"=>"Microsoft-Windows-Time-Service", "ProviderGuid"=>"{06EDCFEB-0FD0-4E53-ACCA-A6F8BBF81BCB}", "Qualifiers"=>"", "EventID"=>261, "Version"=>0, "Level"=>4, "Task"=>0, "Opcode"=>0, "Keywords"=>"0x4000000000000000", "TimeCreated"=>"2023-04-26 03:04:53 +0000", "EventRecordID"=>911, "ActivityID"=>"", "RelatedActivityID"=>"", "ProcessID"=>16380, "ThreadID"=>15532, "Channel"=>"Microsoft-Windows-Time-Service/Operational", "Computer"=>"win2019-dev-machine", "UserID"=>"S-1-5-19", "Message"=>"W32time service has set the system time to 2023-04-26T03:04:53.855Z(UTC). Previous system time was 2023-04-26T03:04:53.852Z(UTC). System Tick Count: 1206877984
For more information, see https://go.microsoft.com/fwlink/?linkid=845961.", "StringInserts"=>"2023-04-26T03:04:53.855Z", "2023-04-26T03:04:53.852Z"=>1206877984}]
[1] winevtlog.0: [[1682478294.262998600, {}], {"ProviderName"=>"Microsoft-Windows-Time-Service", "ProviderGuid"=>"{06EDCFEB-0FD0-4E53-ACCA-A6F8BBF81BCB}", "Qualifiers"=>"", "EventID"=>258, "Version"=>0, "Level"=>4, "Task"=>0, "Opcode"=>0, "Keywords"=>"0x4000000000000000", "TimeCreated"=>"2023-04-26 03:04:53 +0000", "EventRecordID"=>912, "ActivityID"=>"", "RelatedActivityID"=>"", "ProcessID"=>16380, "ThreadID"=>14644, "Channel"=>"Microsoft-Windows-Time-Service/Operational", "Computer"=>"win2019-dev-machine", "UserID"=>"S-1-5-19", "Message"=>"W32time service is stopping at 2023-04-26T03:04:53.858Z (UTC), System Tick Count 1206877984 with return code: 0x00000000: Success.
For more information, see https://go.microsoft.com/fwlink/?linkid=845961.", "StringInserts"=>"2023-04-26T03:04:53.858Z", 1206877984=>"0x00000000: Success."}]
[2023/04/26 03:04:55] [debug] [out flush] cb_destroy coro_id=0
[2023/04/26 03:04:55] [debug] [task] destroy task=000001CF97B9F990 (task_id=0)
[2023/04/26 03:04:56] [debug] [input:winevtlog:winevtlog.0] read 4816 bytes from 'Microsoft-Windows-Time-Service/Operational'
[2023/04/26 03:04:56] [debug] [input chunk] update output instances with new chunk size diff=5472
[2023/04/26 03:04:57] [debug] [task] created task=000001CF97BA0A90 id=0 OK
[0] winevtlog.0: [[1682478296.263893500, {}], [2023/04/26 03:04:57] [debug] [output:stdout:stdout.0] task_id=0 assigned to thread #0
{"ProviderName"=>"Microsoft-Windows-Time-Service", "ProviderGuid"=>"{06EDCFEB-0FD0-4E53-ACCA-A6F8BBF81BCB}", "Qualifiers"=>"", "EventID"=>272, "Version"=>0, "Level"=>4, "Task"=>0, "Opcode"=>0, "Keywords"=>"0x4000000000000000", "TimeCreated"=>"2023-04-26 03:04:55 +0000", "EventRecordID"=>913, "ActivityID"=>"", "RelatedActivityID"=>"", "ProcessID"=>7216, "ThreadID"=>9668, "Channel"=>"Microsoft-Windows-Time-Service/Operational", "Computer"=>"win2019-dev-machine", "UserID"=>"S-1-5-19", "Message"=>"Leap second configuration:
Enabled: 1 (Local)
Count: 0 (Local)
Current Offset from UTC(Seconds): 0 (Local)
Runtime state consistent with settings: 1
Newest Leap Seconds List (Local):

System Tick Count: 1206879312.

For more information, see https://go.microsoft.com/fwlink/?linkid=845961.", "StringInserts"=>1, 0=>0, 1=>""}]
[2023/04/26 03:04:57] [error] [output:stdout:stdout.0] decoder error : -4
[2023/04/26 03:04:57] [debug] [task] destroy task=000001CF97BA0A90 (task_id=0)
[2023/04/26 03:04:57] [debug] [out flush] cb_destroy coro_id=1
[2023/04/26 03:05:01] [debug] [input:winevtlog:winevtlog.0] read 696 bytes from 'Microsoft-Windows-Time-Service/Operational'
[2023/04/26 03:05:01] [debug] [input chunk] update output instances with new chunk size diff=821
[2023/04/26 03:05:02] [debug] [task] created task=000001CF97B9F910 id=0 OK
[0] winevtlog.0: [[1682478301.283720200, {}], {"[2023/04/26 03:05:02] [debug] [output:stdout:stdout.0] task_id=0 assigned to thread #0
ProviderName"=>"Microsoft-Windows-Time-Service", "ProviderGuid"=>"{06EDCFEB-0FD0-4E53-ACCA-A6F8BBF81BCB}", "Qualifiers"=>"", "EventID"=>264, "Version"=>0, "Level"=>4, "Task"=>0, "Opcode"=>0, "Keywords"=>"0x4000000000000000", "TimeCreated"=>"2023-04-26 03:05:00 +0000", "EventRecordID"=>916, "ActivityID"=>"", "RelatedActivityID"=>"", "ProcessID"=>7216, "ThreadID"=>12548, "Channel"=>"Microsoft-Windows-Time-Service/Operational", "Computer"=>"win2019-dev-machine", "UserID"=>"S-1-5-19", "Message"=>"NTP Client observed a change peer reachability. Ntp Client is now receiving time data from the following NTP Servers: metadata.google.internal,0x1 (ntp.m|0x1|0.0.0.0:123->169.254.169.254:123);. System Tick Count: 1206884140.
For more information, see https://go.microsoft.com/fwlink/?linkid=845961.", "StringInserts"=>"metadata.google.internal,0x1 (ntp.m|0x1|0.0.0.0:123->169.254.169.254:123);"}]
[2023/04/26 03:05:02] [error] [output:stdout:stdout.0] decoder error : -4
[2023/04/26 03:05:02] [debug] [out flush] cb_destroy coro_id=2
[2023/04/26 03:05:02] [debug] [task] destroy task=000001CF97B9F910 (task_id=0)
[2023/04/26 03:05:12] [debug] [input:winevtlog:winevtlog.0] read 1392 bytes from 'Microsoft-Windows-Time-Service/Operational'
[2023/04/26 03:05:12] [debug] [input chunk] update output instances with new chunk size diff=1733
[2023/04/26 03:05:13] [debug] [task] created task=000001CF97B9F490 id=0 OK
[0] winevtlog.0: [[1682478312.277244400, {}], {"ProviderName"[2023/04/26 03:05:13] [debug] [output:stdout:stdout.0] task_id=0 assigned to thread #0
=>"Microsoft-Windows-Time-Service", "ProviderGuid"=>"{06EDCFEB-0FD0-4E53-ACCA-A6F8BBF81BCB}", "Qualifiers"=>"", "EventID"=>265, "Version"=>0, "Level"=>4, "Task"=>0, "Opcode"=>0, "Keywords"=>"0x4000000000000000", "TimeCreated"=>"2023-04-26 03:05:11 +0000", "EventRecordID"=>917, "ActivityID"=>"", "RelatedActivityID"=>"", "ProcessID"=>7216, "ThreadID"=>12908, "Channel"=>"Microsoft-Windows-Time-Service/Operational", "Computer"=>"win2019-dev-machine", "UserID"=>"S-1-5-19", "Message"=>"The time service is now synchronizing the system time with the reference time source metadata.google.internal,0x1 (ntp.m|0x1|0.0.0.0:123->169.254.169.254:123) with reference id 0xA9FEA9FE. Current local stratum number is 3, System Tick Count: 1206895343.
For more information, see https://go.microsoft.com/fwlink/?linkid=845961.", "StringInserts"=>"metadata.google.internal,0x1 (ntp.m|0x1|0.0.0.0:123->169.254.169.254:123)", "0xA9FEA9FE"=>3}]
[2023/04/26 03:05:13] [error] [output:stdout:stdout.0] decoder error : -4
[2023/04/26 03:05:13] [debug] [out flush] cb_destroy coro_id=3
[2023/04/26 03:05:13] [debug] [task] destroy task=000001CF97B9F490 (task_id=0)
[2023/04/26 03:05:14] [debug] [input:winevtlog:winevtlog.0] read 640 bytes from 'Microsoft-Windows-Time-Service/Operational'
[2023/04/26 03:05:14] [debug] [input chunk] update output instances with new chunk size diff=871
[2023/04/26 03:05:15] [debug] [task] created task=000001CF97B9FB10 id=0 OK
[0] winevtlog.0: [[1682478314.273482800, {}], {"[2023/04/26 03:05:15] [debug] [output:stdout:stdout.0] task_id=0 assigned to thread #0
ProviderName"=>"[2023/04/26 03:05:15] [debug] [input:winevtlog:winevtlog.0] read 640 bytes from 'Microsoft-Windows-Time-Service/Operational'
Microsoft-Windows-Time-Service", "ProviderGuid"[2023/04/26 03:05:15] [debug] [input chunk] update output instances with new chunk size diff=871
=>"{06EDCFEB-0FD0-4E53-ACCA-A6F8BBF81BCB}", "Qualifiers"=>"", "EventID"=>262, "Version"=>0, "Level"=>4, "Task"=>0, "Opcode"=>0, "Keywords"=>"0x4000000000000000", "TimeCreated"=>"2023-04-26 03:05:13 +0000", "EventRecordID"=>919, "ActivityID"=>"", "RelatedActivityID"=>"", "ProcessID"=>7216, "ThreadID"=>13020, "Channel"=>"Microsoft-Windows-Time-Service/Operational", "Computer"=>"win2019-dev-machine", "UserID"=>"S-1-5-19", "Message"=>"W32time service has adjusted the system clock rate by 3722.90015 PPM and the new nominal clock rate is 155668. Previous nominal clock rate was 155629. System Tick Count: 1206897343.
Clock adjustments below 800.00000 PPM are not logged. Performance counters are recommended to efficiently track small adjustment values.
For more information, see https://go.microsoft.com/fwlink/?linkid=845961.", "StringInserts"=>"3722.90015", 155668=>155629, 1206897343=>"800.00000"}]
[2023/04/26 03:05:15] [debug] [out flush] cb_destroy coro_id=4
[2023/04/26 03:05:15] [debug] [task] destroy task=000001CF97B9FB10 (task_id=0)
[2023/04/26 03:05:16] [debug] [task] created task=000001CF97BA0A90 id=0 OK
[0] winevtlog.0: [[1682478315.276601300, {}], {"[2023/04/26 03:05:16] [debug] [output:stdout:stdout.0] task_id=0 assigned to thread #0
ProviderName[2023/04/26 03:05:16] [debug] [input:winevtlog:winevtlog.0] read 640 bytes from 'Microsoft-Windows-Time-Service/Operational'
[2023/04/26 03:05:16] [debug] [input chunk] update output instances with new chunk size diff=871
"=>"Microsoft-Windows-Time-Service", "ProviderGuid"=>"{06EDCFEB-0FD0-4E53-ACCA-A6F8BBF81BCB}", "Qualifiers"=>"", "EventID"=>262, "Version"=>0, "Level"=>4, "Task"=>0, "Opcode"=>0, "Keywords"=>"0x4000000000000000", "TimeCreated"=>"2023-04-26 03:05:14 +0000", "EventRecordID"=>920, "ActivityID"=>"", "RelatedActivityID"=>"", "ProcessID"=>7216, "ThreadID"=>13020, "Channel"=>"Microsoft-Windows-Time-Service/Operational", "Computer"=>"win2019-dev-machine", "UserID"=>"S-1-5-19", "Message"=>"W32time service has adjusted the system clock rate by 3490.29980 PPM and the new nominal clock rate is 155704. Previous nominal clock rate was 155668. System Tick Count: 1206898343.
Clock adjustments below 800.00000 PPM are not logged. Performance counters are recommended to efficiently track small adjustment values.
For more information, see https://go.microsoft.com/fwlink/?linkid=845961.", "StringInserts"=>"3490.29980", 155704=>155668, 1206898343=>"800.00000"}]
[2023/04/26 03:05:16] [debug] [out flush] cb_destroy coro_id=5
[2023/04/26 03:05:16] [debug] [task] destroy task=000001CF97BA0A90 (task_id=0)
[2023/04/26 03:05:17] [debug] [task] created task=000001CF97B9FB10 id=0 OK
[2023/04/26 03:05:17] [debug] [output:stdout:stdout.0] task_id=0 assigned to thread #0
[2023/04/26 03:05:17] [debug] [input:winevtlog:winevtlog.0] read 640 bytes from 'Microsoft-Windows-Time-Service/Operational'
[0] winevtlog.0: [[[2023/04/26 03:05:17] [debug] [input chunk] update output instances with new chunk size diff=871
1682478316.295540600, {}], {"ProviderName"=>"Microsoft-Windows-Time-Service", "ProviderGuid"=>"{06EDCFEB-0FD0-4E53-ACCA-A6F8BBF81BCB}", "Qualifiers"=>"", "EventID"=>262, "Version"=>0, "Level"=>4, "Task"=>0, "Opcode"=>0, "Keywords"=>"0x4000000000000000", "TimeCreated"=>"2023-04-26 03:05:15 +0000", "EventRecordID"=>921, "ActivityID"=>"", "RelatedActivityID"=>"", "ProcessID"=>7216, "ThreadID"=>13020, "Channel"=>"Microsoft-Windows-Time-Service/Operational", "Computer"=>"win2019-dev-machine", "UserID"=>"S-1-5-19", "Message"=>"W32time service has adjusted the system clock rate by 3272.09985 PPM and the new nominal clock rate is 155738. Previous nominal clock rate was 155704. System Tick Count: 1206899343.
Clock adjustments below 800.00000 PPM are not logged. Performance counters are recommended to efficiently track small adjustment values.
For more information, see https://go.microsoft.com/fwlink/?linkid=845961.", "StringInserts"=>"3272.09985", 155738=>155704, 1206899343=>"800.00000"}]
[2023/04/26 03:05:17] [debug] [out flush] cb_destroy coro_id=6
[2023/04/26 03:05:17] [debug] [task] destroy task=000001CF97B9FB10 (task_id=0)
[2023/04/26 03:05:18] [debug] [task] created task=000001CF97B9F810 id=0 OK
[0] winevtlog.0: [[1682478317.283085600, {}], {[2023/04/26 03:05:18] [debug] [output:stdout:stdout.0] task_id=0 assigned to thread #0
"ProviderName"=>"Microsoft-Windows-Time-Service", "ProviderGuid"=>"{06EDCFEB-0FD0-4E53-ACCA-A6F8BBF81BCB}", "Qualifiers"=>"", "EventID"=>262, "Version"=>0, "Level"=>4, "Task"=>0, "Opcode"=>0, "Keywords"=>"0x4000000000000000", "TimeCreated"=>"2023-04-26 03:05:16 +0000", "EventRecordID"=>922, "ActivityID"=>"", "RelatedActivityID"=>"", "ProcessID"=>7216, "ThreadID"=>13020, "Channel"=>"Microsoft-Windows-Time-Service/Operational", "Computer"=>"win2019-dev-machine", "UserID"=>"S-1-5-19", "Message"=>"W32time service has adjusted the system clock rate by 3067.60010 PPM and the new nominal clock rate is 155770. Previous nominal clock rate was 155738. System Tick Count: 1206900359.
Clock adjustments below 800.00000 PPM are not logged. Performance counters are recommended to efficiently track small adjustment values.
For more information, see https://go.microsoft.com/fwlink/?linkid=845961.", "StringInserts"=>"3067.60010", 155770=>155738, 1206900359=>"800.00000"}]
[2023/04/26 03:05:18] [debug] [out flush] cb_destroy coro_id=7
[2023/04/26 03:05:18] [debug] [task] destroy task=000001CF97B9F810 (task_id=0)
[2023/04/26 03:05:19] [debug] [input:winevtlog:winevtlog.0] read 1920 bytes from 'Microsoft-Windows-Time-Service/Operational'
[2023/04/26 03:05:19] [debug] [input chunk] update output instances with new chunk size diff=2613
[2023/04/26 03:05:20] [debug] [task] created task=000001CF97B9EF10 id=0 OK
[2023/04/26 03:05:20] [debug] [output:stdout:stdout.0] task_id=0 assigned to thread #0
[0] winevtlog.0: [[1682478319.290333200, {}], {"ProviderName"=>"Microsoft-Windows-Time-Service", "ProviderGuid"=>"{06EDCFEB-0FD0-4E53-ACCA-A6F8BBF81BCB}", "Qualifiers"=>"", "EventID"=>262, "Version"=>0, "Level"=>4, "Task"=>0, "Opcode"=>0, "Keywords"=>"0x4000000000000000", "TimeCreated"=>"2023-04-26 03:05:17 +0000", "EventRecordID"=>923, "ActivityID"=>"", "RelatedActivityID"=>"", "ProcessID"=>7216, "ThreadID"=>13020, "Channel"=>"Microsoft-Windows-Time-Service/Operational", "Computer"=>"win2019-dev-machine", "UserID"=>"S-1-5-19", "Message"=>"W32time service has adjusted the system clock rate by 2875.89990 PPM and the new nominal clock rate is 155800. Previous nominal clock rate was 155770. System Tick Count: 1206901375.
Clock adjustments below 800.00000 PPM are not logged. Performance counters are recommended to efficiently track small adjustment values.
For more information, see https://go.microsoft.com/fwlink/?linkid=845961.", "StringInserts"=>"2875.89990", 155800=>155770, 1206901375=>"800.00000"}]
[1] winevtlog.0: [[1682478319.291242700, {}], {"ProviderName"=>"Microsoft-Windows-Time-Service", "ProviderGuid"=>"{06EDCFEB-0FD0-4E53-ACCA-A6F8BBF81BCB}", "Qualifiers"=>"", "EventID"=>262, "Version"=>0, "Level"=>4, "Task"=>0, "Opcode"=>0, "Keywords"=>"0x4000000000000000", "TimeCreated"=>"2023-04-26 03:05:18 +0000", "EventRecordID"=>924, "ActivityID"=>"", "RelatedActivityID"=>"", "ProcessID"=>7216, "ThreadID"=>13020, "Channel"=>"Microsoft-Windows-Time-Service/Operational", "Computer"=>"win2019-dev-machine", "UserID"=>"S-1-5-19", "Message"=>"W32time service has adjusted the system clock rate by 2696.09985 PPM and the new nominal clock rate is 155828. Previous nominal clock rate was 155800. System Tick Count: 1206902390.
Clock adjustments below 800.00000 PPM are not logged. Performance counters are recommended to efficiently track small adjustment values.
For more information, see https://go.microsoft.com/fwlink/?linkid=845961.", "StringInserts"=>"2696.09985", 155828=>155800, 1206902390=>"800.00000"}]
[2] winevtlog.0: [[1682478319.292221300, {}], {"ProviderName"=>"Microsoft-Windows-Time-Service", "ProviderGuid"=>"{06EDCFEB-0FD0-4E53-ACCA-A6F8BBF81BCB}", "Qualifiers"=>"", "EventID"=>262, "Version"=>0, "Level"=>4, "Task"=>0, "Opcode"=>0, "Keywords"=>"0x4000000000000000", "TimeCreated"=>"2023-04-26 03:05:19 +0000", "EventRecordID"=>925, "ActivityID"=>"", "RelatedActivityID"=>"", "ProcessID"=>7216, "ThreadID"=>13020, "Channel"=>"Microsoft-Windows-Time-Service/Operational", "Computer"=>"win2019-dev-machine", "UserID"=>"S-1-5-19", "Message"=>"W32time service has adjusted the system clock rate by 2527.59985 PPM and the new nominal clock rate is 155855. Previous nominal clock rate was 155828. System Tick Count: 1206903390.
Clock adjustments below 800.00000 PPM are not logged. Performance counters are recommended to efficiently track small adjustment values.
For more information, see https://go.microsoft.com/fwlink/?linkid=845961.", "StringInserts"=>"2527.59985", 155855=>155828, 1206903390=>"800.00000"}]
[2023/04/26 03:05:20] [debug] [out flush] cb_destroy coro_id=8
[2023/04/26 03:05:20] [debug] [task] destroy task=000001CF97B9EF10 (task_id=0)
[2023/04/26 03:05:21] [debug] [input:winevtlog:winevtlog.0] read 640 bytes from 'Microsoft-Windows-Time-Service/Operational'
[2023/04/26 03:05:21] [debug] [input chunk] update output instances with new chunk size diff=871
[2023/04/26 03:05:22] [debug] [task] created task=000001CF97B9F490 id=0 OK
[0] winevtlog.0: [[1682478321.310304300, {}], {[2023/04/26 03:05:22] [debug] [output:stdout:stdout.0] task_id=0 assigned to thread #0
"[2023/04/26 03:05:22] [debug] [input:winevtlog:winevtlog.0] read 640 bytes from 'Microsoft-Windows-Time-Service/Operational'
[2023/04/26 03:05:22] [debug] [input chunk] update output instances with new chunk size diff=871
ProviderName"=>"Microsoft-Windows-Time-Service", "ProviderGuid"=>"{06EDCFEB-0FD0-4E53-ACCA-A6F8BBF81BCB}", "Qualifiers"=>"", "EventID"=>262, "Version"=>0, "Level"=>4, "Task"=>0, "Opcode"=>0, "Keywords"=>"0x4000000000000000", "TimeCreated"=>"2023-04-26 03:05:20 +0000", "EventRecordID"=>926, "ActivityID"=>"", "RelatedActivityID"=>"", "ProcessID"=>7216, "ThreadID"=>13020, "Channel"=>"Microsoft-Windows-Time-Service/Operational", "Computer"=>"win2019-dev-machine", "UserID"=>"S-1-5-19", "Message"=>"W32time service has adjusted the system clock rate by 2369.69995 PPM and the new nominal clock rate is 155879. Previous nominal clock rate was 155855. System Tick Count: 1206904406.
Clock adjustments below 800.00000 PPM are not logged. Performance counters are recommended to efficiently track small adjustment values.
For more information, see https://go.microsoft.com/fwlink/?linkid=845961.", "StringInserts"=>"2369.69995", 155879=>155855, 1206904406=>"800.00000"}]
[2023/04/26 03:05:22] [debug] [out flush] cb_destroy coro_id=9
[2023/04/26 03:05:22] [debug] [task] destroy task=000001CF97B9F490 (task_id=0)
[2023/04/26 03:05:23] [debug] [task] created task=000001CF97BA0190 id=0 OK
[0] winevtlog.0: [[1682478322.297178400, {}], {"ProviderName[2023/04/26 03:05:23] [debug] [output:stdout:stdout.0] task_id=0 assigned to thread #0
"[2023/04/26 03:05:23] [debug] [input:winevtlog:winevtlog.0] read 640 bytes from 'Microsoft-Windows-Time-Service/Operational'
=>"Microsoft-Windows-Time-Service[2023/04/26 03:05:23] [debug] [input chunk] update output instances with new chunk size diff=871
", "ProviderGuid"=>"{06EDCFEB-0FD0-4E53-ACCA-A6F8BBF81BCB}", "Qualifiers"=>"", "EventID"=>262, "Version"=>0, "Level"=>4, "Task"=>0, "Opcode"=>0, "Keywords"=>"0x4000000000000000", "TimeCreated"=>"2023-04-26 03:05:21 +0000", "EventRecordID"=>927, "ActivityID"=>"", "RelatedActivityID"=>"", "ProcessID"=>7216, "ThreadID"=>13020, "Channel"=>"Microsoft-Windows-Time-Service/Operational", "Computer"=>"win2019-dev-machine", "UserID"=>"S-1-5-19", "Message"=>"W32time service has adjusted the system clock rate by 2221.59985 PPM and the new nominal clock rate is 155902. Previous nominal clock rate was 155879. System Tick Count: 1206905421.
Clock adjustments below 800.00000 PPM are not logged. Performance counters are recommended to efficiently track small adjustment values.
For more information, see https://go.microsoft.com/fwlink/?linkid=845961.", "StringInserts"=>"2221.59985", 155902=>155879, 1206905421=>"800.00000"}]
[2023/04/26 03:05:23] [debug] [out flush] cb_destroy coro_id=10
[2023/04/26 03:05:23] [debug] [task] destroy task=000001CF97BA0190 (task_id=0)
[2023/04/26 03:05:24] [debug] [task] created task=000001CF97B9FD90 id=0 OK
[2023/04/26 03:05:24] [debug] [output:stdout:stdout.0] task_id=0 assigned to thread #0
[0] winevtlog.0: [[1682478323.299108400, {}], {"ProviderName"=>"Microsoft-Windows-Time-Service", "ProviderGuid"=>"{06EDCFEB-0FD0-4E53-ACCA-A6F8BBF81BCB}", "Qualifiers"=>"", "EventID"=>262, "Version"=>0, "Level"=>4, "Task"=>0, "Opcode"=>0, "Keywords"=>"0x4000000000000000", "TimeCreated"=>"2023-04-26 03:05:22 +0000", "EventRecordID"=>928, "ActivityID"=>"", "RelatedActivityID"=>"", "ProcessID"=>7216, "ThreadID"=>13020, "Channel"=>"Microsoft-Windows-Time-Service/Operational", "Computer"=>"win2019-dev-machine", "UserID"=>"S-1-5-19", "Message"=>"W32time service has adjusted the system clock rate by 2082.69995 PPM and the new nominal clock rate is 155924. Previous nominal clock rate was 155902. System Tick Count: 1206906437.
Clock adjustments below 800.00000 PPM are not logged. Performance counters are recommended to efficiently track small adjustment values.
For more information, see https://go.microsoft.com/fwlink/?linkid=845961.", "StringInserts"=>"2082.69995", 155924=>155902, 1206906437=>"800.00000"}]
[2023/04/26 03:05:24] [debug] [out flush] cb_destroy coro_id=11
[2023/04/26 03:05:24] [debug] [task] destroy task=000001CF97B9FD90 (task_id=0)
[2023/04/26 03:05:25] [debug] [input:winevtlog:winevtlog.0] read 640 bytes from 'Microsoft-Windows-Time-Service/Operational'
[2023/04/26 03:05:25] [debug] [input chunk] update output instances with new chunk size diff=871
[2023/04/26 03:05:26] [debug] [task] created task=000001CF97BA0010 id=0 OK
[0] winevtlog.0: [[1682478325.305249900, {}], [2023/04/26 03:05:26] [debug] [output:stdout:stdout.0] task_id=0 assigned to thread #0
{"ProviderName[2023/04/26 03:05:26] [debug] [input:winevtlog:winevtlog.0] read 640 bytes from 'Microsoft-Windows-Time-Service/Operational'
"=>"Microsoft-Windows-Time-Service", [2023/04/26 03:05:26] [debug] [input chunk] update output instances with new chunk size diff=871
"ProviderGuid"=>"{06EDCFEB-0FD0-4E53-ACCA-A6F8BBF81BCB}", "Qualifiers"=>"", "EventID"=>262, "Version"=>0, "Level"=>4, "Task"=>0, "Opcode"=>0, "Keywords"=>"0x4000000000000000", "TimeCreated"=>"2023-04-26 03:05:23 +0000", "EventRecordID"=>929, "ActivityID"=>"", "RelatedActivityID"=>"", "ProcessID"=>7216, "ThreadID"=>13020, "Channel"=>"Microsoft-Windows-Time-Service/Operational", "Computer"=>"win2019-dev-machine", "UserID"=>"S-1-5-19", "Message"=>"W32time service has adjusted the system clock rate by 1952.50000 PPM and the new nominal clock rate is 155944. Previous nominal clock rate was 155924. System Tick Count: 1206907453.
Clock adjustments below 800.00000 PPM are not logged. Performance counters are recommended to efficiently track small adjustment values.
For more information, see https://go.microsoft.com/fwlink/?linkid=845961.", "StringInserts"=>"1952.50000", 155944=>155924, 1206907453=>"800.00000"}]
[2023/04/26 03:05:26] [debug] [out flush] cb_destroy coro_id=12
[2023/04/26 03:05:26] [debug] [task] destroy task=000001CF97BA0010 (task_id=0)
[2023/04/26 03:05:27] [debug] [task] created task=000001CF97BA0590 id=0 OK
[2023/04/26 03:05:27] [debug] [output:stdout:stdout.0] task_id=0 assigned to thread #0
[0] winevtlog.0: [[1682478326.307095800, {}], {"ProviderName[2023/04/26 03:05:27] [debug] [input:winevtlog:winevtlog.0] read 640 bytes from 'Microsoft-Windows-Time-Service/Operational'
"=>"[2023/04/26 03:05:27] [debug] [input chunk] update output instances with new chunk size diff=871
Microsoft-Windows-Time-Service", "ProviderGuid"=>"{06EDCFEB-0FD0-4E53-ACCA-A6F8BBF81BCB}", "Qualifiers"=>"", "EventID"=>262, "Version"=>0, "Level"=>4, "Task"=>0, "Opcode"=>0, "Keywords"=>"0x4000000000000000", "TimeCreated"=>"2023-04-26 03:05:24 +0000", "EventRecordID"=>930, "ActivityID"=>"", "RelatedActivityID"=>"", "ProcessID"=>7216, "ThreadID"=>13020, "Channel"=>"Microsoft-Windows-Time-Service/Operational", "Computer"=>"win2019-dev-machine", "UserID"=>"S-1-5-19", "Message"=>"W32time service has adjusted the system clock rate by 1830.50000 PPM and the new nominal clock rate is 155963. Previous nominal clock rate was 155944. System Tick Count: 1206908453.
Clock adjustments below 800.00000 PPM are not logged. Performance counters are recommended to efficiently track small adjustment values.
For more information, see https://go.microsoft.com/fwlink/?linkid=845961.", "StringInserts"=>"1830.50000", 155963=>155944, 1206908453=>"800.00000"}]
[2023/04/26 03:05:27] [debug] [out flush] cb_destroy coro_id=13
[2023/04/26 03:05:27] [debug] [task] destroy task=000001CF97BA0590 (task_id=0)
[2023/04/26 03:05:28] [debug] [task] created task=000001CF97BA0010 id=0 OK
[2023/04/26 03:05:28] [debug] [output:stdout:stdout.0] task_id=0 assigned to thread #0
[0] winevtlog.0: [[[2023/04/26 03:05:28] [debug] [input:winevtlog:winevtlog.0] read 640 bytes from 'Microsoft-Windows-Time-Service/Operational'
1682478327.324834800, {}], {"ProviderName"=>"Microsoft-Windows-Time-Service", "ProviderGuid"=>"[2023/04/26 03:05:28] [debug] [input chunk] update output instances with new chunk size diff=871
{06EDCFEB-0FD0-4E53-ACCA-A6F8BBF81BCB}", "Qualifiers"=>"", "EventID"=>262, "Version"=>0, "Level"=>4, "Task"=>0, "Opcode"=>0, "Keywords"=>"0x4000000000000000", "TimeCreated"=>"2023-04-26 03:05:25 +0000", "EventRecordID"=>931, "ActivityID"=>"", "RelatedActivityID"=>"", "ProcessID"=>7216, "ThreadID"=>13020, "Channel"=>"Microsoft-Windows-Time-Service/Operational", "Computer"=>"win2019-dev-machine", "UserID"=>"S-1-5-19", "Message"=>"W32time service has adjusted the system clock rate by 1716.09998 PPM and the new nominal clock rate is 155981. Previous nominal clock rate was 155963. System Tick Count: 1206909453.
Clock adjustments below 800.00000 PPM are not logged. Performance counters are recommended to efficiently track small adjustment values.
For more information, see https://go.microsoft.com/fwlink/?linkid=845961.", "StringInserts"=>"1716.09998", 155981=>155963, 1206909453=>"800.00000"}]
[2023/04/26 03:05:28] [debug] [out flush] cb_destroy coro_id=14
[2023/04/26 03:05:28] [debug] [task] destroy task=000001CF97BA0010 (task_id=0)
[2023/04/26 03:05:29] [debug] [task] created task=000001CF97B9FF10 id=0 OK
[2023/04/26 03:05:29] [debug] [output:stdout:stdout.0] task_id=0 assigned to thread #0
[0] winevtlog.0: [[1682478328.309875700, {}], {"[2023/04/26 03:05:29] [debug] [input:winevtlog:winevtlog.0] read 640 bytes from 'Microsoft-Windows-Time-Service/Operational'
[2023/04/26 03:05:29] [debug] [input chunk] update output instances with new chunk size diff=871
ProviderName"=>"Microsoft-Windows-Time-Service", "ProviderGuid"=>"{06EDCFEB-0FD0-4E53-ACCA-A6F8BBF81BCB}", "Qualifiers"=>"", "EventID"=>262, "Version"=>0, "Level"=>4, "Task"=>0, "Opcode"=>0, "Keywords"=>"0x4000000000000000", "TimeCreated"=>"2023-04-26 03:05:26 +0000", "EventRecordID"=>932, "ActivityID"=>"", "RelatedActivityID"=>"", "ProcessID"=>7216, "ThreadID"=>13020, "Channel"=>"Microsoft-Windows-Time-Service/Operational", "Computer"=>"win2019-dev-machine", "UserID"=>"S-1-5-19", "Message"=>"W32time service has adjusted the system clock rate by 1608.80005 PPM and the new nominal clock rate is 155998. Previous nominal clock rate was 155981. System Tick Count: 1206910468.
Clock adjustments below 800.00000 PPM are not logged. Performance counters are recommended to efficiently track small adjustment values.
For more information, see https://go.microsoft.com/fwlink/?linkid=845961.", "StringInserts"=>"1608.80005", 155998=>155981, 1206910468=>"800.00000"}]
[2023/04/26 03:05:29] [debug] [out flush] cb_destroy coro_id=15
[2023/04/26 03:05:29] [debug] [task] destroy task=000001CF97B9FF10 (task_id=0)
[2023/04/26 03:05:30] [debug] [task] created task=000001CF97BA0510 id=0 OK
[0] winevtlog.0: [[1682478329.311667600, {}], {"ProviderName"=>"Microsoft-Windows-Time-Service", "ProviderGuid"=>"{06EDCFEB-0FD0-4E53-ACCA-A6F8BBF81BCB}", "Qualifiers"=>"", "EventID"[2023/04/26 03:05:30] [debug] [output:stdout:stdout.0] task_id=0 assigned to thread #0
=>[2023/04/26 03:05:30] [debug] [input:winevtlog:winevtlog.0] read 640 bytes from 'Microsoft-Windows-Time-Service/Operational'
262, "Version"[2023/04/26 03:05:30] [debug] [input chunk] update output instances with new chunk size diff=871
=>0, "Level"=>4, "Task"=>0, "Opcode"=>0, "Keywords"=>"0x4000000000000000", "TimeCreated"=>"2023-04-26 03:05:27 +0000", "EventRecordID"=>933, "ActivityID"=>"", "RelatedActivityID"=>"", "ProcessID"=>7216, "ThreadID"=>13020, "Channel"=>"Microsoft-Windows-Time-Service/Operational", "Computer"=>"win2019-dev-machine", "UserID"=>"S-1-5-19", "Message"=>"W32time service has adjusted the system clock rate by 1508.29993 PPM and the new nominal clock rate is 156014. Previous nominal clock rate was 155998. System Tick Count: 1206911484.
Clock adjustments below 800.00000 PPM are not logged. Performance counters are recommended to efficiently track small adjustment values.
For more information, see https://go.microsoft.com/fwlink/?linkid=845961.", "StringInserts"=>"1508.29993", 156014=>155998, 1206911484=>"800.00000"}]
[2023/04/26 03:05:30] [debug] [out flush] cb_destroy coro_id=16
[2023/04/26 03:05:30] [debug] [task] destroy task=000001CF97BA0510 (task_id=0)
[2023/04/26 03:05:31] [debug] [task] created task=000001CF97B9FC10 id=0 OK
[2023/04/26 03:05:31] [debug] [output:stdout:stdout.0] task_id=0 assigned to thread #0
[0] winevtlog.0: [[1682478330.314105500, {}[2023/04/26 03:05:31] [debug] [input:winevtlog:winevtlog.0] read 640 bytes from 'Microsoft-Windows-Time-Service/Operational'
], {[2023/04/26 03:05:31] [debug] [input chunk] update output instances with new chunk size diff=871
"ProviderName"=>"Microsoft-Windows-Time-Service", "ProviderGuid"=>"{06EDCFEB-0FD0-4E53-ACCA-A6F8BBF81BCB}", "Qualifiers"=>"", "EventID"=>262, "Version"=>0, "Level"=>4, "Task"=>0, "Opcode"=>0, "Keywords"=>"0x4000000000000000", "TimeCreated"=>"2023-04-26 03:05:28 +0000", "EventRecordID"=>934, "ActivityID"=>"", "RelatedActivityID"=>"", "ProcessID"=>7216, "ThreadID"=>13020, "Channel"=>"Microsoft-Windows-Time-Service/Operational", "Computer"=>"win2019-dev-machine", "UserID"=>"S-1-5-19", "Message"=>"W32time service has adjusted the system clock rate by 1414.00000 PPM and the new nominal clock rate is 156029. Previous nominal clock rate was 156014. System Tick Count: 1206912500.
Clock adjustments below 800.00000 PPM are not logged. Performance counters are recommended to efficiently track small adjustment values.
For more information, see https://go.microsoft.com/fwlink/?linkid=845961.", "StringInserts"=>"1414.00000", 156029=>156014, 1206912500=>"800.00000"}]
[2023/04/26 03:05:31] [debug] [out flush] cb_destroy coro_id=17
[2023/04/26 03:05:31] [debug] [task] destroy task=000001CF97B9FC10 (task_id=0)
[2023/04/26 03:05:32] [debug] [task] created task=000001CF97B9FF10 id=0 OK
[2023/04/26 03:05:32] [debug] [output:stdout:stdout.0] task_id=0 assigned to thread #0
[0] winevtlog.0: [[1682478331.330893500, [2023/04/26 03:05:32] [debug] [input:winevtlog:winevtlog.0] read 640 bytes from 'Microsoft-Windows-Time-Service/Operational'
{}], {"ProviderName"=>"Microsoft-Windows-Time-Service", "ProviderGuid"[2023/04/26 03:05:32] [debug] [input chunk] update output instances with new chunk size diff=871
=>"{06EDCFEB-0FD0-4E53-ACCA-A6F8BBF81BCB}", "Qualifiers"=>"", "EventID"=>262, "Version"=>0, "Level"=>4, "Task"=>0, "Opcode"=>0, "Keywords"=>"0x4000000000000000", "TimeCreated"=>"2023-04-26 03:05:29 +0000", "EventRecordID"=>935, "ActivityID"=>"", "RelatedActivityID"=>"", "ProcessID"=>7216, "ThreadID"=>13020, "Channel"=>"Microsoft-Windows-Time-Service/Operational", "Computer"=>"win2019-dev-machine", "UserID"=>"S-1-5-19", "Message"=>"W32time service has adjusted the system clock rate by 1325.59998 PPM and the new nominal clock rate is 156042. Previous nominal clock rate was 156029. System Tick Count: 1206913515.
Clock adjustments below 800.00000 PPM are not logged. Performance counters are recommended to efficiently track small adjustment values.
For more information, see https://go.microsoft.com/fwlink/?linkid=845961.", "StringInserts"=>"1325.59998", 156042=>156029, 1206913515=>"800.00000"}]
[2023/04/26 03:05:32] [debug] [out flush] cb_destroy coro_id=18
[2023/04/26 03:05:32] [debug] [task] destroy task=000001CF97B9FF10 (task_id=0)
[2023/04/26 03:05:33] [debug] [task] created task=000001CF97B9FC10 id=0 OK
[2023/04/26 03:05:33] [debug] [output:stdout:stdout.0] task_id=0 assigned to thread #0
[0] winevtlog.0: [[1682478332.316338900, {}], {[2023/04/26 03:05:33] [debug] [input:winevtlog:winevtlog.0] read 640 bytes from 'Microsoft-Windows-Time-Service/Operational'
"ProviderName"[2023/04/26 03:05:33] [debug] [input chunk] update output instances with new chunk size diff=871
=>"Microsoft-Windows-Time-Service", "ProviderGuid"=>"{06EDCFEB-0FD0-4E53-ACCA-A6F8BBF81BCB}", "Qualifiers"=>"", "EventID"=>262, "Version"=>0, "Level"=>4, "Task"=>0, "Opcode"=>0, "Keywords"=>"0x4000000000000000", "TimeCreated"=>"2023-04-26 03:05:30 +0000", "EventRecordID"=>936, "ActivityID"=>"", "RelatedActivityID"=>"", "ProcessID"=>7216, "ThreadID"=>13020, "Channel"=>"Microsoft-Windows-Time-Service/Operational", "Computer"=>"win2019-dev-machine", "UserID"=>"S-1-5-19", "Message"=>"W32time service has adjusted the system clock rate by 1242.80005 PPM and the new nominal clock rate is 156055. Previous nominal clock rate was 156042. System Tick Count: 1206914515.
Clock adjustments below 800.00000 PPM are not logged. Performance counters are recommended to efficiently track small adjustment values.
For more information, see https://go.microsoft.com/fwlink/?linkid=845961.", "StringInserts"=>"1242.80005", 156055=>156042, 1206914515=>"800.00000"}]
[2023/04/26 03:05:33] [debug] [out flush] cb_destroy coro_id=19
[2023/04/26 03:05:33] [debug] [task] destroy task=000001CF97B9FC10 (task_id=0)
[2023/04/26 03:05:34] [debug] [task] created task=000001CF97B9FD90 id=0 OK
[0] winevtlog.0: [[1682478333.318864200, {}], {"[2023/04/26 03:05:34] [debug] [output:stdout:stdout.0] task_id=0 assigned to thread #0
ProviderName"[2023/04/26 03:05:34] [debug] [input:winevtlog:winevtlog.0] read 640 bytes from 'Microsoft-Windows-Time-Service/Operational'
=>"Microsoft-Windows-Time-Service", "ProviderGuid[2023/04/26 03:05:34] [debug] [input chunk] update output instances with new chunk size diff=871
"=>"{06EDCFEB-0FD0-4E53-ACCA-A6F8BBF81BCB}", "Qualifiers"=>"", "EventID"=>262, "Version"=>0, "Level"=>4, "Task"=>0, "Opcode"=>0, "Keywords"=>"0x4000000000000000", "TimeCreated"=>"2023-04-26 03:05:31 +0000", "EventRecordID"=>937, "ActivityID"=>"", "RelatedActivityID"=>"", "ProcessID"=>7216, "ThreadID"=>13020, "Channel"=>"Microsoft-Windows-Time-Service/Operational", "Computer"=>"win2019-dev-machine", "UserID"=>"S-1-5-19", "Message"=>"W32time service has adjusted the system clock rate by 1165.09998 PPM and the new nominal clock rate is 156067. Previous nominal clock rate was 156055. System Tick Count: 1206915531.
Clock adjustments below 800.00000 PPM are not logged. Performance counters are recommended to efficiently track small adjustment values.
For more information, see https://go.microsoft.com/fwlink/?linkid=845961.", "StringInserts"=>"1165.09998", 156067=>156055, 1206915531=>"800.00000"}]
[2023/04/26 03:05:34] [debug] [out flush] cb_destroy coro_id=20
[2023/04/26 03:05:34] [debug] [task] destroy task=000001CF97B9FD90 (task_id=0)
[2023/04/26 03:05:35] [debug] [task] created task=000001CF97B9FB90 id=0 OK
[0] winevtlog.0: [[1682478334.321734900, {}], {[2023/04/26 03:05:35] [debug] [output:stdout:stdout.0] task_id=0 assigned to thread #0
"ProviderName"=>"Microsoft-Windows-Time-Service", "ProviderGuid[2023/04/26 03:05:35] [debug] [input:winevtlog:winevtlog.0] read 640 bytes from 'Microsoft-Windows-Time-Service/Operational'
"=>"{06EDCFEB-0FD0-4E53-ACCA-A6F8BBF81BCB}[2023/04/26 03:05:35] [debug] [input chunk] update output instances with new chunk size diff=871
", "Qualifiers"=>"", "EventID"=>262, "Version"=>0, "Level"=>4, "Task"=>0, "Opcode"=>0, "Keywords"=>"0x4000000000000000", "TimeCreated"=>"2023-04-26 03:05:32 +0000", "EventRecordID"=>938, "ActivityID"=>"", "RelatedActivityID"=>"", "ProcessID"=>7216, "ThreadID"=>13020, "Channel"=>"Microsoft-Windows-Time-Service/Operational", "Computer"=>"win2019-dev-machine", "UserID"=>"S-1-5-19", "Message"=>"W32time service has adjusted the system clock rate by 1092.30005 PPM and the new nominal clock rate is 156079. Previous nominal clock rate was 156067. System Tick Count: 1206916546.
Clock adjustments below 800.00000 PPM are not logged. Performance counters are recommended to efficiently track small adjustment values.
For more information, see https://go.microsoft.com/fwlink/?linkid=845961.", "StringInserts"=>"1092.30005", 156079=>156067, 1206916546=>"800.00000"}]
[2023/04/26 03:05:35] [debug] [out flush] cb_destroy coro_id=21
[2023/04/26 03:05:35] [debug] [task] destroy task=000001CF97B9FB90 (task_id=0)
[2023/04/26 03:05:36] [debug] [task] created task=000001CF97BA0290 id=0 OK
[0] winevtlog.0: [[1682478335.311493100, {}[2023/04/26 03:05:36] [debug] [output:stdout:stdout.0] task_id=0 assigned to thread #0
], {"[2023/04/26 03:05:36] [debug] [input:winevtlog:winevtlog.0] read 640 bytes from 'Microsoft-Windows-Time-Service/Operational'
ProviderName[2023/04/26 03:05:36] [debug] [input chunk] update output instances with new chunk size diff=869
"=>"Microsoft-Windows-Time-Service", "ProviderGuid"=>"{06EDCFEB-0FD0-4E53-ACCA-A6F8BBF81BCB}", "Qualifiers"=>"", "EventID"=>262, "Version"=>0, "Level"=>4, "Task"=>0, "Opcode"=>0, "Keywords"=>"0x4000000000000000", "TimeCreated"=>"2023-04-26 03:05:33 +0000", "EventRecordID"=>939, "ActivityID"=>"", "RelatedActivityID"=>"", "ProcessID"=>7216, "ThreadID"=>13020, "Channel"=>"Microsoft-Windows-Time-Service/Operational", "Computer"=>"win2019-dev-machine", "UserID"=>"S-1-5-19", "Message"=>"W32time service has adjusted the system clock rate by 1024.00000 PPM and the new nominal clock rate is 156090. Previous nominal clock rate was 156079. System Tick Count: 1206917546.
Clock adjustments below 800.00000 PPM are not logged. Performance counters are recommended to efficiently track small adjustment values.
For more information, see https://go.microsoft.com/fwlink/?linkid=845961.", "StringInserts"=>"1024.00000", 156090=>156079, 1206917546=>"800.00000"}]
[2023/04/26 03:05:36] [debug] [out flush] cb_destroy coro_id=22
[2023/04/26 03:05:36] [debug] [task] destroy task=000001CF97BA0290 (task_id=0)
[2023/04/26 03:05:37] [debug] [task] created task=000001CF97B9F110 id=0 OK
[0] winevtlog.0: [[1682478336.312310600, {}], {[2023/04/26 03:05:37] [debug] [output:stdout:stdout.0] task_id=0 assigned to thread #0
[2023/04/26 03:05:37] [debug] [input:winevtlog:winevtlog.0] read 640 bytes from 'Microsoft-Windows-Time-Service/Operational'
"ProviderName"=>[2023/04/26 03:05:37] [debug] [input chunk] update output instances with new chunk size diff=869
"Microsoft-Windows-Time-Service", "ProviderGuid"=>"{06EDCFEB-0FD0-4E53-ACCA-A6F8BBF81BCB}", "Qualifiers"=>"", "EventID"=>262, "Version"=>0, "Level"=>4, "Task"=>0, "Opcode"=>0, "Keywords"=>"0x4000000000000000", "TimeCreated"=>"2023-04-26 03:05:34 +0000", "EventRecordID"=>940, "ActivityID"=>"", "RelatedActivityID"=>"", "ProcessID"=>7216, "ThreadID"=>13020, "Channel"=>"Microsoft-Windows-Time-Service/Operational", "Computer"=>"win2019-dev-machine", "UserID"=>"S-1-5-19", "Message"=>"W32time service has adjusted the system clock rate by 960.00000 PPM and the new nominal clock rate is 156100. Previous nominal clock rate was 156090. System Tick Count: 1206918562.
Clock adjustments below 800.00000 PPM are not logged. Performance counters are recommended to efficiently track small adjustment values.
For more information, see https://go.microsoft.com/fwlink/?linkid=845961.", "StringInserts"=>"960.00000", 156100=>156090, 1206918562=>"800.00000"}]
[2023/04/26 03:05:37] [debug] [out flush] cb_destroy coro_id=23
[2023/04/26 03:05:37] [debug] [task] destroy task=000001CF97B9F110 (task_id=0)
[2023/04/26 03:05:38] [debug] [task] created task=000001CF97BA0790 id=0 OK
[0] winevtlog.0: [[1682478337.328877600, {}], [2023/04/26 03:05:38] [debug] [output:stdout:stdout.0] task_id=0 assigned to thread #0
{[2023/04/26 03:05:38] [debug] [input:winevtlog:winevtlog.0] read 640 bytes from 'Microsoft-Windows-Time-Service/Operational'
[2023/04/26 03:05:38] [debug] [input chunk] update output instances with new chunk size diff=869
"ProviderName"=>"Microsoft-Windows-Time-Service", "ProviderGuid"=>"{06EDCFEB-0FD0-4E53-ACCA-A6F8BBF81BCB}", "Qualifiers"=>"", "EventID"=>262, "Version"=>0, "Level"=>4, "Task"=>0, "Opcode"=>0, "Keywords"=>"0x4000000000000000", "TimeCreated"=>"2023-04-26 03:05:35 +0000", "EventRecordID"=>941, "ActivityID"=>"", "RelatedActivityID"=>"", "ProcessID"=>7216, "ThreadID"=>13020, "Channel"=>"Microsoft-Windows-Time-Service/Operational", "Computer"=>"win2019-dev-machine", "UserID"=>"S-1-5-19", "Message"=>"W32time service has adjusted the system clock rate by 900.00000 PPM and the new nominal clock rate is 156109. Previous nominal clock rate was 156100. System Tick Count: 1206919562.
Clock adjustments below 800.00000 PPM are not logged. Performance counters are recommended to efficiently track small adjustment values.
For more information, see https://go.microsoft.com/fwlink/?linkid=845961.", "StringInserts"=>"900.00000", 156109=>156100, 1206919562=>"800.00000"}]
[2023/04/26 03:05:38] [debug] [out flush] cb_destroy coro_id=24
[2023/04/26 03:05:38] [debug] [task] destroy task=000001CF97BA0790 (task_id=0)
[2023/04/26 03:05:39] [debug] [task] created task=000001CF97B9FD90 id=0 OK
[2023/04/26 03:05:39] [debug] [output:stdout:stdout.0] task_id=0 assigned to thread #0
[0] winevtlog.0: [[1682478338.317209200, {}], {"ProviderName"=>"Microsoft-Windows-Time-Service", "ProviderGuid"=>"{06EDCFEB-0FD0-4E53-ACCA-A6F8BBF81BCB}", "Qualifiers"=>"", "EventID"=>262, "Version"=>0, "Level"=>4, "Task"=>0, "Opcode"=>0, "Keywords"=>"0x4000000000000000", "TimeCreated"=>"2023-04-26 03:05:36 +0000", "EventRecordID"=>942, "ActivityID"=>"", "RelatedActivityID"=>"", "ProcessID"=>7216, "ThreadID"=>13020, "Channel"=>"Microsoft-Windows-Time-Service/Operational", "Computer"=>"win2019-dev-machine", "UserID"=>"S-1-5-19", "Message"=>"W32time service has adjusted the system clock rate by 843.80005 PPM and the new nominal clock rate is 156118. Previous nominal clock rate was 156109. System Tick Count: 1206920578.
Clock adjustments below 800.00000 PPM are not logged. Performance counters are recommended to efficiently track small adjustment values.
For more information, see https://go.microsoft.com/fwlink/?linkid=845961.", "StringInserts"=>"843.80005", 156118=>156109, 1206920578=>"800.00000"}]
[2023/04/26 03:05:39] [debug] [out flush] cb_destroy coro_id=25
[2023/04/26 03:05:39] [debug] [task] destroy task=000001CF97B9FD90 (task_id=0)
[2023/04/26 03:10:33] [debug] [input:winevtlog:winevtlog.0] read 4184 bytes from 'Microsoft-Windows-Time-Service/Operational'
[2023/04/26 03:10:33] [debug] [input chunk] update output instances with new chunk size diff=4475
[2023/04/26 03:10:34] [debug] [task] created task=000001CF97B9F010 id=0 OK
[2023/04/26 03:10:34] [debug] [output:stdout:stdout.0] task_id=0 assigned to thread #0
[0] winevtlog.0: [[1682478633.324759500, {}], {"ProviderName"=>"Microsoft-Windows-Time-Service", "ProviderGuid"=>"{06EDCFEB-0FD0-4E53-ACCA-A6F8BBF81BCB}", "Qualifiers"=>"", "EventID"=>272, "Version"=>0, "Level"=>4, "Task"=>0, "Opcode"=>0, "Keywords"=>"0x4000000000000000", "TimeCreated"=>"2023-04-26 03:10:31 +0000", "EventRecordID"=>943, "ActivityID"=>"", "RelatedActivityID"=>"", "ProcessID"=>7216, "ThreadID"=>12548, "Channel"=>"Microsoft-Windows-Time-Service/Operational", "Computer"=>"win2019-dev-machine", "UserID"=>"S-1-5-19", "Message"=>"Leap second configuration:
Enabled: 1 (Local)
Count: 0 (Local)
Current Offset from UTC(Seconds): 0 (Local)
Runtime state consistent with settings: 1
Newest Leap Seconds List (Local):

System Tick Count: 1207215375.

For more information, see https://go.microsoft.com/fwlink/?linkid=845961.", "StringInserts"=>1, 0=>0, 1=>""}]
[2023/04/26 03:10:34] [error] [output:stdout:stdout.0] decoder error : -4
[2023/04/26 03:10:34] [debug] [out flush] cb_destroy coro_id=26
[2023/04/26 03:10:34] [debug] [task] destroy task=000001CF97B9F010 (task_id=0)
[2023/04/26 03:11:35] [engine] caught signal (SIGINT)
[2023/04/26 03:11:35] [ warn] [engine] service will shutdown in max 5 seconds
[2023/04/26 03:11:35] [ info] [input] pausing winevtlog.0
```

File: plugins/in_winevtlog/pack.c (hunk 1 above)
Comment (cosmo0920) [reply plugins/in_winevtlog/pack.c:304]: Sorry for the inconvenience.... I'd tried to add that, however I wasn't able to handle it. Maybe, in the future, I can take a look on this.
Your work is really helpful for us. :+1:

**Comment by cosmo0920** [comment]
On thing. I found the unexpected behavior changes in pack_string_inserts. I fixed that change.
@igorpeshansky Could you take a look again?

File: plugins/in_winevtlog/pack.c [hunk 2]
```diff
@@ -381,6 +384,11 @@ static void pack_string_inserts(struct winevtlog_config *ctx, PEVT_VARIANT value
             msgpack_pack_str_body(ctx, "?", 1);
```
Comment (leonardo-albertovich) [inline plugins/in_winevtlog/pack.c:384]: It seems that I forgot to update this line and the one above to use `flb_log_event_encoder_append_body_cstring`, would you mind doing it?

Comment (braydonk) [reply plugins/in_winevtlog/pack.c]: Done in [91c68db](https://github.com/fluent/fluent-bit/pull/7272/commits/91c68dbb558719a1275dcc673a658f015497368e)

**Comment by braydonk** [comment]
> I'm not entirely sure of if Hiroshi vouched for the array change or not but that should be settled before merging it.

I believe the change you are referring to was made by Hiroshi if I'm not mistaken.

File: plugins/in_winevtlog/pack.c [hunk 3]
```diff
@@ -377,10 +380,14 @@ static void pack_string_inserts(struct winevtlog_config *ctx, PEVT_VARIANT value
...
             break;
         default:
-            msgpack_pack_str(ctx, 1);
-            msgpack_pack_str_body(ctx, "?", 1);
+            flb_log_event_encoder_append_body_cstring(ctx->log_encoder, "?");
         }
     }
+
+    if (ret == FLB_EVENT_ENCODER_SUCCESS) {
+        ret = flb_log_event_encoder_body_commit_array(ctx->log_encoder);
```
Comment (braydonk) [inline plugins/in_winevtlog/pack.c:388]: Should this `ret` value be checked as well?

Comment (leonardo-albertovich) [reply plugins/in_winevtlog/pack.c:388]: Normally yes, for new code **definitely**, for older code like this it might be acceptable to skip it since it's not worse than the original behavior.

**Review by leonardo-albertovich — APPROVED** [review]

File: plugins/in_winevtlog/pack.c (hunk 3 above)
Comment (cosmo0920) [reply plugins/in_winevtlog/pack.c:388]: Oh, sorry for lacking of the descriptions to this change.
This should be mainly for restoring behavior of the previous code before metadata migration.

**Comment by braydonk** [comment]
That MacOS Sanitize Memory error didn't happen before, is it possible for those tests to flake? It seems so unlikely that these changes would affect those tests but I've never looked at them before.

**Comment by leonardo-albertovich** [comment]
Yes, those macos tests are in the process of being fixed, don't worry about them.
