### PR TITLE
out_loki: use flb_time_in_nanosec to prevent time convertion error

### LINKED ISSUE #3350: Loki Output timestamp not parsed properly
## Bug Report
First of all: I use the docker container of fluent bit v1.7.3 (and also tested with 1.7.2).

**Description of the bug**
Sending any type of input (syslog, tail, forward) to loki ends in an error from loki refering to the timestamp.

**To Reproduce**
- create ```fluent-bit.conf``` with the content
```
[SERVICE]
    Flush        5
    Daemon       Off
    Log_Level    trace
    Parsers_File parsers.conf
    Plugins_File plugins.conf
    HTTP_Server  Off

[INPUT]
    Name forward
    Listen 0.0.0.0
    Port 24224

[OUTPUT]
    Name loki
    Match *
    Host loki
    Port 3100
    Labels job=docker-forward, agent=fluentbit

[OUTPUT]
    Name stdout
    Match *
```
- run loki and fluent-bit docker containers with docker-compose:
```
version: "3"

networks:
  loki:

services:
  loki:
    image: grafana/loki:2.2.1
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki
   
  fluentbit:
    image: fluent/fluent-bit:1.7.3
    container_name: fluentbit
    ports:
      - "24224:24224"
    volumes:
      - ./fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
    command: /fluent-bit/bin/fluent-bit -c /fluent-bit/etc/fluent-bit.conf
    networks:
      - loki
```
- trigger a log message via the fluentd log driver implemented in docker with
```
docker run --rm --log-driver=fluentd -t ubuntu echo "Testing a log message"
```
- Now you should see something like
```
[0] 98bb7a08ba8b: [1617978084.000000000, {"container_name"=>"/zen_franklin", "source"=>"stdout", "log"=>"Testing a log message", "container_id"=>"98bb7a08ba8b403167488f8b6b9f3ea1dec3a0180d4a7b10753be88b0329daee"}]
```
and the error from loki
```
[2021/04/09 14:21:29] [error] [output:loki:loki.0] loki:3100, HTTP status=400 loghttp.PushRequest.Streams: []*loghttp.Stream: loghttp.Stream.Entries: error reading entry timestamp: strconv.ParseInt: parsing "18446744072487954432": value out of range, error found in #10 byte of ...|487954432","{\"conta|..., bigger context ...|nt":"fluentbit"},"values":[["18446744072487954432","{\"container_name\":\"/zen_franklin\",\"source\"|...
```
Loki complains about the parsing of the timestamp. In the log above the timestamp is correct and in the format of fluentbit (```SECONDS.NANOSECONDS```). Apparently loki expects a nanoseconds-timestamp as an integer so the parsing results in a wrong number ```18446744072487954432``` and decoding this timestamp to ```Monday, 22. Juli 2554 01:34:32.487 GMT+02:00 DST``` which is obviously *out of range*.

**Expected behavior**
Sending to loki causes no error and the timestamp is correct.

**Environment**
**Version used:**
- loki v2.2.1
- fluentbit v1.7.3

**Configuration:**
- see above

**Environment name and version:**
- Docker v18.09.1

**Filters and plugins:**
- just used the docker images as it comes

**Additional context**
I want to collect the logs of all my docker containers and monitor them with grafana. So i use Loki as the log storage. 
I also tried to use promtail for log collection and it worked but the CPU load was too high and i want to use fluentbit because its lightweight and written in C.
My host is a raspberrypi 4 (armv7) with 2GB of RAM as my docker host. I could test it on my Synology NAS (x86_64) but my production system is the raspi.

### PR DESCRIPTION
**Pull request by nokute78**
Fixes #3350 

On 32bit platform (e.g. some raspberry pi OS), out_loki fails to convert timestamp in nanosecond.

I added new function `flb_time_in_nanosec` and out_loki uses it.

----
Enter `[N/A]` in the box, if an item is not applicable to your change.

**Testing**
Before we can approve your change; please submit the following in a comment:
- [N/A] Example configuration file for the change
- [X] Debug log output from testing the change

- [N/A] Attached [Valgrind](https://valgrind.org/docs/manual/quick-start.html) output that shows no leaks or memory corruption was found

**Documentation**

- [N/A] Documentation required for this feature

## Debug log output
```
$ bin/flb-it-flb_time 
Test flb_time_in_nanosec...                     [ OK ]
SUCCESS: All unit tests have passed.
```

output using #3350 configuration
```
fluentbit    | [2021/04/10 23:05:25] [trace] [input:forward:forward.0 at plugins/in_forward/fw.c:97] new TCP connection arrived FD=27
fluentbit    | [2021/04/10 23:05:25] [trace] [input:forward:forward.0 at plugins/in_forward/fw_conn.c:73] read()=172 pre_len=0 now_len=172
fluentbit    | [2021/04/10 23:05:25] [debug] [task] created task=0x7f14b7c30980 id=0 OK
fluentbit    | [2021/04/10 23:05:26] [debug] [http_client] not using http_proxy for header
fluentbit    | [2021/04/10 23:05:26] [debug] [http_client] header=POST /loki/api/v1/push HTTP/1.1
fluentbit    | Host: loki:3100
fluentbit    | Content-Length: 292
fluentbit    | User-Agent: Fluent-Bit
fluentbit    | Content-Type: application/json
fluentbit    | 
fluentbit    | 
fluentbit    | [2021/04/10 23:05:26] [debug] [out coro] cb_destroy coro_id=0
fluentbit    | [0] c70e888dc8b3: [1618095925.000000000, {"container_id"=>"c70e888dc8b3119be04a402a076bfec9ed4d2ed8aa7a871cb9bad74e35f6b9ed", "container_name"=>"/wizardly_fer"}], "source"=>"stdout", "log"=>"testing a log message
fluentbit    | [2021/04/10 23:05:26] [ info] [output:loki:loki.0] loki:3100, HTTP status=204
fluentbit    | [2021/04/10 23:05:26] [debug] [upstream] KA connection #28 to loki:3100 is now available
fluentbit    | [2021/04/10 23:05:26] [debug] [out coro] cb_destroy coro_id=0
fluentbit    | [2021/04/10 23:05:26] [debug] [task] destroy task=0x7f14b7c30980 (task_id=0)
fluentbit    | [2021/04/10 23:05:26] [trace] [input:forward:forward.0 at plugins/in_forward/fw_conn.c:84] fd=27 closed connection
```

----

Fluent Bit is licensed under Apache 2.0, by submitting this pull request I understand that this code will be released under the terms of that license.

### CODE REVIEW

File: include/fluent-bit/flb_time.h [hunk 1]
```diff
@@ -75,6 +75,7 @@ static inline int flb_time_equal(struct flb_time *t0, struct flb_time *t1) {
 int flb_time_get(struct flb_time *tm);
 int flb_time_msleep(uint32_t ms);
 double flb_time_to_double(struct flb_time *tm);
+uint64_t flb_time_in_nanosec(struct flb_time *tm);
```
Comment (edsiper) [inline include/fluent-bit/flb_time.h:78]: would you please rename it to ```flb_time_to_nanosec()```? (similar than flb_time_to_double()) ?

**Review by edsiper — CHANGES_REQUESTED** [review]

File: include/fluent-bit/flb_time.h (hunk 1 above)
Comment (nokute78) [reply include/fluent-bit/flb_time.h]: I renamed and force pushed.

**Comment by edsiper** [comment]
thanks!
