### PR TITLE
in_systemd: fix endless loop on reading a rotated journal

### LINKED ISSUE #899: in_systemd: prevent infinite loop
## Bug Report

 Fluent-bit-v0.14.4 was caught in 100% CPU inside sd_journal_enumerate_data() of in_systemd. The GDB backtrace is given below.

The systemd-journald.service was restarted on that node prior to the observed 100% CPU loop, which might have triggered the issue. 
Here we see that negative return values are possible:
https://github.com/systemd/systemd/blob/9e8b1ec08e8eb0b4611b7caf6adb8828feb32312/src/journal/sd-journal.c#L2312
```
assert_return(!journal_pid_changed(j), -ECHILD);
```

But the negative values of the sd_journal_enumerate_data() are not handled in the current FLB:
```
while (sd_journal_enumerate_data(ctx->j, &data, &length)) {
    entries++;
}
```

I was unable to reproduce the issue so far. It seems that it was a combination of journald restart with some other factors, such as removal of a systemd log database file due to journald vacuum.

Backtrace of the frozen process:
```bash
gdb /fluent-bit/bin/fluent-bit 15
Attaching to program: /fluent-bit/bin/fluent-bit, process 15
[New LWP 17]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
0x00007f93c268b883 in ?? () from /lib/x86_64-linux-gnu/libsystemd.so.0
(gdb) i thr
  Id   Target Id         Frame
* 1    Thread 0x7f93c194af00 (LWP 15) "fluent-bit" 0x00007f93c268b883 in ?? () from /lib/x86_64-linux-gnu/libsystemd.so.0
  2    Thread 0x7f93c13ff700 (LWP 17) "fluent-bit" 0x00007f93c21c7207 in epoll_wait (epfd=3, events=0x7f93c144e300, maxevents=16, timeout=-1) at ../sysdeps/unix/sysv/linux/epoll_wait.c:30
(gdb) thread  1
[Switching to thread 1 (Thread 0x7f93c194af00 (LWP 15))]
#0  0x00007f93c268b883 in ?? () from /lib/x86_64-linux-gnu/libsystemd.so.0
(gdb) bt
#0  0x00007f93c268b883 in ?? () from /lib/x86_64-linux-gnu/libsystemd.so.0
#1  0x00007f93c26c66f7 in sd_journal_enumerate_data () from /lib/x86_64-linux-gnu/libsystemd.so.0
#2  0x0000561f6fb1005f in in_systemd_collect (i_ins=0x7f93c1466480, config=0x7f93c141c1c0, in_context=0x7f93c143b000) at /tmp/src/plugins/in_systemd/systemd.c:147
#3  0x0000561f6fb10427 in in_systemd_collect_archive (i_ins=0x7f93c1466480, config=0x7f93c141c1c0, in_context=0x7f93c143b000) at /tmp/src/plugins/in_systemd/systemd.c:259
#4  0x0000561f6fad7f37 in flb_input_collector_fd (fd=15, config=0x7f93c141c1c0) at /tmp/src/src/flb_input.c:995
#5  0x0000561f6fae0421 in flb_engine_handle_event (config=0x7f93c141c1c0, mask=1, fd=15) at /tmp/src/src/flb_engine.c:296
#6  flb_engine_start (config=0x7f93c141c1c0) at /tmp/src/src/flb_engine.c:515
#7  0x0000561f6fa7c332 in main (argc=4, argv=0x7ffc435bd108) at /tmp/src/src/fluent-bit.c:824
```

Unfortunately, GDB messed up with this process upon detach, so i was not able to step over it to find out the actual return value.

### PR DESCRIPTION
**Pull request by kabakaev**
# Description of the issue

Journald may write logs faster than fluent-bit is able to forward.
For example, the receiving part or network may be too slow.

In such situation, journald will rotate (delete) a journal file that is being read by fluent-bit.
Then, sd_journal_next() will return error (ret_j<0). The current master branch code does not address
such case. Therefore, in_systemd_collect() will be restarted in order to retry reading the very same 
deleted log file. It will never succeed, thus leaving fluent-bit in an endless loop.

The proposed PR fixes this endless loop by detecting such a case and returning an error instead of FLB_SYSTEMD_MORE.

# Steps to reproduce the issue

* setup docker logging into systemd;
* disable systemd-journald throttling
  ```bash
    cat <<EOF > /etc/systemd/journald.conf.d/0-ratelimit.conf
    [Journal]
    RateLimitBurst=10000000
    RateLimitIntervalSec=30s
    EOF
    ```
* run a few containers that log a lot of text constantly;
* configure fluent-bit with the `in_systemd` input and some slow networked output, such as `out_es`, so that FLB would save logs slower then they get generated by the container(s);
* wait for `journald` to fill up one log file and switch to the next one;
* truncate journal: `sudo journalctl --vacuum-size=1`

It may require two or three tries till FLB gets frozen.

fixes #899

### CODE REVIEW

**Comment by edsiper** [comment]
@kabakaev thanks for troubleshooting this!

I'm adding some comments in the PR code.

File: plugins/in_systemd/systemd.c [hunk 1]
```diff
@@ -276,15 +282,28 @@ static int in_systemd_collect(struct flb_input_instance *i_ins,
     if (ret_j == 0) {
         ctx->pending_records = FLB_FALSE;
         return FLB_SYSTEMD_OK;
-    }
-
+    } else if (ret_j > 0) {
```
Comment (edsiper) [inline plugins/in_systemd/systemd.c]: Please add the "else if" statement in a new line, according to:

https://github.com/fluent/fluent-bit/blob/master/CONTRIBUTING.md

File: plugins/in_systemd/systemd.c [hunk 2]
```diff
@@ -276,15 +282,28 @@ static int in_systemd_collect(struct flb_input_instance *i_ins,
...
     /*
-     * ret_j == -1, the loop was broken due to some special condition like
+     * ret_j == 1, but the loop was broken due to some special condition like
      * buffer size limit or it reach the max number of rows that it supposed to
      * process on this call. Assume there are pending records.
      */
     ctx->pending_records = FLB_TRUE;
     return FLB_SYSTEMD_MORE;
+    } else {
```
Comment (edsiper) [inline plugins/in_systemd/systemd.c]: Please add the "else" statement in a new line, according to:

https://github.com/fluent/fluent-bit/blob/master/CONTRIBUTING.md

File: plugins/in_systemd/systemd.c [hunk 3]
```diff
@@ -276,15 +282,28 @@ static int in_systemd_collect(struct flb_input_instance *i_ins,
...
+        ctx->pending_records = FLB_FALSE;
+        sd_journal_get_cursor(ctx->j, &cursor);
+        tmp = flb_input_get_property("read_from_tail", ctx->i_ins);
```
Comment (edsiper) [inline plugins/in_systemd/systemd.c]: I see that read_from_tail option is being re-read every time if ret_j == -1, which is not optimal (string comparisson) but I found that we didn't have a variable context for that. I've pushed 5a360ec945b72fc1e4d6d6337fb312d875e850bf that adds the new variable so you can do ctx->read_from_trail == FLB_TRUE instead of get the plugin property. Please adjust the code using the new context.

File: plugins/in_systemd/systemd.c [hunk 4]
```diff
@@ -333,6 +352,12 @@ static int in_systemd_collect_archive(struct flb_input_instance *i_ins,
         return 0;
     }
 
+    if (ret == FLB_SYSTEMD_ERROR) {
```
Comment (edsiper) [inline plugins/in_systemd/systemd.c]: where the systemd context is being re-created ?, how is this part being tested ?

**Comment by edsiper** [comment]
ping

**Comment by kabakaev** [comment]
@edsiper, I saw your comments. Thanks for quick review. I was on on a journey; will rebase tomorrow.

**Comment by edsiper** [comment]
@kabakaev just asking, do you plan to make the changes this week ?, I ask since 1.1 release is coming and this fix I consider it relevant

**Comment by kabakaev** [comment]
@edsiper, excuse me for the delay. I'm struggling to reproduce the issue after rebase on current master. It takes more than expected. I don't want to submit the rebased code blindly, thus a delay. I could return to this task today evening, if it's not too late for the release. Otherwise, we'll make it into the next one.

File: plugins/in_systemd/systemd.c (hunk 4 above)
Comment (kabakaev) [reply plugins/in_systemd/systemd.c]: The context is being re-created somewhere in retry loop.
I've removed this code. It's not needed.

File: plugins/in_systemd/systemd.c (hunk 3 above)
Comment (kabakaev) [reply plugins/in_systemd/systemd.c]: Actually it does not makes sense to read from tail in this case: we want to minimize the amount of lost logs, hence we need to read the earliest possible log message, which is done always by sd_journal_seek_head(), irrespective of `read_from_tail` property.

**Comment by kabakaev** [comment]
@edsiper, i've re-tested the current state in my environment under high flow of logs. Sure enough, logs are lost, but the flow continues. The latest docker image fluent-bit/fluent-bit:1.0.6-debug stops sending logs after less than a minute.

File: plugins/in_systemd/systemd.c [hunk 5]
```diff
@@ -277,14 +283,27 @@ static int in_systemd_collect(struct flb_input_instance *i_ins,
...
     }
-
+    else if (ret_j > 0) {
     /*
-     * ret_j == -1, the loop was broken due to some special condition like
+     * ret_j == 1, but the loop was broken due to some special condition like
      * buffer size limit or it reach the max number of rows that it supposed to
      * process on this call. Assume there are pending records.
      */
     ctx->pending_records = FLB_TRUE;
```
Comment (edsiper) [inline plugins/in_systemd/systemd.c]: please indent this line and the next one

File: plugins/in_systemd/systemd.c [hunk 6]
```diff
@@ -277,14 +283,27 @@ static int in_systemd_collect(struct flb_input_instance *i_ins,
...
     return FLB_SYSTEMD_MORE;
+    }
+    else {
+        /* Supposedly, current cursor points to a deleted file.
+         * Re-seeking to the first journal entry.
+         * Other failures, such as disk read error, would still lead to infinite loop there,
+         * but at least FLB log will be full of errors. */
+        ret = sd_journal_seek_head(ctx->j);
```
Comment (edsiper) [inline plugins/in_systemd/systemd.c]: If journal notify us that a file being read was deleted/rotated, is it safe to consider to get back to the first entry of the journal ?, do we need to update the cursor in the database if enabled ?

I am not sure about the default behavior... what do you think ?

Comment (kabakaev) [reply plugins/in_systemd/systemd.c]: > If journal notify us that a file being read was deleted/rotated, is it safe to consider to get back to the first entry of the journal ?

Short answer: no.
Long answer: Systemd's [sd_journal_process() sends SD_JOURNAL_INVALIDATE](https://www.freedesktop.org/software/systemd/man/sd_journal_get_fd.html) notification when some journal file gets rotated. But that file is not necesserily the file which is being read by sd_journal_next(). I mean, journald deletes the oldest log files all the time, but FLB is already reading the most fresh log file, and thus not affected by rotation.

Also, rotation can happen during the loop inside in_systemd_collect(). Therefore SD_JOURNAL_INVALIDATE notification will be handled only on a next in_systemd_collect() run.

Therefore I cannot just re-seek the journal every time SD_JOURNAL_INVALIDATE notification arrives. This event is purely informational fur our use case. We should read the journal sequentially when possible, and just seek to the beginning if something went terribly wrong.

> , do we need to update the cursor in the database if enabled ?

I don't think so. If FLB hits this race condition over a deleted file, then in_systemd_collect() will be restarted immediately, because `ctx->pending_records = FLB_TRUE;` is set on error. Thus, new valid DB cursor will be written already on the next iteration.

And even if FLB will be killed between detecting a journal read error (=re-seek) and re-run of in_systemd_collect(), the newly restarted instance will read the last processed journal pointer from sqlite. FLB will try to seek to that (invalid) pointer, will be unable to seek to a point in a deleted file, and [will seek implicitly to the first available entry](https://www.freedesktop.org/software/systemd/man/sd_journal_seek_cursor.html):
>> _If no entry matching the specified cursor is found the call will seek to the next closest entry (in terms of time) instead._

> I am not sure about the default behavior... what do you think ?

I think it is save to continue with the way it is implemented now.
We run hundreds of FLB instances using this code without issue so far.

File: plugins/in_systemd/systemd.c (hunk 5 above)
Comment (kabakaev) [reply plugins/in_systemd/systemd.c]: indentation is fixed

**Comment by edsiper** [comment]
@kabakaev thanks for the explanations and fixes.
