### PR TITLE
out_loki: delay mp_sbuf->data derefence (#3796)

### LINKED ISSUE #3796: Loki Output, labels/label_keys Corrupts Memory
## Bug Report

**Describe the bug**
Bulk loading log files into Loki, I've noticed some odd corruptions and I believe I've narrowed it down to label processing.
With the docker image loading will produce some small amount of corruption while built from source produces a SIGABRT.
Removing `labels` I don't see any errors.

**To Reproduce**
```
[INPUT]
    Name    Dummy
    Tag     dummy.log
    Dummy   {"job_name":"fluent-bit", "log":"some logged event body text"}
    Rate    1000
[OUTPUT]
    Name    loki
    Match   *
    Host    10.0.20.226
    labels  $job_name
```

```
Fluent Bit v1.8.1
* Copyright (C) 2019-2021 The Fluent Bit Authors
* Copyright (C) 2015-2018 Treasure Data
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io

[2021/07/19 23:13:04] [ info] [engine] started (pid=498067)
[2021/07/19 23:13:04] [ info] [storage] version=1.1.1, initializing...
[2021/07/19 23:13:04] [ info] [storage] in-memory
[2021/07/19 23:13:04] [ info] [storage] normal synchronization mode, checksum disabled, max_chunks_up=128
[2021/07/19 23:13:04] [ info] [cmetrics] version=0.1.1
[2021/07/19 23:13:04] [ info] [output:loki:loki.0] configured, hostname=10.0.20.226:3100
[2021/07/19 23:13:04] [ info] [sp] stream processor started
malloc(): mismatching next->prev_size (unsorted)
Aborted (core dumped)
```
**Your Environment**
* Version used: v1.8.1 from source.  Also reproduced in HEAD
* Operating System and version: Arch
* Filters and plugins: Loki

### PR DESCRIPTION
**Pull request by richardburakowski**
msgpack_pack_str_body will return with a new mp_sbuf->data
if mp_sbuf->data was resized

Signed-off-by: Richard Burakowski <richard.burakowski@gmail.com>

move mp_sbuf->data dereference to after msgpack_pack_str_body() call

Fixes #3796 

----
Enter `[N/A]` in the box, if an item is not applicable to your change.

**Testing**
Before we can approve your change; please submit the following in a comment:
- [N/A ] Example configuration file for the change
- [ N/A] Debug log output from testing the change

- [ N/A] Attached [Valgrind](https://valgrind.org/docs/manual/quick-start.html) output that shows no leaks or memory corruption was found

**Documentation**

- [ N/A] Documentation required for this feature

----

Fluent Bit is licensed under Apache 2.0, by submitting this pull request I understand that this code will be released under the terms of that license.

### CODE REVIEW

File: plugins/out_loki/loki.c [hunk 1]
```diff
@@ -268,15 +269,22 @@ static int pack_label_key(msgpack_sbuffer *mp_sbuf, msgpack_packer *mp_pck,
         msgpack_pack_str_body(mp_pck, "_", 1);
     }
 
-    /*
-     * 'p' will point to the next memory area where the key will be
-     * written.
+
+    /* save the current size/offset only as
```
Comment (nokute78) [inline plugins/out_loki/loki.c:273]: Could you modify multiline comment style?
https://github.com/fluent/fluent-bit/blob/master/CONTRIBUTING.md#multiline-comment

e.g. 
```
/*
 * aaa
 */
```

not 
```
/* aaa
 */
```

**Review by nokute78 — CHANGES_REQUESTED** [review]
Could you modify comment style ?

**Comment by nokute78** [comment]
Could you modify below comment style ?

```c
    /* save the current size/offset only as
     * msgpack_pack_str_body will return with a new mp_sbuf->data
     * if mp_sbuf->data was resized with realloc()
     */
```

**Review by nokute78 — APPROVED** [review]
Thank you.

**Comment by nokute78** [comment]
Note: I couldn't "rebase and merge" for this PR
So I did merge commit. 
I could do it and "squash and merge"
