### PR TITLE
Replace `select` by `poll` to fix the 1024 fd limit

### LINKED ISSUE #2508: SIGSEGV while getting kubernetes metadata
## Bug Report

**Describe the bug**

We're running fluent-bit as a daemonset on kubernetes 1.18.6. Using either fluent-bit 1.5.4 or 1.5.3 the pods on some of the nodes go into a crush loop. Interestingly, pods on other nodes function correctly.

Running 1.5.2 results in all pods running correctly without any restart. 

While pods are restarting the following line appears in the api server logs:

```
http: TLS handshake error from <ip>:<port>: EOF
```

The fact that some of the pods work suggests the problem may not be in fluent-bit, but because 1.5.2 works perfectly, I thought it was worth asking here to see if you have any insight.

Logs of one of the failing pods:

```
Fluent Bit v1.5.3
* Copyright (C) 2019-2020 The Fluent Bit Authors
* Copyright (C) 2015-2018 Treasure Data
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io

[2020/08/26 14:13:36] [ info] Configuration:
[2020/08/26 14:13:36] [ info]  flush time     | 1.000000 seconds
[2020/08/26 14:13:36] [ info]  grace          | 5 seconds
[2020/08/26 14:13:36] [ info]  daemon         | 0
[2020/08/26 14:13:36] [ info] ___________
[2020/08/26 14:13:36] [ info]  inputs:
[2020/08/26 14:13:36] [ info]      tail
[2020/08/26 14:13:36] [ info]      systemd
[2020/08/26 14:13:36] [ info] ___________
[2020/08/26 14:13:36] [ info]  filters:
[2020/08/26 14:13:36] [ info]      kubernetes.0
[2020/08/26 14:13:36] [ info]      parser.1
[2020/08/26 14:13:36] [ info] ___________
[2020/08/26 14:13:36] [ info]  outputs:
[2020/08/26 14:13:36] [ info]      forward.0
[2020/08/26 14:13:36] [ info] ___________
[2020/08/26 14:13:36] [ info]  collectors:
[2020/08/26 14:13:36] [ info] [engine] started (pid=1)
[2020/08/26 14:13:36] [debug] [engine] coroutine stack size: 24576 bytes (24.0K)
[2020/08/26 14:13:36] [debug] [storage] [cio stream] new stream registered: tail.0
[2020/08/26 14:13:36] [debug] [storage] [cio stream] new stream registered: systemd.1
[2020/08/26 14:13:36] [ info] [storage] version=1.0.5, initializing...
[2020/08/26 14:13:36] [ info] [storage] in-memory
[2020/08/26 14:13:36] [ info] [storage] normal synchronization mode, checksum disabled, max_chunks_up=128
[2020/08/26 14:13:36] [debug] [input:tail:tail.0] inotify watch fd=20
[2020/08/26 14:13:36] [debug] [input:tail:tail.0] scanning path /var/log/containers/*.log
[2020/08/26 14:13:36] [debug] [input:tail:tail.0] inode=516596 appended file following on offset=127922
[2020/08/26 14:13:36] [debug] [input:tail:tail.0] inode=516596 appended as /var/log/containers/xxxx.log
[2020/08/26 14:13:36] [debug] [input:tail:tail.0] scan_glob add(): /var/log/containers/xxxx.log, inode 516596
.
.
.
[2020/08/26 14:13:37] [debug] [input:tail:tail.0] 1489 new files found on path '/var/log/containers/*.log'
[2020/08/26 14:13:37] [debug] [input:systemd:systemd.1] add filter: _SYSTEMD_UNIT=kubelet.service (or)
[2020/08/26 14:13:37] [ info] [input:systemd:systemd.1] seek_cursor=s=56e3151719034948bee60d26cd7540f6;i=1cd... OK
[2020/08/26 14:13:37] [debug] [input:systemd:systemd.1] sd_journal library may truncate values to sd_journal_get_data_threshold() bytes: 65536
[2020/08/26 14:13:37] [ info] [filter:kubernetes:kubernetes.0] https=1 host=kubernetes.default.svc port=443
[2020/08/26 14:13:37] [ info] [filter:kubernetes:kubernetes.0] local POD info OK
[2020/08/26 14:13:37] [ info] [filter:kubernetes:kubernetes.0] testing connectivity with API server...
[engine] caught signal (SIGSEGV)
#0  0x55d5033ac151      in  flb_io_net_connect() at src/flb_io.c:361
#1  0x55d5033969a9      in  create_conn() at src/flb_upstream.c:256
#2  0x55d503396d6f      in  flb_upstream_conn_get() at src/flb_upstream.c:375
#3  0x55d5034238cd      in  get_api_server_info() at plugins/filter_kubernetes/kube_meta.c:213
#4  0x55d503425e84      in  flb_kube_meta_init() at plugins/filter_kubernetes/kube_meta.c:1000
#5  0x55d503421370      in  cb_kube_init() at plugins/filter_kubernetes/kubernetes.c:199
#6  0x55d5033853fc      in  flb_filter_init_all() at src/flb_filter.c:431
#7  0x55d50339098a      in  flb_engine_start() at src/flb_engine.c:457
#8  0x55d5033052f4      in  flb_main() at src/fluent-bit.c:1035
#9  0x55d503305342      in  main() at src/fluent-bit.c:1048
#10 0x7f628992209a      in  ???() at ???:0
#11 0x55d503302fd9      in  ???() at ???:0
#12 0xffffffffffffffff  in  ???() at ???:0
```

### PR DESCRIPTION
**Pull request by XciD**
Seems like the implementation of select define a limit about the maximum amount of fd to monitor. As the documentation recommend, we could use `poll` or `epoll`.

Signed-off-by: Adrien Carreira <adrien.carreira@ovhcloud.com>

Fixes #2508

----
**Testing**
Before we can approve your change; please submit the following in a comment:
- [ ] Attached [Valgrind](https://valgrind.org/docs/manual/quick-start.html) output that shows no leaks or memory corruption was found
I dont know how I could test it with a real kubernetes configuration, maybe some tips here ?

Fluent Bit is licensed under Apache 2.0, by submitting this pull request I understand that this code will be released under the terms of that license.

### CODE REVIEW

**Comment by shinji62** [comment]
@edsiper Sounds like reasonable PR which may unlock more than one user.

File: src/flb_network.c [hunk 1]
```diff
@@ -267,10 +268,9 @@ static int net_connect_sync(int fd, const struct sockaddr *addr, socklen_t addrl
         FD_ZERO(&wait_set);
         FD_SET(fd, &wait_set);
 
-        /* Wait 'connect_timeout' seconds for an event */
-        timeout.tv_sec = connect_timeout;
-        timeout.tv_usec = 0;
-        ret = select(fd + 1, NULL, &wait_set, NULL, &timeout);
+        pfd_read.fd = fd + 1;
+        pfd_read.events = POLLIN;
+        ret = poll(&pfd_read, 1, connect_timeout) != 1;
```
Comment (edsiper) [inline src/flb_network.c:273]: we will need an approach for other OSes... (Windows and potentially MacOS)

**Review by edsiper — CHANGES_REQUESTED** [review]

**Comment by edsiper** [comment]
@XciD as a quick fix, instead of totally replacing ```select(2)```, can you make a pre-processor conditional and use ```poll``` only for Linux ?, otherwise we will face situations where MacOS and Windows will be likely broken.

note: if you can do it shortly let me know, otherwise I can do it; we are preparing next releases v1.6.11 and v1.7...

**Comment by XciD** [comment]
Yes ! I will also check that it work on Mac OS.

**Comment by shinji62** [comment]
@edsiper Can we have a fix release for 1.5.X please ?

**Comment by bluebike** [comment]
@shinji62  I think that this needs some  \#if ... \#else magic 

```c
#ifdef _WIN32
        FD_ZERO(&wait_set);
        FD_SET(fd, &wait_set);
        timeout.tv_sec = connect_timeout;
        timeout.tv_usec = 0;
        ret = select(fd + 1, NULL, &wait_set, NULL, &timeout);
#else 
        pfd_read.fd = fd + 1;
        pfd_read.events = POLLIN;
        ret = poll(&pfd_read, 1, connect_timeout) != 1;
#endif
```
and also put \#include <sys/poll.h>   and  select/poll-variable definitions in #ifdef.

because Windows doesn't have unix/linux poll(2) (right?)

\#ifdef could be using some cmake defined **HAVE_POLL**

File: src/flb_network.c (hunk 1 above)
Comment (bluebike) [reply src/flb_network.c:273]: Notice that  poll(2) timeout is in milliseconds.
To make compatible with select version..
Something like this should be done.. 
```c
 ret = poll(&pfd_read, 1, connect_timeout * 1000) != 1;
```

**Comment by fujimotos** [comment]
> and also put #include <sys/poll.h> and select/poll-variable definitions in #ifdef. 
> because Windows doesn't have unix/linux poll(2) (right?)

@bluebike I investigated that point a bit today, and found that Windows'
network stack has `WSAPoll()` which is an almost equivalent of `poll(2)`.

https://docs.microsoft.com/en-us/windows/win32/api/winsock2/nf-winsock2-wsapoll

All the other points are just as you pointed out -- poll.h needs an ifdef block for
Windows and timeout should be converted to msec.

So here is a patch that incorporated all the required changes:

https://github.com/fujimotos/fluent-bit/commit/db39788

I spent some time today experimenting this version and can confirm that
this version works fine on Windows.

**Comment by fujimotos** [comment]
@XciD Can you incorporate the above fix into your commit?
I'm thinking something like this:

```bash
# Checkout the original branch
$ git checkout fix-select-limit

# Fetch the changeset from my tree
$ git fetch https://github.com/fujimotos/fluent-bit sf/win32-poll

# Cherry-pick the fixup commit
$ git cherry-pick FETCH_HEAD

# Rebase and squash all the commits into one
$ git rebase -i origin/master
```

I don't have macOS devices at hand, so after you've tested the
updated patch on that platform, I think your PR is mergeable.

**Comment by XciD** [comment]
It's done

File: src/flb_network.c [hunk 2]
```diff
@@ -259,18 +265,17 @@ static int net_connect_sync(int fd, const struct sockaddr *addr, socklen_t addrl
...
 
         /*
-         * Prepare a timeout using select(2): we could use our own
+         * Prepare a timeout using poll(2): we could use our own
          * event loop mechanism for this, but it will require an
-         * extra file descriptor, the select(2) call is straightforward
+         * extra file descriptor, the poll(2) call is straightforward
          * for this use case.
          */
         FD_ZERO(&wait_set);
```
Comment (bluebike) [inline src/flb_network.c:273]: Now variable  `fd_set wait_set`, FD_ZERO and  FD_SET  are useless.

**Comment by bluebike** [comment]
Note about select() implementations: 

In unix version  fd_set variables are bit masks,  (fd = 0 is first bit of first byte.... and so on)
fd_set  size is usually 128 bytes (1024 bits => 1024 file descriptors).    So highest fd value 
select can handle is 1023.

Windows select(2) works differently than unix version (if I remember right).
In windows version fd_set is actually list of file descriptors,  because windows file descriptor 
numbers don't come in sequence (starting from 0),  and length of list is in the start of list. 
So always better to use official macros (FD_SET, FD_ISSET,FD_ZERO)

**Comment by edsiper** [comment]
thanks, everyone for putting your effort into fixing this. I will merge it for now

File: src/flb_network.c [hunk 3]
```diff
@@ -259,18 +264,15 @@ static int net_connect_sync(int fd, const struct sockaddr *addr, socklen_t addrl
...
          * for this use case.
          */
-        FD_ZERO(&wait_set);
-        FD_SET(fd, &wait_set);
 
-        /* Wait 'connect_timeout' seconds for an event */
-        timeout.tv_sec = connect_timeout;
-        timeout.tv_usec = 0;
-        ret = select(fd + 1, NULL, &wait_set, NULL, &timeout);
+        pfd_read.fd = fd + 1;
```
Comment (osela) [inline src/flb_network.c:273]: Sorry for the late response, but shouldn't this be just `fd` instead of `fd + 1`?

Another thing is that the `select` waited for the fd to be writable, while the `poll` waits for it to be readable, not sure it makes any difference in this specific scenario though.

**Comment by edsiper** [comment]
oops! @fujimotos @XciD @bluebike can you take a look at @osela comments ?

File: src/flb_network.c (hunk 3 above)
Comment (bluebike) [reply src/flb_network.c:273]: right!
just `pfd_read.fd = fd;`

**Comment by edsiper** [comment]
@bluebike can you submit a quick PR?

**Comment by bluebike** [comment]
> @bluebike can you submit a quick PR?
ok.

File: src/flb_network.c (hunk 3 above)
Comment (XciD) [reply src/flb_network.c:273]: Just to understand. Why we had a +1 and no more ?

**Comment by bluebike** [comment]
> @bluebike can you submit a quick PR?

#2979

File: src/flb_network.c (hunk 3 above)
Comment (osela) [reply src/flb_network.c:273]: Description of the first argument to `select`:
```
This argument should be set to the highest-numbered file
              descriptor in any of the three sets, plus 1.
```

Comment (XciD) [reply src/flb_network.c:273]: Thanks for the answer.

**Comment by bluebike** [comment]
@osela Thanks for finding that bug.

**Comment by shinji62** [comment]
@edsiper Can we expect a bug fix release for 1.5, 1.6, .. Thanks.
