### PR TITLE
tls: Load system certificates on Windows

### LINKED ISSUE #4735: Windows doesn't load system certificates
## Bug Report

**Describe the bug**

Windows does not seem to be loading certificates from the system certificate store.

See https://github.com/fluent/fluent-bit/blob/v1.8.12/src/tls/openssl.c#L144

This means any protocol using oauth2 should not work on Windows, since the `tls.ca_file` and `tls.ca_path` are set to `NULL` for the oauth TLS connection, and `tls.verify` is set true, and cannot be changed.

See https://github.com/fluent/fluent-bit/blob/v1.8.12/src/flb_oauth2.c#L216

**To Reproduce**

```
[2022/02/02 19:09:53] [ info] [engine] started (pid=4248)
[2022/02/02 19:09:53] [debug] [engine] coroutine stack size: 98302 bytes (96.0K)
[2022/02/02 19:09:53] [debug] [storage] [cio stream] new stream registered: tail.0
[2022/02/02 19:09:53] [ info] [storage] version=1.1.5, initializing...
[2022/02/02 19:09:53] [ info] [storage] in-memory
[2022/02/02 19:09:53] [ info] [storage] normal synchronization mode, checksum disabled, max_chunks_up=128
[2022/02/02 19:09:53] [ info] [cmetrics] version=0.2.2
[2022/02/02 19:09:53] [debug] [input:tail:tail.0] flb_tail_fs_stat_init() initializing stat tail input
[2022/02/02 19:09:53] [debug] [input:tail:tail.0] inode=281474977057307 with offset=0 appended as C:\Users\task_164382884507084\logs\live.log
[2022/02/02 19:09:53] [debug] [input:tail:tail.0] 1 new files found on path 'C:\Users\task_164382884507084\logs\live.log'
[2022/02/02 19:09:53] [debug] [input:tail:tail.0] 0 new files found on path 'C:\Users\task_164382884507084\grizzly-auto-run\screenlog.*'
[2022/02/02 19:09:53] [debug] [storage] [cio stream] new stream registered: emitter.1
[2022/02/02 19:09:53] [debug] [stackdriver:stackdriver.0] created event channels: read=688 write=696
[2022/02/02 19:09:53] [ info] [output:stackdriver:stackdriver.0] metadata_server set to http://metadata.google.internal
[2022/02/02 19:09:53] [debug] [output:stackdriver:stackdriver.0] JWT signature: xxx
[2022/02/02 19:09:53] [debug] [upstream] connection #736 failed to www.googleapis.com:443
[2022/02/02 19:09:53] [debug] [upstream] connection #760 failed to www.googleapis.com:443
[2022/02/02 19:09:53] [error] [oauth2] could not get an upstream connection to www.googleapis.com:443
[2022/02/02 19:09:53] [error] [output:stackdriver:stackdriver.0] error retrieving oauth2 access token
[2022/02/02 19:09:53] [ warn] [output:stackdriver:stackdriver.0] token retrieval failed
[2022/02/02 19:09:53] [debug] [file:file.1] created event channels: read=736 write=684
[2022/02/02 19:09:53] [debug] [router] match rule tail.0:stackdriver.0
[2022/02/02 19:09:53] [debug] [router] match rule emitter.1:stackdriver.0
[2022/02/02 19:09:53] [ info] [sp] stream processor started
--- snip input events ---
[2022/02/02 19:10:03] [debug] [upstream] connection #852 failed to logging.googleapis.com:443
[2022/02/02 19:10:03] [debug] [out coro] cb_destroy coro_id=1
[2022/02/02 19:10:03] [debug] [retry] new retry created for task_id=1 attempts=1
[2022/02/02 19:10:03] [ warn] [engine] failed to flush chunk '4248-1643829001.617610000.flb', retry in 7 seconds: task_id=1, input=emitter_for_rewrite_tag.0 > output=stackdriver.0 (out_id=0)
```

*    configure stackdriver output on Windows
*    start fluent-bit
*    check fluent-bit Log_File for successful connection to www.googleapis.com:443

**Expected behavior**
System certificates should be loaded, or `tls.ca_file`/`tls.ca_path` should be changable for oauth2.

**Your Environment**

* Version used: 1.8.12 (but bug exists from 1.7 to current)
* Configuration: 
   ```
   [SERVICE]
       Daemon       Off
       Log_File     $USERPROFILE\\td-agent-bit.log
       Log_Level    debug
       Parsers_File $USERPROFILE\\td-agent-bit\\conf\\parsers.conf
       Plugins_File $USERPROFILE\\td-agent-bit\\conf\\plugins.conf

   [INPUT]
       Name tail
       Path $USERPROFILE\\logs\\live.log,$USERPROFILE\\grizzly-auto-run\\screenlog.*
       Path_Key file
       Key message
       Refresh_Interval 5
       Read_from_Head On
       Skip_Long_Lines On
       Buffer_Max_Size 1M
       DB td-grizzly-logs.pos

   [FILTER]
       Name rewrite_tag
       Match tail.*
       Rule \$file screenlog.([0-9]+)$ screen\$1.log false
       Rule \$file ([^\\\\]+)$ \$1 false

   [FILTER]
       Name record_modifier
       Match *
       Record host task-${TASK_ID}-run-${RUN_ID}
       Record pool ${TASKCLUSTER_FUZZING_POOL-unknown}
       Remove_key file

   [OUTPUT]
       Name stackdriver
       Match *
       google_service_credentials $USERPROFILE\\google_logging_creds.json
       resource global

   [OUTPUT]
       Name file
       Match screen*.log
       Path $USERPROFILE\\logs\\
       Format template
       Template {time} {message}
    ```

* Environment name and version (e.g. Kubernetes? What version?): AWS
* Server type and version:
* Operating System and version: Windows Server 2016
* Filters and plugins: stackdriver

**Additional context**

This was the root cause for #3496. If I use v1.6.10 I can successfully get an oauth token with the same config.

### PR DESCRIPTION
**Pull request by jschwartzentruber**
Signed-off-by: Jesse Schwartzentruber <truber@mozilla.com>

This change ports the code from the mbed implementation to iterate over the Windows CA store and load each into the OpenSSL CA store.

Fixes #4735 

----
Enter `[N/A]` in the box, if an item is not applicable to your change.

**Testing**
Before we can approve your change; please submit the following in a comment:
- [N/A] Example configuration file for the change
- [X] Debug log output from testing the change

In the below case I ran in another terminal: `echo hello world > live.log`
I confirmed this line is reported to Google Cloud Logs properly.
```
[2022/02/04 08:02:35] [ info] [engine] started (pid=4244)
[2022/02/04 08:02:35] [debug] [engine] coroutine stack size: 98302 bytes (96.0K)
[2022/02/04 08:02:35] [debug] [storage] [cio stream] new stream registered: tail.0
[2022/02/04 08:02:35] [ info] [storage] version=1.1.6, initializing...
[2022/02/04 08:02:35] [ info] [storage] in-memory
[2022/02/04 08:02:35] [ info] [storage] normal synchronization mode, checksum disabled, max_chunks_up=128
[2022/02/04 08:02:35] [ info] [cmetrics] version=0.2.2
[2022/02/04 08:02:36] [debug] [input:tail:tail.0] flb_tail_fs_stat_init() initializing stat tail input
[2022/02/04 08:02:36] [debug] [input:tail:tail.0] 0 new files found on path 'C:\Users\User\Desktop\live.log'
[2022/02/04 08:02:36] [debug] [input:tail:tail.0] 0 new files found on path 'C:\Users\User\Desktop\screenlog.*'
[2022/02/04 08:02:36] [debug] [storage] [cio stream] new stream registered: emitter.1
[2022/02/04 08:02:36] [debug] [stackdriver:stackdriver.0] created event channels: read=716 write=720
[2022/02/04 08:02:36] [ info] [output:stackdriver:stackdriver.0] metadata_server set to http://metadata.google.internal
[2022/02/04 08:02:37] [debug] [output:stackdriver:stackdriver.0] JWT signature: xxx
[2022/02/04 08:02:37] [debug] [http_client] not using http_proxy for header
[2022/02/04 08:02:37] [ info] [oauth2] HTTP Status=200
[2022/02/04 08:02:37] [debug] [oauth2] payload: xxx
[2022/02/04 08:02:37] [ info] [oauth2] access token from 'www.googleapis.com:443' retrieved
[2022/02/04 08:02:37] [debug] [upstream] KA connection #796 to www.googleapis.com:443 is now available
[2022/02/04 08:02:37] [debug] [file:file.1] created event channels: read=848 write=852
[2022/02/04 08:02:37] [debug] [router] match rule tail.0:stackdriver.0
[2022/02/04 08:02:37] [debug] [router] match rule emitter.1:stackdriver.0
[2022/02/04 08:02:37] [ info] [sp] stream processor started
[2022/02/04 08:02:37] [debug] [input:tail:tail.0] [static files] processed 0b, done
[2022/02/04 08:02:42] [debug] [input:tail:tail.0] 0 new files found on path 'C:\Users\User\Desktop\live.log'
[2022/02/04 08:02:42] [debug] [input:tail:tail.0] 0 new files found on path 'C:\Users\User\Desktop\screenlog.*'
[2022/02/04 08:02:47] [debug] [input:tail:tail.0] 0 new files found on path 'C:\Users\User\Desktop\live.log'
[2022/02/04 08:02:47] [debug] [input:tail:tail.0] 0 new files found on path 'C:\Users\User\Desktop\screenlog.*'
[2022/02/04 08:02:52] [debug] [input:tail:tail.0] 0 new files found on path 'C:\Users\User\Desktop\live.log'
[2022/02/04 08:02:52] [debug] [input:tail:tail.0] 0 new files found on path 'C:\Users\User\Desktop\screenlog.*'
[2022/02/04 08:02:57] [debug] [input:tail:tail.0] 0 new files found on path 'C:\Users\User\Desktop\live.log'
[2022/02/04 08:02:57] [debug] [input:tail:tail.0] 0 new files found on path 'C:\Users\User\Desktop\screenlog.*'
[2022/02/04 08:03:02] [debug] [input:tail:tail.0] 0 new files found on path 'C:\Users\User\Desktop\live.log'
[2022/02/04 08:03:02] [debug] [input:tail:tail.0] 0 new files found on path 'C:\Users\User\Desktop\screenlog.*'
[2022/02/04 08:03:07] [debug] [input:tail:tail.0] inode=1970324837213267 with offset=0 appended as C:\Users\User\Desktop\live.log
[2022/02/04 08:03:07] [debug] [input:tail:tail.0] 1 new files found on path 'C:\Users\User\Desktop\live.log'
[2022/02/04 08:03:07] [debug] [input:tail:tail.0] 0 new files found on path 'C:\Users\User\Desktop\screenlog.*'
[2022/02/04 08:03:07] [debug] [upstream] drop keepalive connection #-1 to www.googleapis.com:443 (keepalive idle timeout)
[2022/02/04 08:03:07] [debug] [input chunk] update output instances with new chunk size diff=65
[2022/02/04 08:03:07] [debug] [input:tail:tail.0] [static files] processed 16b
[2022/02/04 08:03:07] [debug] [input:tail:tail.0] inode=1970324837213267 file=C:\Users\User\Desktop\live.log promote to TAIL_EVENT
[2022/02/04 08:03:07] [debug] [input:tail:tail.0] [static files] processed 0b, done
[2022/02/04 08:03:12] [debug] [task] created task=0000021F5F943DC0 id=0 OK
[2022/02/04 08:03:12] [debug] [input:tail:tail.0] 0 new files found on path 'C:\Users\User\Desktop\live.log'
[2022/02/04 08:03:12] [debug] [input:tail:tail.0] 0 new files found on path 'C:\Users\User\Desktop\screenlog.*'
[2022/02/04 08:03:13] [debug] [output:stackdriver:stackdriver.0] [logging.googleapis.com/monitored_resource] not found in the payload
[2022/02/04 08:03:13] [debug] [http_client] not using http_proxy for header
[2022/02/04 08:03:13] [debug] [output:stackdriver:stackdriver.0] HTTP Status=200
[2022/02/04 08:03:13] [debug] [upstream] KA connection #948 to logging.googleapis.com:443 is now available
[2022/02/04 08:03:13] [debug] [out flush] cb_destroy coro_id=0
[2022/02/04 08:03:13] [debug] [task] destroy task=0000021F5F943DC0 (task_id=0)
[2022/02/04 08:03:17] [debug] [input:tail:tail.0] 0 new files found on path 'C:\Users\User\Desktop\live.log'
````

With `windows_load_system_certificates` commented out, same machine and config.
In this case I again ran `echo hello world 2 >> live.log` and confirmed this line was not reported to Google Cloud Logs.
```
[2022/02/04 08:07:19] [ info] [engine] started (pid=5672)
[2022/02/04 08:07:19] [debug] [engine] coroutine stack size: 98302 bytes (96.0K)
[2022/02/04 08:07:19] [debug] [storage] [cio stream] new stream registered: tail.0
[2022/02/04 08:07:19] [ info] [storage] version=1.1.6, initializing...
[2022/02/04 08:07:19] [ info] [storage] in-memory
[2022/02/04 08:07:19] [ info] [storage] normal synchronization mode, checksum disabled, max_chunks_up=128
[2022/02/04 08:07:19] [ info] [cmetrics] version=0.2.2
[2022/02/04 08:07:19] [debug] [input:tail:tail.0] flb_tail_fs_stat_init() initializing stat tail input
[2022/02/04 08:07:19] [debug] [input:tail:tail.0] inode=1970324837213267 with offset=16 appended as C:\Users\User\Desktop\live.log
[2022/02/04 08:07:19] [debug] [input:tail:tail.0] 1 new files found on path 'C:\Users\User\Desktop\live.log'
[2022/02/04 08:07:19] [debug] [input:tail:tail.0] 0 new files found on path 'C:\Users\User\Desktop\screenlog.*'
[2022/02/04 08:07:19] [debug] [storage] [cio stream] new stream registered: emitter.1
[2022/02/04 08:07:19] [debug] [stackdriver:stackdriver.0] created event channels: read=732 write=736
[2022/02/04 08:07:19] [ info] [output:stackdriver:stackdriver.0] metadata_server set to http://metadata.google.internal
[2022/02/04 08:07:19] [debug] [output:stackdriver:stackdriver.0] JWT signature: xxx
[2022/02/04 08:07:20] [debug] [upstream] connection #784 failed to www.googleapis.com:443
[2022/02/04 08:07:20] [debug] [upstream] connection #800 failed to www.googleapis.com:443
[2022/02/04 08:07:20] [error] [oauth2] could not get an upstream connection to www.googleapis.com:443
[2022/02/04 08:07:20] [error] [output:stackdriver:stackdriver.0] error retrieving oauth2 access token
[2022/02/04 08:07:20] [ warn] [output:stackdriver:stackdriver.0] token retrieval failed
[2022/02/04 08:07:20] [debug] [file:file.1] created event channels: read=804 write=808
[2022/02/04 08:07:20] [debug] [router] match rule tail.0:stackdriver.0
[2022/02/04 08:07:20] [debug] [router] match rule emitter.1:stackdriver.0
[2022/02/04 08:07:20] [ info] [sp] stream processor started
[2022/02/04 08:07:20] [debug] [input:tail:tail.0] inode=1970324837213267 file=C:\Users\User\Desktop\live.log promote to TAIL_EVENT
[2022/02/04 08:07:20] [debug] [input:tail:tail.0] [static files] processed 0b, done
[2022/02/04 08:07:25] [debug] [input:tail:tail.0] 0 new files found on path 'C:\Users\User\Desktop\live.log'
[2022/02/04 08:07:25] [debug] [input:tail:tail.0] 0 new files found on path 'C:\Users\User\Desktop\screenlog.*'
[2022/02/04 08:07:28] [debug] [input chunk] update output instances with new chunk size diff=67
[2022/02/04 08:07:30] [debug] [input:tail:tail.0] 0 new files found on path 'C:\Users\User\Desktop\live.log'
[2022/02/04 08:07:30] [debug] [input:tail:tail.0] 0 new files found on path 'C:\Users\User\Desktop\screenlog.*'
[2022/02/04 08:07:30] [debug] [task] created task=000001C91C397620 id=0 OK
[2022/02/04 08:07:31] [debug] [upstream] connection #800 failed to logging.googleapis.com:443
[2022/02/04 08:07:31] [debug] [out flush] cb_destroy coro_id=0
[2022/02/04 08:07:31] [debug] [retry] new retry created for task_id=0 attempts=1
[2022/02/04 08:07:31] [ warn] [engine] failed to flush chunk '5672-1643990848.343034000.flb', retry in 6 seconds: task_id=0, input=emitter_for_rewrite_tag.0 > output=stackdriver.0 (out_id=0)
[2022/02/04 08:07:35] [debug] [input:tail:tail.0] 0 new files found on path 'C:\Users\User\Desktop\live.log'
[2022/02/04 08:07:35] [debug] [input:tail:tail.0] 0 new files found on path 'C:\Users\User\Desktop\screenlog.*'
[2022/02/04 08:07:37] [debug] [upstream] connection #884 failed to logging.googleapis.com:443
[2022/02/04 08:07:37] [debug] [out flush] cb_destroy coro_id=1
[2022/02/04 08:07:37] [debug] [task] task_id=0 reached retry-attempts limit 1/1
[2022/02/04 08:07:37] [ warn] [engine] chunk '5672-1643990848.343034000.flb' cannot be retried: task_id=0, input=emitter_for_rewrite_tag.0 > output=stackdriver.0
[2022/02/04 08:07:37] [debug] [task] destroy task=000001C91C397620 (task_id=0)
[2022/02/04 08:07:40] [debug] [input:tail:tail.0] 0 new files found on path 'C:\Users\User\Desktop\live.log'
[2022/02/04 08:07:40] [debug] [input:tail:tail.0] 0 new files found on path 'C:\Users\User\Desktop\screenlog.*'
```

- [N/A] Attached [Valgrind](https://valgrind.org/docs/manual/quick-start.html) output that shows no leaks or memory corruption was found

If this is a change to packaging of containers or native binaries then please confirm it works for all targets.
- [N/A] Attached [local packaging test](./packaging/local-build-all.sh) output showing all targets (including any new ones) build.

**Documentation**
- [N/A] Documentation required for this feature

**Backporting**

- [X] Backport to latest stable release.

1.8: #4752

----

Fluent Bit is licensed under Apache 2.0, by submitting this pull request I understand that this code will be released under the terms of that license.

### CODE REVIEW

File: src/tls/openssl.c [hunk 1]
```diff
@@ -133,14 +133,60 @@ static void tls_context_destroy(void *ctx_backend)
     flb_free(ctx);
 }
 
+#ifdef _MSC_VER
+static int windows_load_system_certificates(struct tls_context *ctx)
+{
+    int ret;
+
+    HANDLE h;
```
Comment (leonardo-albertovich) [inline src/tls/openssl.c:141]: Could you please group variable definitions at the beginning of the function and use meaningful names for them?

File: src/tls/openssl.c [hunk 2]
```diff
@@ -133,14 +133,60 @@ static void tls_context_destroy(void *ctx_backend)
...
+    PCCERT_CONTEXT cert = NULL;
+    X509_STORE *store = SSL_CTX_get_cert_store(ctx->ctx);
+    X509 *x509;
+
+    h = CertOpenSystemStoreA(0, "Root");
```
Comment (leonardo-albertovich) [inline src/tls/openssl.c:146]: I think according to MSDN `NULL` would be the right first parameter here which is a nit for sure but since we're making changes it'd be good to change it as well.

File: src/tls/openssl.c [hunk 3]
```diff
@@ -133,14 +133,60 @@ static void tls_context_destroy(void *ctx_backend)
...
+    if (h == NULL) {
+        flb_error("[tls] Cannot open cert store: %i", GetLastError());
+        return -1;
+    }
+
+    while (cert = CertEnumCertificatesInStore(h, cert)) {
+        if (cert->dwCertEncodingType & X509_ASN_ENCODING) {
+            // Decode the certificate into X509 struct
+            // `buf` is necessary per openssl docs because the pointer is incremented
+            const unsigned char *buf = cert->pbCertEncoded;
```
Comment (leonardo-albertovich) [inline src/tls/openssl.c:156]: Could you move the definition of this variable to the beginning of the function?

File: src/tls/openssl.c [hunk 4]
```diff
@@ -133,14 +133,60 @@ static void tls_context_destroy(void *ctx_backend)
...
+            x509 = d2i_X509(NULL, &buf, cert->cbCertEncoded);
+            if (!x509) {
+                flb_debug("[tls] Cannot parse a certificate. skipping...");
+                continue;
+            }
+
+            // Add X509 struct to the openssl cert store
+            ret = X509_STORE_add_cert(store, x509);
```
Comment (leonardo-albertovich) [inline src/tls/openssl.c:164]: I assume this is well tested but while checking the man page for this call to verify what happens to x509 I saw this : 

```
X509_STORE_add_cert() and X509_STORE_add_crl() add the respective object to the X509_STORE's local storage. Untrusted objects should not be added in this way. The added object's reference count is incremented by one, hence the caller retains ownership of the object and needs to free it when it is no longer needed.
```

I might be wrong but I interpreted that as meaning that they don't make a copy and releasing our instance before the validation is performed would probably end in an illegal access. Could you clarify this for me?

https://www.openssl.org/docs/man1.1.1/man3/X509_STORE_add_cert.html

**Review by leonardo-albertovich — CHANGES_REQUESTED** [review]
Once these issues are addressed it will have my blessing. Obviously the same thing goes for the 1.8 port which is the exact same code.

File: src/tls/openssl.c (hunk 2 above)
Comment (jschwartzentruber) [reply src/tls/openssl.c:146]: MSDN does say `NULL`, but then shows `0` in the example code.  Using `NULL` results in a compiler warning but `0` does not.

```
C:\Users\User\Desktop\fluent-bit-master\src\tls\openssl.c(146,34): warning C4047: 'function': 'HCRYPTPROV_LEGACY' differs in levels of indirection from 'void *' [C:\Users\User\Desktop\fluent-bit-master\build-rls2\src\fluent-bit-static.vcxproj]
C:\Users\User\Desktop\fluent-bit-master\src\tls\openssl.c(146,30): warning C4024: 'CertOpenSystemStoreA': different types for formal and actual parameter 1 [C:\Users\User\Desktop\fluent-bit-master\build-rls2\src\fluent-bit-static.vcxproj]
```

File: src/tls/openssl.c (hunk 3 above)
Comment (jschwartzentruber) [reply src/tls/openssl.c:156]: 👍🏻

**Comment by leonardo-albertovich** [comment]
I've approved this PR and the backport one as well.
