### PR TITLE
in_winlog: Split an identifier into "EventID" and "Qualifiers"

### LINKED ISSUE #2872: [in_winlog] EventID field being incorrectly parsed for large numbers
## Bug Report

**Describe the bug**
When parsing winlog events having big `EventID` numbers, the `EventID` parsing fails and returns an incorrect number having the same 16 low-significant-bits, but aleatory 16 high-significant-bits. For smaller `EventID`s, this does not happen. But then, if I send the log record manually using PowerShell (see in the Screenshots section below) and a big `EventID` number, it works correctly.

**To Reproduce**
- Open `EventViewer`. I recommend starting with a clear log, so you only get the newly created logs.
- Use the following configuration:
```
[INPUT]
    Name winlog
    Tag  test-winlog
    Channels Application

[OUTPUT]
    Name stdout
    Match *
```
- Observe the events flowing in both with Fluent Bit and EventViewer, until you get an event with `EventID` being `16384` or `16394` **as emitted by Windows (not via Powershell).**
- Observe this same record as captured by Fluent Bit. You'll see how the `EventID` does not match. But if you convert both numbers (the correct one and the incorrect one as reported by Fluent Bit) to binary, you'll observe how the 16 least significant bits are the same.
- You can manually send a log record with these commands (as administrator):
```
New-EventLog -LogName Application -Source "Josep Test"
Write-EventLog -LogName Application -Source "Josep Test" -EntryType Information -EventId 16664 -Message "Hello world 3"
```
- You will see how, strangely, in this case it does work.

**Expected behavior**
The `EventID` as reported by EventViewer and Fluent Bit should always match.

**Screenshots**
- Case 1: parsing record with `EventID=16394`:
-- Fluent Bit output:
```
[0] test-winlog: [1608205854.085633700, {"RecordNumber"=>4290, "TimeGenerated"=>"2020-12-17 12:37:18 +0100", "TimeWritten"=>"2020-12-17 12:37:18 +0100", "EventID"=>3221241866, "EventType"=>"Information", "EventCategory"=>0, "Channel"=>"Application", "SourceName"=>"Software Protection Platform Service", "ComputerName"=>"DESKTOP-ER9S966", "Data"=>"", "Sid"=>"", "Message"=>"Offline downlevel migration succeeded.
"}]
```
-- Record XML (from EventViewer):
```
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
	<System>
		<Provider Name="Microsoft-Windows-Security-SPP" Guid="{E23B33B0-C8C9-472C-A5F9-F2BDFEA0F156}" EventSourceName="Software Protection Platform Service" />
		<EventID Qualifiers="49152">16394</EventID>
		<Version>0</Version>
		<Level>4</Level>
		<Task>0</Task>
		<Opcode>0</Opcode>
		<Keywords>0x80000000000000</Keywords>
		<TimeCreated SystemTime="2020-12-17T11:37:18.984807400Z" />
		<EventRecordID>4290</EventRecordID>
		<Correlation />
		<Execution ProcessID="0" ThreadID="0" />
		<Channel>Application</Channel>
		<Computer>DESKTOP-ER9S966</Computer>
		<Security />
	</System>
	<EventData />
</Event>
```
-- Bit representation comparison (note how the lowest 16 significant bits match):
Screen Shot 2020-12-17 at 2 22 12 PM

- Case 2: parsing record with `EventID=16384`:
-- Fluent Bit output:
```
[1] test-winlog: [1608205854.092364000, {"RecordNumber"=>4291, "TimeGenerated"=>"2020-12-17 12:38:11 +0100", "TimeWritten"=>"2020-12-17 12:38:11 +0100", "EventID"=>1073758208, "EventType"=>"Information", "EventCategory"=>0, "Channel"=>"Application", "SourceName"=>"Software Protection Platform Service", "ComputerName"=>"DESKTOP-ER9S966", "Data"=>"", "Sid"=>"", "Message"=>"Successfully scheduled Software Protection service for re-start at 2020-12-18T07:30:11Z. Reason: RulesEngine.
"}]
```
-- Record XML (from EventViewer):
```
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
	<System>
		<Provider Name="Microsoft-Windows-Security-SPP" Guid="{E23B33B0-C8C9-472C-A5F9-F2BDFEA0F156}" EventSourceName="Software Protection Platform Service" />
		<EventID Qualifiers="16384">16384</EventID>
		<Version>0</Version>
		<Level>4</Level>
		<Task>0</Task>
		<Opcode>0</Opcode>
		<Keywords>0x80000000000000</Keywords>
		<TimeCreated SystemTime="2020-12-17T11:38:11.714307300Z" />
		<EventRecordID>4291</EventRecordID>
		<Correlation />
		<Execution ProcessID="0" ThreadID="0" />
		<Channel>Application</Channel>
		<Computer>DESKTOP-ER9S966</Computer>
		<Security />
	</System>
	<EventData>
		<Data>2020-12-18T07:30:11Z</Data>
		<Data>RulesEngine</Data>
	</EventData>
</Event>
```
-- Bit representation comparison (note how the 16 lowest significant bits match):
Screen Shot 2020-12-17 at 2 22 24 PM

- Case 3: parsing record with `EventID=8224` **(this one works correctly)**:
-- Fluent Bit output:
```
[1] test-winlog: [1608211588.235362300, {"RecordNumber"=>4307, "TimeGenerated"=>"2020-12-17 13:57:22 +0100", "TimeWritten"=>"2020-12-17 13:57:22 +0100", "EventID"=>8224, "EventType"=>"Information", "EventCategory"=>0, "Channel"=>"Application", "SourceName"=>"VSS", "ComputerName"=>"DESKTOP-ER9S966", "Data"=>"2d20436f64653a2020434f525356434330303030303735392d2043616c6c3a2020434f525356434330303030303734312d205049443a202030303030343037322d205449443a202030303030333931322d20434d443a2020433a5c57696e646f77735c73797374656d33325c76737376632e6578652020202d20557365723a204e616d653a204e5420415554484f524954595c53595354454d2c205349443a532d312d352d313820", "Sid"=>"", "Message"=>"The VSS service is shutting down due to idle timeout.
```
-- Record XML (from EventViewer):
```
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
	<System>
		<Provider Name="VSS" />
		<EventID Qualifiers="0">8224</EventID>
		<Level>4</Level>
		<Task>0</Task>
		<Keywords>0x80000000000000</Keywords>
		<TimeCreated SystemTime="2020-12-17T12:57:22.002173100Z" />
		<EventRecordID>4307</EventRecordID>
		<Channel>Application</Channel>
		<Computer>DESKTOP-ER9S966</Computer>
		<Security />
	</System>
	<EventData>
		<Data />
		<Binary>2D20436F64653A2020434F525356434330303030303735392D2043616C6C3A2020434F525356434330303030303734312D205049443A202030303030343037322D205449443A202030303030333931322D20434D443A2020433A5C57696E646F77735C73797374656D33325C76737376632E6578652020202D20557365723A204E616D653A204E5420415554484F524954595C53595354454D2C205349443A532D312D352D313820</Binary>
	</EventData>
</Event>
```

- Case 4: parsing record with `EventID=16664` **sent manually** **(this one works correctly)**:
-- Command used to send log (via Powershell):
```
New-EventLog -LogName Application -Source "Josep Test"
Write-EventLog -LogName Application -Source "Josep Test" -EntryType Information -EventId 16664 -Message "Hello world 3"
```
-- Fluent Bit output:
```
[0] test-winlog: [1608211588.231485700, {"RecordNumber"=>4306, "TimeGenerated"=>"2020-12-17 13:19:39 +0100", "TimeWritten"=>"2020-12-17 13:19:39 +0100", "EventID"=>16664, "EventType"=>"Information", "EventCategory"=>1, "Channel"=>"Application", "SourceName"=>"Josep Test", "ComputerName"=>"DESKTOP-ER9S966", "Data"=>"", "Sid"=>"", "Message"=>"Hello world 3
"}]
```
-- Record XML (from EventViewer):
```
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
	<System>
		<Provider Name="Josep Test" />
		<EventID Qualifiers="0">16664</EventID>
		<Level>4</Level>
		<Task>1</Task>
		<Keywords>0x80000000000000</Keywords>
		<TimeCreated SystemTime="2020-12-17T12:19:39.803100300Z" />
		<EventRecordID>4306</EventRecordID>
		<Channel>Application</Channel>
		<Computer>DESKTOP-ER9S966</Computer>
		<Security />
	</System>
	<EventData>
		<Data>Hello world 3</Data>
	</EventData>
</Event>
```

**Your Environment**
* Version used: 1.5.4, 1.6.3
* Configuration: (attached above)
* Environment name and version (e.g. Kubernetes? What version?): -
* Server type and version: MacBook Pro (happens in other servers)
* Operating System and version: Windows 10
* Filters and plugins: `in_winlog`, `stdout`

**Additional context**
I suspect the problem is caused by how the EventID is being parsed or when written to the record outputted by the `in_winlog` plugin. For example,  (instead of parsing it as a 16-bit integer, 32 bits are being considered. I base my hypothesis on the fact that the lower significant bits of both correct and incorrect values match. But then, it is still very weird that if I manually send the log record using PowerShell with a big `EventID` number, it works correctly.

### PR DESCRIPTION
**Pull request by fujimotos**
This changes the plugin to emit `EVENTLOGRECORD.EventID` as two
separate fields.

i.e. it splits an event identifier into:

    +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
    |S|R|C|N|r|    Facility         |               Code            |
    +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
    -------------------------------- --------------------------------
            Qualifiers                          EventID

This is how Windows Event Viewer treats the field, and hence this is
what most users expect. Fixes #2872.

Signed-off-by: Fujimoto Seiji <fujimoto@ceptord.net>

### CODE REVIEW

File: plugins/in_winlog/pack.c [hunk 1]
```diff
@@ -372,7 +372,12 @@ void winlog_pack_event(msgpack_packer *mp_pck, PEVENTLOGRECORD evt,
     /* EventId */
     msgpack_pack_str(mp_pck, 7);
     msgpack_pack_str_body(mp_pck, "EventID", 7);
-    msgpack_pack_uint32(mp_pck, evt->EventID);
+    msgpack_pack_uint16(mp_pck, evt->EventID & 0xffff);
+
+    /* Qualifiers */
+    msgpack_pack_str(mp_pck, 10);
+    msgpack_pack_str_body(mp_pck, "Qualifiers", 10);
+    msgpack_pack_uint16(mp_pck, evt->EventID >> 16);
```
Comment (jsubirat) [inline plugins/in_winlog/pack.c:380]: Hi @fujimotos , apologies in advance since my C knowledge is more than rusty (used it in on by BS degree 15 years ago). When shifting integers having a "1" on their left side, I recall there was some kind of issue in which the "1" was then copied all over the MSBs. After a quick check, though, I saw that[ this supposedly happens when the original number is negative](https://stackoverflow.com/questions/14396858/right-shift-with-zeros-at-the-beginning). So, I guess this is fine, right? Or would it be necessary to do `(evt->EventID >> 16) && 0xffff`?

Comment (fujimotos) [reply plugins/in_winlog/pack.c:380]: @jsubirat As far as I can tell, the current implementation is just fine.

> When shifting integers having a "1" on their left side, I recall there was some kind of issue in which the "1" was then copied all over the MSBs

This issue occurs when we apply bit-shift on a negative integer. So
it becomes problematic only when the operatee is a signed type.

In contrast, `EventID` is declared as DWORD (which is an _unsigned_ integer
in Windows world). So  `EventID >> 16` should always work as expected.

Comment (jsubirat) [reply plugins/in_winlog/pack.c:380]: Thanks for the clarification! :-)

**Comment by edsiper** [comment]
thanks!
