### PR TITLE
out_es: fix es bulk buffer overrun

### LINKED ISSUE #5680: FluentBit crash on Windows
## Bug Report

**Describe the bug**

After updating Fluent Bit from 1.5.2 to 1.9.3, I'm seeing random crashes in production.

**Your Environment**

* Version used: 1.9.3
* Configuration: See below
* Environment name and version: AWS EC2 instance
* Server type and version: Windows
* Operating System and version: Server 2016
* Filters and plugins: in_tail, filter_lua, output_es

`fluent-bit.conf`:
```
[SERVICE]
    daemon              false
    flush               1
    log_level           debug
    # log_file            fluent-bit.log
    parsers_file        parsers.conf
    http_server         true
    http_listen         0.0.0.0
    http_port           2020
    health_check        true

[INPUT]
    name                tail
    tag                 pharos.*
    path                C:\PharosSystems\Logs\Json\PharosMpsLog.txt
    db                  C:\PharosSystems\Logs\Json\FluentBit.db
    parser              json
    buffer_chunk_size   64kb
    buffer_max_size     64kb
    mem_buf_limit       16mb
    skip_long_lines     true
    refresh_interval    10

[FILTER]
    name                lua
    match               *
    script              filters.lua
    call                transform

[OUTPUT]
    name                es
    match               *
    host                logs
    port                443
    logstash_format     true
    replace_dots        true
    retry_limit         5
    trace_error         true
    buffer_size         64kb
    aws_auth            true
    tls                 true
```
`filters.lua`:
```lua
function transform(tag, timestamp, record)
    if record["Payload"] then
        record["Service"] = record["Payload"]["processName"]
    end

    if not record["Message"] and record["Payload"]["message"] then
        record["Message"], record["Payload"]["message"] = record["Payload"]["message"], nil
    end

    if record["Properties"] and record["Properties"]["StatusCode"] then
        record["Properties"]["StatusCode"] = tostring(record["Properties"]["StatusCode"])
    end

    return 1, timestamp, record
end
```
**Additional context**

Dump file captured with Sysinternals [ProcDump](https://docs.microsoft.com/en-us/sysinternals/downloads/procdump) using `procdump64.exe -ma -e fluent-bit.exe`:
* [fluent-bit.exe_220705_151325.zip](https://github.com/fluent/fluent-bit/files/9051931/fluent-bit.exe_220705_151325.zip)

Looking around with [WinDbg Preview](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/windbg-install-preview):
```

Microsoft (R) Windows Debugger Version 10.0.25136.1001 AMD64
Copyright (c) Microsoft Corporation. All rights reserved.


Loading Dump File [D:\Work\Support\FluentBit\fluent-bit.exe_220705_151325\fluent-bit.exe_220705_151325.dmp]
User Mini Dump File with Full Memory: Only application data is available

Comment: '
*** "C:\PharosSystems\SysinternalsSuite\procdump64.exe" -ma -e fluent-bit.exe
*** Unhandled exception: C0000005.ACCESS_VIOLATION'

************* Path validation summary **************
Response                         Time (ms)     Location
Deferred                                       srv*D:\Symbols*http://msdl.microsoft.com/download/symbols
OK                                             D:\SymbolsTemp
Symbol search path is: srv*D:\Symbols*http://msdl.microsoft.com/download/symbols;D:\SymbolsTemp
Executable search path is: 
Windows 10 Version 14393 MP (2 procs) Free x64
Product: Server, suite: TerminalServer DataCenter SingleUserTS
Edition build lab: 10.0.14393.5125 (rs1_release.220429-1732)
Machine Name:
Debug session time: Wed Jul  6 03:13:25.000 2022 (UTC + 12:00)
System Uptime: 2 days 9:41:01.606
Process Uptime: 0 days 13:52:32.000
..........................................
This dump file has an exception of interest stored in it.
The stored exception information can be accessed via .ecxr.
(16ec.16dc): Access violation - code c0000005 (first/second chance not available)
For analysis of this file, run !analyze -v
ntdll!RtlpAllocateHeap+0x12da:
00007ffc`ed175fda 488b08          mov     rcx,qword ptr [rax] ds:2265646f`63704f22=????????????????
0:005> .kframes 0n100
Default stack trace depth is 0n100 frames
0:005> .prefer_dml 1
DML versions of commands on by default
0:005> .reload /f
..........................................
0:005> lm
start             end                 module name
00007ff6`c0230000 00007ff6`c0a5a000   fluent_bit   (private pdb symbols)  d:\symbolstemp\fluent-bit.pdb
00007ffc`dff50000 00007ffc`dff66000   NapiNSP    (pdb symbols)          d:\symbols\NapiNSP.pdb\6A1E2DD884D24B0B8F89441A8693673C1\NapiNSP.pdb
00007ffc`dff70000 00007ffc`dff7e000   winrnr     (pdb symbols)          d:\symbols\winrnr.pdb\A497F69E1B7A41F28EF8390F833AB47A1\winrnr.pdb
00007ffc`e2490000 00007ffc`e249a000   rasadhlp   (pdb symbols)          d:\symbols\rasadhlp.pdb\5EB493878A6F4865AF6EE51C56207CF01\rasadhlp.pdb
00007ffc`e61b0000 00007ffc`e61ca000   dhcpcsvc   (pdb symbols)          d:\symbols\dhcpcsvc.pdb\896F47CEEF60427FBE41C39E04C01D9E1\dhcpcsvc.pdb
00007ffc`e6210000 00007ffc`e6226000   dhcpcsvc6   (pdb symbols)          d:\symbols\dhcpcsvc6.pdb\BC7D98B165E241B7856EA8A03648BD371\dhcpcsvc6.pdb
00007ffc`e6910000 00007ffc`e6928000   nlaapi     (pdb symbols)          d:\symbols\nlaapi.pdb\55CC67AE0E7A423BB758846D361972001\nlaapi.pdb
00007ffc`e7180000 00007ffc`e71e1000   wevtapi    (pdb symbols)          d:\symbols\wevtapi.pdb\2F5835A7F06F43EE86ADF99297D785921\wevtapi.pdb
00007ffc`e8a00000 00007ffc`e8a33000   rsaenh     (pdb symbols)          d:\symbols\rsaenh.pdb\95B56C8731B44E9AA2858411CD4281E21\rsaenh.pdb
00007ffc`e8b80000 00007ffc`e8bb8000   IPHLPAPI   (pdb symbols)          d:\symbols\iphlpapi.pdb\4C53537F0DAA44AF97FA62AD31BC46481\iphlpapi.pdb
00007ffc`e8bc0000 00007ffc`e8c62000   dnsapi     (pdb symbols)          d:\symbols\dnsapi.pdb\5C6526F84E6C4878B0CCB26BA6E564A41\dnsapi.pdb
00007ffc`e8e50000 00007ffc`e8ead000   mswsock    (pdb symbols)          d:\symbols\mswsock.pdb\DAA810367BC04CDD8EBFE12DA2EB501C1\mswsock.pdb
00007ffc`e9000000 00007ffc`e9017000   cryptsp    (pdb symbols)          d:\symbols\cryptsp.pdb\677162669D6740539787653CD28E727F1\cryptsp.pdb
00007ffc`e9020000 00007ffc`e902b000   CRYPTBASE   (pdb symbols)          d:\symbols\cryptbase.pdb\A4945E336F8347DDA43A2E9E5FC0ED541\cryptbase.pdb
00007ffc`e94e0000 00007ffc`e950b000   bcrypt     (pdb symbols)          d:\symbols\bcrypt.pdb\C66626E3ED344020A87327CB85BC26D01\bcrypt.pdb
00007ffc`e9590000 00007ffc`e95a4000   profapi    (pdb symbols)          d:\symbols\profapi.pdb\CAC4E3CC2E9B4973B17D131D0EFC8ACE1\profapi.pdb
00007ffc`e95b0000 00007ffc`e95bf000   kernel_appcore   (pdb symbols)          d:\symbols\Kernel.Appcore.pdb\34F749B066CB4C2DA6F3E8EEB6013A8A1\Kernel.Appcore.pdb
00007ffc`e95c0000 00007ffc`e95d0000   msasn1     (pdb symbols)          d:\symbols\msasn1.pdb\960B2EDD42C2489F8C1AB3816BF8E9341\msasn1.pdb
00007ffc`e95d0000 00007ffc`e961c000   powrprof   (pdb symbols)          d:\symbols\powrprof.pdb\74B38765BC2D4D1B9E53834273CE9ABF1\powrprof.pdb
00007ffc`e9620000 00007ffc`e9813000   crypt32    (pdb symbols)          d:\symbols\crypt32.pdb\37224C862FEF48A78732D55DA43319AF1\crypt32.pdb
00007ffc`e98d0000 00007ffc`e9978000   SHCore     (pdb symbols)          d:\symbols\shcore.pdb\DD5B4BDC74714727A71E4F62D53DB41B1\shcore.pdb
00007ffc`e9980000 00007ffc`e999e000   win32u     (pdb symbols)          d:\symbols\win32u.pdb\CE777C7E22FC4E43A47A1D6EF5E1AF031\win32u.pdb
00007ffc`e99a0000 00007ffc`e99e2000   cfgmgr32   (pdb symbols)          d:\symbols\cfgmgr32.pdb\0C85585E81E54222A3065E20B6C913D41\cfgmgr32.pdb
00007ffc`e99f0000 00007ffc`e9a5c000   bcryptPrimitives   (pdb symbols)          d:\symbols\bcryptprimitives.pdb\66FD402F0E2C4120A9CE02CE189B48E91\bcryptprimitives.pdb
00007ffc`e9a60000 00007ffc`ea133000   windows_storage   (pdb symbols)          d:\symbols\Windows.Storage.pdb\815F10C0A2804CF49A9BEAA4152EBB5F1\Windows.Storage.pdb
00007ffc`ea140000 00007ffc`ea2c4000   gdi32full   (pdb symbols)          d:\symbols\gdi32full.pdb\747C73435FBD4F1784BB0FB4F88D54961\gdi32full.pdb
00007ffc`ea2d0000 00007ffc`ea3c4000   ucrtbase   (pdb symbols)          d:\symbols\ucrtbase.pdb\FB16A8A30FFD4D868EA1F6402B3143F81\ucrtbase.pdb
00007ffc`ea4d0000 00007ffc`ea6ee000   KERNELBASE   (pdb symbols)          d:\symbols\kernelbase.pdb\162A8BD56C304693A8AB2468E50C5F6A1\kernelbase.pdb
00007ffc`ea890000 00007ffc`ebd96000   shell32    (pdb symbols)          d:\symbols\shell32.pdb\C1EE097F73C64A229FFE4097566613111\shell32.pdb
00007ffc`ebe40000 00007ffc`ebf5d000   rpcrt4     (pdb symbols)          d:\symbols\rpcrt4.pdb\C4E0FD0447934EC38FCB2D46A2A4BED21\rpcrt4.pdb
00007ffc`ebf60000 00007ffc`ec006000   advapi32   (pdb symbols)          d:\symbols\advapi32.pdb\0EC476B28EA04617B741EDF5C605AEBC1\advapi32.pdb
00007ffc`ec070000 00007ffc`ec10e000   msvcrt     (pdb symbols)          d:\symbols\msvcrt.pdb\BAFC8C0A0A7648E0A6C2FC97B72A04B11\msvcrt.pdb
00007ffc`ec120000 00007ffc`ec17b000   sechost    (pdb symbols)          d:\symbols\sechost.pdb\F78401B62F914F38AEF989B6261E214B1\sechost.pdb
00007ffc`ec180000 00007ffc`ec22d000   kernel32   (pdb symbols)          d:\symbols\kernel32.pdb\5098B486BCBA4FDFBE1B74CE5C48DC341\kernel32.pdb
00007ffc`ec830000 00007ffc`ec969000   ole32      (private pdb symbols)  d:\symbols\ole32.pdb\0E805AFF195F4448B05AE219EAB08F071\ole32.pdb
00007ffc`ec970000 00007ffc`ec9da000   ws2_32     (pdb symbols)          d:\symbols\ws2_32.pdb\88345C10081E4DA7BC9942E4DDCBA06C1\ws2_32.pdb
00007ffc`ec9e0000 00007ffc`eca14000   gdi32      (pdb symbols)          d:\symbols\gdi32.pdb\44AE0735CFE84F5D847786D34C02BC401\gdi32.pdb
00007ffc`ecae0000 00007ffc`ecb32000   shlwapi    (pdb symbols)          d:\symbols\shlwapi.pdb\BE622E17968E4B1CBFF14120667BC4C61\shlwapi.pdb
00007ffc`ecb40000 00007ffc`ecb48000   nsi        (pdb symbols)          d:\symbols\nsi.pdb\8D9A83E03AC843A09A4D7329EB9186C61\nsi.pdb
00007ffc`ecd10000 00007ffc`ecfd6000   combase    (private pdb symbols)  d:\symbols\combase.pdb\7F9766E264B5460DB6B97F055B10AB241\combase.pdb
00007ffc`ecfe0000 00007ffc`ed146000   user32     (pdb symbols)          d:\symbols\user32.pdb\BB7C068C642C4ED2AA5E9DD14A009B311\user32.pdb
00007ffc`ed150000 00007ffc`ed31f000   ntdll      (pdb symbols)          d:\symbols\ntdll.pdb\13B5E8DAE6F540E49137EE219A7ED12D1\ntdll.pdb
0:005> !analyze -v
*******************************************************************************
*                                                                             *
*                        Exception Analysis                                   *
*                                                                             *
*******************************************************************************

DEBUG_FLR_EXCEPTION_CODE(c0000374) and the ".exr -1" ExceptionCode(c0000005) don't match

KEY_VALUES_STRING: 1

    Key  : AV.Fault
    Value: Read

    Key  : Analysis.CPU.mSec
    Value: 436

    Key  : Analysis.DebugAnalysisManager
    Value: Create

    Key  : Analysis.Elapsed.mSec
    Value: 428

    Key  : Analysis.Init.CPU.mSec
    Value: 452

    Key  : Analysis.Init.Elapsed.mSec
    Value: 30315

    Key  : Analysis.Memory.CommitPeak.Mb
    Value: 184

    Key  : Timeline.OS.Boot.DeltaSec
    Value: 207661

    Key  : Timeline.Process.Start.DeltaSec
    Value: 49952

    Key  : WER.OS.Branch
    Value: rs1_release

    Key  : WER.OS.Timestamp
    Value: 2022-04-29T17:32:00Z

    Key  : WER.OS.Version
    Value: 10.0.14393.5125

    Key  : WER.Process.Version
    Value: 1.9.3.0


FILE_IN_CAB:  fluent-bit.exe_220705_151325.dmp

COMMENT:  
*** "C:\PharosSystems\SysinternalsSuite\procdump64.exe" -ma -e fluent-bit.exe
*** Unhandled exception: C0000005.ACCESS_VIOLATION

NTGLOBALFLAG:  0

APPLICATION_VERIFIER_FLAGS:  0

CONTEXT:  (.ecxr)
rax=2265646f63704f22 rbx=0000026e07d80000 rcx=0000000076654c22
rdx=0000000000040000 rsi=0000026e08755da0 rdi=0000000000000301
rip=00007ffced175fda rsp=000000b2b2dfec70 rbp=000000b2b2dff029
 r8=0000026e07d860b0  r9=000000000000001b r10=0000000000000000
r11=0000026e086a0080 r12=0000026e08755db0 r13=0000026e07d80150
r14=0000026e08a033a0 r15=0000000000000001
iopl=0         nv up ei ng nz ac pe cy
cs=0033  ss=002b  ds=002b  es=002b  fs=0053  gs=002b             efl=00010291
ntdll!RtlpAllocateHeap+0x12da:
00007ffc`ed175fda 488b08          mov     rcx,qword ptr [rax] ds:2265646f`63704f22=????????????????
Resetting default scope

EXCEPTION_RECORD:  (.exr -1)
ExceptionAddress: 00007ffced175fda (ntdll!RtlpAllocateHeap+0x00000000000012da)
   ExceptionCode: c0000005 (Access violation)
  ExceptionFlags: 00000000
NumberParameters: 2
   Parameter[0]: 0000000000000000
   Parameter[1]: ffffffffffffffff
Attempt to read from address ffffffffffffffff

PROCESS_NAME:  fluent-bit.exe

READ_ADDRESS:  ffffffffffffffff 

ERROR_CODE: (NTSTATUS) 0xc0000005 - The instruction at 0x%p referenced memory at 0x%p. The memory could not be %s.

EXCEPTION_CODE_STR:  c0000005

EXCEPTION_PARAMETER1:  0000000000000000

EXCEPTION_PARAMETER2:  ffffffffffffffff

ADDITIONAL_DEBUG_TEXT:  Enable Pageheap/AutoVerifer ; Followup set based on attribute [Is_ChosenCrashFollowupThread] from Frame:[0] on thread:[PSEUDO_THREAD]

FAULTING_THREAD:  000016dc

STACK_TEXT:  
00000000`00000000 00000000`00000000 heap_corruption!fluent-bit.exe+0x0


STACK_COMMAND:  ** Pseudo Context ** ManagedPseudo ** Value: ffffffff ** ; kb

SYMBOL_NAME:  heap_corruption!fluent-bit.exe

MODULE_NAME: heap_corruption

IMAGE_NAME:  heap_corruption

FAILURE_BUCKET_ID:  HEAP_CORRUPTION_c0000005_heap_corruption!fluent-bit.exe

OS_VERSION:  10.0.14393.5125

BUILDLAB_STR:  rs1_release

OSPLATFORM_TYPE:  x64

OSNAME:  Windows 10

FAILURE_ID_HASH:  {e4b4a773-236c-d32e-a7f9-5bb698111271}

Followup:     MachineOwner
---------

0:005> kb
 # RetAddr               : Args to Child                                                           : Call Site
00 00007ffc`ed173ba5     : 0000026e`07d80000 00000000`00000002 00000000`00005000 00000000`00005010 : ntdll!RtlpAllocateHeap+0x12da
01 00007ffc`ed171090     : 0000026e`07d80000 00000000`00005000 0000026e`08a40fc0 00000000`00000000 : ntdll!RtlpAllocateHeapInternal+0x1115
02 00007ffc`ed170b4f     : 00000000`00000000 00000000`00000000 00000000`00000000 0000026e`07b40000 : ntdll!RtlpReAllocateHeap+0x220
03 00007ffc`ed170a51     : 00000000`00000000 00000000`00000000 00000000`00000000 00007ff6`c072902c : ntdll!RtlpReAllocateHeapInternal+0xdf
04 00007ff6`c07e1b53     : 00000000`00000300 000000b2`b2dff6c0 000000b2`b2dff7b0 000000b2`b2dff6c0 : ntdll!RtlReAllocateHeap+0x31
05 00007ff6`c02df2fb     : 000000b2`b2dff550 000000b2`b2dff599 0000026e`08882f25 00000000`00002134 : fluent_bit!_realloc_base+0x73 [minkernel\crts\ucrt\src\appcrt\heap\realloc_base.cpp @ 46] 
06 (Inline Function)     : --------`-------- --------`-------- --------`-------- --------`-------- : fluent_bit!flb_realloc+0x17 [C:\projects\fluent-bit-2e87g\include\fluent-bit\flb_mem.h @ 94] 
07 00007ff6`c02e1682     : 0000026e`08882f25 000000b2`b2dff599 000000b2`b2dff680 00000000`00000000 : fluent_bit!flb_json_tokenise+0x5b [C:\projects\fluent-bit-2e87g\src\flb_pack.c @ 62] 
08 00007ff6`c02df93d     : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : fluent_bit!pack_json_to_msgpack+0xe2 [C:\projects\fluent-bit-2e87g\src\flb_pack.c @ 246] 
09 00007ff6`c034f8a9     : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : fluent_bit!flb_pack_json+0x1d [C:\projects\fluent-bit-2e87g\src\flb_pack.c @ 280] 
0a 00007ff6`c034f5cb     : 0000026e`085a7990 00000000`00000000 00000000`0000e360 00007ff6`c0833ea0 : fluent_bit!elasticsearch_error_check+0x49 [C:\projects\fluent-bit-2e87g\plugins\out_es\es.c @ 662] 
0b 00007ff6`c0306f61     : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`0000e360 : fluent_bit!cb_es_flush+0x4ab [C:\projects\fluent-bit-2e87g\plugins\out_es\es.c @ 884] 
0c 00007ff6`c0765c1e     : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : fluent_bit!output_pre_cb_flush+0xc1 [C:\projects\fluent-bit-2e87g\include\fluent-bit\flb_output.h @ 522] 
0d 00007ffc`ea53e951     : 00007ff6`c0306ea0 00000000`00000000 00000000`00000000 00000000`00000000 : fluent_bit!co_thunk+0xe [C:\projects\fluent-bit-2e87g\lib\monkey\deps\flb_libco\fiber.c @ 23] 
0e 00000000`00000000     : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : KERNELBASE!BaseFiberStart+0x21
0:005> dx Debugger.Sessions[0].Processes[5868].Threads[5852].Stack.Frames[5].SwitchTo();dv /t /v
Debugger.Sessions[0].Processes[5868].Threads[5852].Stack.Frames[5].SwitchTo()
@rdi              void * block = 0x0000026e`08a40fd0
@rbx              unsigned int64 size = 0x5000
@rax              void * new_block = 0x2265646f`63704f22
0:005> dx Debugger.Sessions[0].Processes[5868].Threads[5852].Stack.Frames[6].SwitchTo();dv /t /v
Debugger.Sessions[0].Processes[5868].Threads[5852].Stack.Frames[6].SwitchTo()
0:005> dx Debugger.Sessions[0].Processes[5868].Threads[5852].Stack.Frames[7].SwitchTo();dv /t /v
Debugger.Sessions[0].Processes[5868].Threads[5852].Stack.Frames[7].SwitchTo()
@rsi              char * js = 0x0000026e`08882f25 "{"took":332,"errors":false,"items":[{"create":{"_index":"logstash-2022.07.05","_type":"_doc","_id":"Ty_szoEBF-nUXHgNWXaO","_version":1,"result":"created","_shards":{"total":2,"successful":2,"failed":0},"_seq_no":3041226,"_primary_term":1,"status":201}},{"create":{"_index":"logstash-2022.07.05","_type":"_doc","_id":"UC_szoEBF-nUXHgNWXaO","_version":1,"result":"created","_shards":{"total":2,"successful":2,"failed":0},"_seq_no":3040758,"_primary_term":1,"status":201}},{"create":{"_index":"logstash-2022.07.05","_type":"_doc","_id":"US_szoEBF-nUXHgNWXaO","_version":1,"result":"created","_shards":{"total":2,"successful":2,"failed":0},"_seq_no":3040759,"_primary_term":1,"status":201}},{"create":{"_index":"logstash-2022.07.05","_type":"_doc","_id":"Ui_szoEBF-nUXHgNWXaO","_version":1,"result":"created","_shards":{"total":2,"successful":2,"failed":0},"_seq_no":3038876,"_primary_term":1,"status":201}},{"create":{"_index":"logstash-2022.07.05","_type":"_doc","_id":"Uy_szoEBF-nUXHgNWXaO","_version":1,"result":"created","_shards":{"total":2,"successful":2,"failed":0},"_seq_no":3041227,"_primary_term":1,"status":201}},{"create":{"_index":"logstash-2022.07.05","_type":"_doc","_id":"VC_szoEBF-nUXHgNWXaO","_version":1,"result":"created","_shards":{"total":2,"successful":2,"failed":0},"_seq_no":3036203,"_primary_term":1,"status":201}},{"create":{"_index":"logstash-2022.07.05","_type":"_doc","_id":"VS_szoEBF-nUXHgNWXaO","_version":1,"result":"created","_shards":{"total":2,"successful":2,"failed":0},"_seq_no":3038877,"_primary_term":1,"status":201}},{"create":{"_index":"logstash-2022.07.05","_type":"_doc","_id":"Vi_szoEBF-nUXHgNWXaO","_version":1,"result":"created","_shards":{"total":2,"successful":2,"failed":0},"_seq_no":3040760,"_primary_term":1,"status":201}},{"create":{"_index":"logstash-2022.07.05","_type":"_doc","_id":"Vy_szoEBF-nUXHgNWXaO","_version":1,"result":"created","_shards":{"total":2,"successful":2,"failed":0},"_seq_no":3038878,"_primary_term":1,"status":201}},{"create":{"_index":"logstash-2022.07.05","_type":"_doc","_id":"WC_szoEBF-nUXHgNWXaO","_version":1,"result":"created","_shards":{"total":2,"successful":2,"failed":0},"_seq_no":3040761,"_primary_term":1,"status":201}},{"create":{"_index":"logstash-2022.07.05","_type":"_doc","_id":"WS_szoEBF-nUXHgNWXaO","_version":1,"result":"created","_shards":{"total":2,"successful":2,"failed":0},"_seq_no":3039421,"_primary_term":1,"status":201}},{"create":{"_index":"logstash-2022.07.05","_type":"_doc","_id":"Wi_szoEBF-nUXHgNWXaO","_version":1,"result":"created","_shards":{"total":2,"successful":2,"failed":0},"_seq_no":3040762,"_primary_term":1,"status":201}},{"create":{"_index":"logstash-2022.07.05","_type":"_doc","_id":"Wy_szoEBF-nUXHgNWXaO","_version":1,"result":"created","_shards":{"total":2,"successful":2,"failed":0},"_seq_no":3036204,"_primary_term":1,"status":201}},{"create":{"_index":"logstash-2022.07.05","_type":"_doc","_id":"XC_szoEBF-nUXHgNWXaO","_version":1,"result":"created","_shards":{"total":2,"successful":2,"failed":0},"_seq_no":3041228,"_primary_term":1,"status":201}},{"create":{"_index":"logstash-2022.07.05","_type":"_doc","_id":"XS_szoEBF-nUXHgNWXaO","_version":1,"result":"created","_shards":{"total":2,"successful":2,"failed":0},"_seq_no":3039422,"_primary_term":1,"status":201}},{"create":{"_index":"logstash-2022.07.05","_type":"_doc","_id":"Xi_szoEBF-nUXHgNWXaO","_version":1,"result":"created","_shards":{"total":2,"successful":2,"failed":0},"_seq_no":3041229,"_primary_term":1,"status":201}},{"create":{"_index":"logstash-2022.07.05","_type":"_doc","_id":"Xy_szoEBF-nUXHgNWXaO","_version":1,"result":"created","_shards":{"total":2,"successful":2,"failed":0},"_seq_no":3040763,"_primary_term":1,"status":201}},{"create":{"_index":"logstash-2022.07.05","_type":"_doc","_id":"YC_szoEBF-nUXHgNWXaO","_version":1,"result":"created","_shards":{"total":2,"successful":2,"failed":0},"_seq_no":3039423,"_primary_term":1,"status":201}},{"create":{"_index":"logstash-2022.07.05","_type":"_doc","_id":"YS_szoEBF-nUXHgNWXaO","_version":1,"result":"created","_shards":{"total":2,"successful":2,"failed":0},"_seq_no":3036205,"_primary_term":1,"status":201}},{"create":{"_index":"logstash-2022.07.05","_type":"_doc","_id":"Yi_szoEBF-nUXHgNWXaO","_version":1,"result":"created","_shards":{"total":2,"successful":2,"failed":0},"_seq_no":3038879,"_primary_term":1,"status":201}},{"create":{"_index":"logstash-2022.07.05","_type":"_doc","_id":"Yy_szoEBF-nUXHgNWXaO","_version":1,"result":"created","_shards":{"total":2,"successful":2,"failed":0},"_seq_no":3041230,"_primary_term":1,"status":201}},{"create":{"_index":"logstash-2022.07.05","_type":"_doc","_id":"ZC_szoEBF-nUXHgNWXaO","_version":1,"result":"created","_shards":{"total":2,"successful":2,"failed":0},"_seq_no":3036206,"_primary_term":1,"status":201}},{"create":{"_index":"logstash-2022.07.05","_type":"_doc","_id":"ZS_szoEBF-nUXHgNWXaO","_version":1,"result":"created","_shards":{"total":2,"successful":2,"failed":0},"_seq_no":3036207,"_primary_term":1,"status":201}},{"create":{"_index":"logstash-2022.07.05","_type":"_doc","_id":"Zi_szoEBF-nUXHgNWXaO","_version":1,"result":"created","_shards":{"total":2,"successful":2,"failed":0},"_seq_no":3039424,"_primary_term":1,"status":201}},{"create":{"_index":"logstash-2022.07.05","_type":"_doc","_id":"Zy_szoEBF-nUXHgNWXaO","_version":1,"result":"created","_shards":{"total":2,"successful":2,"failed":0},"_seq_no":3039425,"_primary_term":1,"status":201}},{"create":{"_index":"logstash-2022.07.05","_type":"_doc","_id":"aC_szoEBF-nUXHgNWXaO","_version":1,"result":"created","_shards":{"total":2,"successful":2,"failed":0},"_seq_no":3039426,"_primary_term":1,"status":201}},{"create":{"_index":"logstash-2022.07.05","_type":"_doc","_id":"aS_szoEBF-nUXHgNWXaO","_version":1,"result":"created","_shards":{"total":2,"successful":2,"failed":0},"_seq_no":3041231,"_primary_term":1,"status":201}},{"create":{"_index":"logstash-2022.07.05","_type":"_doc","_id":"ai_szoEBF-nUXHgNWXaO","_version":1,"result":"created","_shards":{"total":2,"successful":2,"failed":0},"_seq_no":3041232,"_primary_term":1,"status":201}},{"create":{"_index":"logstash-2022.07.05","_type":"_doc","_id":"ay_szoEBF-nUXHgNWXaO","_version":1,"result":"created","_shards":{"total":2,"successful":2,"failed":0},"_seq_no":3039427,"_primary_term":1,"status":201}},{"create":{"_index":"logstash-2022.07.05","_type":"_doc","_id":"bC_szoEBF-nUXHgNWXaO","_version":1,"result":"created","_shards":{"total":2,"successful":2,"failed":0},"_seq_no":3041233,"_primary_term":1,"status":201}},{"create":{"_index":"logstash-2022.07.05","_type":"_doc","_id":"bS_szoEBF-nUXHgNWXaO","_version":1,"result":"created","_shards":{"total":2,"successful":2,"failed":0},"_seq_no":3040764,"_primary_term":1,"status":201}},{"create":{"_index":"logstash-2022.07.05","_type":"_doc","_id":"bi_szoEBF-nUXHgNWXaO","_version":1,"result":"created","_shards":{"total":2,"successful":2,"failed":0},"_seq_no":3036208,"_primary_term":1,"status":201}},{"create":{"_index":"logstash-2022.07.05","_type":"_doc","_id":"by_szoEBF-nUXHgNWXaO","_version":1,"result":"created","_shards":{"total":2,"successful":2,"failed":0},"_seq_no":3040765,"_primary_term":1,"status":201}},{"create":{"_index":"logstash-2022.07.05","_type":"_doc","_id":"cC_szoEBF-nUXHgNWXaO","_version":1,"result":"created","_shards":{"total":2,"successful":2,"failed":0},"_seq_no":3036209,"_primary_term":1,"status":201}},{"create":{"_index":"logstash-2022.07.05","_type":"_doc","_id":"cS_szoEBF-nUXHgNWXaO","_version":1,"result":"created","_shards":{"total":2,"successful":2,"failed":0},"_seq_no":3040766,"_primary_term":1,"status":201}},{"create":{"_index":"logstash-2022.07.05","_type":"_doc","_id":"ci_szoEBF-nUXHgNWXaO","_version":1,"result":"created","_shards":{"total":2,"successful":2,"failed":0},"_seq_no":3038880,"_primary_term":1,"status":201}},{"create":{"_index":"logstash-2022.07.05","_type":"_doc","_id":"cy_szoEBF-nUXHgNWXaO","_version":1,"result":"created","_shards":{"total":2,"successful":...2,"failed":0},"_seq_no":3041234,"_primary_term":1,"status":201}},{"create":{"_index":"logstash-2022.07.05","_type":"_doc","_id":"dC_szoEBF-nUXHgNWXaO","_version":1,"result":"created","_shards":{"total":2,"successful":2,"failed":0},"_seq_no":3041235,"_primary_term":1,"status":201}},{"create":{"_index":"logstash-2022.07.05","_type":"_doc","_id":"dS_szoEBF-nUXHgNWXaO","_version":1,"result":"created","_shards":{"total":2,"successful":2,"failed":0},"_seq_no":3038881,"_primary_term":1,"status":201}}]}"
@rdi              unsigned int64 len = 0x2134
@rbx              struct flb_pack_state * state = 0x000000b2`b2dff550
<unavailable>     int ret = <value unavailable>
<unavailable>     unsigned int64 new_size = <value unavailable>
@rax              void * tmp = 0x2265646f`63704f22
0:005> dx -r1 ((fluent_bit!flb_pack_state *)0xb2b2dff550)
((fluent_bit!flb_pack_state *)0xb2b2dff550)                 : 0xb2b2dff550 [Type: flb_pack_state *]
    [+0x000] multiple         : 0 [Type: int]
    [+0x004] tokens_count     : 0 [Type: int]
    [+0x008] tokens_size      : 768 [Type: int]
    [+0x00c] last_byte        : 0 [Type: int]
    [+0x010] tokens           : 0x26e08a40fd0 [Type: jsmntok *]
    [+0x018] parser           [Type: jsmn_parser]
    [+0x028] buf_data         : 0x26e087b64c0 : "2022-07-05T15:13:19.0028054Z" [Type: char *]
    [+0x030] buf_size         : 0x1400 [Type: unsigned __int64]
    [+0x038] buf_len          : 0x0 [Type: unsigned __int64]
0:005> dx -r1 tmp
tmp                 : 0x2265646f63704f22 [Type: void *]
0:005> dd 0x2265646f63704f22
2265646f`63704f22  ???????? ???????? ???????? ????????
2265646f`63704f32  ???????? ???????? ???????? ????????
2265646f`63704f42  ???????? ???????? ???????? ????????
2265646f`63704f52  ???????? ???????? ???????? ????????
2265646f`63704f62  ???????? ???????? ???????? ????????
2265646f`63704f72  ???????? ???????? ???????? ????????
2265646f`63704f82  ???????? ???????? ???????? ????????
2265646f`63704f92  ???????? ???????? ???????? ????????
```

PTAL @fujimotos 🙏

### PR DESCRIPTION
**Pull request by gitfool**
Fixes #5680.

----
Enter `[N/A]` in the box, if an item is not applicable to your change.

**Testing**
Before we can approve your change; please submit the following in a comment:
- [ ] Example configuration file for the change
- [x] Debug log output from testing the change *

- [ ] Attached [Valgrind](https://valgrind.org/docs/manual/quick-start.html) output that shows no leaks or memory corruption was found

If this is a change to packaging of containers or native binaries then please confirm it works for all targets.
- [ ] Attached [local packaging test](./packaging/local-build-all.sh) output showing all targets (including any new ones) build.

**Documentation**

- [ ] Documentation required for this feature

**Backporting**

- [ ] Backport to latest stable release.

Note: All testing was on Windows Server 2016. See https://github.com/fluent/fluent-bit/issues/5680#issuecomment-1194723285 for logs leading up to the crash _before_ these changes.

----

Fluent Bit is licensed under Apache 2.0, by submitting this pull request I understand that this code will be released under the terms of that license.

### CODE REVIEW

**Comment by gitfool** [comment]
PTAL; I've been testing this in production for the last week. The output looks good and the daily crashes have stopped.

**Comment by gitfool** [comment]
I fixed the commit message to comply with the contribution guidelines.

I'm not sure how to fix the linker issues with `max` though, which obviously builds and links for windows. 😕

**Comment by gitfool** [comment]
I've tried a tweak to fix the `max` issue. Just need the workflow approved to run again.

**Comment by gitfool** [comment]
The macos builds are still failing with:
````
[ 67%] Building C object plugins/out_es/CMakeFiles/flb-plugin-out_es.dir/es_conf.c.o
[ 67%] Building C object plugins/out_es/CMakeFiles/flb-plugin-out_es.dir/es_bulk.c.o
[ 67%] Building C object plugins/out_es/CMakeFiles/flb-plugin-out_es.dir/es.c.o
/Users/runner/work/fluent-bit/fluent-bit/plugins/out_es/es_bulk.c:88:27: error: implicit declaration of function 'max' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
            append_size = max(append_size, remaining_size);
                          ^
/Users/runner/work/fluent-bit/fluent-bit/plugins/out_es/es_bulk.c:88:27: note: did you mean 'fmax'?
/Applications/Xcode_13.2.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.1.sdk/usr/include/math.h:532:15: note: 'fmax' declared here
extern double fmax(double, double);
              ^
1 error generated.
make[2]: *** [plugins/out_es/CMakeFiles/flb-plugin-out_es.dir/es_bulk.c.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [plugins/out_es/CMakeFiles/flb-plugin-out_es.dir/all] Error 2
```
Any ideas how to fix this?

**Comment by gitfool** [comment]
@PettitWesley I'm hoping to get this fix into the next 1.9 release. Any ideas how to fix the non-windows builds?

File: plugins/out_es/es_bulk.c [hunk 1]
```diff
@@ -77,13 +78,14 @@ int es_bulk_append(struct es_bulk *bulk, char *index, int i_len,
...
         if (converted_size == 0) {
             /* converted_size = 0 causes div/0 */
             flb_debug("[out_es] converted_size is 0");
-            append_size = required - available;
         } else {
-            append_size = (whole_size - converted_size) /* rest of size to convert */
-                        * (bulk->size / converted_size); /* = json size / msgpack size */
+            int remaining_size = ceil((whole_size - converted_size) /* rest of size to convert */
+                * ((double)bulk->size / converted_size));           /* = json size / msgpack size */
+            append_size = max(append_size, remaining_size);
```
Comment (PettitWesley) [inline plugins/out_es/es_bulk.c:88]: I ma not sure these functions exist in math.h: https://man7.org/linux/man-pages/man0/math.h.0p.html

Looks like it may be called fmax?

```
../../library/libflb-plugin-out_es.a(es_bulk.c.o): In function `es_bulk_append':
/home/runner/work/fluent-bit/fluent-bit/plugins/out_es/es_bulk.c:88: undefined reference to `max'
collect2: error: ld returned 1 exit status
tests/runtime/CMakeFiles/flb-rt-in_cpu.dir/build.make:323: recipe for target 'bin/flb-rt-in_cpu' failed
make[2]: *** [bin/flb-rt-in_cpu] Error 1
CMakeFiles/Makefile2:6777: recipe for target 'tests/runtime/CMakeFiles/flb-rt-in_cpu.dir/all' failed
make[1]: *** [tests/runtime/CMakeFiles/flb-rt-in_cpu.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
../library/libflb-plugin-out_es.a(es_bulk.c.o): In function `es_bulk_append':
/home/runner/work/fluent-bit/fluent-bit/plugins/out_es/es_bulk.c:88: undefined reference to `max'
collect2: error: ld returned 1 exit status
```

Comment (PettitWesley) [reply plugins/out_es/es_bulk.c:88]: @gitfool

Comment (gitfool) [reply plugins/out_es/es_bulk.c]: I'll switch to `fmax` but I thought an integer `max` function was available as I saw it used elsewhere in the code.

Comment (PettitWesley) [reply plugins/out_es/es_bulk.c]: Looks like that's the windows code though, be careful, Fluent Bit is compiled on lots of platforms...

Comment (gitfool) [reply plugins/out_es/es_bulk.c]: Of course! That helps explain my confusion. 😊

**Comment by gitfool** [comment]
Rebased with recent changes.

**Comment by gitfool** [comment]
Also added the buffer read overrun fixes since I've been testing with those too (with es).

**Comment by PettitWesley** [comment]
@gitfool you need signoff on all commits, also for a small change to one plugin, one commit is best I think.

**Comment by gitfool** [comment]
Okay, I'll squash and signoff.

**Comment by PettitWesley** [comment]
@gitfool Actually sorry just realized you didn't make these same changes for `opensearch`... would you mind doing that? the code is basically exactly the same so it should be copy  paste?

**Comment by gitfool** [comment]
@PettitWesley I only fixed the buffer read overrun in the `opensearch` plugin since it doesn't seem to do bulk operations like the `es` plugin.

**Comment by gitfool** [comment]
If this gets approved then I presume I should submit another pull request to master with the same fixes?

**Comment by PettitWesley** [comment]
@gitfool Yup

**Comment by gitfool** [comment]
@PettitWesley is there anything else I can do to help get this reviewed and merged? 🙏

**Comment by PettitWesley** [comment]
@nokute78 @edsiper CI has passed on this one, I think its ready for review

@gitfool This is all we can sorry.

**Comment by gitfool** [comment]
Missed the [1.9.8 release](https://github.com/fluent/fluent-bit/releases/tag/v1.9.8) too. 😭

**Comment by gitfool** [comment]
Rebased with recent changes. @nokute78 @edsiper PTAL.

**Comment by leonardo-albertovich** [comment]
This seemed correct to me at the time and think it makes no sense to keep stalling it. 

Could we do a quick recap so we can give it closure? 

I'm not familiar at all with this but the way I understood is that there are two issues this fixes : 

1. When nothing has been converted yet `i_len` is not taken in account when calculating `required`

This seems fairly straightforward considering there is a `memcpy` in line 101 that places `i_len` bytes from `index` into the bulk structure buffer. 

After reviewing the rest of the code I noticed that the previous statement could not be true so please correct me if I'm wrong but the code seems to use `ES_BULK_HEADER` when calculating `required` which according to es.c is the maximum value `i_len` could have (it's used to allocate the buffer we receive there in `index`). 

2. When calculating (this is speculation right?) how much space would be required for the remaining msgpack bytes to be converted to json the original code was implcitly rounding down the result of the division of `bulk->size / converted_size` which is used to establish a conversion ratio which is then multiplied by the remainder byte count to get a ballpark of how much space we think we will need for that.

Unless I completely misunderstood it I'm not entirely convinced of the original approach to buffer size requirement because due to how msgpack is internally represented and I see no checks to validate that the new buffer size is large enough to fit `i_len` + `j_len` bytes.

I wonder if I'm missing the point or if this could be simplified this way with no noticeable side effects : 

```
#define BULK_BUFFER_GROWTH_SIZE 4096

required  = i_len + j_len;
required  = fmaxl(required, BULK_BUFFER_GROWTH_SIZE);
available = bulk->size - bulk->len;

if (available < required) {
    ptr = flb_realloc(bulk->ptr, bulk->size + required);
}
```

Which could be considered wasteful if you're flushing before you fill the 4kb or sub optimal if what you are appending to it usually causes the raw required size to be larger than  4kb (ie. reallocating on each append) but that could be improved either by turning it into something the user can set or having the plugin start with a sensible value and adjust based on the average append size.

I want to give closure to this and considering that your fix is working for you I'm inclined to approve it because the way I see it, the only side effect it could have would be using a little bit more memory. I'm only mentioning these other aspects because it's what I understood after trying to make sense of the original code and thought it could help make. 

Please don't hesitate to correct me if there is anything I missed or misunderstood so we can promptly get these improvements merged.

Note on msgpack vs json : an array comprised of 10 False values msgpack encoded would be 11 bytes long, however the same array json encoded would take 70 bytes.

**Comment by gitfool** [comment]
@leonardo-albertovich thank you very much for the review!

1. I agree that using `ES_BULK_HEADER` to calculate `required` seems redundant given the 3 subsequent writes to `bulk->ptr` (`i_len` and `j_len` bytes then `1` byte for the trailing newline).

I left this in place because I did not know this code at all and wanted to merely tweak it to work as I determined was intended; but it would make more sense if reference to `ES_BULK_HEADER` was removed as it seems to be irrelevant to `es_bulk_append`.

2. As I noted in the [issue](https://github.com/fluent/fluent-bit/issues/5680#issuecomment-1179293436), this calculation to predict future buffer requirements seems overly complex, which lead to bugs.

I'm sure it could and probably should be simplified, but I would firmly but politely ask for that to be done in a separate pull request after this one is merged to `1.9` and `master` (in https://github.com/fluent/fluent-bit/pull/6396) since I know the current changes work after extensive "testing" in production, going on for 4 months now.

Also, as I [commented](https://github.com/fluent/fluent-bit/pull/5770#issuecomment-1211280428) above in this pull request, the `opensearch` plugin doesn't seem to have an equivalent bulk append, unless I'm missing something, and I'd expect its implementations to be similar, so whatever is eventually applied here should presumably be applied there too, which again should be done in a separate pull request.

**Comment by leonardo-albertovich** [comment]
Good news everyone!

In order to be confident enough to back your PR I wrote a quick PoC to demonstrate the value expansion issue I commented in my previous message and realized that two changes you made sealed the deal : 

1. Moving the assignment of `append_size` which actually takes in account the length of what we are trying to append to line 82
2. Adding the `fmax` line to ensure that the calculated size is large enough to fit data or fall back to `append_size`

Without those changes I could crash fluent-bit while running with this configuration : 

```
[SERVICE]
  flush 10
  log_level trace

[INPUT]
  Name tcp
  listen 127.0.0.1
  port 9556

[OUTPUT]
  Name es
  Match *
  host 127.0.0.1
  port 9555
  retry_limit no_retries
  workers 0
  tls off
```

Just launching fluent-bit and then running these two lines before the first flush cycle ran : 

```
python  gen_good_json.py  | nc 127.0.0.1 9556
python  gen_bad_json.py  | nc 127.0.0.1 9556
```

```
# gen_good_json.py

payload = "a" * 4000
generated = '{"a": "%s"}' % (payload)
print(generated)
```

```
# gen_bad_json.py

payload = [False] * 1100
payload = (str(e).lower() for e in payload)
payload = ", ".join(payload)
generated = '{"a": [%s]}' % (payload)
print(generated)
```

The idea there is to prime the bulk structure with the first message where each input character roughly translates to one output character (sending enough characters that the relationship between whole and converted gives us a small multiplier (in fact, if you send a 10 byte payload followed by a 7kb payload the result of the calculation is 285kb) and then send a large json payload that shrinks up when converted to msgpack.

Anyway, the result is I proved that your patch is good enough, not because of the correction in how floating point numbers are handled but because it properly handles that corner case I was rightfully worried about.

@edsiper please, let's get this PR and #6396 merged ASAP.

And once again, thanks a lot for finding the issue, fixing it and sticking through @gitfool, we really appreciate it.
